<?php
    $catalogHelperData = $this->helper('Magento\Catalog\Helper\Data');
    $categoryObject = $catalogHelperData->getCategory();
    $categoryId = $categoryObject->getId();
    $categoryName = $categoryObject->getName();
    
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        

    $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
    // Load category by category ID
    $category = $categoryFactory->create()->load($categoryId);
    //Get all children category ids ids comma-separated
    $allChildrenCategoryIds = $category->getAllChildren(false);
    $allChildrenCategoryIdsArr = $category->getAllChildren(true);
    //echo $allChildrenCategoryIds;
    
    
    $categoryCameras = $categoryFactory->create()->load(17);
    $allChildrenCategoryIdsCameras = $categoryCameras->getAllChildren(true);
    
    $categoryLenses = $categoryFactory->create()->load(18);
    $allChildrenCategoryIdsLenses = $categoryLenses->getAllChildren(true);
    
    $categoryAudioAndVisual = $categoryFactory->create()->load(73);
    $allChildrenCategoryIdsAudioAndVisual = $categoryAudioAndVisual->getAllChildren(true);
    
    $categoryComputersAndMobile = $categoryFactory->create()->load(999);
    $allChildrenCategoryIdsComputersAndMobile = $categoryComputersAndMobile->getAllChildren(true);
    
    $categoryDrones = $categoryFactory->create()->load(21);
    $allChildrenCategoryIdsDrones = $categoryDrones->getAllChildren(true);
    
    $categoryLightingAndStudio = $categoryFactory->create()->load(19);
    $allChildrenCategoryIdsLightingAndStudio = $categoryLightingAndStudio->getAllChildren(true);
    
    $categoryOptics = $categoryFactory->create()->load(22);
    $allChildrenCategoryIdsOptics = $categoryOptics->getAllChildren(true);
    
    $categoryPhotoAndAccessories = $categoryFactory->create()->load(71);
    $allChildrenCategoryIdsPhotoAndAccessories = $categoryPhotoAndAccessories->getAllChildren(true);
    
    $categoryProVideo = $categoryFactory->create()->load(77);
    $allChildrenCategoryIdsProVideo = $categoryProVideo->getAllChildren(true);
    
    $categorySmartHome = $categoryFactory->create()->load(75);
    $allChildrenCategoryIdsSmartHome = $categorySmartHome->getAllChildren(true);
    
    $categoryDigiSeconds = $categoryFactory->create()->load(2564);
    $allChildrenCategoryIdsDigiSeconds = $categoryDigiSeconds->getAllChildren(true);
?>


<?php 
    $catalogHelperData = $this->helper('Magento\Catalog\Helper\Data');
    $categoryObject = $catalogHelperData->getCategory();
    $categoryId = $categoryObject->getId();
    $categoryName = $categoryObject->getName();
?>


<!--digi-seconds modal-->
<div class="digi-seconds-modal" style="width: 1095px;margin-right: 0;margin-left: auto;">
    <a href="#" id="digisecondsForm_trigger">
        <img class="digisecondsForm_triggerImg" src="https://mcstaging2.digidirect.com.au/media/wysiwyg/digiseconds/digi-seconds-trigger-button.png">
        <!-- <//?php if (in_array($categoryId, $allChildrenCategoryIdsDigiSeconds)) : ?>
            <img src="<//?php echo $block->getUrl("media/wysiwyg/digiseconds")?>digi-seconds-trigger-button.png"/>
        <//?php endif; ?> -->
    </a>

    <div id="digisecondsForm">
        <h1>Booking page</h1>

        <form action="<?php echo $block->getFormAction() ?>" method="post">
            <input name="firstname" type="text">
            <input name="lastname" type="text">
            <input name="phone" type="text">
            <input name="bookingTime" type="date">
            <input type="submit" value="Send booking informations">
        </form>
    </div>
    
</div>

<div class="category-page-banner" style="width: 1095px;margin-right: 0;margin-left: auto;">
    <div class="custom-preloader-container"><div class="custom-preloader"></div></div>
    <div class="banner-desktop" style="display: none;">
        <?php if (in_array($categoryId, $allChildrenCategoryIdsCameras)) :?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>cameras.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsLenses)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>lenses.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsAudioAndVisual)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>audio_and_visual.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsComputersAndMobile)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>computers_and_mobile.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsDrones)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>drones.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsLightingAndStudio)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>lighting_and_studio.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsOptics)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>optics.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsPhotoAndAccessories)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>photo_and_accessories.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsProVideo)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>pro_video.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsSmartHome)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>smart_home.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsDigiSeconds)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>digiseconds.png"/>
        <?php endif; ?>
    </div>
    <div class="banner-tablet" style="display: none;">
        <?php if (in_array($categoryId, $allChildrenCategoryIdsCameras)) :?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>cameras.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsLenses)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>lenses.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsAudioAndVisual)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>audio_and_visual.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsComputersAndMobile)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>computers_and_mobile.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsDrones)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>drones.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsLightingAndStudio)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>lighting_and_studio.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsOptics)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>optics.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsPhotoAndAccessories)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>photo_and_accessories.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsProVideo)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>pro_video.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsSmartHome)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>smart_home.png"/>
        <?php elseif (in_array($categoryId, $allChildrenCategoryIdsDigiSeconds)) : ?>
            <img src="<?php echo $block->getUrl("media/wysiwyg/category-header-tablet-view")?>digiseconds.png"/>
        <?php endif; ?>
    </div>
    
    
</div>

<script>
    require(['jquery'],function(){
        jQuery(document).ready(function() {
            var categoryName = "<?= /* @escapeNotVerified */ $categoryName ?>";
            if (categoryName == "digiSeconds" ||
                categoryName == "REFURB" ||
                categoryName == "OPENBOX" ||
                categoryName == "PRELOVED") {
                //alert("This is digiSeconds category page!");
                jQuery('.product-item').addClass('digiseconds-li');
            }
        });
        
        jQuery(".product-category-listing .product-items").bind("DOMSubtreeModified", function() {
            //console.log("DOMSubtreeModified Working On Banner Category");
        });
    });
    
//    digi-seconds modal form
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }],
                opened: function($Event) {
                    // $(".modal-footer").hide();
                    $(".modal-header").css("background-color","transparent");
                    // $(".modal-header button.action-close:before").css("color","#cacaca");
                    $(".modal-footer").hide();
                }
            };


            var popup = modal(options, $('#digisecondsForm'));
            $("#digisecondsForm_trigger").on('click',function(){ 
                $("#digisecondsForm").modal("openModal");
            });
            // $( "#digisecondsForm_trigger" ).prepend( "<b>Hello </b>" );

        }
    );
</script>

<style>
    .digiseconds-li {
        width: 46.7% !important;
    }
</style>

