<?php
    $catalogHelperData = $this->helper('Magento\Catalog\Helper\Data');
    $categoryObject = $catalogHelperData->getCategory();
    $categoryId = $categoryObject->getId();
    $categoryName = $categoryObject->getName();
    
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        

    $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
    // Load category by category ID
    $category = $categoryFactory->create()->load($categoryId);
    //Get all children category ids ids comma-separated
    $allChildrenCategoryIds = $category->getAllChildren(false);
    $allChildrenCategoryIdsArr = $category->getAllChildren(true);
    //echo $allChildrenCategoryIds;
    
    
    $categoryCameras = $categoryFactory->create()->load(17);
    $allChildrenCategoryIdsCameras = $categoryCameras->getAllChildren(true);
    
    $categoryLenses = $categoryFactory->create()->load(18);
    $allChildrenCategoryIdsLenses = $categoryLenses->getAllChildren(true);
    
    $categoryAudioAndVisual = $categoryFactory->create()->load(73);
    $allChildrenCategoryIdsAudioAndVisual = $categoryAudioAndVisual->getAllChildren(true);
    
    $categoryComputersAndMobile = $categoryFactory->create()->load(999);
    $allChildrenCategoryIdsComputersAndMobile = $categoryComputersAndMobile->getAllChildren(true);
    
    $categoryDrones = $categoryFactory->create()->load(21);
    $allChildrenCategoryIdsDrones = $categoryDrones->getAllChildren(true);
    
    $categoryLightingAndStudio = $categoryFactory->create()->load(19);
    $allChildrenCategoryIdsLightingAndStudio = $categoryLightingAndStudio->getAllChildren(true);
    
    $categoryOptics = $categoryFactory->create()->load(22);
    $allChildrenCategoryIdsOptics = $categoryOptics->getAllChildren(true);
    
    $categoryPhotoAndAccessories = $categoryFactory->create()->load(71);
    $allChildrenCategoryIdsPhotoAndAccessories = $categoryPhotoAndAccessories->getAllChildren(true);
    
    $categoryProVideo = $categoryFactory->create()->load(77);
    $allChildrenCategoryIdsProVideo = $categoryProVideo->getAllChildren(true);
    
    $categorySmartHome = $categoryFactory->create()->load(75);
    $allChildrenCategoryIdsSmartHome = $categorySmartHome->getAllChildren(true);
?>


<?php 
    $catalogHelperData = $this->helper('Magento\Catalog\Helper\Data');
    $categoryObject = $catalogHelperData->getCategory();
    $categoryId = $categoryObject->getId();
    $categoryName = $categoryObject->getName();
?>

<div class="category-page-banner" style="width: 1095px;margin-right: 0;margin-left: auto;">
    <div class="custom-preloader-container"><div class="custom-preloader"></div></div>
    
    <?php if (in_array($categoryId, $allChildrenCategoryIdsCameras)) :?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>cameras.png"/>
    <?php elseif (in_array($categoryId, $allChildrenCategoryIdsLenses)) : ?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>lenses.png"/>
    <?php elseif (in_array($categoryId, $allChildrenCategoryIdsAudioAndVisual)) : ?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>audio_and_visual.png"/>
    <?php elseif (in_array($categoryId, $allChildrenCategoryIdsComputersAndMobile)) : ?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>computers_and_mobile.png"/>
    <?php elseif (in_array($categoryId, $allChildrenCategoryIdsDrones)) : ?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>drones.png"/>
    <?php elseif (in_array($categoryId, $allChildrenCategoryIdsLightingAndStudio)) : ?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>lighting_and_studio.png"/>
    <?php elseif (in_array($categoryId, $allChildrenCategoryIdsOptics)) : ?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>optics.png"/>
    <?php elseif (in_array($categoryId, $allChildrenCategoryIdsPhotoAndAccessories)) : ?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>photo_and_accessories.png"/>
    <?php elseif (in_array($categoryId, $allChildrenCategoryIdsProVideo)) : ?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>pro_video.png"/>
    <?php elseif (in_array($categoryId, $allChildrenCategoryIdsSmartHome)) : ?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>smart_home.png"/>
    <?php endif; ?>
    
    <?php if ($categoryName == "digiSeconds") : ?>
        <img src="<?php echo $block->getUrl("media/wysiwyg/category-header")?>digiseconds.png"/>
    <?php endif; ?>
    
</div>

<script>
    require(['jquery'],function(){
        jQuery(document).ready(function() {
            if ("<?= /* @escapeNotVerified */ $categoryName ?>" == "digiSeconds") {
                //alert("This is digiSeconds category page!");
                jQuery('.page-products.products-grid.product-item').addClass('digiseconds-li');
            }
        });
    });
</script>

<style>
    .digiseconds-li {
        width: 46.7% !important;
    }
</style>

