<div class="custom-sorter">
    <div id="custom-most-viewed"><i class="fas fa-certificate"></i>  Most Viewed</div>
    <div id="custom-new-products"><i class="fas fa-star-of-life"></i>  New Products</div>
    <div id="custom-best-sellers"><i class="fas fa-star"></i>  Best Sellers</div>
    <div id="custom-product-name-asc"><i class="fas fa-sort-alpha-up"></i>  Product Name (A-Z)</div>
    <div id="custom-product-name-desc"><i class="fas fa-sort-alpha-up-alt"></i>  Product Name (Z-A)</div>
    <div id="custom-price-asc"><i class="fas fa-sort-numeric-down"></i>  Price Low to High</div>
    <div id="custom-price-desc"><i class="fas fa-sort-numeric-down-alt"></i>  Price High to Low</div>
</div>

<script>
    require([
        'jquery'
    ],
    function ($) {
  
        $("#custom-most-viewed").click(function() {
            $('#sorter').val('most_viewed').trigger('change');
        });
        
        $("#custom-new-products").click(function() {
            $('#sorter').val('latest').trigger('change');
        });
        
        $("#custom-best-sellers").click(function() {
            $('#sorter').val('position').trigger('change');
        });
        
        $("#custom-product-name-asc").click(function() {
            $('#sorter').val('product_name_asc').trigger('change');
        });
        
        $("#custom-product-name-desc").click(function() {
            $('#sorter').val('product_name_desc').trigger('change');
        });
        
        $("#custom-price-asc").click(function() {
            $('#sorter').val('price_lowest_first').trigger('change');
        });
        
        $("#custom-price-desc").click(function() {
            $('#sorter').val('price_highest_first').trigger('change');
        });
        
        
    });
</script>

<style>
    
    .custom-sorter {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        border: 1px solid #cacaca;
        margin-left: -57px;
        max-width: 1093px;
        justify-items: center;
        margin-top: 12px;
        cursor: pointer;
    }
    
    .custom-sorter div {
        font-size: 12px;
        padding: 10px;
    }
    
</style>