<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$urlInterface = $objectManager->get('Magento\Framework\UrlInterface');
$currentUrl = $urlInterface->getCurrentUrl();

$isBrandCanon = str_contains($currentUrl, 'brands/canon');
$isBrandNikon = str_contains($currentUrl, 'brands/nikon');
$isBrandAsus = str_contains($currentUrl, 'brands/asus');

if ($request->getFullActionName() == 'catalog_category_view') {
    
    $categoryName = "";
    
    $catalogHelperData = $this->helper('Magento\Catalog\Helper\Data');
    $categoryObject = $catalogHelperData->getCategory();
    $categoryId = $categoryObject->getId();
    $categoryName = $categoryObject->getName();
    
    if ($categoryId == 17 || $categoryId == 37) {
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('cameras-product-featured-banner')
        ->toHtml();
    } 
    
} elseif ($request->getFullActionName() == 'eaa_attribute_option_index') {
    if ($isBrandCanon == true) {
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('cameras-product-featured-banner')
        ->toHtml();
    } elseif ($isBrandNikon == true) {
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('brands-nikon-featured-banner')
        ->toHtml();
    } elseif ($isBrandAsus == true) {
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('brands-asus-featured-banner')
        ->toHtml();
    }
}

?>

<script>
    require([
        'jquery'
    ],
    function ($) {
        $('.featured-banner-heading').attr("style", "margin-top: -30px !important;");
    });
</script>