<?php

$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
$url = $urlInterface->getCurrentUrl();

$urlParts = explode('/', str_ireplace(array('http://', 'https://'), '', $url));
//echo $urlParts[1];

if ($urlParts[1] != 'brands') {

?>

<div class="custom-preloader-container"><div class="custom-preloader"></div></div>

<?php } ?>

<style type="text/css">
    .custom-preloader-container {
        height: 70.52px;
        width: 1095px;
        margin-right: 55px;
        margin-top: 70px;
        margin-left: auto;
        display: none !important;
        
    }
    .custom-preloader {
        display: block;
        margin: auto;
        vertical-align: middle;
        border: 7px solid #f5f5f5;
        border-radius: 50%;
        border-top: 7px solid #000;
        width: 50px;
        height: 50px;
        -webkit-animation: spin 2s linear infinite; /* Safari */
        animation: spin 2s linear infinite;
    }
    
    @-webkit-keyframes spin {
        0% { -webkit-transform: rotate(0deg); }
        100% { -webkit-transform: rotate(360deg); }
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>