<div class="custom-preloader-container"><div class="custom-preloader"></div></div>

<style type="text/css">
    .custom-preloader-container {
        height: 140.52px;
        margin-left: -55px;
        width: 1095px;
    }
    .custom-preloader {
        display: block;
        margin: auto;
        vertical-align: middle;
        border: 7px solid #f5f5f5;
        border-radius: 50%;
        border-top: 7px solid #000;
        width: 50px;
        height: 50px;
        -webkit-animation: spin 2s linear infinite; /* Safari */
        animation: spin 2s linear infinite;
    }
</style>