<div class="plp-banner-widget">
    <div class="plp-banner" style="height: 265px;">
        <img style="height: 100%; object-fit: cover;" src="<?= $block->getViewFileUrl('images/plp-banner-refurb.png') ?>" />
        <div class="plp-banner-label">
            <div style="text-align: center; justify-content: center; display: flex; flex-direction: column; color: #fff; font-size: 128px; font-family: Inter; font-weight: 600;">Refurbished</div>
            <div style="text-align: center; color: #fff; font-size: 32px; font-weight: 600;">We repaired it and restored it to it's original glory and beyond!</div>
        </div>
    </div>
    <div class="plp-row pa-widget" style="margin: -4px 0 0 0;">
        <div class="pa-digidirect-product-widget refurb-recommended-widget">
            <div class="product-widget-header">
                <div style="color: #242426; font-size: 32px; font-family: Inter; font-weight: 500; line-height: 33px; word-wrap: break-word">Here's our Recommended Refurbished products for you</div>
            </div>
            <div id="refurb-recommended-widget-desktop" class="pa-digidirect-product-widget-container desktop-widget real-container owl-carousel custom"></div>
        </div>
    </div>
</div>