<?php
/**
 * @var \Digidirect\AbstractGiftCard\Block\Adminhtml\Sales\Order\Create\Payment\Container $block
 */
?>
<div class="admin__field abstract-gift-card-container">
    <label class="admin__field-label">
        <span><?php echo $block->escapeHtml(__('Abstract Gift Cards')); ?></span>
    </label>
    <div class="admin__field-control">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>
