<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$urlInterface = $objectManager->get('Magento\Framework\UrlInterface');
$currentUrl = $urlInterface->getCurrentUrl();

echo $this->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('sony-featured-products')
->toHtml();

?>

<script>
    require([
        'jquery'
    ],
    function ($) {
    });
</script>