<?php
use Magento\Framework\App\Action\Action;
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $_helper \Magento\Catalog\Helper\Output
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$showWishlist = true;
//$productBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Digidirect\Catalog\Block\ProductInfoBlock');
                
?>
<script>
    console.log("Product Count Log: " + "<?= $_productCollection->count() ?>");
</script>
<?= $block->getToolbarHtml() ?>
<?= $block->getAdditionalHtml() ?>

<?php 
    $currentPage = "Test Current Page";
?>
<script>
    console.log("Current Page Log: " + "<?= $currentPage ?>");
</script>
<?php 
    if ($currentPage != "catalogsearch_result_index") {
        $catalogHelperData = $this->helper('Magento\Catalog\Helper\Data');
        $categoryObject = $catalogHelperData->getCategory();
        $categoryId = $categoryObject->getId();
        $categoryName = $categoryObject->getName();
    }
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper products-widget product-category-listing <?= $block->escapeHtml($viewMode); ?> products-<?= $block->escapeHtml($viewMode); ?>">
        <?php $iterator = 1; ?>
        <ol class="products items product-items -<?= $block->escapeHtml($viewMode); ?>"
            data-mage-init='{
                "truncateCollection": {
                    "addOn": "js/dist/widgets/truncate-collection/addons/catalog/index"
                }
            }'>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php
                $blockMode = $block->getMode();
                $productId = $_product->getId();
                $productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
                $qff_base = $_helper->productAttribute($_product, $_product->getQffBase(), 'qff_base');
                $qff_bonus = $_helper->productAttribute($_product, $_product->getQffBonusPoints(), 'qff_bonus_points');
                $stock = $_helper->productAttribute($_product, $_product->getPrice(), 'price');
                
                $brandNewProductPrice = "";
                $brandNewProductUrl = "";
                $secondsSavings = "";
                
                $finalProductPrice = $_product->getFinalPrice();
                $qff_bonus_points = 0;
                
                $d2BrandNewProductSKU = $_product->getData('d2newsku');
                $d2ItemCondition = $_product->getData('item_codition');
                $d2ItemDescription = $_product->getData('d2desc'); 
                $d2ItemRating = $_product->getData('item_rating');
                $d2PackageInclusion = $_product->getData('whats_in_the_box');
                
                $objectManagerProduct = \Magento\Framework\App\ObjectManager::getInstance();
                $brandNewProduct = $objectManagerProduct->get('Magento\Catalog\Model\Product')->loadByAttribute('sku', $d2BrandNewProductSKU);
                
                if ($brandNewProduct) {
                    $brandNewProductPrice = $brandNewProduct->getPrice();
                    $brandNewProductUrl = $brandNewProduct->getProductUrl();
                    $secondsSavings = round(($finalProductPrice/$brandNewProductPrice)*100);
                }
                
                ?>
               
                <?php if (!empty($qff_base) && !empty($qff_bonus)) {

                    $bonusPlusBase = $qff_base + $qff_bonus;

                    $points = number_format($finalProductPrice * $bonusPlusBase);
                }else {
                    if(!empty($qff_bonus)){

                        $points = number_format($finalProductPrice * $qff_bonus);
                    } else {
                        $points = number_format($finalProductPrice * 1);
                    }
                }  

                $finalQffPoints = $_product->getPoints();
                
                $productUrl = $_product->getProductUrl(); 
                
                ?>
                
            <script>
            </script>
            
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info -<?= $block->escapeHtml($viewMode); ?>"
                     data-container="product-grid"
                     data-qff-points="<?= $block->escapeHtml($qff_bonus_points); ?>"
                     data-parent-product-id="<?= $block->escapeHtml($productId); ?>">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    
                    <?php if ($d2ItemCondition): ?>
                        <div class="digiseconds-overlay">
                            <?php if ($d2ItemCondition == "PRELOVED"): ?>
                                <img src="<?php echo $block->getUrl("media/wysiwyg/digiseconds/overlays/")?>badge-pre-loved.png"/>
                            <?php elseif ($d2ItemCondition == "OPENBOX"): ?>
                                <img src="<?php echo $block->getUrl("media/wysiwyg/digiseconds/overlays/")?>badge-demo.png"/>
                            <?php elseif ($d2ItemCondition == "REFURB"): ?>
                                <img src="<?php echo $block->getUrl("media/wysiwyg/digiseconds/overlays/")?>badge-refurbished.png"/>
                            <?php endif; ?>
                            <div class="digiseconds-rating">
                                <?php if ($d2ItemRating == 5): ?>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                <?php elseif ($d2ItemRating == 4): ?>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="far fa-star"></i>
                                <?php elseif ($d2ItemRating == 3): ?>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="far fa-star"></i>
                                    <i class="far fa-star"></i>
                                <?php elseif ($d2ItemRating == 2): ?>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="far fa-star"></i>
                                    <i class="far fa-star"></i>
                                    <i class="far fa-star"></i>
                                <?php elseif ($d2ItemRating == 1): ?>
                                    <i class="fas fa-star"></i>
                                    <i class="far fa-star"></i>
                                    <i class="far fa-star"></i>
                                    <i class="far fa-star"></i>
                                    <i class="far fa-star"></i>
                                <?php elseif ($d2ItemRating == 0): ?>
                                    <i class="far fa-star"></i>
                                    <i class="far fa-star"></i>
                                    <i class="far fa-star"></i>
                                    <i class="far fa-star"></i>
                                    <i class="far fa-star"></i>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    
                    <?php // Product Image ?>
                    <a href="<?= $block->escapeUrl($productUrl); ?>"
                       title="<?= $block->escapeHtml($productName); ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml(); ?>
                    </a>
                    
                    <?php
                        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                    ?>
                    
                    <?php
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $reviewFactory = $objectManager->create('Magento\Review\Model\Review');
                        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
                        $storeManager  = $objectManager->create('\Magento\Store\Model\StoreManagerInterface');
                        $storeId = $storeManager->getStore()->getStoreId();
                        $reviewFactory->getEntitySummary($product, $storeId);

                        $ratingSummary = $product->getRatingSummary()->getRatingSummary();
                        $reviewCount = $product->getRatingSummary()->getReviewsCount();
                    ?>
                    
                    <?php if ($reviewCount > 0) : ?>
                        <div><?php echo $block->getReviewsSummaryHtml($_product, $templateType, true) ?></div>
                    <?php else: ?>
                        <div class="product-reviews-summary short">
                            <div class="rating-summary">
                                <span class="label"><span>Rating:</span></span>
                                    <div class="rating-result blank-star-rating" title="100%">
                                    <span style="width: 100%;"><span>100%</span></span>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                    
                    <?php if ($currentPage != "catalogsearch_result_index"): ?>
                        <?php if ($categoryName == "digiSeconds") : ?>
                            <strong class="product name product-item-name -grid" style="visibility:visible; display: block !important; font-size: 12px !important;">
                                <a href="<?= $block->escapeUrl($productUrl); ?>"
                                   class="product-item-link">
                                    <?php if ($brandNewProductPrice != "" || $brandNewProductPrice): ?>
                                        Seconds Savings: <?= $secondsSavings; ?>%
                                    <?php endif; ?>
                                </a>
                            </strong>
                        <?php endif; ?>
                    <?php endif; ?>
                        
                    <?php if($blockMode === 'grid'):?>
                        <strong class="product name product-item-name -grid">
                            <a href="<?= $block->escapeUrl($productUrl); ?>"
                               title="<?= $block->escapeHtml($productName); ?>"
                               class="product-item-link">
                                <?= $block->escapeHtml($productName); ?>
                            </a>
                        </strong>
                    <?php endif;?>
                    <div class="product details product-item-details">
                        <div class="no-display">
                            <?php
                                // Must be called for Preorder plugin
                                echo $block->getReviewsSummaryHtml($_product);
                            ?>
                        </div>
                        <?= $this->getLayout()
                            ->createBlock('Digidirect\ExtendedCatalogPriceRule\Block\ExtendedRule')
                            ->setTemplate('Digidirect_ExtendedCatalogPriceRule::product/view/list/display_message.phtml')
                            ->setProduct($_product)
                            ->toHtml();
                        ?>
                        <?php if($blockMode === 'grid'):?>
                            <?php if ($afterProductPriceBlock = $block->getChildBlock('after.product.price.container')): ?>
                                <?= /* @escapeNotVerified */ $afterProductPriceBlock->setProduct($_product)->getChildHtml(); ?>
                            <?php endif; ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?php endif;?>
                        <?php if($blockMode === 'list'):?>
                            <strong class="product name product-item-name -list">
                                <a href="<?= $block->escapeUrl($productUrl) ?>"
                                   title="<?php  echo $block->escapeHtml($productName); ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($productName); ?>
                                </a>
                            </strong>
                            <?php if ($afterProductPriceBlock = $block->getChildBlock('after.product.price.container')): ?>
                                <?= /* @escapeNotVerified */ $afterProductPriceBlock->setProduct($_product)->getChildHtml(); ?>
                            <?php endif; ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?php endif;?>

                        <div class="product-item-inner">
                            <?= $block->getProductDetailsHtml($_product); ?>
                            <div class="product actions product-item-actions"<?= /* @escapeNotVerified */ strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?= /* @escapeNotVerified */ strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form"
                                          data-product-sku="<?=  /* @NoEscape */ $_product->getSku(); ?>"
                                          data-mage-init='{"validation": {"ignore": ".super-attribute-select"}}'
                                          action="<?= /* @escapeNotVerified */ $postParams['action']; ?>" method="post"
                                    >
                                        <input type="hidden"
                                               name="product"
                                               value="<?= /* @escapeNotVerified */ $postParams['data']['product']; ?>"/>
                                        <input type="hidden"
                                               name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED; ?>"
                                               value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>"/>
                                        <?= /* @escapeNotVerified */ $block->getBlockHtml('formkey'); ?>
                                        <?php if ($toCartFormBlock = $block->getChildBlock('tocart_form')): ?>
                                            <?= /* @escapeNotVerified */ $toCartFormBlock->setProduct($_product)->getChildHtml(); ?>
                                        <?php endif; ?>
                                        <button type="submit"
                                                title="<?= /* @escapeNotVerified */ __('Add to Cart'); ?>"
                                                class="action tocart primary">
                                            <span><?= /* @escapeNotVerified */ __('Add to Cart'); ?></span><i class="fas fa-cart-plus" style="float: right; color: #ff3c00;"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php if ($currentPage != "catalogsearch_result_index"): ?>
                        <?php if ($categoryName == "digiSeconds"): ?>
                            <div class="digiseconds-product-details">
                                <div class="digiseconds-product-name"><?= $block->escapeHtml($productName); ?></div>
                                <?php if ($d2ItemDescription): ?>
                                    <div class="item-note-wrapper-plp">
                                        <span class="item-note-label">
                                            Item Note: 
                                        </span>
                                        <span class="item-note" style="padding-left: 15px;">
                                            <?= /* @escapeNotVerified */ $d2ItemDescription ?>
                                        </span>
                                    </div>
                                <?php endif; ?>
                                <?php if ($d2PackageInclusion): ?>
                                    <div class="package-inclusion-wrapper">
                                        <div>
                                            PACKAGE INCLUSION:
                                        </div>
                                        <div class="whats-in-the-box-wrapper">
                                            <?= /* @escapeNotVerified */ $d2PackageInclusion ?>
                                        </div>
                                        <div class="digiseconds-show-more">
                                            <a href="<?= $block->escapeUrl($productUrl) . "#whatinthebox"; ?>" title="<?= $block->escapeHtml($productName); ?>">
                                                 Show More <i class="far fa-angle-down"></i>
                                            </a>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php if ($brandNewProductPrice && $brandNewProductPrice != ""): ?>
                                    <div class="other-options-wrapper">
                                        <div>
                                            Other Buying Options
                                        </div>
                                        <div class="other-options-new">
                                            NEW: <a href="<?= $block->escapeUrl($brandNewProductUrl); ?>" title="View Brand New">$<?= /* @escapeNotVerified */ number_format($brandNewProductPrice, 2) ?>
                                            </a>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <?= /* @escapeNotVerified */ ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                   "bindSubmit": true
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
        
<script>
    require(['jquery'],function(){
        jQuery(document).ready(function() {
            if ("<?= /* @escapeNotVerified */ $currentPage ?>" != "catalogsearch_result_index") {
                if ("<?= /* @escapeNotVerified */ $categoryName ?>" == "digiSeconds") {
                    jQuery('.product-item-info>a').addClass('digiseconds-left-width');
                    jQuery('.testfreaks-items').addClass('digiseconds-left-width');
                    jQuery('.product-reviews-summary').addClass('digiseconds-left-width');
                    jQuery('.product-item-name').addClass('digiseconds-left-width');
                    jQuery('.product-item-details').addClass('digiseconds-left-width');
                }
            }
        });
    });
</script>

<style>
    .product-category-listing .digiseconds-left-width {
        width: 33% !important;
        position: relative;
    }
    
    .digiseconds-product-details {
        position: absolute;
        left: 230px;
        max-width: 315px;
        font-size: 13px;
    }
    
    .digiseconds-product-name {
        font-size: 18px;
        width: 324px;
        overflow: hidden;
        height: auto;
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
        background: #f5f5f5;
        padding: 5px 0px 5px 15px;
        margin-left: -31px;
    }

    .item-note-wrapper-plp {
        text-align: left;
        float: left;
        width: 100%;
        margin-bottom: 10px;
        padding-top: 5px;
        margin-top: 5px;
        margin-left: 0;
        font-size: 13px;
        font-weight: 500;
    }
    
    .package-inclusion-wrapper ul {
        margin-left: 40px;
    }

    .whats-in-the-box-wrapper {
        height: 150px;
        overflow: hidden !important;
    }

    .package-inclusion-wrapper em strong {
        display: none !important;
    }

    .package-inclusion-wrapper li::marker {
        content: '-' !important;
    }

    .package-inclusion-wrapper li {
        margin-bottom: 4px !important;
    }
    
    .package-inclusion-wrapper p {
        margin-bottom: 4px;
    }

    .package-inclusion-wrapper li span {
        margin-left: 20px;
        font-size: 12px !important;
    }

    .digiseconds-show-more a {
        color: #ef3c00 !important;
        font-weight: 500;
        margin-left: 32px;
    }

    .digiseconds-show-more i {
        color: #ef3c00 !important;
        font-weight: 600;
        margin-left: 5px;
    }

    span.item-note-label {
        color: #8f8f8f;
    }
    
    .other-options-wrapper {
        margin-top: 10px;
    }
    
    .other-options-new {
        margin-top: 6px;
    }
    
    .other-options-wrapper a {
        font-size: 17px;
        margin-left: 5px;
    }
    
    .product-item .product-reviews-summary .rating-summary {
        display: none !important;
    }
    
    .product-category-listing .digiseconds-li .product-item-name {
        visibility: hidden;
        display: none;
    }
    
    .product-category-listing>.product-items>.product-item>.product-item-info>a>span>.product-image-wrapper>.product-image-photo {
        margin-top: 70px !important;
    }

</style>

<style type="text/css">
    .product-category-listing .digiseconds-overlay {
        position: absolute;
        padding: 0;
        z-index: 97;
        max-width: 120px;
    }
    .digiseconds-rating {
        margin-left: 42px;
        margin-top: -28px;
        color: #FFAE00;
        font-size: 11px;
    }
</style>

<style>
    .page-main {
        background: #f5f5f5;
    }
</style>
