<?php
$_product = $block->getLayout()->getBlock('product.info')->getProduct();
$addToCartUrl = $this->helper('Magento\Checkout\Helper\Cart')->getAddUrl($_product);
$seller = $_product->getData('marketplacer_seller');
?>

<div class="payment-gateways-container-main">
    <div id="payment-options-toggle" class="payment-options-toggle close">PAYMENT OPTIONS</div>
    <div id="payment-options" class="payment-options close">
        <?= $this->getLayout()->createBlock(\Magento\Framework\View\Element\Template::class)->setProduct($_product)->setAddToCartUrl($addToCartUrl)->setTemplate("Magento_Catalog::product/payment-gateways.phtml")->toHtml() ?>
        <?= $this->getLayout()->createBlock(\Magento\Framework\View\Element\Template::class)->setProduct($_product)->setAddToCartUrl($addToCartUrl)->setTemplate("Magento_Catalog::product/payment-gateways-bottom.phtml")->toHtml() ?>
    </div>
</div>
