<div class="payment-gateways-container-main">
    <div id="payment-options-toggle" class="payment-options-toggle close">PAYMENT OPTIONS</div>
    <div id="payment-options" class="payment-options close">
        <?= $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/payment-gateways.phtml")->toHtml() ?>
        <?= $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/payment-gateways-bottom.phtml")->toHtml() ?>
    </div>
</div>

