<?php

?>

<div class="payment-gateways">
    <div class="row-first">
        <div div="union-alipay-wechat">
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>union-alipay-wechat.png"/>
        </div>
        <div id="latitude-pay-custom">
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>latitudepay.png"/>
        </div>
        <div id="klarna-custom">
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>klarna.png"/>
        </div>
    </div>
</div>

<script>
    require([
            'jquery'
        ],
        function ($) {
            
    });
</script>
