<?php

?>

<div class="payment-gateways">
    <div class="row-first">
        <div class="credit-cards">
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>visa.png"/><span>
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>mastercard.png"/><span>
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>amex.png"/><span>
        </div>
        <div class="paypal-custom">
        </div>
        <div class="zip-custom">
            <span>
                <span>0% Interest for 6 Months</span>
                <span>APPLY NOW!</span>
            </span>
        </div>
    </div>
</div>
