<?php

?>

<div class="payment-gateways">
    <div class="row-first">
        <div class="credit-cards">
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>visa.png"/>
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>mastercard.png"/>
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>amex.png"/>
        </div>
        <div id="paypal-custom">
        </div>
        <div id="zip-custom">
            <span>
                <span>0% Interest for 6 Months</span>
                <span>APPLY NOW!</span>
            </span>
        </div>
    </div>
</div>

<script>
    require([
            'jquery'
        ],
        function ($) {
           $('#paypal-custom').append($('#paypal-smart-button'));
    });
</script>
