

<div class="payment-gateways">
    <div class="row-first">
        <div class="actions">
            <button type="submit"
                class="action tocart btn_cart tocart-pdp-btn"
                id="product-addtocart-button"
                data-action="add-to-cart-action"
                >
                <div class="credit-cards">
                    <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>visa.png"/>
                    <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>mastercard.png"/>
                    <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>amex.png"/>
                </div>
            </button>
        </div>
        <div class="credit-cards">
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>visa.png"/>
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>mastercard.png"/>
            <img src="<?php echo $block->getUrl("media/wysiwyg/payment-gateways/icons/")?>amex.png"/>
        </div>
        <div id="paypal-custom">
        </div>
        <div id="zip-custom">
            <span class="zip-caption">
                <span class="zip-interest">0% Interest for 6 Months</span>
                <span class="zip-apply-now">APPLY NOW!</span>
            </span>
        </div>
    </div>
</div>

<script>
    require([
            'jquery'
        ],
        function ($) {
           $('#paypal-custom').append($('#paypal-smart-button'));
    });
</script>
