<div class="custom-preloader"></div>

<style type="text/css">
    .custom-preloader {
        display: none;
        margin: auto;
        margin-top: 240px;
        vertical-align: middle;
        border: 7px solid #f5f5f5;
        border-radius: 50%;
        border-top: 7px solid #000;
        width: 50px;
        height: 50px;
        -webkit-animation: spin 2s linear infinite; /* Safari */
        animation: spin 2s linear infinite;
    }
    
    @-webkit-keyframes spin {
        0% { -webkit-transform: rotate(0deg); }
        100% { -webkit-transform: rotate(360deg); }
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>