<?php

$pricingHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_attributeValue = $block->getProduct()->getResource()->getAttribute('preorder')->getFrontend()->getValue($block->getProduct());
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset qty-fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                <div class="control qty-group-control" data-bind="scope: 'qty-change'">
                    <input data-bind="value: qty()"
                           type="number"
                           name="qty"
                           id="qty"
                           value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                           title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                           class="input-text qty qty-pdp"
                           data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />

                    <div class="qty-buttons">
                        <div role="button" data-bind="click: increaseQty"><i class="fas fa-angle-up"></i></div>
                        <div role="button" data-bind="click: decreaseQty"><i class="fas fa-angle-down"></i></div>
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <div class="actions">
                    <?php if ($_attributeValue == "Yes"): ?>
                        <button type="submit"
                            class="action tocart btn_cart tocart-pdp-btn"
                            id="product-addtocart-button"
                            data-action="add-to-cart-action"
                            style="background: #00C3FF !important"
                        >
                            <div class="addtocart-tooltip" style="float: left;">
                                <i class="fas fa-info-circle" style="font-family: 'Font Awesome 5 Free';font-style: unset;float: left;color: #fff;"></i>
                                <div class="addtocart-tooltiptext tooltip-bottom">
                                    Clicking this button and moving through to purchase means you reserve your allocation for this awesome product. For the latest ETA, please click <a href="https://www.digidirect.com.au/contact/">here</a> to contact us.
                                </div>
                            </div>
                            <i class="fa-solid fa-cart-plus" style=" font-family: 'Font Awesome 5 Free';font-style: unset;color: #fff;padding-right: 5px;"></i>
                            <span class="addcart_words"><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                        </button>
                    <?php else : ?>
                        <button type="submit"
                            class="action tocart btn_cart tocart-pdp-btn"
                            id="product-addtocart-button"
                            data-action="add-to-cart-action"
                            >
                            <i class="fa-solid fa-cart-plus" style=" font-family: 'Font Awesome 5 Free';font-style: unset;color: #fff;padding-right: 5px;"></i>
                            <span class="addcart_words"><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                        </button>
                    <?php endif; ?>

                <?= $block->getChildHtml('', true) ?>
            </div>
            <div class="product-addto-wishlist" data-role="add-to-wishlist">
                <?= $block->getLayout()
                    ->createBlock('Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist')
                    ->setProduct($_product)
                    ->setTemplate("Magento_Wishlist::catalog/product/list/addto/wishlist.phtml")
                    ->toHtml(); ?>
            </div>
        </div>
    </div>
<?php endif; ?>