<?php
$productInfoBlock = $block->getLayout()->getBlock('product.info');
$_product = $productInfoBlock ? $productInfoBlock->getProduct() : null;
$addToCartUrl = $_product ? $productInfoBlock->getSubmitUrl($_product) : '';
?>


<div class="sticky-addtocart">
    <form action="<?php echo $addToCartUrl; ?>" method="post" id="product_addtocart_form" novalidate="novalidate">
        <?php echo $block->getBlockHtml('formkey')?>
        <button type="submit"
            class="action tocart btn_cart tocart-pdp-btn"
            id="product-addtocart-button"
            data-action="add-to-cart-action"
            >
            ADD TO CART
        </button>
    </form>
</div>
