<div class="header-links header-link-left">
    <a class="call-us-link" href="tel:1300 889 148" title="call-us">
        <img src="<?= $block->getViewFileUrl('images/icons/iconsax-call.svg') ?>" alt="Call Us" />
        <span class="company-number"> 1300 889 148</span>
    </a>
    <a class="store-locator-link" href="/store-locator" title="Store Locator">
        <img src="<?= $block->getViewFileUrl('images/icons/iconsax-location.svg') ?>" alt="Store Locator" /> Store Locator
    </a>
    <a class="digiservices-link" href="/#digiservices" title="digiServices">
        <img src="<?= $block->getViewFileUrl('images/icons/box.svg') ?>" alt="Services" /> Services
    </a>
    <a class="faq-link" href="/faq" title="FAQ">
        <img src="<?= $block->getViewFileUrl('images/icons/message-text.svg') ?>" alt="Questions" /> Questions?
    </a>
</div>
<div class="header-links header-link-right" style="margin-left: auto;">
    <a class="digiclub-link" href="/digiclub" title="digiClub">
        <img src="<?= $block->getViewFileUrl('images/icons/airdrop.svg') ?>" alt="digiClub" /> <span style="font-weight: 700;"><span style="color: #FE4C25;"> digi</span>Club</span>
    </a>
    <a class="gift-cards-link" href="https://digidirectgiftcards.viisolutions.com.au/" title="GIFT CARDS">
        <img src="<?= $block->getViewFileUrl('images/icons/iconsax-gift.svg') ?>" alt="Gift Card" /> Gift Card
    </a>
    <a class="click-and-collect-link" href="/pickup-instore" title="Click & Collect">
        <img src="<?= $block->getViewFileUrl('images/icons/cc.png') ?>" alt="Click & Collect" /> Click & Collect
    </a>
    <a class="digibusiness-link" href="/b2b" title="digiClub">
        <img src="<?= $block->getViewFileUrl('images/icons/iconsax-briefcase-cross.svg') ?>" alt="digiDirect Business" /> digiDirect Business
    </a>
</div>