<!-- START: RUBY DEMO HEADER -->
<div class="ruby-menu-demo-header">
    <!-- ########################### -->
    <!-- START: RUBY HORIZONTAL MENU -->
    <div class="ruby-wrapper">
      <button class="c-hamburger c-hamburger--htx visible-xs">
        <span>toggle menu</span>
      </button>
      <ul class="ruby-menu">

        <li class="ruby-menu-mega-blog"><a href="#">Products </a><img src="<?= $block->getViewFileUrl('images/icons/iconsax-arrow-down-02.svg') ?>"/>
          <div class="facelift-dropdown-container">
            <ul class="ruby-menu-mega-blog-nav">
              <li class="ruby-active-menu-item"><a href="https://www.digidirect.com.au/cameras">Photography</a>
                <div class="ruby-grid ruby-grid-lined" style="">
                  <div class="ruby-row">
                    <div class="ruby-col-3">
                      <ul class="facelift-mega-menu-items">
                        <li class="facelift-mega-menu-item item-heading">
                          <a class="item-link" href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/camera-cables-and-adapters">Cables & Adaptors</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables-and-adaptors/adaptors">Adaptors</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables">Audio Cables</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables-and-adaptors/usb-cables">USB Cables</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/pro-video/video-monitors-and-recorders/video-cables">Video Cables</a>
                        </li>
                      </ul>
                      <ul class="facelift-mega-menu-items">
                        <li class="facelift-mega-menu-item item-heading">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras">Cameras</a> 
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/action-cameras">Action Cameras</a> 
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/video-cameras">Camcorders</a> 
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/pro-video/pro-video-cameras">Cinema Cameras</a> 
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/compact-cameras">Compact Cameras</a> 
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/cameras-dslr-cameras">DSLR Cameras</a> 
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/film-cameras">Film Cameras</a> 
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/mirrorless-cameras">Full Frame Cameras</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/instant-cameras">Instant Cameras</a> 
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/medium-format-cameras">Medium Format Cameras</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/mirrorless-cameras">Mirrorless Cameras</a>  
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/pro-video/pro-video-cameras">Pro Video Cameras</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/rangefinder-cameras">Rangefinder Cameras</a> 
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/cameras/waterproof-cameras">Waterproof Cameras</a> 
                        </li>
                      </ul>
                    </div>
                    <div class="ruby-col-3">
                      Content
                    </div>
                    <div class="ruby-col-3">
                      Content
                    </div>
                    <div class="ruby-col-3">
                      Content
                    </div>
                  </div>
                </div>
              <span class="ruby-dropdown-toggle"></span></li>

              <li class="hidden-md"><a href="https://www.digidirect.com.au/computers-mobile">Computers & Monitors</a>
                <div class="ruby-grid ruby-grid-lined" style="">
                  <div class="ruby-row">
                    <div class="ruby-col-4">
                      <ul class="facelift-mega-menu-items">
                        <li class="facelift-mega-menu-item item-heading">
                          <a class="item-link" href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/camera-cables-and-adapters">Cables & Adaptors</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables-and-adaptors/adaptors">Adaptors</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables">Audio Cables</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables-and-adaptors/usb-cables">USB Cables</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/pro-video/video-monitors-and-recorders/video-cables">Video Cables</a>
                        </li>
                      </ul>
                    </div>
                    <div class="ruby-col-4">
                      Content
                    </div>
                    <div class="ruby-col-4">
                      Content
                    </div>
                  </div>
                </div>
              <span class="ruby-dropdown-toggle"></span></li>

              <li><a href="https://www.digidirect.com.au/computers-mobile/mobile-phones-and-accessories">Mobile Phones & Tablets</a>
                <div class="ruby-grid ruby-grid-lined" style="">
                  <div class="ruby-row">
                    <div class="ruby-col-6">
                      <ul class="facelift-mega-menu-items">
                        <li class="facelift-mega-menu-item item-heading">
                          <a class="item-link" href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/camera-cables-and-adapters">Cables & Adaptors</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables-and-adaptors/adaptors">Adaptors</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables">Audio Cables</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables-and-adaptors/usb-cables">USB Cables</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/pro-video/video-monitors-and-recorders/video-cables">Video Cables</a>
                        </li>
                      </ul>
                    </div>
                    <div class="ruby-col-6">
                      Content
                    </div>
                  </div>
                </div>
              <span class="ruby-dropdown-toggle"></span></li>

              <li><a href="https://www.digidirect.com.au/audio-and-visual">Audio & Visual</a>
                <div class="ruby-grid ruby-grid-lined" style="">
                  <div class="ruby-row">
                    <div class="ruby-col-6">
                      <ul class="facelift-mega-menu-items">
                        <li class="facelift-mega-menu-item item-heading">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/dvd-player">Blu-Ray & DVD Players</a>
                        </li>
                        <li class="facelift-mega-menu-item item-heading">
                          <a class="item-link" href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/camera-cables-and-adapters">Cables & Adaptors</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables-and-adaptors/adaptors">Adaptors</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables">Audio Cables</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/audio-and-visual/cables-and-adaptors/usb-cables">USB Cables</a>
                        </li>
                        <li class="facelift-mega-menu-item">
                          <a class="item-link" href="https://www.digidirect.com.au/pro-video/video-monitors-and-recorders/video-cables">Video Cables</a>
                        </li>
                      </ul>
                    </div>
                    <div class="ruby-col-6">
                      Content
                    </div>
                  </div>
                </div>
              <span class="ruby-dropdown-toggle"></span></li>
            </ul>
          </div>
        <span class="ruby-dropdown-toggle"></span></li>
        
        <li class="ruby-menu-mega-blog"><a href="#">Brands </a><img src="<?= $block->getViewFileUrl('images/icons/iconsax-arrow-down-02.svg') ?>"/></li>
        <li class="ruby-menu-mega-blog"><a href="#"><span class="digi">digi</span>Deals</a></li>
        <li class="ruby-menu-mega-blog"><a href="#"><span class="digi">digi</span>Seconds </a><img src="<?= $block->getViewFileUrl('images/icons/iconsax-arrow-down-02.svg') ?>"/></li>
        <li class="ruby-menu-mega-blog"><a href="#"><span class="digi">digi</span>Market</a></li>
        <li class="ruby-menu-mega-blog"><a href="#"><span class="digi">digi</span>Print </a><img src="<?= $block->getViewFileUrl('images/icons/iconsax-arrow-down-02.svg') ?>"/></li>

      </ul>
    </div>
    <!-- END:   RUBY HORIZONTAL MENU -->
    <!-- ########################### -->

  </div>
<!-- END: RUBY DEMO HEADER -->