<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<div class="mobile-menu" style="display: none;">
    <h2>Products</h2>
    <h2>Brands</h2>
    <ul class="brand-list">
        <li><a href="#"><span class="brand-prefix">digi</span>Deals</a></li>
        <li><a href="#"><span class="brand-prefix">digi</span>Seconds</a></li>
        <li><a href="#"><span class="brand-prefix">digi</span>Print</a></li>
        <li><a href="#"><span class="brand-prefix">digi</span>Business</a></li>
        <li><a href="#"><span class="brand-prefix">digi</span>Club<sup>®</sup></a></li>
    </ul>

    <ul class="info-list">
        <li><a href="tel:1300889148">1300 889 148</a></li>
        <li><a href="#">Store Locator</a></li>
        <li><a href="#">Gift Card</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Click & Collect</a></li>
        <li><a href="#">Questions?</a></li>
    </ul>
</div>
