<div class="account-popup-header-in-pages">

<!--    <button class="close-popup" aria-label="Close">&times;</button>-->
<!--    <div class="close-popup">-->
<!--        <img src="--><?php //= $block->getViewFileUrl('images/mobile-menu-close.png') ?><!--">-->
<!--    </div>-->
    <div class="goback">
        <img src="<?= $block->getViewFileUrl('images/mobile-menu-back.png') ?>"/>
        <span class="goback-txt">Back</span>
    </div>
    <span class="signout">Sign Out</span>
</div>

