<nav class="custom-nav">
  <ul class="nav-menu">
    <li><a href="#">Products <img src="<?= $block->getViewFileUrl('images/icons/iconsax-arrow-down-02.svg') ?>"/></a></li>
    <li><a href="#">Brands <img src="<?= $block->getViewFileUrl('images/icons/iconsax-arrow-down-02.svg') ?>"/></a></li>
    <li><a href="#"><span class="digi">digi</span>Deals</a></li>
    <li><a href="#"><span class="digi">digi</span>Seconds <img src="<?= $block->getViewFileUrl('images/icons/iconsax-arrow-down-02.svg') ?>"/></a></li>
    <li><a href="#"><span class="digi">digi</span>Market</a></li>
    <li><a href="#"><span class="digi">digi</span>Print <img src="<?= $block->getViewFileUrl('images/icons/iconsax-arrow-down-02.svg') ?>"/></a></li>
  </ul>
</nav>