<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */
?>
<?php
$_product = $block->getProduct();
$prontoStockStatus = $_product->getAttributeText('stock_status');
$prontoStockStatusSpecialValue = 'I';

?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($prontoStockStatus && $prontoStockStatus == $prontoStockStatusSpecialValue): ?>
        <div class="stock special" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span><?= /* @escapeNotVerified */ __('Special Delivery') ?></span>
        </div>
    <?php else: ?>
        <?php if ($_product->isAvailable()): ?>
            <p class="stock available" title="<?= /* @escapeNotVerified */ __('Availability:') ?>">
                <span><?= /* @escapeNotVerified */ __('In stock') ?></span>
            </p>
        <?php else: ?>
            <p class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability:') ?>">
                <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
            </p>
        <?php endif; ?>
    <?php endif ?>
<?php endif; ?>
<?= $block->getChildHtml('bundle_prices') ?>
