<?php use Ewave\Digi\Helper\SddShippingChecker;

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$freeGift = ($_item->getPrice()==0) ? '-free-gift':'';
$congigProductClass = ($isVisibleProduct && $block->getItem()->getData('product_type')!='simple') ? '-config':'';
$quoteHelper = $helper = $this->helper('Ewave\Digi\Helper\Quote');
$isProductWebOnly = $quoteHelper->isProductWebOnly($product);
$preOrderStatus = \Ewave\PreOrder\Helper\Data::BACKORDERS_PREORDER_OPTION;
$points = $product->getFinalPrice();
$finalQffPoints = $product->getPoints();
/**
 * @var $sddShippingChecker Ewave\Digi\Helper\SddShippingChecker
 */
$sddShippingChecker = $this->helper(SddShippingChecker::class);
$productData = $sddShippingChecker->createProductData($product->getId(), $_item->getQty());
$isSddAvailable = $sddShippingChecker->getCheckResult($productData);
?>
<tbody class="cart item <?php /* @escapeNotVerified */ echo $freeGift;?>" id="cart-item-<?php echo (int)$_item->getId(); ?>">
<tr class="item-info <?php echo $congigProductClass; ?>">
    <td data-th="<?php echo $block->escapeHtml(__('Item')); ?>" class="col item">
        <?php if ($block->hasProductUrl()):?>
            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
               title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo">
                <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>

            <?php if ($block->hasProductUrl()):?>
            </a>
    <?php else: ?>
        </span>
    <?php endif; ?>
        <span class="item-actions">
            <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
        </span>
        <div class="product-item-details">
            <?php $checkExtensionAttr = $product->getExtensionAttributes(); ?>
            <?php if (!empty($checkExtensionAttr)): ?>
            <?php  $checkIsPreOrderStatus = $product->getExtensionAttributes()->getStockItem()->getBackOrders();?>
                <?php if ($checkIsPreOrderStatus == $preOrderStatus): ?>
                    <div class="preorder-title">
                        <span><?php /* @escapeNotVerified */ echo __("Pre-order"); ?></span>
                    </div>
                    <div class="preorder-note-txt">
                        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                        <?php if ($addInfoBlock): ?>
                            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
                        <?php endif;?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()):?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?php echo $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($isSddAvailable):?>
            <div class="pickup-available-wrapper">
                <span class="pickup-available-text"><?php /* @escapeNotVerified */ echo __("Available for Same-Day Delivery"); ?></span>
            </div>
            <?php endif; ?>
            <?php if ($_options = $block->getOptionList()):?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_option['custom_html'])): ?>
                                <?php /* @escapeNotVerified */ echo $_option['custom_html'] ?>
                            <?php elseif (isset($_formatedOptionValue['full_view'])): ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if ($isProductWebOnly) : ?>
                <div class="cart item message webonly-message">
                    <span><?php /* @escapeNotVerified */ echo __("This product is available for delivery only."); ?></span>
                </div>
            <?php endif; ?>
                    
            <div class="qantas-pts-wrapper push-left">
                <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-qantas"></use></svg>
                <span>Earn <?= ceil($points*2); ?> Qantas Points</span>
            </div>
        </div>
    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                    </a>
                </span>
        </td>
    <?php else: ?>
        <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <?php echo $block->getUnitPriceHtml($_item); ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <div class="field qty">
            <label class="label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
            </label>
            <div class="control qty">
                <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                       name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                       data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                       value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                       type="number"
                       size="4"
                       title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                       class="input-text qty"
                       maxlength="12"
                       data-validate="{'required':true,'validate-greater-than-zero':true}"
                       data-role="cart-item-qty"/>
            </div>
            <button type="submit"
                    name="update_cart_action"
                    data-cart-item-update=""
                    value="update_qty"
                    title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                    class="action update">
                <span><?= /* @escapeNotVerified */ __('Update') ?></span>
            </button>
        </div>
    </td>

    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?php echo $block->getRowTotalHtml($_item); ?>
        <?php endif; ?>
    </td>
</tr>
</tbody>