<?php
/** @var \Magento\Contact\Block\ContactForm $block */
?>

<style>
.cms-bg-block .bg-cms { display: none !important; }
.page-main.cms-bg-block .page-title { color: #222 !important; }
.contact-page.-cms-page { background: #f5f5f5; }

.form.contact legend,
.form.contact .field.note.no-label { display: none; }

.form.contact .fieldset > .field:not(.choice) > .label {
    text-align: left !important;
    margin-bottom: 10px;
}

.form.contact input,
.form.contact textarea {
    border-radius: 5px !important;
    border: 1px solid #D9D9D9 !important;
}

.form.contact input { height: 40px !important; }
.form.contact textarea { height: 150px !important; }

.contact-page > .left-column {
    width: 100% !important;
    padding-right: 0 !important;
    margin: 15px 0 0;
}

.contact-form button {
    background: #FE4C25 !important;
    border-radius: 50px !important;
}

@media screen and (max-width: 768px) {
    .contact-form .actions-toolbar { margin-left: unset; }
    .contact-form .actions-toolbar > .primary,
    .contact-form .actions-toolbar > .secondary {
        text-align: center;
        margin-bottom: 10px;
    }
}
</style>

<div class="contact-us-wrapper">
    <form class="form contact contact-form"
          action="<?= $block->escapeUrl($block->getFormAction()) ?>"
          id="contact-form"
          method="post"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>

        <fieldset class="fieldset">
            <legend class="legend"><?= $block->escapeHtml(__('What is your enquiry about?')) ?></legend><br/>

            <div class="field name required">
                <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                <div class="control">
                    <input name="name" id="name" autocomplete="name"
                           title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                           value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>"
                           class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>

            <div class="fields -row">
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="email" id="email" autocomplete="email"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                               value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>"
                               class="input-text" type="email"
                               data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>

                <div class="field telephone">
                    <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone')) ?></span></label>
                    <div class="control">
                        <input name="telephone" id="telephone" autocomplete="tel"
                               title="<?= $block->escapeHtmlAttr(__('Phone')) ?>"
                               value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>"
                               class="input-text" type="text"/>
                    </div>
                </div>
            </div>

            <div class="field comment required">
                <label class="label" for="comment"><span><?= $block->escapeHtml(__('Message')) ?></span></label>
                <div class="control">
                    <textarea name="comment" id="comment" class="comment-input input-text"
                              title="<?= $block->escapeHtmlAttr(__('Message')) ?>"
                              cols="5" rows="6"
                              data-validate="{required:true}">
                        <?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?>
                    </textarea>
                </div>
            </div>

            <?= $block->getChildHtml('form.additional.info') ?>
        </fieldset>

        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value=""/>
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"
                        class="action submit -responsive">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
