<div id="modal-container" data-bind="scope:'login-popup'" >
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
           "components": {
                "login-popup": {
                    "component": "Digidirect_PaSalesForceProductRecommendation/js/login_popup"
                }
            }
        }
    }
}
</script>