<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Remove $block */
?>

<a href="#"
   data-role="remove"
   data-post-remove='<?= /* @noEscape */ $block->getItemRemoveParams($block->getItem()); ?>'
   title="<?= $block->escapeHtmlAttr(__('Remove')); ?>"
   class="btn-remove action delete">
    <span><?= $block->escapeHtml(__('Remove')); ?></span>
</a>
