<?php
/** @var $block \Digidirect\Customer\Block\CustomerHeaderLinks*/
?>
<?php
/** @var \Digidirect\Customer\ViewModel\Customer $viewModel */
$viewModel = $block->getData('view_model');
$isLoggedIn = $viewModel->isLoggedIn();
?>
<!-- 🔹 Wishlist -->
<a class="wishlist-container" href="<?= $block->getUrl('wishlist') ?>">
    <img src="<?= $block->getViewFileUrl('images/icons/iconsax-heart.svg') ?>" alt="Wishlist" />
    <span>Wishlist</span>

    <?php if ($isLoggedIn) :?>
        <div class="wishlist-count"><?= $viewModel->getWishlistItemsCount(); ?></div>
    <?php endif; ?>
</a>

<!-- 🔹 Cart Trigger -->
<a class="action showcart" href="javascript:void(0);" data-bind="scope: 'minicart_content'">
    <img src="<?= $block->getViewFileUrl('images/icons/iconsax-shopping-cart.svg') ?>" alt="Cart" />
    <span>Cart</span>
    <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
    <span class="counter qty empty"
          data-bind="css: { empty: !getCartParam('summary_count') }, blockLoader: isLoading">
            <span class="counter-number" data-bind="text: getCartParam('summary_count')"></span>
        </span>
</a>

<!-- 🔹 Login -->
<?php if (!$isLoggedIn) :?>
    <a class="action login" href="<?= $block->getUrl('customer/account/login') ?>">
        <img src="<?= $block->getViewFileUrl('images/icons/iconsax-user.svg') ?>" alt="Login" />
        <span>Login</span>
    </a>
<?php else :?>
    <a class="action logout" href="<?= $block->getUrl('customer/account/logout') ?>" class="account-box">
        <div class="account-icon">
            <img src="<?= $block->getViewFileUrl('images/myaccount/account.svg') ?>" alt="Log out" />
        </div>
        <div class="account-text">
            <p class="hello"><span class="username"><?= $viewModel->getFirstName();?></span></p>
            <span class="logout">Logout</span>
        </div>
    </a>
<?php endif; ?>
