<?php

?>

<div class="pa-digidirect-product-widget pa-minicart-widget">
    <div class="product-widget-header" style="display: block;">
      <div class="widget-main-label" style="text-align: center; color: #242426; font-size: 64px; font-weight: 600;">You may also like</div>
    </div>
    <div id="pa-minicart-widget-desktop" class="pa-digidirect-product-widget-container desktop-widget real-container owl-carousel pa-minicart"></div>
</div>
