<div class="helpful-info" id="helpfullSlider" data-mage-init='{
                                "slickInit":{
                                    "arrows": false,
                                    "slidesToShow": 1,
                                    "slidesToScroll": 1,
                                    "mobileFirst": true,
                                    "waitForAnimate": false,
                                    "infinite": false,
                                    "swipeToSlide": false,
                                    "dots": false,
                                    "autoplay": true,
                                    "autoplaySpeed": 5000,
                                    "fade": true,
                                    "cssEase": "linear",
                                    "speed": 500,
                                    "responsive": [
                                        {
                                            "breakpoint": 767,
                                            "settings": {"slidesToShow": 3,
                                            "arrows": false,
                                            "fade": false,
                                            "autoplay": false,
                                            "autoplaySpeed": 0
                                            }
                                        }
                                    ]
                                }
                            }'>
    <?= $block->getChildHtml('default.cms.helpful.info.one') ?>
    <?= $block->getChildHtml('default.cms.helpful.info.two') ?>
    <?= $block->getChildHtml('default.cms.helpful.info.three') ?>
</div>