<?php
/**
 * @var \Magento\GiftCardAccount\Block\Account\Redeem $block
 * @see \Magento\GiftCardAccount\Block\Account\Redeem
 */
?>
<div class="giftcard-account block">
    <span id="gc-please-wait" class="please-wait load indicator"
          data-text="<?= $block->escapeHtml(__('This won\'t take long . . .')) ?>" style="display: none;">
        <span><?= $block->escapeHtml(__('This won\'t take long . . .')) ?></span>
    </span>
    <form class="form form-giftcard-redeem" id="giftcard-form" action="<?= $block->escapeUrl($block->getUrl('*/*/*')) ?>" method="post"
          data-mage-init='{
            "giftCard": {
                "giftCardCodeSelector": "#giftcard-code",
                "checkStatus": ".action.check",
                "giftCardFormSelector": "#giftcard-form",
                "giftCardStatusUrl": "<?= $block->escapeUrl($block->getUrl('magento_giftcardaccount/cart/quickCheck',  ['_secure' => true])) ?>",
                "giftCardStatusId": "#giftcard-balance-lookup", "giftCardSpinnerId": "#gc-please-wait", "messages": ".page.messages .messages",
                "preventSubmit": true
            }
        }'>
        <div id="giftcard-balance-lookup" class="giftcard ballance"></div>
        <div class="wrap-content">
            <fieldset class="fieldset">
                <div class="field giftcard required">
                    <label class="label" for="giftcard-code">
                        <span><?= $block->escapeHtml(__('Enter gift card code')) ?></span>
                    </label>
                    <div class="control">
                        <input class="input-text" id="giftcard-code" type="text" name="giftcard_code"
                               data-validate="{required:true}"
                               value="<?= /* @noEscape */ $block->getCurrentGiftcard() ?>" />
                    </div>
                </div>
            </fieldset>
            <?= /* @noEscape */ $block->getChildHtml('captcha') ?>
            <div class="actions-toolbar">
                <div class="secondary">
                    <button class="action check -default" id="gca_balance_button" type="submit"
                            value="<?= $block->escapeHtml(__('Check balance')) ?>">
                        <span><?= $block->escapeHtml(__('Check Balance')) ?></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
