<?php
    /** @var Ewave\ProductCalculator\Block\Product\Renderer\Listing\Configurable $block */
    $productId = $block->getProduct()->getId();
?>
<div class="swatch-opt-<?php /* @escapeNotVerified */ echo $productId ?>" data-role="swatch-option-<?= /* @escapeNotVerified */ $productId ?>"></div>
<?php
    if ($block->isProductRendered($block->getProduct())) {
        return '';
    }
    $block->saveRenderedProduct($block->getProduct());
?>
<script type="text/x-magento-init">
    {
        "[data-role=swatch-option-<?= /* @escapeNotVerified */ $productId ?>]": {
            "Magento_Swatches/js/swatch-renderer": {
                "selectorProduct": ".product-item-details",
                "onlySwatches": true,
                "enableControlLabel": false,
                "numberToShow": <?= /* @escapeNotVerified */ $block->getNumberSwatchesPerProduct(); ?>,
                "jsonConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig(); ?>,
                "jsonSwatchConfig": <?= /* @escapeNotVerified */ $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?= /* @escapeNotVerified */ $block->getMediaCallback() ?>"
            }
        }
    }
</script>
