<?php
/** @var \Ewave\LayeredNavigation\Helper\FilterRemember $remember */
$remember = $this->helper('Ewave\LayeredNavigation\Helper\FilterRemember');
$isRemember = $remember->isFilterRememberEnabled() && !$remember->isFiltersApplied();
$applyMobileOnly = $block->showApplyButtonOnMobileOnly();
?>
<?php if ($isRemember): ?>
    <div class="block filter" data-role="filter-remember"></div>
<?php endif; ?>
<?php if ($block->canShowBlock()): ?>
    <button id="ln-apply" class="primary ln-apply<?php if ($isRemember): ?> -hide<?php endif; ?><?php if
    ($applyMobileOnly): ?> -mobile-only<?php endif; ?> -color-type-3" title="<?php echo
    $block->escapeHtml(__('Show Results')); ?>">
        <?php echo $block->escapeHtml(__('Show Results')); ?>
    </button>
<?php endif; ?>