<?php
/** @var \Ewave\Faq\Block\Overview $block */
$categories = $block->getAllCategory();
$id = $block->getRequest()->getParam('id');
$faqType = $block->getFaqType();
$faqId = $block->getFaqId();
/**
 * @var $helper Ewave\Faq\Helper\Data
 */
$helper = $this->helper('Ewave\Faq\Helper\Data');
$ajaxCategoryLoading = $helper->isAjaxEnabled();
?>
<?php
/*    echo $this->escapeHtml($this->helper('Ewave\Utilities\Helper\Data')->getConfig('general/store_information/phone'));
*/?>

<div class="faq-wrapper" data-testid="faq-wrapper-container" data-mage-init='{"faq": {"url": "<?php echo $block->escapeUrl($block->getUrl('faq/index/ajaxview')); ?>", "baseUrl": "<?php echo $block->escapeUrl($block->getUrl($helper->getFaqUrl())); ?>"}}'>
    <div id="faq-container" class="faq-container<?php if ($id): ?> -active<?php endif; ?>" data-mage-init='{"loader": { "icon": "<?php /* @escapeNotVerified */ echo $block->escapeUrl($this->helper('Ewave\Utilities\Helper\Animation')->getImage()); ?>"
            <?php if($_loaderText = $this->helper('Ewave\Utilities\Helper\Animation')->getText()): ?>, "texts" : {"loaderText" : "<?php /* @escapeNotVerified */ echo $_loaderText; ?>"} <?php endif; ?>}}'>
        <div class="sidebar">
            <div class="faq-categories secondary-nav -cms" data-mage-init='{"secondaryNavigation": {"breakpoint": "(min-width: 1280px)", "element": ".secondary-nav", "trigger": ".-active, .-default", "navOpenClass": "-open", "navOverlay": ".secondary-nav-overlay"}}'>
                <?php $iterator = 1; foreach ($categories as $category): ?>
                    <?php /** @var $category Ewave\Faq\Model\Category */ ?>
                    <a class="item<?php if(!$faqType && $iterator == 1 || $faqType == 'category' && $faqId ==
                        $category->getId()): ?> -active<?php endif; ?>" data-testid="faq-category-item"
                        <?php if($ajaxCategoryLoading): ?> data-role="faq-item" <?php endif; ?> data-type="category" <?php if($ajaxCategoryLoading): ?> data-category-id="<?php echo $block->escapeHtml($category->getId()); ?>" <?php endif; ?> data-page="1"
                        href="<?php echo $block->escapeHtml($block->getUrl($category->getRequestPath())); ?>"
                        title="<?php echo $block->escapeHtml($category->getTitle()); ?>">
                        <?php /* @escapeNotVerified */ echo $block->stripTags($category->getTitle()); ?>
                    </a>
                <?php $iterator++; endforeach; ?>
                <a class="item -default"
                    href="<?php echo $block->escapeUrl($block->getUrl($helper->getFaqUrl())); ?>" title="<?php /* @escapeNotVerified */ echo __('Please select a ctegory'); ?>">
                    <?php /* @escapeNotVerified */ echo __('Please select a ctegory'); ?>
                </a>
            </div>
            <div class="secondary-nav-overlay">
            </div>
            <a href="#faq-question-form" title="<?php /* @escapeNotVerified */ echo __('Ask a Question') ?>" class="button ask-button _hide-for-mobile-tablet-l" data-role="question-button">
                <?php /* @escapeNotVerified */ echo __('Ask a Question') ?>
            </a>
        </div>
        <div class="background">
            <?php echo $block->getChildHtml('page.cms.bg'); ?>
        </div>
        <div class="listing">
            <div class="title _text-center">
                <?php echo $block->getChildHtml('page.main.title'); ?>
            </div>
            <?php if ($this->helper('Ewave\Faq\Helper\Data')->isSearchEnabled()) : ?>
                <div class="faq-block -search faq-search-block">
                    <div class="text">
                        <?php /* @escapeNotVerified */ echo __('Save time! Here\'s some Frequently Asked Questions to help you find the answer you\'re looking for.') ?>
                    </div>
                    <form class="faq-search form" method="post" id="faq-form" data-mage-init='{"validation":{}}'
                          action="<?php /* @escapeNotVerified */ echo $block->escapeUrl($block->getUrl('faq/index/ajaxview')) ?>">
                        <div class="input-group">
                            <div class="control">
                                <input type="text" name="keyword" id="keyword" data-testid="faq-search-key" placeholder="<?php /* @escapeNotVerified */ echo __('Search FAQ') ?>"
                                       class="input" size="30" maxlength="150" data-validate="{required: true}"/>
                            </div>
                            <button class="button" data-testid="faq-search-button" title="<?php /* @escapeNotVerified */ echo __('Search'); ?>">
                                <?php /* @escapeNotVerified */ echo __('Search'); ?>
                            </button>
                        </div>
                    </form>
                    <?php echo $block->getChildHtml('faq.tags'); ?>
                </div>
            <?php endif; ?>
            <div class="faq-block -listing faq-listing" data-role="faq-listing">
                <?php echo $block->getChildHtml('faq.listing'); ?>
            </div>
            <input type="hidden" value="most" id="faqtype" name="type"/>
            <input type="hidden" value="" id="faqid" name="categoryId"/>
            <a href="#faq-question-form" title="<?php /* @escapeNotVerified */ echo __('Ask a Question') ?>" class="button ask-button _hide-for-desktop" data-role="question-button">
                <?php /* @escapeNotVerified */ echo __('Ask a Question') ?>
            </a>
            <?php echo $block->getChildHtml('faq.question'); ?>
        </div>
    </div>
</div>
