<?php

use Mirasvit\SeoAutolink\Block\Adminhtml\Import\Edit;

/** @var Edit $block */
?>

<div class="import-export-link">
    <div class="import-link">
        <form id="import_form"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('seoautolink/import/save') ?>"
              method="post"
              enctype="multipart/form-data">
            <?php echo $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset admin__fieldset">
                <div class="admin__field required">
                    <label for="import_file" class="admin__field-label">
                        <span><?php /* @escapeNotVerified */ echo __('Import Links (.csv)') ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="file" id="import_file" name="import_file" class="input-file required-entry"/>
                        <?php echo $block->getButtonHtml(__('Import Links'), '', 'import-submit') ?>
                        <label for="file" id="file-error" class="mage-error" style="display: none;">
                            This is a required field.
                        </label>
                        <div class="note" id="file-note">
                            <a href="<?php  /* @escapeNotVerified */  echo $block->getDownloadUrl() ?>">Example of CSV file</a>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="export-link">
        <form id="export_form"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('seoautolink/import/export') ?>"
              method="post"
              enctype="multipart/form-data">
            <?php echo $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset admin__fieldset">
                <div class="admin__field">
                    <span class="admin__field-label">
                        <span><?php /* @escapeNotVerified */ echo __('Export Links (.csv)') ?></span>
                    </span>
                    <div class="admin__field-control">
                        <?php echo $block->getButtonHtml(__('Export Links'), 'export_form.submit()') ?>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<script>
    require(['jquery', "mage/mage", "loadingPopup"], function (jQuery) {
        jQuery('#import_form').mage('form').mage('validation');
        (function ($) {
            $('.import-submit').click(function () {
                if ($(':input[name="import_file"]').val()) {
                    $(this.form).submit();
                } else {
                    $('#file-error').show();
                }
            });
        })(jQuery);
    });
</script>
