stage:
  deploy:
    VERBOSE_COMMANDS: "-vvv"
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: true
    CACHE_CONFIGURATION:
      _merge: true
      default:
        backend_options:
          use_stale_cache: false
        stale_cache_enabled:
          backend_options:
            use_stale_cache: true
        type:
          default:
            frontend: "default"
          layout:
            frontend: "stale_cache_enabled"
          block_html:
            frontend: "stale_cache_enabled"
          reflection:
            frontend: "stale_cache_enabled"
          config_integration:
            frontend: "stale_cache_enabled"
          config_integration_api:
            frontend: "stale_cache_enabled"
          full_page:
            frontend: "stale_cache_enabled"
          translate:
            frontend: "stale_cache_enabled"
      frontend:
        default:
          backend_options:
            max_lifetime: 57600
            timeout: 10
    SESSION_CONFIGURATION:
      _merge: true
      redis:
        disable_locking: 1
        max_concurrency: 10
        max_lifetime: 100000
        timeout: 10
      save: redis
