<div class="plp-banner-widget">
    <div class="plp-banner" style="height: 265px;">
        <img class="banner-web" style="height: 100%; object-fit: cover;" src="<?= $block->getViewFileUrl('images/brands-pages/web/default.png') ?>" />
        <img class="banner-mobile" style="height: 100%; object-fit: cover; display: none;" src="<?= $block->getViewFileUrl('images/brands-pages/mobile/default.png') ?>" />
    </div>
</div>