<div class="plp-banner-widget">
    <div class="plp-banner" style="height: 265px;">
        <img class="banner-web" style="height: 100%; object-fit: cover;" src="<?= $block->getViewFileUrl('images/brands-pages/web/apple.png') ?>" />
        <img class="banner-mobile" style="height: 100%; object-fit: cover; display: none;" src="<?= $block->getViewFileUrl('images/brands-pages/mobile/apple.png') ?>" />
    </div>
    <div class="plp-row pa-widget" style="margin: -4px 0 0 0;">
        <div class="pa-digidirect-product-widget">
            <div class="product-widget-header">
                <div style="color: #242426; font-size: 32px; font-family: Inter; font-weight: 500; line-height: 33px; word-wrap: break-word">Here’s our top deals</div>
            </div>
            <div id="brands-recommended-widget-desktop" class="pa-digidirect-product-widget-container desktop-widget real-container owl-carousel custom"></div>
        </div>
    </div>
</div>