<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$faceBookPixel = $this->helper('Ewave\Digi\Helper\FaceBookPixel');
$googleAnalytic = $this->helper('Ewave\Digi\Helper\GoogleAnalytics');

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()): ?>
        <span class="header"><?= /* @escapeNotVerified */__('Your order has been received') ?></span>
        <span class="title"><?= /* @escapeNotVerified */__('Thank you for your purchase') ?></span>
        <?php if ($block->getCanViewOrder()) : ?>
            <span class="title -addition"><?= __('Your order no # %1', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></span>
        <?php else : ?>
            <span class="title -addition"><?= __('Your order # <span>%1</span>', $block->escapeHtml($block->getOrderId())) ?></span>
        <?php endif; ?>
        <p class="content"><?= /* @escapeNotVerified */__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" title="Continue Shopping" href="<?= /* @escapeNotVerified */$block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */__('Continue Shopping') ?></span></a>
        </div>
    </div>
    <div class="init _hidden">
        <script>
            if (typeof fbq !== undefined) {
                fbq('trackCustom', 'Purchase', <?php echo $faceBookPixel->getPurchaseData() ?>);
            }
        </script>
    </div>
</div>

<script>
    ga('require', 'ecommerce');

    ga('ecommerce:addTransaction', <?php echo $googleAnalytic->getPurchaseData() ?> );

    ga('ecommerce:send');
</script>