<div class="messages">
    <div class="message message-notice notice">
        <span class="code-sample">
            <?php /* @escapeNotVerified */ echo __('<b>‘Discount Amount’</b> field is used to specify the number of promo items provided for each discount step.') ?><br/>
            <?php /* @escapeNotVerified */ echo __('<b>‘Type’</b> field is used to specify if all specified products will be added to cart.') ?><br/>
            <?php /* @escapeNotVerified */ echo __('Choose <b>‘All SKUs below’</b> option to automatically add to cart all promo items.') ?><br/>
            <?php /* @escapeNotVerified */ echo __('<b>‘One of the SKUs below’</b> option will allow customers to choose one of available promo items, specified in Promo Items field.') ?><br/>
            <?php /* @escapeNotVerified */ echo __('<b>‘Maximum Qty Discount is Applied To’</b> is used to specify the max. number of free product customer can get per order.') ?><br/>
            <?php /* @escapeNotVerified */ echo __('<b>‘Discount Qty Step (Buy X)’</b> is used to choose per how many paid products one free should be added.') ?><br/>
            <?php /* @escapeNotVerified */ echo __(
                'It is impossible to use free gift options <b>‘%1’</b> or <b>‘%2’</b> with any rule conditions.',
                __('Enable Free Gift Block On Product Detail'),
                __('Show description on product details')
            ) ?>
        </span>
    </div>
</div>
