<?php
/** @var \Magento\Framework\View\Element\Template $block */

$faqIconUrl = $block->getViewFileUrl('Magento_Email::images/email-faq.png');
$accountIconUrl = $block->getViewFileUrl('Magento_Email::images/email-account.png');

$faqUrl = $block->getUrl('faq', ['_nosid' => true]);
$accountUrl = $block->getUrl('customer/account/', ['_nosid' => true]);
?>
<tr>
    <td>
        <table bgcolor="#f5f5f5" width="100%" cellpadding="0" cellspacing="0" border="0" style="border:none;">
            <tr>
                <td>
                    <table width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:600px; margin:0 auto; margin-bottom: 40px;">
                        <tr>
                            <td align="center" style="padding:15px;">
                                <table width="100%" cellpadding="0" cellspacing="0" border="0" class="mobiletable" style="background-color:#ffffff; max-width:600px; margin:0 auto; padding:20px; border-radius: 50px;">
                                    <tr>
                                        <td align="center">
                                            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                                                <tr>
                                                    <td width="60" align="center" valign="top" style="padding-right:10px; padding: 20px;">
                                                        <img src="<?= $block->escapeUrl($faqIconUrl) ?>" alt="questions" width="40" style="display:block; max-width:55px; margin-left: 60px; width: 40px;">
                                                    </td>
                                                    <td valign="top" style="padding-top: 17px;">
                                                        <p style="margin:0; font-size:14px; font-family:Arial,Helvetica,sans-serif; font-weight:bold; line-height:24px; color:#000000;">
                                                            <?= $block->escapeHtml(__('Have a question?')) ?>
                                                        </p>
                                                        <p style="font-size:12px; font-family:Arial,Helvetica,sans-serif; color:#666666; line-height:20px;">
                                                            <a href="<?= $block->escapeUrl($faqUrl) ?>" title="FAQS" style="color:#666666; text-decoration:none;"><?= $block->escapeHtml(__('View our FAQs')) ?></a>
                                                        </p>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>

                                        <td align="left" valign="top" style="width:50%; padding:10px 10px 10px 30px;" class="mobileStack">
                                            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                                                <tr>
                                                    <td width="60" align="center" valign="top" style="padding-right:5px;padding-top: 8px;">
                                                        <img src="<?= $block->escapeUrl($accountIconUrl) ?>" alt="account" width="44" style="display:block; max-width:44px;">
                                                    </td>
                                                    <td valign="top" style="padding-top: 10px;">
                                                        <p style="margin:0; font-size:14px; font-family:Arial,Helvetica,sans-serif; font-weight:bold; line-height:24px; color:#000000;">
                                                            <?= $block->escapeHtml(__('Manage my order')) ?>
                                                        </p>
                                                        <p style="font-size:12px; font-family:Arial,Helvetica,sans-serif; color:#666666; line-height:20px;">
                                                            <a href="<?= $block->escapeUrl($accountUrl) ?>" style="color:#666666; text-decoration:none;"><?= $block->escapeHtml(__('View My Account')) ?></a>
                                                        </p>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
