<?php
/**
 * @var \Ewave\ProductAttachment\Block\Product\View\Attachment $block
 * @var \Ewave\ProductAttachment\Model\Attachment $attachment
 */
?>
<?php foreach ($block->getAttachments() as $attachment): ?>
    <?php if ($block->canBeShown($attachment)): ?>
        <?php $attachmentName = $attachment->getName() ?>
        <div class="product-attachment">
            <?php echo $block->escapeHtml($attachmentName); ?>
            <a class="download" href="<?php echo $block->escapeUrl($block->getDownloadLink($attachment->getId())); ?>"
               title="<?php echo $block->escapeHtml(__('Download %1', $attachmentName)); ?>">
                <?php echo $block->escapeHtml(__('Download')); ?>
                <?php echo $block->escapeHtml($block->getFileFormat($attachment->getFileFormat())); ?>
                (<?php echo $block->escapeHtml($block->getFileSize($attachment->getFileSize())); ?>)
            </a>
        </div>
    <?php endif; ?>
<?php endforeach; ?>
