<?php
/**
 * Product list toolbar
 *
 * @var $block \Ewave\InfiniteScroll\Block\Product\ProductList\Toolbar
 */
?>
<?php $isShowAlways = true; ?>
<?php if ($block->getCollection()->getSize() || $isShowAlways): ?>
    <div class="toolbar toolbar-products" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
        <div class="mobile-row">
            <?= $block->getChildHtml('page.main.title');?>
            <?php if ($block->isExpanded()): ?>
                <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
            <?php endif; ?>
        </div>
        <div class="desktop-row">
            <div class="filter filter-trigger -mobile" data-container="#catalogSidebar" data-mage-init='{ "offcanvas": {"addOn":
            "js/components/offcanvas/dist/addons/catalog/index"} }'><?=  __('Filter');?></div>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
            <?php if ($block->isExpanded()): ?>
                <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
                <div class="sorter -mobile">
                    <span class="sorter-trigger" data-container="#sorterOffcanvas" data-mage-init='{ "offcanvas": {"addOn":
                    "js/components/offcanvas/dist/addons/catalog/index"} }'><?=  __('Sort By');?>
                    </span>

                    <?php if ($block->getCurrentDirection() == 'desc'): ?>
                        <a title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
                            <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
                        </a>
                    <?php else: ?>
                        <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
                            <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
                        </a>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <div id="sorterOffcanvas" class="sorter-container offcanvas-panel offcanvas-left -device-only -without-padding">
        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/sorter.phtml')) ?>
    </div>
<?php endif ?>