<?php

use Mirasvit\SeoToolbar\Api\Data\DataProviderItemInterface;
use Mirasvit\SeoToolbar\Block\Toolbar;

/** @var Toolbar $block */
?>
<div class="mst-seo-toolbar__toolbar">
    <div class="mst-seo-toolbar__toolbar-header" data-role="header">
        <i class="fa fa-tachometer"></i> <?= $block->escapeHtml(__('SEO Toolbar')) ?>

        <div class="close" data-role="close">
            <div class="icon-close">×</div>
        </div>
    </div>

    <div class="mst-seo-toolbar__toolbar-content">
        <?php foreach ($block->getSections() as $section => $items): ?>
            <section>
                <label><?= $block->escapeHtml($section) ?></label>

                <ul>
                    <?php /** @var DataProviderItemInterface $item */ ?>
                    <?php foreach ($items as $item): ?>
                        <li>
                            <div class="title"><?= $block->escapeHtml($item->getTitle()) ?></div>
                            <div class="status _<?= $block->escapeHtml($item->getStatus()) ?>"></div>
                                <div class="description">
                                    <div class="action"><?= /* @noEscape */ $item->getAction() ?></div>
                                    <?= /* @noEscape */ nl2br($block->escapeHtml($item->getDescription())) ?>
                                    <div class="note"><?= /* @noEscape */ nl2br($block->escapeHtml($item->getNote())) ?></div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ul>
            </section>
        <?php endforeach ?>
    </div>
</div>

<script>
    require([
        'jquery',
        'mage/cookies'
    ], function ($) {
        var $toolbar = $('.mst-seo-toolbar__toolbar');
        var cookieName = "mst-seo-toolbar";

        if ($.mage.cookies.get(cookieName) === 'off') {
            $toolbar.removeClass('_hidden').addClass('_hidden');
        } else {
            $toolbar.removeClass('_hidden');
        }

        $('[data-role=close]', $toolbar).on('click', function (e) {
            e.preventDefault();
            $toolbar.removeClass('_hidden').addClass('_hidden');
            $.mage.cookies.set(cookieName, 'off', {expires: new Date(Date.now() + (24 * 60 * 60)), path: '/'});
        });

        $('[data-role=header]', $toolbar).on('click', function (e) {
            if (!$(e.target).hasClass('icon-close')) {
                e.preventDefault();
                $toolbar.removeClass('_hidden');
                $.mage.cookies.set(cookieName, 'on', {expires: new Date(Date.now() + (24 * 60 * 60)), path: '/'});
            }
        });
    });
</script>
