<?php
/**
 * @var \Ewave\AbstractAttributes\Block\Widget\AttributeOptionsList $block
 */
?>
<?php $options = $block->getOptions() ?>
<?php if ($options): ?>
    <div class="widget-attribute widget" data-role="widget-attribute-carousel-<?php echo (int)$block->getAttributeId()
    ?>">
        <?php /** @var \Ewave\AbstractAttributes\Model\Option $option */ ?>
        <?php foreach ($options as $option): ?>
            <?php $image = $block->getImage($option) ?>
            <?php $title = $block->escapeHtml($option->getLabel()) ?>
            <div class="attribute-item">
                <a class="link" href="<?php echo $block->escapeUrl($option->getUrl()) ?>" title="<?php echo $block->escapeHtml($title); ?>">
                    <?php if ($image): ?>
                        <img class="image" src="<?php echo $block->escapeUrl($image->getSrc()) ?>" alt="<?php echo $block->escapeHtml($title); ?>"/>
                    <?php else: ?>
                        <?php echo $block->escapeHtml($title); ?>
                    <?php endif ?>
                </a>
            </div>
        <?php endforeach; ?>
    </div>

    <?php if (count($options) > 1): ?>
    <script>
        require([
            'jquery',
            'slickCarousel'
        ], function ($) {
            var $slider = $('[data-role="widget-attribute-carousel-<?php echo (int)$block->getAttributeId() ?>"]');
            if (!$slider.hasClass('slick-slider')) {
                $slider.slick({
                    infinite: false,
                    prevArrow: "<span class=\"slick-prev\">&larr;</span>",
                    nextArrow: "<span class=\"slick-next\">&rarr;</span>",
                    slidesToShow: 2,
                    slidesToScroll: 2,
                    mobileFirst: true,
                    responsive: [{
                        breakpoint: 1199,
                        settings: {
                            slidesToShow: 7,
                            slidesToScroll: 7
                        }
                    }, {

                        breakpoint: 767,
                        settings: {
                            slidesToShow: 4,
                            slidesToScroll: 4
                        }
                    }]
                });
            }
        });
    </script>
    <?php endif ?>
<?php endif ?>
