<?php
// @codingStandardsIgnoreFile
/**
 * @var $animationHelper \Digidirect\Utilities\Helper\Animation
 * if you want to get image url - use $animationHelper->getImage();
 * if you want to check if it's enabled - use $animationHelper->isEnabled();
 * if you want to get loader text - use $animationHelper->getText();
 */
$animationHelper = $this->helper('Digidirect\Utilities\Helper\Animation');
?>
<?php /* ?>
<script>
    var animationConfigJson = '<?php echo $animationHelper->getLoadingAnimationConfig(true); ?>';
</script>
<?php */ ?>