<div id="digimarketseler_form">
        <div class="container" >
            <header>Submit a request to join the digiDirect Marketplace</header>

                <form id="sellerForm" name="frm" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl("digimarketseller/index/index")?>">
                    
                    <label for="email">Your email address<span style="color: #ff0000">*</span></label>
                    <input type="email" id="email" name="email" placeholder="Your email address">

                    <div class="inline-row">
                        <div class="row1">
                            <label for="firstname">Firstname<span style="color: #ff0000">*</span></label>
                            <input type="text" id="firstname" name="firstname" placeholder="Firstname">
                        </div>
                        <div class="row1">
                            <label for="lastname">Lastname<span style="color: #ff0000">*</span></label>
                            <input type="text" id="lastname" name="lastname" placeholder="Lastname">
                        </div>
                    </div>

                    <label for="message">Message</label>
                    <textarea name="message" id="message" cols="10" rows="3"></textarea>

                    <label for="message">Attachement (optional)</label>
                    <div class="uploadfile drop-zone">
                        <span class="drop-zone__prompt1">Add file</span>
                        <span class="drop-zone__prompt2">or drop files here</span>
                        <input type="file" name="attachedfiles" class="drop-zone__input">
                    </div>
                    
                    <p>Hit submit and a digiDirect Marketplace specialist will contact you shortly.</p>

                    <br>

                    <?=$block->getChildHtml('form.additional.info') ?>
                    <input type="hidden" name="hideit" id="hideit" value="" />
                    <button type="submit" id="add" title="" class="action submit primary">
                        <span><?= $block->escapeHtml(__('SUBMIT')) ?></span>
                    </button>

                    <br><br>
                </form>
        </div>
</div>

<script>
document.querySelectorAll(".drop-zone__input").forEach((inputElement) => {
const dropZoneElement = inputElement.closest(".drop-zone");

  dropZoneElement.addEventListener("click", (e) => {
    inputElement.click();
  });

  inputElement.addEventListener("change", (e) => {
    if (inputElement.files.length) {
      updateThumbnail(dropZoneElement, inputElement.files[0]);
    }
  });

  dropZoneElement.addEventListener("dragover", (e) => {
    e.preventDefault();
    dropZoneElement.classList.add("drop-zone--over");
  });

  ["dragleave", "dragend"].forEach((type) => {
    dropZoneElement.addEventListener(type, (e) => {
      dropZoneElement.classList.remove("drop-zone--over");
    });
  });

  dropZoneElement.addEventListener("drop", (e) => {
    e.preventDefault();

    if (e.dataTransfer.files.length) {
      inputElement.files = e.dataTransfer.files;
      updateThumbnail(dropZoneElement, e.dataTransfer.files[0]);
    }

    dropZoneElement.classList.remove("drop-zone--over");
  });
});

/**
 * Updates the thumbnail on a drop zone element.
 *
 * @param {HTMLElement} dropZoneElement
 * @param {File} file
 */
function updateThumbnail(dropZoneElement, file) {
  let thumbnailElement = dropZoneElement.querySelector(".drop-zone__thumb");

  // First time - remove the prompt
  if (dropZoneElement.querySelector(".drop-zone__prompt")) {
    dropZoneElement.querySelector(".drop-zone__prompt").remove();
  }

  // First time - there is no thumbnail element, so lets create it
  if (!thumbnailElement) {
    thumbnailElement = document.createElement("div");
    thumbnailElement.classList.add("drop-zone__thumb");
    dropZoneElement.appendChild(thumbnailElement);
  }

  thumbnailElement.dataset.label = file.name;

  // Show thumbnail for image files
  if (file.type.startsWith("image/")) {
    const reader = new FileReader();

    reader.readAsDataURL(file);
    reader.onload = () => {
      thumbnailElement.style.backgroundImage = `url('${reader.result}')`;
    };
  } else {
    thumbnailElement.style.backgroundImage = null;
  }
}
</script>

<script>
require(['jquery'],function($){

    $(document).ready(function(){
        $("#add").click(function(){
        var customurl = "<?php echo $this->getUrl("digimarketseller/index/index") ?>";

        $.ajax({
            url: customurl,
            type: "POST",
            data: $(this).closest('form').serialize(),
            dataType: "json",
            success: function(result){
                console.log(result);
            }
        });
        $('#sellerForm')[0].reset(); 
        return false;
        });
    });


}); 


</script>
 