<?php

if(isset($_POST['button']))
{
  $recipient_email = 'digimarket@digidirect.com.au'; //recipient email address
	// $recipient_email = 'jireh.c@digidirect.com.au'; //developer email
	$from_email = $_POST["email"]; //from mail, sender email address
	$firstname = $_POST["firstname"];
	$lastname = $_POST["lastname"];
  $phone = $_POST["phonenumber"];
	$note = $_POST["message"]; //body of the email

	//Get uploaded file data using $_FILES array
	$tmp_name = $_FILES['attachment']['tmp_name']; // get the temporary file name of the file on the server
	$name	 = $_FILES['attachment']['name']; // get the name of the file
	$size	 = $_FILES['attachment']['size']; // get size of the file for size validation
	$type	 = $_FILES['attachment']['type']; // get type of the file
	// $error	 = $_FILES['attachment']['error']; // get the error (if any)

	//Load POST data from HTML form
	$sender_name = $firstname." ".$lastname; //sender name
	$subject = "DigiMarketSeller Form"; //subject for the email
	$message = "\n"."\n"."Fullname :"."\t".$sender_name."\n"."Email : "."\t".$from_email."\n"."Phone Number : "."\t".$phone."\n"."Message : "."\t".$note."\n"."\n";


	if (empty($tmp_name)) {

		$boundary = md5("random"); // define boundary with a md5 hashed value
		
		//header
		$headers = "MIME-Version: 1.0\r\n"; // Defining the MIME version
		$headers .= "From:".$from_email."\r\n"; // Sender Email
		$headers.='Bcc: Jai <jireh.c@digidirect.com.au>';

		$headers .= "Content-Type: multipart/mixed;"; // Defining Content-Type
		$headers .= "boundary = $boundary\r\n"; //Defining the Boundary

		//plain text
		$body = "--$boundary\r\n";
		$body .= "Content-Type: text/plain; charset=ISO-8859-1\r\n";
		$body .= "Content-Transfer-Encoding: base64\r\n\r\n";
		$body .= chunk_split(base64_encode($message));
	
	}else {

		//read from the uploaded file & base64_encode content
		$handle = fopen($tmp_name, "r"); // set the file handle only for reading the file
		$content = fread($handle, $size); // reading the file
		fclose($handle);				 // close upon completion

		$encoded_content = chunk_split(base64_encode($content));
		$boundary = md5("random"); // define boundary with a md5 hashed value

		//header
		$headers = "MIME-Version: 1.0\r\n"; // Defining the MIME version
		$headers .= "From:".$from_email."\r\n"; // Sender Email
		$headers.='Bcc: Jai <jireh.c@digidirect.com.au>';

		$headers .= "Content-Type: multipart/mixed;"; // Defining Content-Type
		$headers .= "boundary = $boundary\r\n"; //Defining the Boundary
			
		//plain text
		$body = "--$boundary\r\n";
		$body .= "Content-Type: text/plain; charset=ISO-8859-1\r\n";
		$body .= "Content-Transfer-Encoding: base64\r\n\r\n";
		$body .= chunk_split(base64_encode($message));

		//attachment
		$body .= "--$boundary\r\n";
		$body .="Content-Type: $type; name=".$name."\r\n";
		$body .="Content-Disposition: attachment; filename=".$name."\r\n";
		$body .="Content-Transfer-Encoding: base64\r\n";
		$body .="X-Attachment-Id: ".rand(1000, 99999)."\r\n\r\n";
		$body .= $encoded_content; // Attaching the encoded file with email


	}

	$sentMailResult = mail($recipient_email, $subject, $body, $headers);

	if($sentMailResult ){
		echo "<p class='successmessage'>Successfully Sent. Thank You"." ".$sender_name."!."."</p>";
		// unlink($name); // delete the file after attachment sent.
	}
	else{
		die("Sorry but the email could not be sent.
					Please go back and try again!");
	}
}
?>


<?php
    echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('digimarket-seller-form-header')->toHtml();
?>


<div id="digimarketseler_form">
    <div class="container" >
          <header>Submit a request to join the digiDirect Marketplace</header>

          <form enctype="multipart/form-data" method="POST" action="">
                
                  <!--   <label for="email">Your email address<span style="color: #ff0000">*</span></label>
                  <input type="email" id="email" name="email" placeholder="Your email address" required /> -->

                  <div class="inline-row">
                      <div class="row1">
                          <label for="firstname">First Name<span style="color: #ff0000">*</span></label>
                          <input type="text" id="firstname" name="firstname" placeholder="First Name" required />
                      </div>
                      <div class="row1">
                          <label for="lastname">Last Name<span style="color: #ff0000">*</span></label>
                          <input type="text" id="lastname" name="lastname" placeholder="Last Name" required />
                      </div>
                  </div>

                  <div class="inline-row">
                      <div class="row1">
                          <label for="email">Your email address<span style="color: #ff0000">*</span></label>
                          <input type="email" id="email" name="email" placeholder="Your email address" required />
                      </div>
                      <div class="row1">
                          <label for="phonenumber">Phone Number<span style="color: #ff0000">*</span></label>
                          <input type="text" id="phonenumber" name="phonenumber" placeholder="Phone Number" required />
                      </div>
                  </div>

                  <label for="message">Message</label>
                  <textarea name="message" id="message" cols="10" rows="3"></textarea>

                  <label for="message">Attachement (optional)</label>
                  <div class="uploadfile drop-zone">
                      <span class="drop-zone__prompt1">Add file</span>
                      <span class="drop-zone__prompt2">or drop files here</span>
                      <input type="file" name="attachment" class="drop-zone__input">
                  </div>

                  <br>
                  <p>Hit submit and a digiDirect Marketplace specialist will contact you shortly.</p>

                  <br>

                  <input class="btn btn-primary" type="submit" name="button" value="Submit" />

                  <br><br>
            </form>
    </div>    

</div>



<script>
document.querySelectorAll(".drop-zone__input").forEach((inputElement) => {
const dropZoneElement = inputElement.closest(".drop-zone");

  dropZoneElement.addEventListener("click", (e) => {
    inputElement.click();
  });

  inputElement.addEventListener("change", (e) => {
    if (inputElement.files.length) {
      updateThumbnail(dropZoneElement, inputElement.files[0]);
    }
  });

  dropZoneElement.addEventListener("dragover", (e) => {
    e.preventDefault();
    dropZoneElement.classList.add("drop-zone--over");
  });

  ["dragleave", "dragend"].forEach((type) => {
    dropZoneElement.addEventListener(type, (e) => {
      dropZoneElement.classList.remove("drop-zone--over");
    });
  });

  dropZoneElement.addEventListener("drop", (e) => {
    e.preventDefault();

    if (e.dataTransfer.files.length) {
      inputElement.files = e.dataTransfer.files;
      updateThumbnail(dropZoneElement, e.dataTransfer.files[0]);
    }

    dropZoneElement.classList.remove("drop-zone--over");
  });
});

/**
 * Updates the thumbnail on a drop zone element.
 *
 * @param {HTMLElement} dropZoneElement
 * @param {File} file
 */
function updateThumbnail(dropZoneElement, file) {
  let thumbnailElement = dropZoneElement.querySelector(".drop-zone__thumb");

  // First time - remove the prompt
  if (dropZoneElement.querySelector(".drop-zone__prompt")) {
    dropZoneElement.querySelector(".drop-zone__prompt").remove();
  }

  // First time - there is no thumbnail element, so lets create it
  if (!thumbnailElement) {
    thumbnailElement = document.createElement("div");
    thumbnailElement.classList.add("drop-zone__thumb");
    dropZoneElement.appendChild(thumbnailElement);
  }

  thumbnailElement.dataset.label = file.name;

  // Show thumbnail for image files
  if (file.type.startsWith("image/")) {
    const reader = new FileReader();

    reader.readAsDataURL(file);
    reader.onload = () => {
      thumbnailElement.style.backgroundImage = `url('${reader.result}')`;
    };
  } else {
    thumbnailElement.style.backgroundImage = null;
  }
}
</script>
