<?php
/** @var \Ewave\Storelocator\Block\ListStore\SearchBox $block */
$locatorName = $block->getData('locatorName');
$default = $block->getDefaultRadius();
$items = $block->getRadiusOptions();
$metric = $block->getMetric();
$showLocator = true;
?>

<?php if ($showLocator) : ?>
<div class="locator-search">
    <form action="<?php echo $block->escapeUrl($block->getSearchUrl()); ?>" class="form" data-locator="<?php /* @escapeNotVerified */ echo $locatorName ?>" data-mage-init='{"validation": {}}'>
        <div class="input-group">
            <div class="control -text">
                <input type="text"
                       name="<?php echo $block->escapeHtmlAttr(\Ewave\StoreLocator\Model\Store\Processor::SEARCH_TERM_PARAM) ?>"
                       class="input-text input-search"
                       data-validate="{required:true, minlength:<?php echo $block->escapeHtmlAttr((int)$block->getSearchMinLength()) ?>}"
                       placeholder="<?php echo $block->escapeHtmlAttr(__('Enter your postcode and suburb')) ?>"
                       value=""
                />
            </div>
            <div class="control -select">
                <select name="radius" class="radius" data-mage-init='{"customSelectInit": {}}'>
                    <?php foreach ($items as $item):?>
                        <option value="<?php echo (int)$item;?>" <?php if ($default == $item):?>selected="selected"<?php endif;?>>
                            <?php /* @escapeNotVerified */ echo __('Within ')?><?php /* @escapeNotVerified */ echo $item;?> <?php /* @escapeNotVerified */ echo $metric?>
                        </option>
                    <?php endforeach;?>
                </select>
            </div>
            <button type="submit" id="btn-search" class="button action -responsive" title="<?php /* @escapeNotVerified */ echo
            __('Search')?>">
                <span><?php /* @escapeNotVerified */ echo __('Search')?></span>
            </button>
        </div>
    </form>
</div>
<?php endif; ?>