<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="field<?= /* @noEscape */ $class ?>">
    <?php
        if ($_option->getTitle() == 'digiProtect') {?>
        <div class="tooltip">
            <img class="digiprotect-info-logo" data-bind="attr: { src: require.toUrl('images/digiProtect.png') }" />
            <span class="tooltiptext">
                digiProtect your purchase beyond the manufacturer's warranty and have access to replacement 
                or repair guarantee, surge protection, freight and service call cover and more. Click here for more info.<!-- comment -->
                <br>
                <a href="https://mcstaging2.digidirect.com.au/digiprotect"><span>https://mcstaging2.digidirect.com.au/digiprotect</span></a>
            </span>
        </div>
            
    <?php
        } ?>
    <?php
        if ($_option->getTitle() != 'digiProtect') {?>
        <label class="label" for="select_<?= $block->escapeHtmlAttr($_option->getId()) ?>">
            <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
        </label> 
    <?php
        } ?>
            
    <div class="control">
        <?= $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()) :?>
            <?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_CHECKBOX) :?>
                <span id="options-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>
