<?php
/**
 * Product list toolbar
 *
 * @var $block \Digidirect\InfiniteScroll\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar toolbar-products test" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>
    </div>
<?php endif ?>
