<?php
/**
 * @var $block \Digidirect\SocialSharing\Block\Sharing
 * @var $sharingHelper \Digidirect\SocialSharing\Helper\Config\Twitter
 */
?>
<?php
$sharingHelper = $this->helper('Digidirect\SocialSharing\Helper\Config\Twitter');
?>
<div class="button-social -twitter">
    <a href="https://twitter.com/share" class="twitter-share-button"
       data-url="<?php echo $block->escapeUrl($block->getSharingUrl()); ?>">Tweet</a>
    <script>!function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
            if (!d.getElementById(id)) {
                js = d.createElement(s);
                js.id = id;
                js.src = p + '://platform.twitter.com/widgets.js';
                fjs.parentNode.insertBefore(js, fjs);
            }
        }(document, 'script', 'twitter-wjs');</script>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Digidirect_SocialSharing/js/twitter-reinit": {}
        }
    }
</script>
