<div class="competition-content">
    <h2><span class="title-color-orange">digi</span>Club Competition</h2>
    <img src="pic_trulli.jpg" alt="Trulli" width="500" height="333">
    <img src="{{media url=wysiwyg/digiclub-competition/digiclub_competition_main_img.png}}">
    <p>Login or Join digiClub and enter below for your chance</p>
    <h2>to<span class="title-color-orange">Win </span>a</h2>
    <h2>DJI Mini 4 Pro Drone</h2>
    <h2>thanks to C.R.Kenndy Australia.</h2>
</div>


<script></script>
<script></script>

<style>
.competition-content h2 {
    font-size: 18px;
}

.title-color-orange {
    color: #ff6600;
}

.competition-content {
    border: 1px color #cccccc;
    background: #F6F6F6;
}

</style>