<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select */ ?>
<?php $_option      = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>
<?php $isEnableImages = $block->getIsEnableBundleImages(); ?>
<div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <?php if ($block->getChildBlock('bundle.option.comment.select')): ?>
        <?php echo /* @noEscape */ $block->getChildBlock('bundle.option.comment.select')->setOption($_option)->toHtml();?>
    <?php endif; ?>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <?php if ($isEnableImages): ?>
                <?php $imageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($_selections[0], 'bundle_product_image_thumbnail')->getUrl(); ?>
                <figure class="bundle-img"
                        data-role="bundle-simple"
                        data-product-id="<?=$_selections[0]->getProductId() ?>"
                        data-product-url="<?= $block->escapeUrl($_selections[0]->getProductUrl()); ?>">
                    <img src="<?php echo $block->escapeUrl($imageUrl); ?>" alt="<?php echo $block->escapeHtml($_selections[0]->getName()) ?>">
                    <figcaption class="name">
                        <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selections[0]) ?>
                        <input type="hidden"
                               class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                               name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                               value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"/>
                    </figcaption>
                </figure>
            <?php else:?>
                <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                       value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"/>
            <?php endif; ?>
            <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.select.selection')): ?>
                <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selections[0])->toHtml(); ?>
            <?php endif; ?>
        <?php else:?>
            <?php if ($isEnableImages): ?>
                <?php foreach ($_selections as $_selection): ?>
                    <?php $imageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($_selection, 'bundle_product_image_thumbnail')->getUrl(); ?>
                    <figure class="bundle-img">

                        <img src="<?php echo $block->escapeUrl($imageUrl); ?>" alt="<?php echo $block->escapeHtml($_selection->getName()) ?>">
                        <figcaption class="name"><?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($_selection, false) ?></figcaption>
                    </figure>
                <?php endforeach; ?>
            <?php endif; ?>
            <div class="bundle-item">
                <select id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                        name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                        data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                        class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?> product bundle option bundle-option-select change-container-classname"
                    <?php if ($_option->getRequired()) echo 'data-validate = {required:true}' ?>>
                    <option value=""><?php /* @escapeNotVerified */ echo __('Choose a selection...') ?></option>
                    <?php foreach ($_selections as $_selection): ?>
                        <option value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                                data-role="bundle-simple"
                                data-product-id="<?=$_selection->getProductId() ?>"
                                data-product-url="<?= $block->escapeUrl($_selection->getProductUrl()); ?>"
                            <?php if ($block->isSelected($_selection)) echo ' selected="selected"' ?>
                            <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>>
                            <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selection, false) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.select.selection')): ?>
                <?php foreach ($_selections as $_selection): ?>
                    <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selection)->toHtml(); ?>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endif; ?>
        <div class="nested">
            <div class="field qty qty-holder">
                <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input">
                    <span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span>
                </label>
                <div class="control">
                    <input <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?>
                           id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input"
                           class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>"
                           type="number"
                           name="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           data-selector="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           value="<?php /* @escapeNotVerified */ echo $_defaultQty ?>"/>
                </div>
            </div>
        </div>
        <?php $addOptionInfoBlock = $block->getChildBlock('product.info.bundle.option.additional'); ?>
        <?php if ($addOptionInfoBlock): ?>
            <?php echo $addOptionInfoBlock->setItem($_option)->setQty($_defaultQty)->toHtml() ?>
        <?php endif;?>
    </div>
</div>
