<?php
/**
 * @var \Digidirect\Blog\Block\Blog $block
 * @var \Digidirect\Blog\Model\Post $post
 */

/**
 * @var \Digidirect\Digi\Helper\Blog $blogHelper
 */
$blogHelper = $this->helper('Digidirect\Digi\Helper\Blog');
$categoriesArrayNames = [];
?>

<?php if (!$block->getCollection()->getSize()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('There are no blog posts.') ?></div></div>
<?php endif; ?>
    
    
<?php if ($block->showPager() == true): ?>
<div class="toolbar blog-toolbar">
    <div class="pager" id="blogPager">  
        <div class="pages">
            <strong class="label pages-label" id="paging-label">Page</strong> 
            <ul class="items pages-items" aria-labelledby="paging-label">    
                 <?php /* @escapeNotVerified */ echo $block->getPagerHtml() ?>
            </ul>
        </div>
    </div>
</div>
<?php endif; ?>