<?php
/** @var Digidirect\ExtendedShippingRates\Block\Adminhtml\ExtendedShippingRates\Widget\TimeSlider $block */
/** @var Digidirect\ExtendedShippingRates\Model\Rule $rule */

$rule = $block->getRule();
$timeFrom = (int)$rule->getTimeFrom();
$timeTo = (int)$rule->getTimeTo();
$formName = $block->getFormName();
?>
<div id="time-range" class="field field-time_range">
    <label class="label">
        <?php echo $block->escapeHtml(__('Time Range: '));?>
        <span class="slider-time">
            <?php echo $block->escapeHtml($block->minutesToTime($timeFrom));?>
        </span>
        <?php echo ' - '; ?>
        <span class="slider-time2">
            <?php echo $block->escapeHtml($block->minutesToTime($timeTo));?>
        </span>
    </label>
    <div class="sliders_step1 control">
        <div id="slider-range"></div>
        <input type="hidden"
               name="<?php echo $block->escapeHtml($block->getNameFrom());?>"
               value="<?php echo $block->escapeHtml($timeFrom)?>"
               id="<?php echo $block->escapeHtml($block->getNameFrom());?>"
               data-form-part="<?php  echo $block->escapeHtml($formName); ?>"
            />
        <input type="hidden"
               name="<?php echo $block->escapeHtml($block->getNameTo());?>"
               value="<?php echo $block->escapeHtml($timeTo)?>"
               id="<?php echo $block->escapeHtml($block->getNameTo());?>"
               data-form-part="<?php  echo $block->escapeHtml($formName); ?>"
            />
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $("#slider-range").slider({
            range: true,
            min: 0,
            max: 1440,
            step: 15,
            values: [<?php echo $block->escapeHtml($timeFrom)?>, <?php echo $block->escapeHtml($timeTo)?>],
            slide: function (e, ui) {
                var hours1 = Math.floor(ui.values[0] / 60);
                var minutes1 = ui.values[0] - (hours1 * 60);

                if (hours1.length == 1) hours1 = '0' + hours1;
                if (minutes1.length == 1) minutes1 = '0' + minutes1;
                if (minutes1 == 0) minutes1 = '00';
                if (hours1 >= 12) {
                    if (hours1 == 12) {
                        hours1 = hours1;
                        minutes1 = minutes1 + " PM";
                    } else {
                        hours1 = hours1 - 12;
                        minutes1 = minutes1 + " PM";
                    }
                } else {
                    hours1 = hours1;
                    minutes1 = minutes1 + " AM";
                }
                if (hours1 == 0) {
                    hours1 = 12;
                    minutes1 = minutes1;
                }


                $('.slider-time').html(hours1 + ':' + minutes1);

                var hours2 = Math.floor(ui.values[1] / 60);
                var minutes2 = ui.values[1] - (hours2 * 60);

                if (hours2.length == 1) hours2 = '0' + hours2;
                if (minutes2.length == 1) minutes2 = '0' + minutes2;
                if (minutes2 == 0) minutes2 = '00';
                if (hours2 >= 12) {
                    if (hours2 == 12) {
                        hours2 = hours2;
                        minutes2 = minutes2 + " PM";
                    } else if (hours2 == 24) {
                        hours2 = 11;
                        minutes2 = "59 PM";
                    } else {
                        hours2 = hours2 - 12;
                        minutes2 = minutes2 + " PM";
                    }
                } else {
                    hours2 = hours2;
                    minutes2 = minutes2 + " AM";
                }

                $('.slider-time2').html(hours2 + ':' + minutes2);
                $('#<?php echo $block->escapeHtml($block->getNameFrom());?>').val(ui.values[0]);
                $('#<?php echo $block->escapeHtml($block->getNameTo());?>').val(ui.values[1]);
            }
        });
    });
</script>