<?php
/**
 * @see \Seo\Block\Adminhtml\System\Message\CategoryPath
 */
?>

<div data-id="information-dialog-removecategorypath-message" class="messages" style="display: none;">
    <div class="message message-notice">
    	<div><?php /* @escapeNotVerified */ echo __('This operation can take a long time.'); ?></div>
    	<div><?php /* @escapeNotVerified */ echo __('All category URLs will be changed. This action cannot be undone. Do you want to confirm it?'); ?></div>
    </div>
</div>