<?php
/**
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */

namespace Plumrocket\Newsletterpopup\Controller\Index;

use Magento\Backend\App\Action\Context;
use Magento\Framework\App\Action\Action;
use Plumrocket\Base\Api\ExtensionStatusInterface;

/**
 * @deprecated since 4.6.0 - integration with social login is only in one popup.
 * Therefore, is not reasonable to support this feature
 */
class Pslogin extends Action
{

    /**
     * @var \Plumrocket\Base\Api\ExtensionStatusInterface
     */
    private $extensionStatus;

    /**
     * @param \Magento\Backend\App\Action\Context           $context
     * @param \Plumrocket\Base\Api\ExtensionStatusInterface $extensionStatus
     */
    public function __construct(
        Context $context,
        ExtensionStatusInterface $extensionStatus
    ) {
        parent::__construct($context);
        $this->extensionStatus = $extensionStatus;
    }

    /**
     * Integration with Social Login.
     *
     * @return \Magento\Framework\App\ResponseInterface|\Magento\Framework\Controller\ResultInterface|void
     */
    public function execute()
    {
        $js = [];
        if ($pslogin = $this->getRequest()->getParam('pslogin')) {
            $js[] = 'var newspopupForm = window.opener.jQuery(".newspopup_up_bg_form");';

            if (!empty($pslogin['firstname'])) {
                $js[] = 'newspopupForm.find("input[name=firstname]").val("'. trim($pslogin['firstname']) .'");';
            }

            if (!empty($pslogin['lastname'])) {
                $js[] = 'newspopupForm.find("input[name=lastname]").val("'. trim($pslogin['lastname']) .'");';
            }

            if (!empty($pslogin['email']) && ! $this->isFakeMail(trim((string) $pslogin['email']))) {
                $js[] = 'newspopupForm.find("input[type=email]").val("'. trim($pslogin['email']) .'");';
            }

            if (!empty($pslogin['dob'])) {
                [$year, $month, $day] = explode('-', $pslogin['dob'], 3);
                if ($year > 0) {
                    $js[] = 'newspopupForm.find("input[name=year]").val("'. $year .'");';
                }
                if ($month > 0) {
                    $js[] = 'newspopupForm.find("input[name=month]").val("'. $month .'");';
                }
                if ($day > 0) {
                    $js[] = 'newspopupForm.find("input[name=day]").val("'. $day .'");';
                }
            }

            if (!empty($pslogin['gender'])) {
                $js[] = "newspopupForm.find(\"input[name=gender][value={$pslogin['gender']}]\")" .
                    '.prop("checked", true);';
            }

            if (count($js) > 1) {
                $js[] = 'window.opener.jQuery(".newspopup_up_bg_form:visible").submit();';
            }
        }

        $jsString = implode('', $js);
        $html = <<<HTML
<html>
<head></head>
<body>
<script>
if (window.opener && window.opener.location && !window.opener.closed) {
    $jsString
    window.close();
}
</script>
</body>
</html>
HTML;

        $this->getResponse()->setBody($html);
    }

    /**
     * Check if email is real and not generated by social login extension.
     *
     * @param string $email
     * @return bool
     */
    private function isFakeMail(string $email): bool
    {
        if ($this->extensionStatus->isEnabled('SocialLoginPro')
            && class_exists(\Plumrocket\SocialLoginPro\Model\Account\Data\FakeEmail::class)
        ) {
            $fakeEmail = $this->_objectManager->get(\Plumrocket\SocialLoginPro\Model\Account\Data\FakeEmail::class);
            return $fakeEmail->detect($email);
        }

        if ($this->extensionStatus->isEnabled('SocialLoginFree')
            && class_exists(\Plumrocket\SocialLoginFree\Model\Account\Data\FakeEmail::class)
        ) {
            $fakeEmail = $this->_objectManager->get(\Plumrocket\SocialLoginFree\Model\Account\Data\FakeEmail::class);
            return $fakeEmail->detect($email);
        }
        return false;
    }
}
