<?php
/** @var \Digidirect\MyOrderItemsGroups\Block\Customer\MyOrderItems\Group\ItemsList $block */
$itemsList = $block->getItems();
$requestParams = $block->collectFilterParams();
?>

<div class="group-block" data-mage-init='{"orderGroupManage": {"allItemsIds": <?= /* @escapeNotVerified */  $block->getItemIds() ?>, "groupId": "<?= (int)$block->getCurrentGroupId() ?>", "addNewItemUrl": "<?php echo $block->getAddItemUrl(); ?>", "loaderConfig": {"config": {"icon": "<?php echo $block->escapeUrl($this->helper('Digidirect\Utilities\Helper\Animation')->getImage()); ?>", "texts": {"loaderText": "<?php echo $block->escapeHtml($this->helper('Digidirect\Utilities\Helper\Animation')->getText()); ?>"}}}}}'>
    <div class="group-header">
        <?= $block->getGroupFilterHtml() ?>
        <div class="group-actions">
            <?= $block->getChildHtml('my_order_item_groups_sharing') ?>
            <?= $block->getChildHtml('my_order_item_groups_management') ?>
        </div>
    </div>
    <div class="group-help"><?= $block->escapeHtml(__('You can drag the purchased product to add new item here')) ?></div>
    <?php if (!$block->isEmptyGroup()): ?>
        <form action="<?php echo $block->getFormClearActionUrl() ?>" method="post" id="group-action-clear">
            <input type="hidden" name="group_id" class="group_id" value="<?= $block->getCurrentGroupId() ?>"/>
            <input type="hidden" data-role="remove-items-id" name="sales_item_ids"/>
        </form>
            <div class="items-block" data-role="drop-container">
                <?php foreach ($itemsList as $salesItem): ?>
                    <?php $requestParams['group_item_id'] = $salesItem->getItemId(); ?>
                    <div class="item" data-item-id="<?= (int)$salesItem->getItemId(); ?>">
                        <?php /** @var \Magento\Sales\Model\Order\Item $salesItem */ ?>
                        <div class="hidden-control">
                            <div class="field item choice">
                                <input type="checkbox" class="checkbox" id="item-id-<?= (int)$salesItem->getItemId(); ?>" data-id-value="<?= $salesItem->getItemId() ?>" data-role="remove-item"/>
                                <label class="label" for="item-id-<?= (int)$salesItem->getItemId(); ?>"></label>
                            </div>
                        </div>
                        <h3 class="name"><?php echo $block->escapeHtml($salesItem->getName()); ?></h3>
                        <div class="image"><img src="<?php echo $block->escapeUrl($block->getDataHelper()->getImageFilePath($salesItem)) ?>" alt="<?php echo $block->escapeHtml($salesItem->getName()); ?>"></div>
                        <a class="details-link" href="<?= $block->getIndexUrl($requestParams) ?>" title="<?php echo $block->escapeHtml(__('View Details')) ?>"><?php echo $block->escapeHtml(__('View Details')) ?></a>
                    </div>
                <?php endforeach; ?>
            </div>

        <?php if($block->isPagerDisplayed()): ?>
            <div data-block="order-items-pager-bottom" class="order-products-toolbar toolbar bottom">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <?= $block->getChildHtml('my_order_item_group_info') ?>
    <?php else: ?>
        <div class="items-block" data-role="drop-container"></div>
    <?php endif; ?>
</div>
