<?php
    /**
     * Copyright © Magento, Inc. All rights reserved.
     * See COPYING.txt for license details.
     */

    // @codingStandardsIgnoreFile

    /** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<div data-block="minicart" class="minicart-wrapper">
    <div class="action link showcart"
         data-container="#minicartSidebar"
         data-bind="scope: 'minicart_content'"
         data-mage-init='{"offcanvas": {
         "styleClasses":{"offcanvasOpenedClass": "-minicart-opened"},
         "addOn": "Magento_Checkout/js/dist/addons/offcanvas/minicart"
         }}'>
<!--        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -cart">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-cart"></use>
        </svg>-->
        <i class="fas fa-shopping-bag circle-icon -cart icon-badge-icon"></i>

        <div class="icon-badge">
            <!-- ko if: getCartParam('summary_count') -->
            <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
            <!-- /ko -->
            <!-- ko ifnot: getCartParam('summary_count') -->
            0
            <!-- /ko -->
        </div>
        
        <span class="text"><?=/* @escapeNotVerified */ __('My Cart'); ?><br>
        <span data-bind="html: getCartParam('subtotal')" style="color: #ff3c00;"></span></span>
<!--        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number">( ko text: getCartParam('summary_count')  /ko )</span>
            <span class="counter-label">
             ko if: getCartParam('summary_count') 
                 ko text: getCartParam('summary_count')  /ko 
                 ko i18n: 'items'  /ko 
             /ko 
            </span>
        </span>-->
    </div>
    <form action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/updatePost') ?>"
            method="post"
            id="form-validate"
            data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
                {"validationURL" : "/checkout/cart/updateItemQty"}
            }'
            class="form form-cart">
      <?= $block->getBlockHtml('formkey') ?>
      <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
          <?php if ($block->getPagerHtml()): ?>
              <div class="cart-products-toolbar cart-products-toolbar-top toolbar" data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?></div>
          <?php endif ?>
          <table id="shopping-cart-table"
                 class="cart items data table"
                 data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
                 "updateCartActionContainer": "#update_cart_action_container"}}'>
              <caption role="heading" aria-level="2" class="table-caption"><?= /* @escapeNotVerified */ __('Shopping Cart Items') ?></caption>
              <thead>
                  <tr>
                      <th class="col item" scope="col"><span><?= /* @escapeNotVerified */ __('Item') ?></span></th>
                      <th class="col price" scope="col"><span><?= /* @escapeNotVerified */ __('Price') ?></span></th>
                      <th class="col qty" scope="col"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                      <th class="col subtotal" scope="col"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
                  </tr>
              </thead>
              <?php foreach ($block->getItems() as $_item): ?>
                  <?= $block->getItemHtml($_item) ?>
              <?php endforeach ?>
          </table>
          <?php if ($block->getPagerHtml()): ?>
              <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar" data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?></div>
          <?php endif ?>
      </div>
      <div class="cart main actions">
          <?php if ($block->getContinueShoppingUrl()): ?>
              <a class="action continue"
                 href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
                 title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                  <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
              </a>
          <?php endif; ?>
          <button type="submit"
                  name="update_cart_action"
                  data-cart-item-update=""
                  value="update_qty"
                  title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                  class="action update">
              <span><?= /* @escapeNotVerified */ __('Update Shopping Cart') ?></span>
          </button>
          <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
      </div>
  </form>
    <script>
        window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig(); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?=/* @escapeNotVerified */ $block->getJsLayout(); ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?=/* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $('.minicart-wrapper').on('contentLoading', function (event) {
            $('[data-block="minicart"]').on('contentUpdated', function () {
                $('.action.showcart').addClass("-active");
                $('#minicartSidebar').addClass("-active");
                $('.minicart-items.item-qty').attr("style", "visibility: hidden !important;");
                console.log('jQuery Test On Minicart PHTML');
            });
        });
    });
</script>