<?php /** @var \Algolia\AlgoliaSearch\Block\Instant\Wrapper $block */ ?>

<!-- Wrapping template -->
<script type="text/template" id="instant_wrapper_template">
    {{#findAutocomplete}}
        <div id="algolia-autocomplete-container"></div>
    {{/findAutocomplete}}

    <div id="algolia_instant_selector"
         class="<?php echo $block->escapeHtml($block->hasFacets() ? ' with-facets' : ''); ?>">
        <div class="row">
            <div class="col-md-3" id="algolia-left-container">
                <div id="refine-toggle" class="visible-xs visible-sm">
                    + <?php echo $block->escapeHtml(__('Refine')); ?>
                </div>
                <div class="hidden-xs hidden-sm" id="instant-search-facets-container">
                    <div id="clear-refinements"></div>
                    <div id="current-refinements"></div>
                </div>
            </div>

            <div class="col-md-9" id="algolia-right-container">
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            {{#second_bar}}
                               <div id="instant-search-bar"></div>
                            {{/second_bar}}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div itemscope itemtype="http://schema.org/ItemList" class="hits">
                            <div class="algolia-infos">
                                <div class="pull-left" id="algolia-stats"></div>
                                <div class="pull-right">
                                    <div class="sort-by-label pull-left">
                                        <?php echo $block->escapeHtml(__('SORT BY')); ?> &nbsp;
                                    </div>
                                    <div class="pull-left" id="algolia-sorts"></div>
                                </div>
                                <div class="algolia-clearfix"></div>
                            </div>
                            <div id="algolia-banner"></div>
                            <div id="instant-empty-results-container"></div>
                            <div id="instant-search-results-container"></div>
                        </div>
                    </div>
                    <div class="algolia-clearfix"></div>
                </div>

                <div class="text-center">
                    <div id="instant-search-pagination-container"></div>
                </div>
            </div>
        </div>
    </div>
</script>

<script>
    require(['jquery'],
        function ($) {
            
            const observer = new MutationObserver((mutations) => { 
                //if ($("#instant-search-results-container").length) {
                $(".custom_final_price").each(function() {
                    var customFinalPrice = $(this).text();
                    console.log("customFinalPrice", customFinalPrice);
                    var customFinalPriceFormatted = Number(customFinalPrice).toFixed(2);
                    $(this).text('$' + customFinalPriceFormatted);
                });
                stopMutationObserver();
                //}
            }); 

            const config = { attributes: true, childList: true, subtree: true }; 
            observer.observe(document.querySelector("#maincontent"), config); 

            function stopMutationObserver() {
                observer.disconnect(); 
            }
            
        }
    );
</script>
