export const
    RELATED_INITIALIZED = 'RELATED_INITIALIZED',
    TOGGLE_DETAILS = 'TOGGLE_DETAILS',
    OPEN_DETAILS = 'OPEN_DETAILS',
    OPENED_DETAILS = 'OPENED_DETAILS',
    CLOSE_DETAILS = 'CLOSE_DETAILS',
    CLOSED_DETAILS = 'CLOSED_DETAILS',
    FILTERED = 'FILTERED';
