<?php
/** @var \Digidirect\StoreLocator\Block\ListStore\DetailPage $block */
$currentApi = $this->helper('Digidirect\StoreLocator\Helper\Config')->getApi();
?>
<?php if ($currentApi === 'google') : ?>
    <script type="text/x-magento-init">
        {
            ".store-view": {
                "locator": {
                    "defaultAddress": "<?php echo $block->escapeHtml($block->getDefaultCountry()) ?>",
                    "defaultCountryCode": "<?php echo $block->escapeHtml($block->getDefaultCountryCode()) ?>",
                    "availableCountries": <?php /* @escapeNotVerified */ echo json_encode($block->getAvailableCountries()) ?>,
                    "search": {"onLoad": false},
                    "mapInline": {
                        "enable": true,
                        "item": <?php /* @escapeNotVerified */ echo $block->getStoreData() ?>
                    },
                    "radius": {"enable": false}
                }
            }
        }
    </script>
<?php endif; ?>
