<?php
/**
 * @var $block Ewave\MyStoreWidget\Block\MyStore
 * @var $helper Ewave\MyStoreWidget\Helper\Config
 * @var $urlHelper Ewave\AbstractEntity\Helper\Url
 */
$helper = $this->helper('Ewave\MyStoreWidget\Helper\Config');
$urlHelper = $this->helper('Ewave\AbstractEntity\Helper\Url');
$selectedStore = $block->getStoreName();
$isGeoLocationEnabled = $helper->isGeoLocationEnabled() && $block->getIsGeoLocationEnabled();
?>
<?php if ($helper->isGoogleAutoSuggestEnabled()): ?>
    <?php
    $availableCountries = $helper->getAvailableCountries();
    $countCountries = count($availableCountries);
    ?>
<?php endif; ?>
<div data-bind="scope: 'my-store-widget'" class="mystorebar-wrapper">
    <div id="block-mystorebar" class="block-mystorebar" data-bind='attr: {"class": store.isStoreSelected() ? "block-mystorebar -selected" : "block-mystorebar"}, mageInit:
        {
            "myStoreSwitcher": {
                "searchUrl": "<?php /* @escapeNotVerified */ echo $block->getSearchUrl(); ?>",
                <?php if ($isGeoLocationEnabled): ?>
                    "isGeoLocationEnabled": <?php echo (int)$isGeoLocationEnabled; ?>,
                    "isNeedKeepGeoLocation": <?php /* @escapeNotVerified */ echo (int)$helper->isNeedKeepGeolocation(); ?>,
                    "storesList": <?php /* @escapeNotVerified */ echo $block->getStores(); ?>,
                    "isMobileGeoLocationAutocomliteDisabled": <?php echo (int)$helper->isDisabledGeoLocationAutocompliteForMobileDivices(); ?>,
                    "googleAutoSuggestApiKey": "<?php echo /* @escapeNotVerified */ $helper->getGoogleAutoSuggestApiKey(); ?>",
                <?php endif; ?>
                <?php if ($helper->isGoogleAutoSuggestEnabled()): ?>
                    "isGoogleAutoSuggestEnabled": <?php /* @escapeNotVerified */ echo (int)$helper->isGoogleAutoSuggestEnabled(); ?>,
                    <?php if ($countCountries == 1): ?>
                        "singleCountryData":{"country": ["<?php /* @escapeNotVerified */ echo current($availableCountries); ?>"]},
                    <?php endif; ?>
                    <?php if ($countCountries > 1): ?>
                        "singleCountryData":{"country": <?php /* @escapeNotVerified */ echo json_encode($availableCountries); ?>},
                    <?php endif; ?>
                <?php endif; ?>
                "autocompleteSettings": {
                    "minLength": <?php echo (int)$helper->getSearchMinLength(); ?>
                },
                "isSelectedStore": <?php if ($selectedStore) :?>true<?php else: ?>false<?php endif; ?>
            }
        }
    '>
        <form class="form" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="mystore-form" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-bind="mageInit: {'validation': {}}">
            <input type="hidden" name="abstract_entity_id" id="abstract_entity_id" value="<?php if ($block->isStoreSelected()): ?><?php /* @escapeNotVerified */ echo $block->getStore()->getId() ?><?php endif; ?>" />
            <?php echo $block->getBlockHtml('formkey')?>
            <input type="hidden" name="<?php /* @escapeNotVerified */ echo \Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED ?>" value="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Url\Helper\Data')->getEncodedUrl() ?>"/>
            <div class="change-mode">
                <label class="message" for="<?= /* @escapeNotVerified */ $block->getMyStoreInputId() ?>">
                    <!-- ko if: (store.isStoreSelected()) -->
                        <!-- ko i18n: 'My'--><!-- /ko -->
                        <!-- ko text: store.entityName() --><!-- /ko -->:
                    <!--/ko-->
                    <!-- ko ifnot: (store.isStoreSelected()) -->
                        <!-- ko i18n: 'My Store:'--><!-- /ko -->
                    <!--/ko-->
                </label>
                <div class="input-group">
                    <div class="control">
                        <div class="selection">
                            <!-- ko if: (store.isStoreSelected() && store.storeUrl()) -->
                                <a data-bind="{attr: {href: store.storeUrl(), title: store.selectedStore()}}"><!-- ko text: store.selectedStore() --><!-- /ko --></a>
                            <!--/ko-->
                            <!-- ko ifnot: (store.isStoreSelected() && store.storeUrl()) -->
                                <!-- ko text: store.selectedStore() --><!-- /ko -->
                            <!--/ko-->
                        </div>
                    </div>
                    <button type="button" class="button action -change" data-action="change-store" title="<?php /* @escapeNotVerified */ echo __('Change') ?>">
                        <?php /* @escapeNotVerified */ echo __('Change') ?>
                    </button>
                </div>
            </div>
            <div class="search-mode">
                <label class="message" for="<?= /* @escapeNotVerified */ $block->getMyStoreInputId() ?>"><?php /* @escapeNotVerified */ echo __('Select Your Store'); ?>:</label>
                <div class="input-group">
                    <div id="mystore-control" class="control">
                        <input type="text" name="store_name" id="<?= /* @escapeNotVerified */ $block->getMyStoreInputId() ?>" class="input-text" data-validate="{'required': true}" data-bind="attr: {value: store.selectedStore()}""/>
                    </div>
                    <button type="submit" class="button action primary -submit" data-action="save-mystore" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                        <?php /* @escapeNotVerified */ echo __('Submit') ?>
                    </button>
                </div>
            </div>
            <?php if ($helper->isGoogleAutoSuggestEnabled()): ?>
                <input type="hidden" name="find_store" id="mystore_find_store" value="0" />
                <input type="hidden" name="postcode" id="mystore_postal_code" value="" />
                <input type="hidden" name="city" id="mystore_locality" value="" />
                <input type="hidden" name="country" id="mystore_country" value="" />
            <?php endif; ?>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "my-store-widget": {
                    "component": "Ewave_MyStoreWidget/js/view/mystore-widget"
                }
            }
        }
    }
}
</script>
