<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div data-bind="scope: 'messages'">
    <div data-bind="foreach: { data: cookieMessages, as: 'message' }" class="messages">
        <div data-bind="attr: {
            class: 'message-' + message.type + ' ' + message.type + ' message',
            'data-ui-id': 'message-' + message.type
        }">
            <div data-bind="html: message.text, afterRender: $parent.addExtraClassName($element)"></div>
            <button type="button" class="message-close" data-bind="click: function() { $root.removeCookieMessage($index()) }" aria-label="Close">&#x2715;</button>
        </div>
    </div>
    <div data-bind="foreach: { data: messages().messages, as: 'message' }" class="messages">
        <div data-bind="attr: {
            class: 'message-' + message.type + ' ' + message.type + ' message',
            'data-ui-id': 'message-' + message.type
        }">
            <div data-bind="html: message.text, afterRender: $parent.addExtraClassName($element)"></div>
            <button type="button" class="message-close" data-bind="click: function() { $root.removeMessage($index()) }" aria-label="Close">&#x2715;</button>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "messages": {
                        "component": "Digidirect_Utilities/js/view/messages"
                    }
                }
            }
        }
    }
</script>