<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Sharing $block */
?>
<form class="form wishlist share block"
      action="<?= $block->escapeUrl($block->getSendUrl()) ?>"
      id="form-validate"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend block-title"><span><?= $block->escapeHtml(__('Sharing Information')) ?></span></legend><br />
        <div class="field emails required">
            <label class="label" for="email_address"><span><?= $block->escapeHtml(__('Email addresses, separated by commas')) ?></span></label>
            <div class="control">
                <textarea name="emails" cols="60" rows="6" id="email_address" data-validate="{required:true,'validate-emails':true}" class="textarea"><?= /* @noEscape */ $block->getEnteredData('emails') ?></textarea>
            </div>
        </div>
        <div class="field text">
            <label class="label" for="message"><span><?= $block->escapeHtml(__('Message')) ?></span></label>
            <div class="control">
                <textarea id="message" name="message" cols="60" rows="6" class="textarea"><?= /* @noEscape */ $block->getEnteredData('message') ?></textarea>
            </div>
        </div>
        <?php if ($this->helper('Magento\Wishlist\Helper\Rss')->isRssAllow()): ?>
            <div class="field choice rss">
                <input type="checkbox" name="rss_url" id="rss_url" value="1" title="<?= $block->escapeHtmlAttr(__('Check here to link an RSS feed to your Wish List.')) ?>" class="checkbox">
                <label class="label" for="rss_url">
                    <span>
                        <?= $block->escapeHtml(__('Check here to link an RSS feed to your Wish List.')) ?>
                    </span>
                </label>
            </div>
        <?php endif; ?>
    </fieldset>
    <?= $block->getChildHtml('captcha'); ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Share Wishlist')) ?>" class="action submit">
                <span><?= $block->escapeHtml(__('Share Wishlist')) ?></span>
            </button>
        </div>
    </div>
</form>
