<div id="collect-single-cart" data-bind="scope: 'collect-single-cart'" class="collect_place_class">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<?php
$quoteHelper = $helper = $this->helper('Ewave\Digi\Helper\Quote');
$hasWebOnly = $quoteHelper->isQuoteHasWebOnlyProducts();
?>
<?php $pickUpStoreCmsBlock = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('pick-up-store')->toHtml() ?>
<script type="text/javascript">
    window.pickUpStoreCmsBlock = <?php echo json_encode($pickUpStoreCmsBlock)?>;
</script>
<script type="text/x-magento-init">
    {
        "#collect-single-cart": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout();?>
        }
    }
</script>
<?php if ($hasWebOnly) : ?>
    <script>
        window.hasWebOnly = <?= $hasWebOnly ?>;
    </script>
<?php endif; ?>