<div class="styleguide-block" data-block="styleguide-block" data-bind="scope: 'styleguide'">
    <ul class="nav">
        <!-- ko foreach: { data: elems, as: 'element' } -->
        <li class="item">
            <a class="link" data-bind="attr: { href: '#' + name}, text:title "></a>
        </li>
        <!-- /ko -->
    </ul>
    <div class="elements">
        <!-- ko foreach: { data: elems, as: 'element' } -->
        <div class="styleguide-item">
            <a data-bind="attr: { name: name}"><!--anchor--></a>

            <h2 class="title" data-bind="text: title"></h2>

            <div class="output">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>

            <div class="code-viewer -closed">
                <button data-bind="click: viewSource"><?= $block->escapeHtml(__('View source')) ?></button>
                <button class="copy" data-bind="click: copyCode"><?= $block->escapeHtml(__('Copy')) ?></button>
                <pre class="pre">
                    <code class="code"
                          data-styleguide="code-example"
                          data-bind="template: { name: getTemplate(), afterRender: highlight }"></code>
                </pre>
            </div>
        </div>
        <!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
    {
        "[data-block='styleguide-block']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
