<?php

namespace Digidirect\AbstractGiftCard\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

/**
 * Flat sales order resource
 */
class AbstractGiftCardEntity extends AbstractDb
{

    /**
     * @var \Magento\Framework\Stdlib\DateTime
     */
    protected $_dateTime;

    /**
     * Model Initialization
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init('abstract_gift_card_entity', 'entity_id');
    }

    /**
     * AbstractGiftCardEntity constructor.
     * @param \Magento\Framework\Model\ResourceModel\Db\Context $context
     * @param \Magento\Framework\Stdlib\DateTime $dateTime
     * @param null $connectionName
     */
    public function __construct(
        \Magento\Framework\Model\ResourceModel\Db\Context $context,
        \Magento\Framework\Stdlib\DateTime $dateTime,
        $connectionName = null
    ) {
        parent::__construct($context, $connectionName);
        $this->_dateTime = $dateTime;
    }

    /**
     * Count existent products of order items by specified product types
     *
     * @param int $orderId
     * @param array $productTypeIds
     * @param bool $isProductTypeIn
     * @return array
     */
    public function aggregateProductsByTypes($orderId, $productTypeIds = [], $isProductTypeIn = false)
    {
        $connection = $this->getConnection();
        $select = $connection->select()
            ->from(
                ['o' => $this->getTable('sales_order_item')],
                ['o.product_type', new \Zend_Db_Expr('COUNT(*)')]
            )
            ->where('o.order_id=?', $orderId)
            ->where('o.product_id IS NOT NULL')
            ->group('o.product_type');
        if ($productTypeIds) {
            $select->where(
                sprintf(
                    '(o.product_type %s (?))',
                    $isProductTypeIn ? 'IN' : 'NOT IN'
                ),
                $productTypeIds
            );
        }
        return $connection->fetchPairs($select);
    }

    /**
     * @param \Digidirect\AbstractGiftCard\Api\AbstractGiftCardEntityInterface $entity
     * @param string $serviceCode
     * @param string $giftCardCode
     * @return $this
     */
    public function loadByServiceAndCode(
        \Digidirect\AbstractGiftCard\Api\AbstractGiftCardEntityInterface $entity,
        $serviceCode,
        $giftCardCode
    ) {
        $connection = $this->getConnection();
        $select = $connection->select()->from($this->getMainTable())
            ->where('service_code = ?', $serviceCode)
            ->where('code = ?', $giftCardCode);

        $data = $connection->fetchRow($select);

        if ($data) {
            $entity->setData($data);
        }

        $this->unserializeFields($entity);
        $this->_afterLoad($entity);

        return $this;
    }

    /**
     * @param \Magento\Framework\Model\AbstractModel $object
     * @return $this
     */
    protected function _afterSave(\Magento\Framework\Model\AbstractModel $object)
    {
        if ($object->getToken() && $object->getOrderId()) {
            $this->getConnection()->insertOnDuplicate($this->getTable(), [
                'order_id'                      => $object->getOrderId(),
                'abstract_gift_card_entity_id'  => $object->getEntityId(),
                'token'                         => $object->getToken(),
                'amount'                        => $object->getAmount(),
                'status'                        => $object->getStatus(),
            ], ['status']);
        }
        return parent::_beforeSave($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Magento\Framework\Model\AbstractModel $object
     * @return $this
     */
    protected function _afterLoad(\Magento\Framework\Model\AbstractModel $object)
    {
        if ($object->getEntityId()) {
            $select = $this->getConnection()->select()->from($this->getTable('abstract_gift_card_entity_order'))
                ->where('abstract_gift_card_entity_id = ?', $object->getEntityId());
            $data = $this->getConnection()->fetchAll($select);
            foreach ($data as $row) {
                $entityOrderData = new \Magento\Framework\DataObject($row);
                $object->addEntityOrderData($entityOrderData->getOrderId(), $entityOrderData);
            }
        }

        return parent::_afterLoad($object);
    }

    /**
     * @param \Magento\Framework\DataObject $entityOrderData
     * @return $this
     */
    public function saveEntityOrderData(\Magento\Framework\DataObject $entityOrderData)
    {
        if ($entityOrderData->getAbstractGiftCardEntityId() && $entityOrderData->getOrderId()) {
            $this->getConnection()->insertOnDuplicate($this->getTable('abstract_gift_card_entity_order'), [
                'order_id'                      => $entityOrderData->getOrderId(),
                'abstract_gift_card_entity_id'  => $entityOrderData->getAbstractGiftCardEntityId(),
                'token'                         => $entityOrderData->getToken(),
                'amount'                        => $entityOrderData->getAmount(),
                'status'                        => $entityOrderData->getStatus(),
            ], ['status']);
        }
        return $this;
    }
}
