<?php

use Magento\Framework\App\Action\Action;

/**
 * Author: Rondel Dalumpines
 */
/** @var \Digidirect\YouMayAlsoLikeProducts\Block\Widget\YouMayAlsoLikeProducts $block */
?>
<?php
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    
    $title = __('You May Also Like Products');
}
?>

 <?php if ($exist) :?>

    <div>

        <div class="ymal-title">You may also like</div>
        <div class="ymal-product-wrapper">

            <?php foreach ($items as $_item) :?>

            <?php
                $productName = $_item->getName();
                $productUrl = $block->getProductUrl($_item);
                $finalProductPrice = $_item->getFinalPrice();
                $qff_bonus_points = 0;
                if ($_item->offsetExists("qff_bonus_points") && $_item->offsetExists("qff_base")) {
                    $qff_bonus_points = $_item->getQffBonusPoints();
                    $qff_base_points = $_item->getQffBase();
                    $bonusPlusBase = $qff_bonus_points + $qff_base_points;

                    $points = number_format($finalProductPrice * $bonusPlusBase);
                }else {
                    if($_item->offsetExists("qff_base")){
                        $qff_base_points = $_item->getQffBase();
                        $points = number_format($finalProductPrice * $qff_base_points);
                    } else {
                        $points = number_format($finalProductPrice * 2);
                    }
                } 

                $finalQffPoints = $_item->getPoints();
            ?>

            <div class="ymal-product product-item item">
                <div class="ymal-product-info product-item-info" style="margin-left: 20px !important;">
                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                       class="ymal-item-photo product-item-photo">
                        <?= $block->getImage($_item, $image)->toHtml() ?>
                    </a>
                    <div class="ymal-item-details product-item-details">
                        <strong class="ymal-item-name product-item-name">
                            <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product-item-link">
                                <?= $block->escapeHtml($_item->getName()); ?>
                            </a>
                        </strong>

                        <?= $this->getLayout()
                            ->createBlock('Digidirect\ExtendedCatalogPriceRule\Block\ExtendedRule')
                            ->setTemplate('Digidirect_ExtendedCatalogPriceRule::product/view/list/display_message.phtml')
                            ->setProduct($_item)
                            ->toHtml();
                        ?>

                        <?= $block->getProductPriceHtml($_item, $type); ?>

                        <?php if ($templateType) :?>
                            <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                        <?php endif; ?>

                        <?php if ($showWishlist || $showCompare || $showCart) :?>
                            <div class="ymal-item-inner product-item-inner">
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart) :?>
                                        <div class="ymal-actions actions-primary">
                                            <?php $addToCartUrl = $block->getAddToCartUrl($_item); ?>

                                            <form data-role="tocart-form"
                                                data-product-sku="<?=  /* @escapeNotVerified */ $_item->getSku(); ?>"
                                                data-mage-init='{"validation": {}}'
                                                action="<?= $block->escapeUrl($addToCartUrl); ?>"
                                                method="post">

                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ (int)$_item->getEntityId(); ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Url\Helper\Data')->getEncodedUrl($addToCartUrl); ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                        <?php if ($toCartFormBlock = $block->getChildBlock('tocart_form')): ?>
                                                            <?php /* @escapeNotVerified */ echo $toCartFormBlock->setProduct($_item)->getChildHtml(); ?>
                                                        <?php endif; ?>ca
                                                <button class="primary ymal-button"
                                                        type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    <span class="cart_plus_logo" style="float: none; margin-left: 3px;"><i class="fas fa-cart-plus"></i></span>
                                                </button>
                                          </form>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
             </div>
            <?php endforeach ?>

        </div>


    </div>
    
    

            <?= $block->getPagerHtml() ?>
<?php endif;?>