<?php
use Magento\ConfigurableProduct\Model\Product\Type\Configurable;
use Magento\Framework\App\Action\Action;

/* @var $block \Ewave\ProductCalculator\Block\Calculator\ProductList */
?>

<?php
$productCollection = $block->getLoadedProductCollection();
$helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $variationsBlock = $block->getChildBlock('product.variations');
    if ($variationsBlock) {
        $variationsBlock->setCalculator($block->getCurrentCalculator());
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $items = $block->getGroupedByCategoryProducts();

    ?>
    <?php foreach ($items as $categoryName => $products): ?>
    <?php if ($categoryName) { ?>
        <h3 class="category"><?= $block->escapeHtml($categoryName)?></h3>
    <?php } ?>

    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products items product-items -calculator -<?php /* @escapeNotVerified */ echo $viewMode; ?>"
            data-mage-init='{
                "productTile": {
                    <?php if ($block->isRedirectToCartEnabled()): ?>
                    "isRedirectToCartEnabled": true,
                    <?php endif; ?>
                    "truncateCollectionConfig": {"addOn": "js/dist/widgets/truncate-collection/addons/catalog/index"}
                }
            }'>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($products as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info -<?php /* @escapeNotVerified */ echo $viewMode; ?>" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>

                    <?php
                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                    ?>
                    <strong class="product name product-item-name -grid">
                        <a class="product-item-link"
                           href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                            <?php /* @escapeNotVerified */ echo $helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                        </a>
                    </strong>

                    <div class="product details product-item-details">
                        <?php if ($afterProductPriceBlock = $block->getChildBlock('after.product.price.container')): ?>
                            <?php /* @escapeNotVerified */ echo $afterProductPriceBlock->setProduct($_product)->getChildHtml(); ?>
                        <?php endif; ?>

                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>

                        <div class="product-item-inner">
                            <?php
                            if ($_product->getTypeId() === Configurable::TYPE_CODE) {
                                echo $variationsBlock ? $variationsBlock->setProduct($_product)->toHtml() : $block->getProductDetailsHtml($_product);
                            }
                            ?>
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?=  /* @escapeNotVerified */ $_product->getSku(); ?>"
                                              action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>"
                                              method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <?php if ($toCartFormBlock = $block->getChildBlock('tocart_form')): ?>
                                                <?php /* @escapeNotVerified */ echo $toCartFormBlock->setProduct($_product)->getChildHtml(); ?>
                                            <?php endif; ?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                        <?php if ($afterToCartFormBlock = $block->getChildBlock('tocart_form.after')): ?>
                                            <?php echo $afterToCartFormBlock->setProduct($_product)->getChildHtml(); ?>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>

                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                </div>
                            <?php endif; ?>

                            <?php if ($rentBlock = $block->getChildBlock('product.tile.rent')): ?>
                                <?php echo $rentBlock->toHtml(); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($productCollection)+1) ? '</li>' : '' ?><?php endforeach; ?></ol>
    </div>

    <?php endforeach; ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            ".product-items.-calculator [data-role=tocart-form], .product-items.-calculator .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
