<?php
/**
 * @var \Digidirect\Blog\Block\Post $block
 */
$post = $block->getPost();
$mainImage = $post->getMainImage();
$categoryExeption = "top contributors";
$categoriesArrayNames = [];
?>
<div class="post-view post-card item">
    <?php if (!$block->isDisplayCategories() && $categories = $block->getCategories()): ?>
        <?php $categoriesTitlesCount = count($categories); ?>
        <?php if ($categoriesTitlesCount) : ?>
            <div class="categories">
                <?php /** @var $category \Digidirect\Blog\Model\Category*/ ?>
                <?php $i=1; foreach ($categories as $key => $category): ?>
                    <a href="<?php echo $block->escapeUrl($category->getViewUrl())?>" class="link" title="<?php echo /* @escapeNotVerified */  $category->getName(); ?>"><?php /* @escapeNotVerified */  echo $category->getName(); ?></a><?php if ($categoriesTitlesCount != $i) : ?>,<?php endif; ?>
                    <?php $i++; ?>
                    <?php array_push($categoriesArrayNames, $category->getName())?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
    <img src="<?php echo $block->escapeHtml($post->getImageUrl(null, null)); ?>" alt="<?php echo $block->escapeHtml($post->getTitle()) ?>">
    <!-- <img src="<?php //echo $block->getViewFileUrl('Digidirect_Blog::images/post-image.jpg'); ?>" alt="<?php //echo $block->escapeHtml($post->getTitle()) ?>"> -->
    <div class="post-container">
        <h1 class="title"><?php /* @escapeNotVerified */ echo $post->getTitle() ?></h1>
        <?php if (($categoryName = $category->getName()) && (strcasecmp($categoryName, $categoryExeption) != 0)):?>
            <div class="posted">
                <span class="label"><?php /* @escapeNotVerified */ echo __('Posted on') ?></span>
                <?php echo $block->escapeHtml($post->getCreatedDate()); ?>
            </div>
        <?php endif; ?>

        <div class="content">
            <?php
            /* @escapeNotVerified */

            $description = html_entity_decode($block->getDescription());
            $description = str_replace("ÔÇØ", "'", $description);
            $description = str_replace("ÔÇ£", "'", $description);
            $description = str_replace("ÔÇÖ", "'", $description);

            echo $description;
            ?>
        </div>
        <div class="post-share icons -light">
            <span class="label"><?php echo $block->escapeHtml(__('Share this Article:')); ?></span>
            <div class="social-icons">
             <a class="link"
            target="_blank"
            href="http://twitter.com/share?url=<?php echo $block->escapeUrl($post->getViewUrl()) ?>">
                <img src="<?php echo $block->getViewFileUrl('Digidirect_Blog::images/x.svg'); ?>" alt="twitter">
            </a>

            <a href="https://www.threads.net/intent/post?text=<?php echo $block->escapeUrl($post->getViewUrl()) ?>"
            target="_blank"
            rel="noopener noreferrer">
                <img src="<?php echo $block->getViewFileUrl('Digidirect_Blog::images/threads.svg'); ?>" alt="threads">
            </a>
            <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $block->escapeUrl($post->getViewUrl()) ?>" target="_blank" rel="noopener" class="-facebook">
                <img src="<?php echo $block->getViewFileUrl('Digidirect_Blog::images/fb.svg'); ?>" alt="facebook">
            </a>
            <a class="link"
            target="_blank"
            href="https://plus.google.com/share?url=<?php echo $block->escapeUrl($post->getViewUrl()) ?>">
                <img src="<?php echo $block->getViewFileUrl('Digidirect_Blog::images/google.svg'); ?>" alt="google plus">
            </a>
            </div>
           
        </div>
    </div>
</div>
<script>
    require([], function () {
        var elemWrapper = document.querySelector('.wrapper-top'),
            elemTag = elemWrapper.querySelector('.tags'),
            tagLabel = elemWrapper.querySelector('.label'),
            tagItem = elemTag.querySelector('.item');

        if (tagLabel && !tagItem) {
            tagLabel.style.display = 'none';
        }
    });
</script>
