<input type="hidden" name="<?php echo $block->getNamePrefix() ?>" value="" /><!-- this is send if nothing is checked -->
<ul class="checkboxes">
    <?php foreach ($block->getValues() as $name => $label): ?>
        <li>
            <input
                type="checkbox"
                value="<?=/* @noEscape */$name?>"
                name="<?=/* @noEscape */ $block->getNamePrefix() ?>[]"
                id="<?=/* @noEscape */ $block->getHtmlId() . '_' . $name ?>"
                <?=/* @noEscape */ ($block->isChecked($name) ? ' checked="checked"' : '') ?>
            />
            <label for="<?=/* @noEscape */ $block->getHtmlId() . '_' . $name ?>">
                <?=/* @noEscape */ $label ?>
            </label>
        </li>
    <?php endforeach;?>
</ul>