<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list toolbar sorter
 *
 * @var $block Digidirect\InfiniteScroll\Block\Product\ProductList\Toolbar
 */
use Digidirect\InfiniteScroll\Block\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort By ') ?></label>
        <a title="<?= /* @escapeNotVerified */ __('Descending Direction') ?>"
           href="#"
           class="action sorter-action sort-desc <?php if ($block->getCurrentDirection() == 'desc'): ?>-active<?php else: ?>-passive<?php endif; ?>"
           data-role="direction-switcher"
           data-value="<?php if ($block->getCurrentDirection() == 'desc'): ?>asc<?php else: ?>desc<?php endif; ?>">
        </a>
        <a title="<?= /* @escapeNotVerified */ __('Ascending Direction') ?>"
           href="#"
           class="action sorter-action sort-asc <?php if ($block->getCurrentDirection() == 'asc'): ?>-active<?php else: ?>-passive<?php endif; ?>"
           data-role="direction-switcher"
           data-value="<?php if ($block->getCurrentDirection() == 'asc'): ?>desc<?php else: ?>asc<?php endif; ?>">
        </a>
</div>
