<?php
/**
 * Product list toolbar
 *
 * @var $block \Digidirect\InfiniteScroll\Block\Product\ProductList\Toolbar
 */
?>
<?php $isShowAlways = true; ?>
<?php if ($block->getCollection()->getSize() || $isShowAlways): ?>
    <div class="toolbar toolbar-products chuchu" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
        <div class="mobile-row">
            <?= $block->getChildHtml('page.main.title');?>
            <?php if ($block->isExpanded()): ?>
                <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
            <?php endif; ?>
        </div>
        <div class="desktop-row">
            <div class="filter filter-trigger -mobile" data-container="#catalogSidebar" data-mage-init='{ "offcanvas": {"addOn":
            "js/components/offcanvas/dist/addons/catalog/index"} }'><?=  __('Filter');?>
            </div>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
            <?php if ($block->isExpanded()): ?>
                <?php include ($block->getTemplateFile('Digidirect_InfiniteScroll::product/list/sorter.phtml')) ?>
                <div class="sorter -mobile">
                    <div class="sort-label-wrapper">
                        <span class="sorter-trigger" data-container="#sorterOffcanvas" data-mage-init='{ "offcanvas": {"addOn":
                        "js/components/offcanvas/dist/addons/catalog/index"} }'><?=  __('Sort By');?>
                        </span>
                        <span class="sort-label-mobile">
                            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                                <?php if ($_order == 'Position'): /**  Label hardcoded in vendor/magento/module-catalog/Model/Config.php*/ ?>
                                    <?php $_order = 'Bestsellers'; /**  according #287685 */ ?>
                                <?php endif; ?>
                                <span <?php if ($block->isOrderCurrent($_key)): ?> class="selected" <?php endif; ?> >
                                    <?= $block->escapeHtml(__($_order)) ?>
                                </span>
                            <?php endforeach; ?>
                        </span>
                    </div>
                    <div class="sorter-mobile-wrapper">
                        <a title="<?= /* @escapeNotVerified */ __('Descending Direction') ?>"
                           href="#"
                           class="action sorter-action sort-desc <?php if ($block->getCurrentDirection() == 'desc'): ?>-active<?php else: ?>-passive<?php endif; ?>"
                           data-role="direction-switcher"
                           data-value="<?php if ($block->getCurrentDirection() == 'desc'): ?>asc<?php else: ?>desc<?php endif; ?>">
                        </a>
                        <a title="<?= /* @escapeNotVerified */ __('Ascending Direction') ?>"
                           href="#"
                           class="action sorter-action sort-asc <?php if ($block->getCurrentDirection() == 'asc'): ?>-active<?php else: ?>-passive<?php endif; ?>"
                           data-role="direction-switcher"
                           data-value="<?php if ($block->getCurrentDirection() == 'asc'): ?>desc<?php else: ?>asc<?php endif; ?>">
                        </a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <div id="sorterOffcanvas" class="sorter-container offcanvas-panel offcanvas-left -device-only -without-padding">
        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/sorter.phtml')) ?>
    </div>
<?php endif ?>