<script>
    if (typeof window.fotoramaDefaults === 'undefined') {
        window.fotoramaDefaults = {};
        window.fotoramaDefaults.thumbmargin = 10;
        window.fotoramaDefaults.navwidth = "530px";
    } else {
        window.fotoramaDefaults.thumbmargin = 10;
        window.fotoramaDefaults.navwidth = "530px";
    }
    
    require(['jquery'],function(){
        
        jQuery(document).ready(function() {
            //jQuery(".fotorama__thumb__arr").remove();
            jQuery(".fotorama__thumb__arr--left").detach().appendTo(".fotorama__nav-wrap");
            jQuery(".fotorama__thumb__arr--right").detach().appendTo(".fotorama__nav-wrap");
        });
    });
</script>