<?php /** @var $block \Digidirect\PreOrder\Block\Product\ListProduct\Preorder */ ?>
<div class="preorder-note -listing"><?php echo $block->escapeHtml($block->getPreorderNote()) ?></div>
<script>
    require(['jquery', 'preOrder'], function ($, preOrder) {
        var $button = $($('input[name="product"][value="<?php echo (int) $block->getProduct()->getId() ?>"]').parent().find('.tocart')[0]),
            $form = $button.closest('[data-role="tocart-form"]');
        $button.preOrder({
            "autoEnable": <?php echo (int) $block->isAutoEnabled() ?>,
            "addToCartButton": $button,
            "addToCartLabel": "<?php echo $block->escapeHtml($block->getCartLabel()) ?>",
            "addToCartForm": $form
        })
    });
</script>
