<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var \Magento\LayeredNavigation\Block\Navigation\FilterRenderer $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\LayeredNavigation\ViewModel\Layer\Filter $viewModel */
$viewModel = $block->getData('product_layer_view_model');
?>

<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a
                    href="<?= $escaper->escapeUrl($filterItem->getUrl()) ?>"
                    rel="nofollow"
                ><?= /* @noEscape */ $filterItem->getLabel() ?><?php
                if ($viewModel->shouldDisplayProductCountOnLayer()): ?><span
                        class="count"><?= /* @noEscape */ (int) $filterItem->getCount() ?><span
                            class="filter-count-label"><?php
                            if ($filterItem->getCount() == 1): ?>
                                <?= $escaper->escapeHtml(__('item')) ?><?php
                            else:
                                ?><?= $escaper->escapeHtml(__('item')) ?><?php
                            endif;?></span></span>
                    <?php endif; ?></a>
            <?php else: ?>
                <?= /* @noEscape */ $filterItem->getLabel() ?><?php
                if ($viewModel->shouldDisplayProductCountOnLayer()): ?><span
                        class="count"><?= /* @noEscape */ (int) $filterItem->getCount() ?><span
                            class="filter-count-label"><?php
                            if ($filterItem->getCount() == 1): ?>
                                <?= $escaper->escapeHtml(__('items')) ?><?php
                            else:
                                ?><?= $escaper->escapeHtml(__('items')) ?><?php
                            endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
    <div class="show-more-options">Show More<i class="fas fa-chevron-down" style="margin-left: 10px;"></i></div>
    <div class="show-less-options" style="display: none;">Show Less<i class="fas fa-chevron-up" style="margin-left: 10px;"></i></div>
</ol>

<script>
    require(['jquery', 'jquery/ui'], function($){ 
        $('#narrow-by-list .filter-options-content').each(function () {
            //console.log("Test JQuery!");
            var ctrOption = 0;
            var hiddenOptions = 0;
            $(this).find('li.item').each(function () {
                ctrOption++;
                if (ctrOption > 5) {
                    $(this).hide();
                    hiddenOptions++;
                }
                //console.log("ctrOption++: " + ctrOption++);
            });
            if (hiddenOptions == 0) {
                $(this).find('.show-more-options').hide();
            }
        });
        
        
        $('#narrow-by-list .filter-options-content .items').each(function () {
            //var optionLimit = 5;
            var thisElement = $(this);
            thisElement.find('.show-more-options').click(function(event) {
                var optionCtr = 0;
                thisElement.find('li.item:hidden').each(function () {
                    optionCtr++;
                    $(this).show();
                    console.log("optionCtr: " + optionCtr);
                    /*if (optionCtr == optionLimit) {
                        return false;
                    }*/
                });
                
                var hiddenOption = 0;
                thisElement.find('li.item:hidden').each(function () {
                    hiddenOption++;
                })

                if (hiddenOption == 0) {
                    thisElement.find('.show-more-options').hide();
                    thisElement.find('.show-less-options').show();
                }
                event.stopPropagation();
            });
            
            thisElement.find('.show-less-options').click(function() {
                var ctrOption = 0;
                var hiddenOptions = 0;
                thisElement.find('li.item').each(function () {
                    ctrOption++;
                    if (ctrOption > 5) {
                        $(this).hide();
                        hiddenOptions++;
                    }
                    //console.log("ctrOption++: " + ctrOption++);
                });
                thisElement.find('.show-more-options').show();
                thisElement.find('.show-less-options').hide();
            });
            
        });
        
        
    });
    
</script>
