<?php
/**
 * @var $block \Ewave\Banner\Block\Widget\Banner
 *
 * If you need json_encode/json_decode please use $block->jsonEncode($valueToEncode) $block->jsonDecode($valueToDecode)
 *
 */
?>
<?php

$bannersToDisplay = $block->getBannersToDisplay();
$displayMode = $block->getDisplayMode();
if (empty($bannersToDisplay)) {
    return;
}
$bannerId = $block->getUniqueId();
$isLazyLoad = $block->getIsLazyLoad();
$mediaQueryFull = $block->jsonEncode($block->getMediaQuery());
$autoPlay = $block->isAutoplay() ? 'true' : 'false';
$breadcrumbsType = $block->getBreadcrumbsType();
$isLoop = $block->isLoop() ? 'true' : 'false';
$getDelaySpeedValue = $block->getDelaySpeedValue() * 1000;
$navigationTitles = 'false';
$prevArrow = $block->getArrowPrevious();
$nextArrow = $block->getArrowNext();

if ($breadcrumbsType == 'no'):
    $dots = 'false';
else :
    $dots = 'true';
endif;

if ($breadcrumbsType == 'content'):
    $navigationTitles = 'true';
endif;
?>

<?php if ($isLazyLoad) : ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "lazySizes": {}
            }
        }
    </script>
<?php endif; ?>
<div class="widget block block-banners round-arrows banner-main-wrapper" data-testid="bannerRotator-widget">
    <div class="banner-items" id="banner-<?= /* @noEscape */ $bannerId ?>" data-role="banner-rotator">
        <?php foreach ($bannersToDisplay as $id => $bannerItem): ?>
            <?= /* @noEscape */ $block->renderBannerItem($bannerItem); ?>
        <?php endforeach; ?>
    </div>
    <?php if (!$isLazyLoad) : ?>
        <img class="loader" src="<?= /* @noEscape */ $this->helper(\Ewave\Banner\Helper\DefaultLoader::class)->getImage() ?>" alt="<?= /* @noEscape */ __('Loading...') ?>">
    <?php endif; ?>
   <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-additional')->toHtml(); ?>
</div>
<script type="text/x-magento-init">
    {
        "#banner-<?= /* @noEscape */ $bannerId ?>": {
            "bannerStatic": {
                "config": {
                    "navigationTitles": <?= /* @noEscape */ $navigationTitles; ?>,
                    "mediaQuery": <?= /* @noEscape */ $mediaQueryFull; ?>
                },
                "slick": {
                    "prevArrow": "<span class='slick-prev'><svg xmlns='http://www.w3.org/2000/svg' class='svg-icon svgi-left'><use xmlns:xlink='http://www.w3.org/1999/xlink' xlink:href='#svgi-left'></use></svg></span>",
                    "nextArrow": "<span class='slick-next'><svg xmlns='http://www.w3.org/2000/svg' class='svg-icon svgi-right'><use xmlns:xlink='http://www.w3.org/1999/xlink' xlink:href='#svgi-left'></use></svg></span>",
                    "autoplay": <?= /* @noEscape */ $autoPlay; ?>,
                    "autoplaySpeed": <?= (float)$getDelaySpeedValue; ?>,
                    "dots": <?= /* @noEscape */ $dots; ?>,
                    "infinite": <?= /* @noEscape */ $isLoop; ?>
                }
            }<?php if ($block->widgetHasVideo()) : ?>,
            "bannerVideo": {
                "mediaQuery": <?= /* @noEscape */ $mediaQueryFull; ?>
            }<?php endif; ?>
        }
    }
</script>
