<?php
    //Checkout GA
?>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-141669409-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-141669409-1');
    ga('create', 'UA-141669409-1', 'auto');
    ga('send', 'pageview');
    ga('require', 'ecommerce');
</script>