<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var \Magento\LayeredNavigation\Block\Navigation\FilterRenderer $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\LayeredNavigation\ViewModel\Layer\Filter $viewModel */
$viewModel = $block->getData('product_layer_view_model');
?>

<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a
                    href="<?= $escaper->escapeUrl($filterItem->getUrl()) ?>"
                    rel="nofollow"
                ><?= /* @noEscape */ $filterItem->getLabel() ?><?php
                if ($viewModel->shouldDisplayProductCountOnLayer()): ?><span
                        class="count"><?= /* @noEscape */ (int) $filterItem->getCount() ?><span
                            class="filter-count-label"><?php
                            if ($filterItem->getCount() == 1): ?>
                                <?= $escaper->escapeHtml(__('item')) ?><?php
                            else:
                                ?><?= $escaper->escapeHtml(__('item')) ?><?php
                            endif;?></span></span>
                    <?php endif; ?></a>
            <?php else: ?>
                <?= /* @noEscape */ $filterItem->getLabel() ?><?php
                if ($viewModel->shouldDisplayProductCountOnLayer()): ?><span
                        class="count"><?= /* @noEscape */ (int) $filterItem->getCount() ?><span
                            class="filter-count-label"><?php
                            if ($filterItem->getCount() == 1): ?>
                                <?= $escaper->escapeHtml(__('items')) ?><?php
                            else:
                                ?><?= $escaper->escapeHtml(__('items')) ?><?php
                            endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
    <div class="show-more-options">Show More</div>
</ol>

<script>
    require(['jquery', 'jquery/ui'], function($){ 
        $('#narrow-by-list .filter-options-content').each(function () {
            //console.log("Test JQuery!");
            var ctrOption = 0;
            var hiddenOptions = 0;
            $(this).find('li.item').each(function () {
                ctrOption++;
                if (ctrOption > 5) {
                    $(this).hide();
                    hiddenOptions++;
                }
                //console.log("ctrOption++: " + ctrOption++);
            });
            if (hiddenOptions == 0) {
                $(this).find('.show-more-options').hide();
            }
        });
        
        
        $('#narrow-by-list .filter-options-content .items').each(function () {
            var optionLimit = 5;
            var optionCtr = 0;
            var thisElement = $(this)
            thisElement.find('.show-more-options').click(function() {
                thisElement.find('li.item[style*="display: none"]').each(function () {
                    if (optionCtr <= optionLimit) {
                        $(this).show();
                        optionCtr++;
                        console.log("optionCtr: " + optionCtr);
                    } else {
                        optionCtr = 0;
                        return false;
                    }
                });
                
                var hiddenOption = 0;
                thisElement.find('li.item:hidden').each(function () {
                    hiddenOption++;
                })

                if (hiddenOption == 0) {
                    thisElement.find('.show-more-options').hide();
                }
                
            });
        });
        
        
    });
    
</script>
