<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
$priorityAttributes = ["Price", "Color", "MP_Brand", "Category", "Seller"];
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter -core">
        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if (!$wrapOptions) : ?>
                    <dl class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState":"active", "collapsible": true, "active":false,"multipleCollapsible":false}}'>
                    <?php $wrapOptions = true;
                endif; ?>
                    <?php if ($filter->getItemsCount()) : ?>
                        <?php if ($filter->getName() == "MP_Brand") : ?>
                            <dt role="heading" aria-level="3" class="filter-options-title">Brand</dt>
                        <?php else: ?>
                            <dt role="heading" aria-level="3" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></dt>
                        <?php endif; ?>
                        <dd class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></dd>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<script>
    require(['jquery', 'jquery/ui'], function($){ 
        $('#narrow-by-list > .filter-options-content').each(function () {
            var ctrOption = 0;
            var hiddenOptions = 0;
            $(this).children('.item').each(function () {
                ctrOption++;
                if (ctrOption > 5) {
                    $(this).hide();
                    hiddenOptions++;
                }
                console.log("ctrOption++: " + ctrOption++);
            });
            if (hiddenOptions == 0) {
                $(this).children('.show-more-options').hide();
            }
        });
    });
    
</script>
