<?php
/**
 * @var $block \Digidirect\OutOfStockNotif\Block\Product\View\Stock
 * @var $helper \Digidirect\OutOfStockNotif\Helper\Data
 */
$helper = $this->helper(\Digidirect\OutOfStockNotif\Helper\Data::class);
?>
<?php if($helper->showButton()) : ?>
    <div data-role="outofstock-button" class="outofstock-button">
        <button data-role="outofstock-popup-show" class="action primary"
                title="<?php echo $block->escapeHtml(__($block->getButtonLabel())); ?>" type="button">
            <span><?php echo $block->escapeHtml(__($block->getButtonLabel())); ?></span>
        </button>
    </div>
<?php endif; ?>
