<?php
/** @var $block \Magento\Catalog\Block\Product\View */
$_product = $block->getProduct();
$helper = $this->helper(\Digidirect\OutOfStockNotif\Helper\Data::class);
$helperSession = $this->helper(\Digidirect\OutOfStockNotif\Helper\Session::class);
$isNotificationForBackorder = $helper->isEnabledForBackorder();
$stock = $helper->getStockProvider($_product);
$isBackorderProduct = (bool)$stock->getBackorders();
$isBackOrderAllow = $helper->isBackOrderAllow($_product);
?>
<?php if ($isNotificationForBackorder && $_product->isSaleable() && $stock->getQty() <= 0 && $isBackorderProduct && $isBackOrderAllow ) : ?>
    <div data-role="outofstock-block" class="outofstock-block product alert <?php echo $block->getHtmlClass() ?>">
        <div data-role="outofstock-form">
            <p><?php /* @escapeNotVerified */ echo __("Enter your email address and we'll email you as soon as the item is back in stock"); ?></p>
            <form action="<?php echo $block->escapeUrl($helper->getPostAction()); ?>"
                  method="post"
                  data-mage-init='{"validation": {}}'>
                <input data-role="outofstock-input" type="hidden" name="product_id" value="<?php echo (int)$_product->getId(); ?>" />
                <div class="field">
                    <label for="outofstock-email" class="label"><?php echo $block->escapeHtml(__($block->getSignupLabel())); ?></label>
                    <div class="control">
                        <input type="email" name="email" id="outofstock-email"
                           data-validate="{required:true, 'validate-email':true}"
                           value="<?php echo $block->escapeHtml($helperSession->getCustomerEmail()); ?>" />
                    </div>
                </div>
                <button type="submit" class="action primary" title="<?php echo $block->escapeHtml(__($block->getButtonLabel())); ?>">
                    <span><?php echo $block->escapeHtml(__($block->getButtonLabel())); ?></span>
                </button>
            </form>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "outstockNotification": {
                    "modalOptions": <?= /* @noEscape */ json_encode($block->getModalOptions()); ?>,
                    "notificationForBackorder": 1,
                    "isBackorderProduct": <?= /* @noEscape */ $isBackorderProduct; ?>,
                    "backorderButtonLabel": "<?php echo $block->escapeHtml(__($block->getBackorderButtonLabel())); ?>"
                }
            }
        }
    </script>
<?php endif; ?>
