<?php

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Arrivals');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>

<?php if ($exist):?>
    <div class="widget block-new-products products-widget _full-width-background <?= /* @escapeNotVerified */ $mode ?>">
        <span class="title" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></span>
        <div class="block-content">
            <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @escapeNotVerified */ $mode ?> <?= /* @escapeNotVerified */ $mode ?>">
                <div class="product-items product-carousel <?= /* @escapeNotVerified */ $type ?>"
                    <?php if (count($items) > 2):?>   
                        data-mage-init='{
                                            "slickInit":{
                                                "infinite": false,
                                                "slidesToShow": 2,
                                                "slidesToScroll": 2,
                                                "mobileFirst": true,
                                                "arrows": false,
                                                "responsive": [{
                                                    "breakpoint": 1024,
                                                    "settings": {
                                                        "slidesToShow": 4,
                                                        "slidesToScroll": 4
                                                    }
                                                }, {
                                                    "breakpoint": 767,
                                                    "settings": {
                                                        "slidesToShow": 3,
                                                        "slidesToScroll": 3
                                                    }
                                                },
                                                {
                                                    "breakpoint": 1439,
                                                    "settings": {
                                                        "slidesToShow": 5,
                                                        "slidesToScroll": 5,
                                                        "arrows": true
                                                    }
                                                }]
                                            }
                                        }'
                        <?php endif; ?>>
                        <?php foreach ($items as $_item): ?>
                        <div class="product-item">
                            <div class="product-item-info">
                                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>

                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                        title="<?= $block->escapeHtml($_item->getName()) ?>"
                                        href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>                     

                                <div class="product details product-item-details">

                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>
                                    <?php echo $block->getProductPriceHtml($_item, $type); ?>


                                    <div class="product-item-inner">
                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product actions product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="action tocart"
                                                                        data-mage-init='{"redirectUrl":{"url":"<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}'
                                                                        type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php
                                                                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="action tocart"
                                                                        data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                        type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                                <?php if ($showWishlist || $showCompare): ?>
                                                    <div class="actions-secondary" data-role="add-to-links">
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                            <a href="#"
                                                            data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item) ?>'
                                                            class="action towishlist" data-action="add-to-wishlist"
                                                            title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>">
                                                            <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-heart"></use></svg>
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                            <a href="#" class="action tocompare"
                                                            data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_item) ?>'
                                                            title="<?= /* @escapeNotVerified */ __('Add to Compare') ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php echo $this->getLayout()
                                            ->createBlock('Magento\Cms\Block\Block')
                                            ->setBlockId('product-tile-rent')
                                            ->toHtml(); ?>
                                    </div>
                                </div>                        
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>
