<div class="brand-header" style="background: #F2F2F7">
    <div style="max-width: 1327px; margin: 0 auto; padding: 20px 0 30px;">
        <div style="color: #242426; font-size: 32px; font-weight: 600; margin-bottom: 15px;">Shop by Brand</div>
        <div style="width: 100%; justify-content: center; display: flex; color: #545456; font-size: 16px; font-weight: 500;">
            At digiDirect, we’re proud to serve as an officially authorized reseller for many of our trusted brand partners. When you purchase through an authorized channel, you receive an unmatched level of transparency, reliability, and support. Our partners provide continuous training to our team, ensuring that every customer benefits from expert product advice. We believe our responsibility extends well beyond checkout. Our service and support continue long after your purchase is complete, so you can shop with real confidence. Choosing digiDirect means choosing a seamless, informed shopping experience rooted in integrity and quality.
        </div>
    </div>
</div>
<div class="brand-filter-container">
    <div class="brand-filter">
        <div class="brand-alphabet">
            <span class="letter active" data-letter="all">All</span>
            <?php foreach (range('A', 'Z') as $char): ?>
                <span class="letter" data-letter="<?= $char ?>"><?= $char ?></span>
            <?php endforeach; ?>
        </div>
        <input type="text" id="brand-search" placeholder="Search brands..." class="brand-search-input"/>
        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 35 35" fill="none">
            <rect width="35" height="35" rx="17.5" fill="#FE4C25"></rect>
            <path d="M26 26L22.2223 22.2156M24.3158 17.1579C24.3158 19.0563 23.5617 20.8769 22.2193 22.2193C20.8769 23.5617 19.0563 24.3158 17.1579 24.3158C15.2595 24.3158 13.4389 23.5617 12.0965 22.2193C10.7541 20.8769 10 19.0563 10 17.1579C10 15.2595 10.7541 13.4389 12.0965 12.0965C13.4389 10.7541 15.2595 10 17.1579 10C19.0563 10 20.8769 10.7541 22.2193 12.0965C23.5617 13.4389 24.3158 15.2595 24.3158 17.1579Z" stroke="white" stroke-width="1.5" stroke-linecap="round"></path>
        </svg>
    </div>
</div>
