<?php
/**
 * @var \Ewave\Blog\Block\Widget\Latest $block
 * @var \Ewave\Blog\Model\Post $post
 */
?>

<?php $latestPosts = $block->getCollection(); ?>
<div class="blog-latest blog-widget widget _negative-gutter _full-width-background">
    <div class="blog-list">
        <?php foreach ($latestPosts as $post): ?>
            <?php $postTitle = $block->escapeHtml($post->getTitle()); ?>
            <?php $mainImage = $post->getMainImage(); ?>
            <a class="post-card item" href="<?php echo $block->escapeUrl($post->getViewUrl()) ?>" title="<?php /* @escapeNotVerified */ echo $postTitle; ?>">
                <?php if (!empty($mainImage)): ?>
                    <img class="image" src="<?php echo $block->escapeHtml($mainImage); ?>" alt="<?php /* @escapeNotVerified */ echo $postTitle; ?>" />
                <?php endif; ?>
                <div class="container">
                    <h3 class="title"><?php /* @escapeNotVerified */ echo $postTitle; ?></h3>
                    <p class="content"><?php /* @escapeNotVerified */ echo $post->getShortContent(); ?></p>
                    <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon svgi-arrow">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-arrow"></use>
                    </svg>
                </div>
            </a>
        <?php endforeach; ?>
    </div>
</div>
