<?php
/** @var \Digidirect\StoreLocator\Block\ListStore\DetailPage $block */
$currentApi = $this->helper('Digidirect\StoreLocator\Helper\Config')->getApi();
?>
<?php if ($currentApi === 'google') : ?>
    <script type="text/x-magento-init">
        {
            ".store-view": {
                "locator": {
                    "defaultAddress": "<?php echo $block->escapeHtml($block->getDefaultCountry()) ?>",
                    "search": {"onLoad": false},
                    "mapInline": {
                        "enable": true,
                        "item": <?php /* @escapeNotVerified */ echo $block->getStoreData() ?>
                    },
                    "radius": {"enable": false},
                    "marker": {
                        "settings": {
                            "icon": {
                                "url": "<?php echo $block->escapeHtml($block->getViewFileUrl('images/cluster/pin.png')) ?>"
                            }
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>
