<div class="admin__field-control giftcard_service">
    <input type="hidden" name="service_code" value="vii"/>
    <input id="code" name="code" type="text" class="input-text admin__control-text" style="max-width: 170px;" placeholder="Code" />
    <input id="pin" name="pin" type="text" class="input-text admin__control-text" style="max-width: 60px;" placeholder="Pin"/>
    <button type="button" value="" class="action-default">
        <span><?php echo $block->escapeHtml(__('Add Gift Card')); ?></span>
    </button>
</div>