<div class="field qff-number">
    <label class="label" for="qff-number">
      <span><?= $block->escapeHtml(__('Qantas Frequent Flyer Number')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="qff_number" id="qff-number" value="" title="<?= $block->escapeHtmlAttr(__('Qantas Frequent Flyer Number')) ?>" class="input-text" data-validate="{required:false}">
    </div>
</div>
<div class="field qff-number">
    <label class="label" for="qff-lastname">
      <span><?= $block->escapeHtml(__('Qantas Frequent Flyer Lastname')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="qff_lastname" id="qff-lastname" value="" title="<?= $block->escapeHtmlAttr(__('Qantas Frequent Flyer Lastname')) ?>" class="input-text" data-validate="{required:false}">
    </div>
</div>