<?php
    /** @var $block \Ewave\ProductOverlay\Block\Overlay */
?>

<?php
    /** @var \Ewave\ProductOverlay\Model\Overlays $overlay */
    $overlay = $this->getOverlay();
    $overlayId = (int)$overlay->getId();
    $productId = (int)$overlay->getProduct()->getId();
    $key = $overlayId . '-' . $productId;
    $text = $overlay->getText();
    $nativeText = strip_tags($text);
    $containerPath = $block->getContainerPath();
    $hasImageSize = $overlay->getImageSize() ? ' -has-size' : '';
?>
<?php if ($containerPath): ?>
    <div data-testid="productOverlay-overlayBlock"
         class="product-overlay-<?php echo $block->escapeHtml($key); ?> product-overlay -<?php echo $block->escapeHtml($overlay->getCssClass()) ?><?php /* @escapeNotVerified */ echo $hasImageSize; ?>"
        <?php if ($overlay->getUseForParent()): ?> data-role="use-for-parent"<?php endif; ?>
         style="<?php echo $block->escapeHtml($overlay->getValue('block_style')); ?>"
         data-overlay-id="<?= $block->escapeHtml($overlayId); ?>"
         data-product-id="<?= $block->escapeHtml($productId); ?>"
    >
        <img class="img"
             src="<?php echo $block->escapeUrl($block->getImageScr()) ?>"
             title="<?php echo $block->escapeHtml($nativeText) ?>"
             alt="<?php echo $block->escapeHtml($nativeText) ?>"
        >
        <div class="text" style="<?php echo $block->escapeHtml($overlay->getValue('text_style')); ?>">
            <?php /* @escapeNotVerified */ echo $text; ?>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            ".product-overlay-<?= $block->escapeHtml($key); ?>": {
                "productOverlay": {
                    "size": <?= /* @escapeNotVerified */ $overlay->getImageSize() ?>,
                    "path": "<?= $block->escapeHtml($containerPath) ?>",
                    "mode": "<?= $block->escapeHtml($overlay->getMode()) ?>",
                    "hideForConfigurable": "<?= /* @escapeNotVerified */ $overlay->getHideInConfigurable(); ?>"
                }
            }
        }
    </script>


    <?php  /** Start: Overlay Settings for You may also Like slider (Ewave_ProductOverlay/web/js/upsell-slider.js) */ ?>

    <script type="text/javascript">
        window.overlayOnSlideSize = <?= /* @escapeNotVerified */ $overlay->getImageSize() ?>;
        window.overlayOnSliderPath = "<?= $block->escapeHtml($containerPath) ?>";
        window.overlayOnSliderMode = "<?= /* @escapeNotVerified */ $overlay->getImageSize() ?>";
        window.overlayOnSliderHideForConfigurable = "<?= /* @escapeNotVerified */ $overlay->getHideInConfigurable(); ?>";
    </script>

    <?php /** End */ ?>


    <script type="text/x-magento-init">
    {
        "*": {
            "Ewave_ProductOverlay/js/upsell-slider": {}
        }
    }
    </script>
<?php endif; ?>


