<?php
/**
 * @var $block View
 * @var $sellerDataHelper Data
 * @var $seller SellerInterface
 * @var $escaper Escaper
 */

use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;
use Marketplacer\Seller\Api\Data\SellerInterface;
use Marketplacer\Seller\Helper\Data;

$product = $block->getProduct();
$sellerDataHelper = $this->helper(Data::class);
$seller = $sellerDataHelper->getSellerByProduct($product);

if (!$seller instanceof SellerInterface || !$seller->isEnabled()) {
    return;
}

$sellerName = $seller->getName();
$sellerLogo = $seller->getLogo();
$sellerPolicies = $seller->getPolicies();
$sellerUrl = $sellerDataHelper->getSellerUrl($seller);
?>

<div class="mrkt-product-info-seller">
    <span class="name">This item will be shipped from our trusted digiMarket Sellers.</span>
    <br>
    <strong class="name">
        Shipped by: <?= $escaper->escapeHtml($sellerName) ?>
    </strong>
    <?php if ($sellerLogo): ?>
        <span class="image">
            <img src="<?= $escaper->escapeUrl($sellerLogo) ?>" alt="<?= $escaper->escapeHtmlAttr($sellerName) ?>"/>
        </span>
    <?php endif ?>
    <br/>
    <?php if ($sellerPolicies): ?>
        <a class="policy" href="<?= $escaper->escapeUrl($sellerPolicies) ?>">
            <?= $escaper->escapeHtml(__('Policies')) ?>
        </a>
    <?php endif ?>
</div>
