<?php
/** @var $block \Ewave\Navigation\Block\Menu */
$menuJson = $block->getMenuJson();
?>
<?php $menuArray = json_decode($menuJson); ?>
<?php
if (empty($menuArray)) {
    return;
}
?>

<nav data-mage-init='{"mainMenu": {}}' data-action="navigation" class="<?php echo $block->escapeHtml($block->getAreaSelector());?><?php echo
$block->getResponsive()? ' -responsive -'.$block->getOffCanvasSide()  : ''?>">
    <ul class="<?php echo $block->getWrapperClass() ? ' ' . $block->escapeHtml($block->getWrapperClass()) : '';?><?php echo $block->getHorizontal() == 'true' ? ' -horizontal' : '';?><?php echo $block->getExpanded() == 'true' ? ' -expanded' : '';?>">
        <?php $i = 1; $j = 1; foreach ($menuArray as $item) : ?>
        <?php if (isset($item->cms_block_content)){
            $length = strlen($item->cms_block_content) ;
        } else {
            $length = false;
        }
        if ($length || isset($item->children) && !empty($item->children)) {
            $have_parent = true;
        } else {
            $have_parent = false;
        }?>
            <?php if(isset($item->style)) : ?>
                <?php $style = $item->style; ?>
            <?php else: ?>
                <?php $style = null; ?>
            <?php endif;?>
        <li class="category-item <?php echo $block->escapeHtml($item->frontend_class); ?><?php echo $block->getItemClass
        () ? ' ' . $block->escapeHtml($block->getItemClass()) : '';?><?php echo $item->is_active ? ' -active': '' ?><?php echo $have_parent ? ' -parent' : '' ?> -level<?php echo $block->escapeHtml((int)$i) ?>">
            <?php if ($item->url && ($item->is_link == '1' || $item->is_link === true)): ?>
                <a <?php if($style) : ?>style="<?php echo $block->escapeHtml($style) ?>" <?php endif; ?> class="prevented<?php echo $block->getItemLabelClass() ? ' ' . $block->escapeHtml($block->getItemLabelClass()) : '';?>" title="<?php echo $block->escapeHtml($item->title) ?>" href="<?php echo $block->escapeUrl($item->url) ?>" id="mi-<?php echo (int)$i ?>-<?php echo $block->escapeHtml((int)$j) ?>">
                    <?php echo $block->escapeHtml($item->title) ?>
                </a>
            <?php else: ?>
                <span <?php if($style) : ?>style="<?php echo $block->escapeHtml($style)?>" <?php endif; ?> class="<?php echo $block->getItemLabelClass() ? ' ' . $block->escapeHtml($block->getItemLabelClass()) : '';?>" id="mi-<?php echo $block->escapeHtml((int)$i) ?>-<?php echo $block->escapeHtml((int)$j) ?>">
                    <?php echo $block->escapeHtml($item->title) ?>
                </span>
            <?php endif; ?>
            <?php
            $function = function ($children, $i, $j, $m) use (&$function, $block, $item) { ?>
                <?php $i++; $k = 1; $n = 0; $v = $m; ?>
                <?php foreach ($children as $child) : ?>
                    <?php if (isset($child->cms_block_content)){
                        $length = strlen($child->cms_block_content) ;
                    } else {
                        $length = false;
                    }
                    if ($length || isset($child->children) && !empty($child->children)) {
                        $have_parent = true;
                    } else {
                        $have_parent = false;
                    }?>
                    <?php if(isset($child->frontend_class)): ?>
                        <?php $frontendChildClass = $child->frontend_class; ?>
                    <?php else: ?>
                        <?php $frontendChildClass = ''; ?>
                    <?php endif; ?>
                    <?php if(isset($child->style)) : ?>
                        <?php $style = $child->style; ?>
                    <?php else: ?>
                        <?php $style = null; ?>
                    <?php endif;?>
                    <li class="category-item <?php echo $block->escapeHtml($frontendChildClass) ?><?php echo
                    $block->getItemClass() ? ' ' . $block->escapeHtml($block->getItemClass()) : '';?><?php echo $child->is_active ? ' -active': '' ?><?php echo $have_parent? ' -parent' : '' ?> -level<?php echo (int)$i?><?php if(isset($child->menu_item_type)): ?> -type-<?= /* @noEscape */ $child->menu_item_type ?><?php endif;?>">
                        <?php if ($child->url && ($child->is_link == '1' || $child->is_link === true)) : ?>
                            <a <?php if($style) : ?>style="<?php echo $block->escapeHtml($style)?>" <?php endif; ?> class="<?php /* @escapeNotVerified */ echo $block->getItemLabelClass() ? ' ' .  $block->escapeHtml($block->getItemLabelClass()) : '';?>" title="<?php /* @escapeNotVerified */ echo $child->title ?>" href="<?php /* @escapeNotVerified */ echo $child->url ?>" id="mi-<?php echo (int)$i ?>-<?php echo (int)$j ?><?php if ($m): ?>-<?php echo (int)$m; ?><?php endif; ?>-<?php echo (int)$k ?>">
                                <?php /* @escapeNotVerified */ echo $child->title ?>
                            </a>
                        <?php else : ?>
                            <span <?php if($style) : ?>style="<?php echo $block->escapeHtml($style) ?>" <?php endif; ?> class="<?php /* @escapeNotVerified */ echo $block->getItemLabelClass() ? ' ' . $block->getItemLabelClass() : '';?>" id="mi-<?php echo (int)$i ?>-<?php echo (int)$j ?><?php if ($m): ?>-<?php echo (int)$m; ?><?php endif; ?>-<?php echo (int)$k ?>">
                                <?php /* @escapeNotVerified */ echo $child->title ?>
                            </span>
                        <?php endif; ?>
                        <?php if ($have_parent):?>
                        <div class="<?php /* @escapeNotVerified */ echo $block->getSubMenuBlockClass() ? ' ' . $block->getSubMenuBlockClass() : '';?> -level<?php echo (int)$i?>" data-id="mi-<?php echo (int)$i ?>-<?php echo (int)$j ?><?php if ($m): ?>-<?php echo (int)$m; ?><?php endif; ?>-<?php echo (int)$k ?>" data-level-dip="-level<?php echo (int)$i+1?>">
                            <?php if (isset($child->cms_block_content)): ?>
                                <div class="<?php /* @escapeNotVerified */ echo $block->getCmsBlockClassName()? $block->getCmsBlockClassName() : ''?>"><?php echo isset($child->cms_block_content) ? $child->cms_block_content : '' ?></div>
                            <?php endif; ?>
                            <?php if (isset($child->children)) : ?>
                                <?php $n++; $m = $n; ?>
                                <ul class="<?php /* @escapeNotVerified */ echo $block->getInnerListsClass() ? ' ' . $block->getInnerListsClass() : '';?>">


                                <!-- START DIGI CATEGORY BRAND MENU HARDCODE FOR SEO PURPOSES -->
                                <?php
                                    if (strpos($child->title, 'Brands') == 0 && count($child->children)) {
                                        foreach ($child->children as $brandLink) {
                                            if (strpos($brandLink->url, '/brands/') !== false && $item->url) {
                                                $brandLinkLastPart = last(array_filter(explode('/', $brandLink->url)));
                                                $brandLink->url = $item->url . '/' . $brandLinkLastPart;
                                            }
                                        }
                                    }
                                ?>
                                <!-- END DIGI CATEGORY BRAND MENU HARDCODE FOR SEO PURPOSES -->

                                    <?php $function($child->children, $i, $j, $m); ?>
                                </ul>
                                <?php $m = $v; ?>
                            <?php endif; ?>
                        </div>
                        <?php endif;?>
                    </li>
                <?php $k++;  endforeach; ?>
            <?php }; ?>
            <?php if ($have_parent || (isset($item->content) && !empty($item->content))):?>
                <div class="<?php echo $block->getSubMenuBlockClass() ? ' ' . $block->escapeHtml($block->getSubMenuBlockClass()) : '';?> -level<?php echo (int)$i ?>" data-id="mi-<?php echo (int)$i ?>-<?php echo (int)$j ?>" data-level-dip="-level<?php echo (int)$i+1?>">
                    <?php if (isset($item->cms_block_content)): ?>
                        <div class="<?php echo $block->getCmsBlockClassName()? $block->escapeHtml($block->getCmsBlockClassName()) : ''?>"><?php /* @escapeNotVerified */ echo $item->cms_block_content ?></div>
                    <?php endif; ?>
                    <?php
                    if (isset($item->children)) : ?>
                        <?php $m = 0; ?>
                        <ul class="<?php echo $block->getInnerListsClass() ? ' ' . $block->getInnerListsClass() : '';?>">
                            <?php $function($item->children, $i, $j, $m); ?>
                        </ul>
                    <?php endif; ?>

                    <?php if (isset($item->content) && !empty($item->content)) : ?>
                        <div class="<?php echo $block->getExtraContentClassName()? $block->escapeHtml($block->getExtraContentClassName()) : ''?>"><?php /* @escapeNotVerified */ echo $item->content ?></div>
                    <?php endif; ?>
                </div>
            <?php endif;?>
        </li>
        <?php $j++; endforeach; ?>
    </ul>
</nav>

<?php if ($mainMenuBottom = $block->getChildHtml('main.menu.bottom')) : ?>
    <div class="menu-cmsitem">
        <div class="helpful-info">
            <?php echo $mainMenuBottom ?>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*": {
            "navigation": {
                "area": ".<?php /* @escapeNotVerified */ echo $block->getAreaSelector();?>",
                "wrapperClass": ".<?php /* @escapeNotVerified */ echo $block->getWrapperClass();?>",
                "itemClass": ".<?php /* @escapeNotVerified */ echo $block->getItemClass();?>",
                "itemLabelClass": ".<?php /* @escapeNotVerified */ echo $block->getItemLabelClass();?>",
                "innerListsClass": ".<?php /* @escapeNotVerified */ echo $block->getInnerListsClass();?>",
                "subMenuBlockClass": ".<?php /* @escapeNotVerified */ echo $block->getSubMenuBlockClass();?>",
                "cmsBlockClassName": ".<?php /* @escapeNotVerified */ echo $block->getCmsBlockClassName();?>",
                "expanded": <?php /* @escapeNotVerified */ echo $block->getExpanded() ? 'true' : 'false';?>,
                "place": "<?php /* @escapeNotVerified */ echo $block->getPlace();?>",
                "horizontal": <?php /* @escapeNotVerified */ echo $block->getHorizontal() ? 'true' : 'false';?>,
                "static": <?php /* @escapeNotVerified */ echo $block->getStatic() ? 'true' : 'false';?>,
                "action": "<?php /* @escapeNotVerified */ echo $block->getAction();?>",
                "responsive": <?php /* @escapeNotVerified */ echo $block->getResponsive() ? 'true': 'false';?>,
                "togglerSelector": "<?php /* @escapeNotVerified */ echo $block->getTogglerSelector();?>",
                "offCanvasClass": "<?php /* @escapeNotVerified */ echo $block->getOffCanvasClass();?>",
                "offCanvasSide": "<?php /* @escapeNotVerified */ echo $block->getOffCanvasSide();?>",
                "offCanvasEvent": "<?php /* @escapeNotVerified */ echo $block->getOffCanvasEvent();?>",
                "breakpoint": "<?php /* @escapeNotVerified */ echo $block->getBreakpoint();?>",
                "viewCustom": "<?php /* @escapeNotVerified */ echo $block->hasViewCustom() ? $block->getViewCustom() : '';?>",
                "linkString": "<?php /* @escapeNotVerified */ echo $block->getLinkString();?>",
                "addLinkToTop": <?php /* @escapeNotVerified */ echo $block->getAddLinkToTop() ? 'true' : 'false';?>
            }
        }
    }
</script>
