<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart update">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                <div class="control qty-group-control" data-bind="scope: 'qty-change'">
                    <input data-bind="value: qty()"
                           type="number" 
                           name="qty" 
                           id="qty" 
                           value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>" 
                           title="<?= /* @escapeNotVerified */ __('Qty') ?>" 
                           class="input-text qty qty-pdp" 
                           data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" /> 
                    
                    <div class="qty-buttons">
                        <button data-bind="click: increaseQty"><i class="fas fa-angle-up"></i></button> 
                        <button data-bind="click: decreaseQty"><i class="fas fa-angle-down"></i></button>
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action tocart"
                        id="product-updatecart-button">
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action tocart btn_cart tocart-pdp-btn"
                        id="product-updatecart-button">
                    <span class="addcart_words"><?= /* @escapeNotVerified */ $buttonTitle ?></span><span class="addcart_plus_logo"><i class="fas fa-cart-plus fa-lg"></i></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
