<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="placestorage" type="placestorageDeclaration" minOccurs="1" maxOccurs="unbounded">
                    <xs:unique name="uniqueHandleName">
                        <xs:annotation>
                            <xs:documentation>
                                Handle name must be unique.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="config"/>
                        <xs:field xpath="@handle"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniquePlacestorageName">
            <xs:annotation>
                <xs:documentation>
                    Collect place storage name must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="placestorage" />
            <xs:field xpath="@name" />
        </xs:unique>
    </xs:element>
    <xs:complexType name="placestorageDeclaration">
        <xs:annotation>
            <xs:documentation>
                Collect Place Storage declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="config" type="configDeclaration" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="name" type="placestorageName" use="required" />
    </xs:complexType>
    <xs:complexType name="configDeclaration">
        <xs:annotation>
            <xs:documentation>
                Config declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="handle" type="xs:string" use="required" />
        <xs:attribute name="instance" type="xs:string" use="required" />
        <xs:attribute name="source" type="xs:string" use="required" />
    </xs:complexType>

    <xs:simpleType name="placestorageName">
        <xs:annotation>
            <xs:documentation>
                Storage name can contain only [a-zA-Z_].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z_]+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>