<?php
/**
 * @var \Digidirect\AbstractGiftCard\Block\Check $block
 * @see \Magento\GiftCardAccount\Block\Check
 */
$card = $block->getCard();
$helper = $this->helper('Digidirect\Vii\Helper\Data');
?>
<?php if ($card): ?>
    <?php $status = $helper->getCardStatusLabel($card->getCardStatus()); ?>
    <div class="giftcard-info table-wrapper">
        <table class="data table">
            <thead>
                <tr>
                    <th class="col"><?php echo $block->escapeHtml(__('Gift Card'));?></th>
                    <th class="col"><?php echo $block->escapeHtml(__('Current Balance')); ?></th>
                    <th class="col"><?php echo $block->escapeHtml(__('Expiry Date')); ?></th>
                    <th class="col"><?php echo $block->escapeHtml(__('Card Status')); ?></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="col" data-th="<?php echo $block->escapeHtml(__('Gift Card')); ?>"><?php echo $block->escapeHtml($card->getCode()); ?></td>
                    <td class="col" data-th="<?php echo $block->escapeHtml(__('Current Balance')); ?>"><?php /* @noEscape */ echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($card->getBalance()); ?></td>
                    <td class="col" data-th="<?php echo $block->escapeHtml(__('Expiry Date')); ?>"> <?php if ($card->getDateExpires()): ?><?php echo $block->escapeHtml($card->getDateExpires()); ?> <?php endif; ?></td>
                    <td class="col" data-th="<?php echo $block->escapeHtml(__('Card Status')); ?>"><?php echo $block->escapeHtml($status); ?></td>
                </tr>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <?php if ($message = $block->getMesssages()->getLastAddedMessage()): ?>
        <div class="message error">
            <span><?php echo $block->escapeHtml(__($message->getText())); ?></span>
        </div>
    <?php else: ?>
        <div class="message error">
            <span><?php echo $block->escapeHtml(__('Please enter a valid gift card code.')); ?></span>
        </div>
    <?php endif;?>
<?php endif; ?>
