<?php
/**
 * @var \Ewave\SitemapWidget\Block\Widget\AdditionalEntity\Renderer $block
 * @var array $entity
 */
$entity = $block->getEntity();
?>
<li>
    <a href="<?php echo $block->escapeUrl($entity->getUrl()); ?>" title="<?php echo $block->escapeHtml($entity->getTitle()); ?>">
        <?php echo $block->escapeHtml($entity->getTitle()); ?>
    </a>
    <?php if ($entity->hasChildren()): ?>
        <ul>
            <?php /* @escapeNotVerified */ echo $block->render($entity->getChildren()); ?>
        </ul>
    <?php endif; ?>
</li>
