<?php
$payment = $block->getInfo();

$ccType  = $payment->getAdditionalInformation('cc_type');
$ccLast4 = $payment->getCcLast4();
?>

<p><strong><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></strong></p>

<?php if ($ccType): ?>
    <p>
        <strong><?= __('Credit Card Type') ?>:</strong>
        <?= $block->escapeHtml($ccType) ?>
    </p>
<?php endif; ?>

<?php if ($ccLast4): ?>
    <p>
        <strong><?= __('Credit Card Number') ?>:</strong>
        xxxx-<?= $block->escapeHtml($ccLast4) ?>
    </p>
<?php endif; ?>