<?php
    $productBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Digidirect\Catalog\Block\ProductInfoBlock');
    $currentProduct = $productBlock->getCurrentProduct();

    $digiprintItemCondition = ($currentProduct->getItemCodition() ? $currentProduct->getItemCodition() : '');
    $digiprintItemDescription = ($currentProduct->getData('digiprint_desc') ? $currentProduct->getData('digiprint_desc') : '');
    $digiprintCustomLinkProductSKU = ($currentProduct->getData('digiprint_customlink') ? $currentProduct->getData('digiprint_customlink') : '');

    $categoryIds = $currentProduct->getCategoryIds();


    // echo $digiprintItemDescription;
//    var_dump($categoryIds);


//    foreach ($categoryIds as $value) {
//     echo "$value ";

//   }


?>


<?php foreach($categoryIds as $digiprintID): ?>
    <?php if ($digiprintID == 2580): ?>
        <br><br>
        <p><a class="create-now-btn" href="<?php echo $digiprintCustomLinkProductSKU;?>"> <button>Create Now </button></a></p>
        <br>
        <span class="digiprint-note">
            <?= /* @escapeNotVerified */ $digiprintItemDescription ?>
        </span>

       <?php echo '<style>.qantas-pts-wrapper, .box-tocart, .payment-gateways-container, .payment-gateways-container-bottom, .product-info-main-bottom {display:none !important;}</style>'; ?>
    <?php endif; ?>
<?php endforeach ?>


<style>
    .create-now-btn {
        /* background: #ff3c00 !important; */
        line-height: 2.2rem;
        width:100%;
        margin-left:0;
        margin-right:0;
        padding-left:0;
        padding-right:0;
        display:block;
        text-align:center;
        color: #fff !important;
        text-decoration: none !important;
        line-height: 2.2rem;
        /* padding: 14px 17px; */
        height: 50px;
        border-radius: 4px;
        font-size: 1.8rem;
        text-transform: uppercase;
    }

    .create-now-btn button {
        margin-top: 10px;
        background: #ff3c00 !important;
        border-radius: 4px;
        font-size: 15px;
        font-weight: 500;
        color: #fff !important;
        text-transform: uppercase;
        width:100%;
        

    }
</style>
