<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if ($block->hasSpecialPrice()): ?>
    <div class="current-price-wrapper">
        <svg class="svg-icon digidirectprice">
            <use xlink:href="#svgi-digidirectprice" />
        </svg>
        <span class="special-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __(''),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
    </div>
    <div class="old-price-wrapper">
        <span class="old-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Original Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
    </div>
<?php else: ?>
    <div class="current-price-wrapper">
        <svg class="svg-icon digidirectprice">
            <use xlink:href="#svgi-digidirectprice" />
        </svg>
        <span class="special-price">
             <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __(''),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
    </div>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>

<?php
    // Note: Change $d2ItemCondition to digiSeconds attribute when pushing to live site.
    $productBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Digidirect\Catalog\Block\ProductInfoBlock');

    $currentProduct = $productBlock->getCurrentProduct();
    $d2BrandNewProductSKU = $currentProduct->getData('d2newsku');  
    $d2ItemCondition = $currentProduct->getItemCodition();  
    $d2ItemDescription = $currentProduct->getData('d2desc'); 
    $d2ItemRating = $currentProduct->getItemRating();  
    
    //$brandNewProduct = $productBlock->getProductBySku($d2BrandNewProductSKU);
    //$brandNewProductPrice = $brandNewProduct->getPrice();
?>

<div class="digiseconds-info-wrapper">
    <div class="brand-new-price-wrapper old-price-wrapper">
        <span class="brand-new-label">
            Brand New Price
        </span>
        <span class="brand-new-price old-price">
        </span>
    </div>
    <div class="refurb-price-wrapper old-price-wrapper" style="display: none !important;">
        <span class="refurb-label">
            Refurbished Price
        </span>
        <span class="refurb-price old-price">
            $2,500
        </span>
    </div>
    <div class="item-note-wrapper">
        <span class="item-note-label">
            Item Note: 
        </span>
        <span class="item-note">
        </span>
    </div>
    <div class="warranty-wrapper old-price-wrapper" style="display: none !important;">
        <span class="warranty-label">
            WARRANTY 
        </span>
        <span class="warranty-description">
            7 days replacement and 6 months service
        </span>
    </div>
</div>


