<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
    /** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
    /** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
    /** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
    $priceModel = $block->getPriceType('regular_price');

    /** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
    /** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
    $finalPriceModel = $block->getPriceType('final_price');
    $idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
    $schema = ($block->getZone() == 'item_view') ? true : false;
    
    $originalPrice = number_format((float)$block->getSaleableItem()->getPrice(), 2, '.', '');
    $promoPrice = number_format((float)$block->getSaleableItem()->getFinalPrice(), 2, '.', '');
    $wiserPrice = number_format((float)$block->getSaleableItem()->getWiserPrice(), 2, '.', '');
    $discountWiserPrice = round($originalPrice - $wiserPrice, 2);
    
    if (is_null($wiserPrice) || $wiserPrice == 0) {
        $discountPrice = round($originalPrice - $promoPrice, 2);
    } else {
        if ($wiserPrice < $promoPrice) {
            $discountPrice = round($originalPrice - $wiserPrice, 2);
        } else {
            $discountPrice = round($originalPrice - $promoPrice, 2);
        }
    }

    //$_product = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Registry::class)->registry('product');
    $mpDiscountPrice = 0;
    $marketPlacePrice = number_format((float)$block->getSaleableItem()->getMarketplacesPrice(), 2, '.', '');
    if (!is_null($marketPlacePrice) || $marketPlacePrice != 0) {
        if ($marketPlacePrice > $promoPrice) {
            $mpDiscountPrice = round($marketPlacePrice - $promoPrice, 2);
        }
    }
    
    $quoteHelper = $this->helper('Digidirect\Digi\Helper\Quote');
    $customerGroupId = $quoteHelper->getCustomerGroupId();
?>
<?php if ($block->hasSpecialPrice()): ?>
    <?php if (($marketPlacePrice && $marketPlacePrice != 0) && ($priceModel->getAmount() < $marketPlacePrice)): ?>
        <div class="old-price-wrapper marketplaces-price">
            <span class="old-price">  
                <span class="price-container price-final_price tax weee"> 
                    <span class="price-label">PRICE SLASHED</span>  
                    <span class="price" data-price-amount="<?php echo $marketPlacePrice;?>">
                        <span class="marketplaces-price">$<?php echo $marketPlacePrice;?></span>
                    </span>  
                </span>
            </span>
        </div>
        <div class="current-price-wrapper">
            <?php if ($customerGroupId == 10) { ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Club <span style="font-weight: 400;">Member Price</span></span></div>
            <?php } else { ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>
            <?php } ?>
            <span class="special-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label'     => __(''),
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </span>
        </div>
        <div class="discount-price-wrapper">$<span class="discount-price"><?= number_format($mpDiscountPrice, 2)?></span> Off</div>
    <?php else: ?>
        <div class="old-price-wrapper">
            <span class="old-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
                    'display_label'     => __('Price Slashed'),
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
        </div>
        <div class="current-price-wrapper has-special-price">
            <?php if ($customerGroupId == 10) { ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Club <span style="font-weight: 400;">Member Price</span></span></div>
            <?php } else { ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>
            <?php } ?>
            <span class="special-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label'     => __(''),
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </span>
        </div>
        <div class="discount-price-wrapper">$<span class="discount-price"><?= number_format($discountPrice, 2)?></span> Off</div>
    <?php endif; ?>
<?php else: ?>
    <?php if (($marketPlacePrice && $marketPlacePrice != 0) && ($finalPriceModel->getAmount() < $marketPlacePrice)): ?>
        <div class="old-price-wrapper marketplaces-price">
            <span class="old-price">  
                <span class="price-container price-final_price tax weee"> 
                    <span class="price-label">PRICE SLASHED</span>  
                    <span class="price" data-price-amount="<?php echo $marketPlacePrice;?>">
                        <span class="marketplaces-price">$<?php echo $marketPlacePrice;?></span>
                    </span>  
                </span>
            </span>
        </div>
        <div class="current-price-wrapper">
            <?php if ($customerGroupId == 10) { ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Club <span style="font-weight: 400;">Member Price</span></span></div>
            <?php } else { ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>
            <?php } ?>
            <span class="special-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label'     => __(''),
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </span>
        </div>
        <div class="discount-price-wrapper">$<span class="discount-price"><?= number_format($mpDiscountPrice, 2)?></span> Off</div>
    <?php else: ?>  
        <div class="current-price-wrapper no-special-price">
            <?php if ($customerGroupId == 10) { ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Club <span style="font-weight: 400;">Member Price</span></span></div>
            <?php } else { ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>
            <?php } ?>
            <span class="special-price">
                 <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label'     => __(''),
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </span>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
