<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php 
?>

<?php
    /** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

    /** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
    /** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
    $priceModel = $block->getPriceType('regular_price');

    /** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
    /** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
    $finalPriceModel = $block->getPriceType('final_price');
    $idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
    $schema = ($block->getZone() == 'item_view') ? true : false;

    //$_product = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Registry::class)->registry('product');
    $marketPlacePrice = number_format((float)$block->getSaleableItem()->getMarketplacesPrice(), 2, '.', '');

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->create('Magento\Customer\Model\Session');
    if ($customerSession->isLoggedIn()) {
        $customerGroupId = $customerSession->getCustomer()->getGroupId();
    }
?>

<?php if ($block->hasSpecialPrice()): ?>
    <div class="current-price-wrapper has-special-price">
        <?php if ($customerGroupId == 10): ?>
            <div class="digidirectprice"><span>digi</span><span style="color: #000;">Club</span> <span style="font-weight: 400;">PRICE</span></div>
        <?php else: ?>
            <div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct</span> <span style="font-weight: 400;">PRICE</span></div>
        <?php endif; ?>
        <span class="special-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __(''),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
    </div>
    <div class="old-price-wrapper">
        <span class="old-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Original Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
    </div>
<?php else: ?>
    <?php if (($marketPlacePrice && $marketPlacePrice != 0) && ($finalPriceModel->getAmount() < $marketPlacePrice)): ?>
        <div class="current-price-wrapper">
            <?php if ($groupId == 10): ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Club</span> <span style="font-weight: 400;">PRICE</span></div>
            <?php else: ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct</span> <span style="font-weight: 400;">PRICE</span></div>
            <?php endif; ?>
            <span class="special-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label'     => __(''),
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </span>
        </div>
        <div class="old-price-wrapper marketplaces-price">
            <span class="old-price">  
                <span class="price-container price-final_price tax weee"> 
                    <span class="price-label">Everyday Price</span>  
                    <span data-price-amount="<?php echo $marketPlacePrice;?>">
                        <span class="marketplaces-price">$<?php echo $marketPlacePrice;?></span>
                    </span>  
                </span>
            </span>
        </div>
    <?php else: ?>  
        <div class="current-price-wrapper no-special-price">
            <?php if ($groupId == 10): ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Club</span> <span style="font-weight: 400;">PRICE</span></div>
            <?php else: ?>
                <div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct</span> <span style="font-weight: 400;">PRICE</span></div>
            <?php endif; ?>
            <span class="special-price">
                 <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label'     => __(''),
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </span>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>

