<?php
use Digidirect\Faq\Block\Adminhtml\Faq\Edit\Tags;
/** @var  Tags $block */
$tags = $block->getCollection();
?>
<div id="box-tags" class="box-tags" data-widget="faqTags">
    <?php foreach ($tags as $tag): ?>
        <span id="sug-<?php echo $block->escapeHtml($tag->getId()); ?>" class="post-tag" key="<?php echo
        $block->escapeHtml($tag->getId()
        ); ?>">
            <?php /* @escapeNotVerified */ echo $tag->getTitle(); ?>
        </span>
    <?php endforeach; ?>
    <span id="close-tags" class="close-tags" title="<?php /* @escapeNotVerified */ echo __('Close'); ?>">[X]</span>
</div>
<script>
    require([
        'jquery',
        'mage/mage',
        'Digidirect_Faq/js/tags'
    ], function ($) {
        'use strict';

        $('[data-widget=faqTags]').faqTags();
    });
</script>
