<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var Magento\CustomerCustomAttributes\Block\Form $block */
?>
<form class="form form-edit-account" action="<?= /* @escapeNotVerified */ $block->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= /* @escapeNotVerified */ __('Account Information') ?></span></legend><br>
        <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <div class="field choice email">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
            <label class="label" for="change-email"><span><?= $block->escapeHtml(__('Change Email')) ?></span></label>
        </div>
        <div class="field choice password">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
        </div>
        <div class="field choice qff-number">
            <input type="checkbox" name="change_qff_number" id="change-qff-number" data-role="change-qff-number" value="1" title="<?= $block->escapeHtmlAttr(__('Change QFF Number')) ?>" class="checkbox" />
            <label class="label" for="change-qff-number"><span><?= $block->escapeHtml(__('Change QFF Number')) ?></span></label>
        </div>
        
        <fieldset class="fieldset qff-fieldset hide">
            <legend class="legend title-form"><span><?= /* @escapeNotVerified */ __('Qantas Frequent Flyer Details') ?></span></legend><br>

            <div class="qantas-promo-box">
                <div class="qff-logo-container"></div>
                <span><strong>Earn 2 Qantas Points</strong> per $1 spent when you add a valid Qantas Frequent Flyer number.</a>
                <a href="/qantas" target="_blank" rel="noopener">Learn more</a>
            </div>
            <div class="field">
                <label for="qff_number" class="label"><span><?= /* @escapeNotVerified */ __('Qantas Frequent Flyer Number') ?></span></label>
                <div class="control">
                    <input type="text" 
                           name="qff_number" 
                           id="qff_number" 
                           autocomplete="text" 
                           value="<?= $block->escapeHtml($block->getCustomer()->getQffNumber())?>"
                           title="<?= /* @escapeNotVerified */ __('Qantas Frequent Flyer Number') ?>" class="input-text"/>
                </div>
            </div>
            <div class="field no-margin-bottom">
                <label for="qff_lastname" class="label"><span><?= /* @escapeNotVerified */ __('Qantas Frequent Flyer Last Name') ?></span></label>
                <div class="control">
                    <input type="text" 
                           name="qff_lastname" 
                           id="qff_lastname" 
                           autocomplete="text"
                           title="<?= /* @escapeNotVerified */ __('Qantas Frequent Flyer Last Name') ?>" 
                           value="<?= $block->escapeHtml($block->getCustomer()->getQffLastname())?>"
                           class="input-text"/>
                </div>
            </div>
            
        </fieldset>
        
        
        <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_user_attributes'); ?>
        <?php if ($userDefinedAttributes):?>
            <?php $userDefinedAttributes->setEntityType('customer')->setShowContainer(false);?>
            <?php $block->restoreSessionData($userDefinedAttributes->getMetadataForm());?>
            <?= $userDefinedAttributes->toHtml() ?>
        <?php endif;?>
    </fieldset>

    <?= /* @noEscape */ $block->getChildHtml('form_fields_before_in_form') ?>

    <fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend"><span data-title="change-email-password"><?= /* @escapeNotVerified */ __('Change Email and Password') ?></span></legend><br>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?= /* @escapeNotVerified */ __('Email') ?></span></label>
            <div class="control">
                <input type="email" autocomplete="email" name="email" id="email" data-input="change-email" value="<?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>" title="<?= /* @escapeNotVerified */ __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?= /* @escapeNotVerified */ __('Current Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password">
            <label class="label" for="password"><span><?= /* @escapeNotVerified */ __('New Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                    data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= /* @escapeNotVerified */ __('Password Strength') ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= /* @escapeNotVerified */ __('No Password') ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?= /* @escapeNotVerified */ __('Confirm New Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>
        
       
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    
    <div class="actions-toolbar">
        <div class="primary">
            <button id="submit" type="submit" class="action save" title="<?= /* @escapeNotVerified */ __('Save') ?>"><span><?= /* @escapeNotVerified */ __('Save') ?></span></button>
        </div>
    </div>
</form>
<script>
    require(['jquery'],function($){
    
            $('#submit').on('click',function (e){
                
                   var url = "<?php echo $block->getBaseUrl().'/customer/account/editpost'?>";
                   var qff_number =  $("#qff_number").val();
                   var qff_lastname = $("#qff_lastname").val();
                   var action = "update";
                   if (qff_number != "" && qff_lastname != ""){
                    
                                $.ajax({
                                    url: url,
                                    type: "POST",
                                    async: false,
                                    data: {
                                        qff_number: qff_number,
                                        qff_lastname: qff_lastname,
                                        qff_action: action
                                    },
                                    success: function(data){
                                        
                                      var res = data;
                                      var json = JSON.parse(res);
                                      console.log(json.result);
                                      
                                      var test = json.result;
                                        if(test == true){
                                            if($(".qff-link-error").length > 0){
                                                $(".qff-link-error").remove();
                                            }
                                            //console.log("true");
                                            if($(".qff-link-success").length > 0){
                                                $(".qff-link-success").remove();
                                            }
                                            
                                             var success_message = "<span class='qff-link-success'>Validation success.</span>";
                                             $(success_message).insertAfter("#qff_lastname");
                                            
                                        }
                                        else{
                                            //console.log("false");
                                            e.preventDefault();
                                            if($(".qff-link-error").length > 0){
                                                $(".qff-link-error").remove();
                                            }

                                             if($(".qff-link-success").length > 0){
                                                $(".qff-link-success").remove();
                                            }

                                            var error_message = "<span class='qff-link-error'>Details does not match our record. Please enter the correct details.</span>";
                                            $(error_message).insertAfter("#qff_lastname");
                                            
                                        }
                                    },
                                    error: function(){
                                     
                                        if($(".qff-link-error").length > 0){
                                            $(".qff-link-error").remove();
                                        }
                                        var error_message = "<span class='qff-link-error'>Details does not match our record. Please enter the correct details.</span>";
                                         
                                          $(error_message).insertAfter("#qff_lastname");
                                        }
                                });
                    }
            });
      });
  

  
</script>

<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
             
        <?php if (isset($_GET["a"]) && $_GET["a"] == "link"): ?>
            $("#change-qff-number").attr("checked", true);
            $(".qff-fieldset").removeClass("hide");
        <?php endif; ?>
        
        $("#change-qff-number").click(function()
        {
            $(".qff-fieldset").toggleClass("hide");
        });
        
        var dataForm = $('#form-validate');
        var ignore = <?= /* @escapeNotVerified */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= /* @escapeNotVerified */ __('Change Email') ?>",
                "titleChangePassword": "<?= /* @escapeNotVerified */ __('Change Password') ?>",
                "titleChangeEmailAndPassword": "<?= /* @escapeNotVerified */ __('Change Email and Password') ?>"
            }
        },
        "*": {
            "Magento_CustomerCustomAttributes/validation": {
                "ignore": <?= (int) ($_dob->isEnabled() || $userDefinedAttributes->hasUserDefinedAttributes()) ?>,
                "hasUserDefinedAttributes": <?= (int) $userDefinedAttributes->hasUserDefinedAttributes() ?>,
                "isDobEnabled": <?= (int) $_dob->isEnabled() ?>,
                "mixins": [
                    "Magento_CustomerCustomAttributes/error-placement",
                    "Magento_CustomerCustomAttributes/validation-ignore"
                ]
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>