<span class="header-content-links"> 
    <a href="http://digidirect.dev.ph/blog/digi-life/" class="link digi-life-link" title="Digi Life"> 
        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon digi-life"> 
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-logo-digi-life"></use> 
        </svg>
    </a>
    <a href="http://digidirect.dev.ph/photo-lab/" class="link" title="PhotoLab"> 
        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon photolab"> 
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-photolab"></use>
        </svg>
    </a> 
</span>