<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$urlInterface = $objectManager->get('Magento\Framework\UrlInterface');
$currentUrl = $urlInterface->getCurrentUrl();

$isStoreBrandSmallRig = str_contains($currentUrl, 'smallrig-store');
//$isBrandSmallRig = str_contains($currentUrl, 'brands/smallrig');
$isBrandSmallRig = str_contains($currentUrl, 'cameras/action-cameras');

if ($isStoreBrandSmallRig || $isBrandSmallRig) { ?>
    <div class="brand-banner" style="
        max-height: 500px;
    "><img src="<?php echo $block->getUrl("media/wysiwyg/brands-store-page")?>smallrig-header.png"/>
        
    <div class="brand-profile" style="
        width: 225px;
        position: relative;
        top: -125px;
        left: 270px;
        border: 1px solid #cacacaca;
        bottom: 0;
        background: #fff;
    ">
    <img src="https://mcstaging2.digidirect.com.au/media/wysiwyg/brand-logos/smallrig.jpg" style="
        width: 300px;
        position: relative;
    "><i class="fas fa-check-circle" style="
        position: absolute;
        color: #ff3c00;
        top: 0;
        right: 0;
        font-size: 20px;
        z-index: 9999;
        margin: 15px;
    "></i><div style="
        text-align: center;
        font-size: 19px;
        font-weight: 700;
        margin-top: -35px;
        position: relative;
    ">@ digi<span style="color: #ff3c00;">Direct</span></div>

    <div class="brand-banner-links" style="
        text-align: center;
        background: #ff3c00;
        margin: 10px;
        padding: 5px;
        position: relative;
    ">
        <a href="" style="
        color: #fff;
        width: 100%;
        font-weight: 600;
    ">ALL PRODUCTS</a></div>
            </div>
    
    <div class="brand-qantas" style="
        position: relative;
        top: -171px;
        left: 715px;
    "><img src="<?php echo $block->getUrl("media/wysiwyg/brands-store-page")?>desktop-qantas.png"/><div style="
        max-width: 529px;
        position: relative;
        top: -44px;
        text-align: center;
        color: #fff;
        font-size: 10px;
        left: 30px;
    "><div style="
    ">Earn <span style="
        font-weight: 700;
    ">1 Qantas Points per $1 spent</span></div>
    <div>when you add a valid Qantas Frequent Flyer number</div></div></div>
    
    </div>




<?php }

?>

<style>
    .breadcrumbs {
        visibility: hidden !important;
    }
</style>