<span id="header-toggle-nav" data-action="toggle-nav" class="action nav-toggle ninjamenus-top-triggered"><svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-menu"></use></svg></span>
<div class="logo-wrapper">
    <a class="c-logo" href="/">
        <img src="<?php echo $block->getUrl("media/wysiwyg/")?>logo.svg"/>
    </a>
</div>

<style type="text/css">
    .sticky {
        position: fixed;
        top: 0;
        width: 100%;
        z-index: 99;
        border-bottom: 1px solid #e6e6e6;
        max-width: 1440px;
        margin-left: -9999px;
        margin-right: -9990px;
        padding-left: 9999px;
        padding-right: 9999px;
    }
    
    .sticky + .page-main {
        padding-top: 102px;
    }
    
    .navigation > .ninjamenus.ninjamenus-desktop {
        padding-left: 35px !important;
    }
    
    .ninjamenus-top-triggered-sticky {
        position: static !important;
        width: auto;
        padding-top: 15px;
        padding-right: 15px;
        box-sizing: content-box;
    }

    .ninjamenus-top-triggered-sticky:before{
        display: none !important;
    }

    .ninjamenus-top-triggered-sticky > .svg-icon {
        width: 20px;
        height: 20px;
    }
    
    .ninjamenus-scrolltofixed {
        top: 90px !important;
        z-index: 98 !important;
    }
    
</style>

<script>
    
    require(['jquery', 'owl_carousel'],
        function ($) {
            
            $(".top-red-banner-wrapper").slideDown("slow");
            
            $(window).scroll(function() {stickyHeader()}); // OR  $(window).scroll(function() {
            var header = document.getElementById("main-header-wrapper");
            var trigger = document.getElementById("header-toggle-nav");
            var sticky = header.offsetTop;

            function stickyHeader() {
                
                if (window.pageYOffset > sticky) {
                    header.classList.add("sticky");
                    trigger.classList.add("ninjamenus-top-triggered-sticky");
                } else {
                    header.classList.remove("sticky");
                    trigger.classList.remove("ninjamenus-top-triggered-sticky");
                }
            }
            $(".top-red-banner-block").click(function() {
                $(".top-red-banner-wrapper").slideUp("slow");
            });
            
            $(window).load(function() {
                //$(".top-red-banner-wrapper").slideDown("slow");
                $("#top-red-banner-block-id:before").css("visibility", "visible !important");
            });
            
            <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $customerSession = $objectManager->get('Magento\Customer\Block\Account\AuthorizationLink');

            if ($customerSession->isLoggedIn() == true) { ?>    
                $('#mobile-menu-only-header').prepend('<img id="digi-white-logo" src="https://www.digidirect.com.au/media/.thumbswysiwyg/logos/white-digi-logo.png" /><span id="menu-mobile-span-signin"><a class="mobile-menu-signin" href="/customer/account/logout" title="Logout">Logout <i class="fas fa-sign-out-alt"></i></a></span>')
            <?php } else { ?>
                $('#mobile-menu-only-header').prepend('<img id="digi-white-logo" src="https://www.digidirect.com.au/media/.thumbswysiwyg/logos/white-digi-logo.png" /><span id="menu-mobile-span-signin"><a class="mobile-menu-signin" href="/customer/account/login" title="Login">Sign In <i class="far fa-user"></i></a></span>')
            <?php } ?>
            
        }
    );
    
</script>

