<span id="header-toggle-nav" data-action="toggle-nav" class="action nav-toggle"><svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-menu"></use></svg></span>
<div class="logo-wrapper">
    <a class="c-logo" href="/">
        <img src="<?php echo $block->getUrl("media/wysiwyg/")?>logo.svg"/>
    </a>
</div>

<style type="text/css">
    .sticky {
        position: fixed;
        top: 0;
        width: 100%;
        z-index: 99;
        margin-left: -9999px;
        margin-right: -9999px;
        padding-left: 9999px !important;
        padding-right: 9999px !important;
        border-bottom: 1px solid #e6e6e6;
        box-shadow: 0 0 7px 0 #e6e6e6;
    }
    
    .sticky + .page-main {
        padding-top: 102px;
    }
    
    .ninjamenus-top-triggered-sticky {
        position: static !important;
        width: auto;
        padding-top: 15px;
        padding-right: 15px;
        box-sizing: content-box;
        display: block !important;
    }

    .ninjamenus-top-triggered-sticky:before{
        display: none !important;
    }

    .ninjamenus-top-triggered-sticky > .svg-icon {
        width: 20px;
        height: 20px;
    }
    
</style>

<script>
    window.onscroll = function() {stickyHeader()};
    var header = document.getElementById("main-header-wrapper");
    var trigger = document.getElementById("header-toggle-nav");
    var sticky = header.offsetTop;
    function stickyHeader() {
        if (window.pageYOffset > sticky) {
            header.classList.add("sticky");
            trigger.classList.add("ninjamenus-top-triggered-sticky");
        } else {
            header.classList.remove("sticky");
            trigger.classList.remove("ninjamenus-top-triggered-sticky");
        }
    }
</script>