<?php /** @var $block Magento\Framework\View\Element\Template */ ?>
<meta name="og:title" content="Home page | digiDirect"/>
<meta name="og:type" content="website"/>
<meta name="og:url" content="<?= $block->getUrl() ?>"/>
<meta name="og:image" content="<?= $block->getViewFileUrl('pub/media/qff-logo.png') ?>"/>
<meta name="og:description" content="Your leading digital camera experts! digiDirect prides itself on price, range and service, covering a wide range of digital imaging needs."/>
