<div class="panel wrapper">
    <div class="panel header">

        <div class="header-links">
            <a class="store-locator-link" href="/store-locator" title="Store Locator">Store Locator</a>
            <a class="call-us-link" href="tel:1300 889 148" title="call-us">CALL US <span class="company-number">1300 889 148</span></a>
        </div>
        <div class="header-links" style="position: absolute; right: 30px;">
            <a href="/qantas" class="qantas-link" title="qantas">
                <img src="<?php echo $block->getUrl("media/wysiwyg/")?>qantas/qantas-logo-white.png" alt="Qantas" width="73px" height="2rem">
            </a>
            <div class="header-links-account">
                <a class="register-link" href="/customer/account/create" title="Register">Register</a>
                <a class="login-link" href="/customer/account/login" title="Login">Login</a>
            </div>
        </div>
    </div>
</div>
