
<div class="panel wrapper">
    <div class="panel header">

        <div class="header-links header-link-left" style="margin-left: 50px;">
            <a class="store-locator-link" href="/store-locator" title="Store Locator">Store Locator</a>
            <a class="call-us-link" href="tel:1300 889 148" title="call-us">CALL US <span class="company-number">1300 889 148</span></a>
        </div>
        <div class="header-links header-link-right" style="position: absolute; right: 0; margin-right: 50px;">
            <div class="header-links-account">
                <a href="/qantas" class="qantas-link" title="qantas">
                    <img src="<?php echo $block->getUrl("media/wysiwyg/")?>qantas/qantas-logo-white.png" alt="Qantas" width="73px" height="2rem">
                </a>
                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $customerSession = $objectManager->get('Magento\Customer\Block\Account\AuthorizationLink');
                
                if ($customerSession->isLoggedIn() == true) { ?>
                    <a class="register-link" href="/customer/account" title="Account">My Account</a>
                    <a class="login-link" href="/customer/account/logout" title="Logout">Logout</a>
                <?php } else { ?>
                    <a class="register-link" href="/customer/account/create" title="Register">Register</a>
                    <a class="login-link" href="/customer/account/login" title="Login">Login</a>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
