<?php

use Magento\Framework\App\Action\Action;

$brands = $block->getBrands();

/**
 * Author: Rondel Dalumpines
 */
/** @var \Digidirect\ShopByCategory\Block\Widget\ShopByCategory $block */
?>



<div class="shop-by-category-dropdown">
    <label class="label-brands-dropdown" for="brands-dropdown">Shop By Category</label>
    <select name="brands-dropdown" id="brands-dropdown" style="width: 20%">
        <option value="all-brands">All Brands</option>
        <?php foreach($brands as $brand) : ?>
            <?php if ($brand) :?>
                <?php $brandName = $brand->getLabel();?>
                <option value="<?php echo $brand->getValue();?>"><?php echo $brandName; ?></option>
            <?php endif; ?>
        <?php endforeach ?>
    </select>
</div>

<div id="shop-by-category-carousel" class="mgz-carousel owl-carousel mgz-product-items mgz-carousel-nav-position-center_split mgz-carousel-nav-size-normal owl-loaded owl-drag">
    <div class="owl-stage-outer">
         <div id="shop-by-category-container" class="owl-stage shop-by-category-container" style="transform: translate3d(-2185px, 0px, 0px); transition: all 0s ease 0s; width: 8470px;">
             <div class="owl-item">
                 <div class="shop-by-category-category">
                     <a href="<?php echo $block->getUrl("cameras")?>">
                         <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-cameras.jpg"/>
                         <div class="product-count" id="cameras-count">Cameras(<?php echo $block->getProductCollectionCount(17); ?>)</div>
                     </a>
                 </div>
             </div>
             <div class="owl-item">
                 <div class="shop-by-category-category">
                     <a href="<?php echo $block->getUrl("lenses")?>">
                         <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-lens.jpg"/>
                         <div class="product-count"  id="lenses-count">Lenses(<?php echo $block->getProductCollectionCount(18); ?>)</div>
                     </a>
                 </div>
             </div>
             <div class="owl-item">
                 <div class="shop-by-category-category">
                     <a href="<?php echo $block->getUrl("drones")?>">
                         <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-drones.jpg"/>
                         <div class="product-count"  id="drones-count">Drones(<?php echo $block->getProductCollectionCount(21); ?>)</div>
                     </a>
                 </div>
             </div>
             <div class="owl-item">
                 <div class="shop-by-category-category">
                     <a href="<?php echo $block->getUrl("lighting-and-studio")?>">
                         <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-lights-and-studio.jpg"/>
                         <div class="product-count"  id="lighting-and-studio-count">Lighting & Studio(<?php echo $block->getProductCollectionCount(19); ?>)</div>
                     </a>
                 </div>
             </div>
             <div class="owl-item">
                 <div class="shop-by-category-category">
                     <a href="<?php echo $block->getUrl("photo-accessories")?>">
                         <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-photomemories.jpg"/>
                         <div class="product-count"  id="photo-accessories-count">Photo Accessories(<?php echo $block->getProductCollectionCount(71); ?>)</div>
                     </a>
                 </div>
             </div>
             <div class="owl-item">
                 <div class="shop-by-category-category">
                     <a href="<?php echo $block->getUrl("optics")?>">
                         <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-optics.jpg"/>
                         <div class="product-count"  id="optics-count">Optics(<?php echo $block->getProductCollectionCount(22); ?>)</div>
                     </a>
                 </div>
             </div>
             <div class="owl-item">
                 <div class="shop-by-category-category">
                     <a href="<?php echo $block->getUrl("audio-and-visual")?>">
                         <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-audio-and-visual.jpg"/>
                         <div class="product-count"  id="audio-and-visual-count">Audio & Visual(<?php echo $block->getProductCollectionCount(73); ?>)</div>
                     </a>
                 </div>
             </div>
             <div class="owl-item">
                 <div class="shop-by-category-category">
                     <a href="<?php echo $block->getUrl("pro-video")?>">
                         <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-provideo.jpg"/>
                         <div class="product-count"  id="pro-video-count">Pro Video(<?php echo $block->getProductCollectionCount(77); ?>)</div>
                     </a>
                 </div>
             </div>
             <div class="owl-item">
                 <div class="shop-by-category-category">
                     <a href="<?php echo $block->getUrl("home/smart-home")?>">
                         <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-smarthome.jpg"/>
                         <div class="product-count"  id="smart-home-count">Smart Home(<?php echo $block->getProductCollectionCount(704); ?>)</div>
                     </a>
                 </div>
             </div>
             <div class="owl-item">
                 <div class="shop-by-category-category">
                     <a href="<?php echo $block->getUrl("computers-mobile")?>">
                         <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-pcandlaptop.jpg"/>
                         <div class="product-count"  id="computers-mobile-count">Computers & Mobile(<?php echo $block->getProductCollectionCount(662); ?>)</div>
                     </a>
                 </div>
             </div>
         </div>
    </div>
</div>    
