<div data-role="locator-list" class="locator-list" data-bind="scope: 'locator_list'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/javascript">
    require(['jquery', 'clickAndCollect'], function($, initialize) {
        initialize();
    });
</script>
<script type="text/x-magento-init">
{
    "[data-role='locator-list']": {
        "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
    }
}
</script>
