<?php
/** @var \Digidirect\Storelocator\Block\Wrapper $block */
$isInPopup = $block->getOpenInPopup();
?>
<div class="store-locator test3">
    <?php echo $block->getChildHtml('storelocator.search'); ?>
    <div class="grid-row test4">

        <div class="<?php echo /* @noEscape */ $isInPopup ? 'inpopup' : 'store-wrapper column -left'; ?>">
            <?php echo $block->getChildHtml('storelocator.list'); ?>
        </div>

        <div class="<?php echo /* @noEscape */ $isInPopup ? 'inpopup' : 'store-wrapper column -right'; ?>">
            <!-- <//?php echo $block->getChildHtml('storelocator.list'); ?> -->
            <p>test</p>
                <div id="tabs">
                    <ul>
                        <li>
                            <a href="#a">Tab A</a>
                        </li>
                        <li>
                            <a href="#b">Tab B</a>
                        </li>
                        <li>
                            <a href="#c">Tab C</a>
                        </li>
                        <li>
                            <a href="#d">Tab D</a>
                        </li>
                    </ul>

                    <div id="a">
                        Content of A
                    </div>
                    <div id="b">
                        Content of B
                    </div>
                    <div id="c">
                        Content of C
                    </div>
                    <div id="d">
                        Content of D
                    </div>

                </div>
        </div>

        <?php if ($isInPopup): ?>
            <?php echo $block->getChildHtml('storelocator.popup'); ?>
        <?php else: ?>
            <div class="google-map-wrapper column -main storemap">
                <?php echo $block->getChildHtml('storelocator.map'); ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php echo $block->getChildHtml('storelocator.list.after'); ?>


<script>
    require([
        'jquery'
    ],
    function ($) {
        $('#tabs').tabs();
    });
</script>
