<?php
/** @var \Digidirect\Storelocator\Block\Wrapper $block */
$isInPopup = $block->getOpenInPopup();
?>
<div class="store-locator test3" id="tabsection">
    <?php echo $block->getChildHtml('storelocator.search'); ?>
    <div class="grid-row test4">

        <div class="<?php echo /* @noEscape */ $isInPopup ? 'inpopup' : 'store-wrapper column -left sbanner1'; ?>">
        <img src="https://mcstaging2.digidirect.com.au/media/wysiwyg/store-locatorbanner1.png" alt="store-locatorbanner1">
            
            <//?php echo $block->getChildHtml('storelocator.list'); ?>

                    <ul>
                        <li class="store-items">
                            <img src="https://mcstaging2.digidirect.com.au/media/digidirect/abstractentity/images/s/y/sydney.jpeg" alt="sydney" width="150">
                            <div class="store-details">
                                <h3>Test name</h3>
                                <a class="tablinks" href="#tabs">Tab A</a>
                            </div>
                        </li>
                        <li>
                            <a class="tablinks" href="#tabs">Tab B</a>
                        </li>
                        <li>
                            <a class="tablinks" href="#tabs">Tab C</a>
                        </li>
                        <li>
                            <a class="tablinks" href="#tabs" >Tab D</a>
                        </li>
                    </ul>
        </div>

        <div class="<?php echo /* @noEscape */ $isInPopup ? 'inpopup' : 'store-wrapper column -right sbanner2'; ?>">
        <img src="https://mcstaging2.digidirect.com.au/media/wysiwyg/store-locatorbanner2.png" alt="store-locatorbanner2">

            <p>test</p>

                    <div id="tabs" class="tabcontent">
                        Content of A
                    </div>
                    <div id="tabs" class="tabcontent">
                        Content of B
                    </div>
                    <div id="tabs" class="tabcontent">
                        Content of C
                    </div>
                    <div id="tabs" class="tabcontent">
                        Content of D
                    </div>
              
        </div>

        <?php if ($isInPopup): ?>
            <?php echo $block->getChildHtml('storelocator.popup'); ?>
        <?php else: ?>
            <div class="google-map-wrapper column -main storemap">
                <?php echo $block->getChildHtml('storelocator.map'); ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php echo $block->getChildHtml('storelocator.list.after'); ?>

<?php ?>

<script>
    require([
        'jquery',
        'jquery/ui'
    ],
    function ($, tabs) {
        var tabID = 0;
        var tabContentID = 0;

        $(".tablinks").each(function(){
        tabID++;
        var tabnewID="#"+"tabs"+tabID;
        // var newID='store'+i;
        // $(this).attr('id',newID);
        $(this).attr("href",tabnewID);
        // $(this).val(i);

        // alert(tabnewID);
        });	

        $(".tabcontent").each(function(){
        tabContentID++;
        var tabContentnewID='tabs'+tabContentID;

        $(this).attr('id',tabContentnewID);

        // alert(tabContentnewID);

        });

        $("#tabsection").tabs()

        alert(storelocator);
    });
</script>
