<?php
/** @var \Digidirect\Storelocator\Block\Wrapper $block */
$isInPopup = $block->getOpenInPopup();
?>
<div class="store-locator test3">
    <?php echo $block->getChildHtml('storelocator.search'); ?>
    <div class="grid-row test4" id="tabs">

        <div class="<?php echo /* @noEscape */ $isInPopup ? 'inpopup' : 'store-wrapper column -left sbanner1'; ?>">
            <?php echo $block->getChildHtml('storelocator.list'); ?>
        </div>

        <div class="<?php echo /* @noEscape */ $isInPopup ? 'inpopup' : 'store-wrapper column -right sbanner1'; ?>">
            <!-- <//?php echo $block->getChildHtml('storelocator.list'); ?> -->
            <p>test</p>
                <div id="tabsection">
                    <ul>
                        <li>
                            <a class="tablinks" href="#tabs">Tab A</a>
                        </li>
                        <li>
                            <a class="tablinks" href="#tabs">Tab B</a>
                        </li>
                        <li>
                            <a class="tablinks" href="#tabs">Tab C</a>
                        </li>
                        <li>
                            <a class="tablinks" href="#tabs" >Tab D</a>
                        </li>
                    </ul>
                    <div id="tabs" class="tabcontent">
                        Content of A
                    </div>
                    <div id="tabs" class="tabcontent">
                        Content of B
                    </div>
                    <div id="tabs" class="tabcontent">
                        Content of C
                    </div>
                    <div id="tabs" class="tabcontent">
                        Content of D
                    </div>
                </div>
        </div>

        <?php if ($isInPopup): ?>
            <?php echo $block->getChildHtml('storelocator.popup'); ?>
        <?php else: ?>
            <div class="google-map-wrapper column -main storemap">
                <?php echo $block->getChildHtml('storelocator.map'); ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php echo $block->getChildHtml('storelocator.list.after'); ?>


<script>
    require([
        'jquery',
        'jquery/ui'
    ],
    function ($, tabs) {
        var tabID = 0;
        var tabContentID = 0;

        $(".tablinks").each(function(){
        tabID++;
        var tabnewID="#"+"tabs"+tabID;
        // var newID='store'+i;
        // $(this).attr('id',newID);
        $(this).attr("href",tabnewID);
        // $(this).val(i);

        // alert(tabnewID);
        });	

        $(".tabcontent").each(function(){
        tabContentID++;
        var tabContentnewID='tabs'+tabContentID;

        $(this).attr('id',tabContentnewID);

        // alert(tabContentnewID);

        });

        $("#tabsection").tabs()
    });
</script>
