<?php
/** @var $block \Digidirect\Navigation\Block\Widget\Set */
$menuArray = $block->getMenuAsArray();

/**
 *
 * As widgets in magento does not have static layout you can not specify settings as it's done in default menu block
 * Instead you need to set this parameters directly in template with $block->setData('key', 'value')
 * But recommended way is to use $block->setSetting('key', 'value')
 * or $block->setDefaultSetting('key', 'value')
 *
 * 1) Some default settings from core extension block are here. Feel free to remove them
 * 2) Use $block->getSetting($settingCode) to get any setting from "settings" field in widget
 * 3) Use $block->setSetting($settingCode, $settingValue) if you want to overwrite what customer specified in settings field
 * 4) Use $block->setDefaultSetting($settingCode, $settingValue) if you do not want to overwrite customer's settings but
 * this setting is important to be presented (have default value)
 * 5) You don't need json_decode anymore if you don't use json
 * 6) If you need menu in json format use $block->getMenuJson() or json_encode($menuArray) in this template
 * 7) instead of using echo if(isset($data['key'])) ? $data['key'] : ''
 * you can use echo $block->returnIfIsset($data, 'key', 'defaultValue')
 *
 * 8) if you want to use echo  if($block->getSetting('setting')) ? $block->getSetting('setting') : ''
 * you can use $block->returnSettingItselfIfPresented('setting', 'defaultValue')
 *
 */

$block->setDefaultSetting('area_selector', 'navigation-wrapper');
$block->setDefaultSetting('wrapper_class', 'menu-wrapper');
$block->setDefaultSetting('horizontal', true);
$block->setDefaultSetting('cms_block_class_name', 'cms');
$block->setDefaultSetting('extra_content_class_name', 'extra');
$block->setDefaultSetting('expanded', false);
$block->setDefaultSetting('sub_menu_block_class', 'sub-menu');
$block->setDefaultSetting('item_class', 'item');
$block->setDefaultSetting('item_label_class', 'link');
$block->setDefaultSetting('inner_lists_class', 'menu');
$block->setDefaultSetting('responsive', true);
$block->setDefaultSetting('off_canvas_side', 'left');

?>
<?php if (empty($menuArray)) return; ?>

<nav data-testid="navigation-menu-container"
     class="<?php echo $block->escapeHtml($block->getSetting('area_selector')); ?><?php echo $block->conditionalSettingReturn('responsive', ' -responsive -' . $block->getSetting('off_canvas_side'), ''); ?>">
    <ul class="<?php echo $block->conditionalSettingReturn('wrapper_class', $block->getSetting('wrapper_class'), ''); ?><?php echo $block->conditionalSettingReturn('horizontal', ' -horizontal', ''); ?><?php echo $block->conditionalSettingReturn('expanded', '-expanded', ''); ?>">
        <?php $i = 1;$j = 1;
        foreach ($menuArray as $item) : ?>
            <?php $length = strlen($block->returnIfIsset($item, 'cms_block_content', false)); ?>
            <?php $have_parent = $length || !empty($item['children']); ?>
            <?php $style = $block->returnIfIsset($item, 'style'); ?>
        <li class="<?php echo $block->escapeHtml($item['frontend_class']); ?><?php echo $block->escapeHtml($block->conditionalSettingReturn('item_class', $block->getSetting('item_class'), '')); ?><?php echo $item['is_active'] ? ' -active' : '' ?><?php echo $have_parent ? ' -parent' : '' ?> -level<?php echo $block->escapeHtml((int)$i) ?>">
            <?php if ($item['url'] && ($item['is_link'] == '1' || $item['is_link'] === true)): ?>
                <a <?php if ($style) : ?>style="<?php echo $block->escapeHtml($style) ?>" <?php endif; ?>
                   class="<?php echo $block->escapeHtml($block->returnSettingItselfIfPresented('item_label_class')); ?>"
                   title="<?php echo $block->escapeHtml($item['title']) ?>"
                   href="<?php echo $block->escapeUrl($item['url']) ?>"
                   id="mi-<?php echo (int)$i ?>-<?php echo $block->escapeHtml((int)$j) ?>">
                    <?php echo $block->escapeHtml($item['title']) ?>
                </a>
            <?php else: ?>
                <span <?php if ($style) : ?>style="<?php echo $block->escapeHtml($style) ?>" <?php endif; ?>
                      class="<?php echo $block->escapeHtml($block->returnSettingItselfIfPresented('item_label_class')); ?>"
                      id="mi-<?php echo $block->escapeHtml((int)$i) ?>-<?php echo $block->escapeHtml((int)$j) ?>">
                    <?php echo $block->escapeHtml($item['title']) ?>
                </span>
            <?php endif; ?>
            <?php
            $function = function ($children, $i, $j, $m) use (&$function, $block) { ?>
                <?php $i++; $k = 1; $n = 0; $v = $m; ?>
                <?php foreach ($children as $child) : ?>
                    <?php $length = strlen($block->returnIfIsset($child, 'cms_block_content', false)); ?>
                    <?php $have_parent = $length || !empty($child['children']); ?>
                    <?php if (isset($child['frontend_class'])): ?>
                        <?php $frontendChildClass = $child['frontend_class']; ?>
                    <?php else: ?>
                        <?php $frontendChildClass = ''; ?>
                    <?php endif; ?>
                    <?php if (isset($child['style'])) : ?>
                        <?php $style = $child['style']; ?>
                    <?php else: ?>
                        <?php $style = null; ?>
                    <?php endif; ?>
                    <li class="<?php echo $block->escapeHtml($frontendChildClass) ?><?php echo $block->escapeHtml($block->returnSettingItselfIfPresented('item_class')); ?><?php echo $child['is_active'] ? ' -active' : '' ?><?php echo $have_parent ? ' -parent' : '' ?> -level<?php echo (int)$i ?>">
                        <?php if ($child['url'] && ($child['is_link'] == '1' || $child['is_link'] === true)) : ?>
                            <a <?php if ($style) : ?>style="<?php echo $block->escapeHtml($style) ?>" <?php endif; ?>
                               class="<?php /* @escapeNotVerified */
                               echo $block->returnSettingItselfIfPresented('item_label_class') ?>"
                               title="<?php /* @escapeNotVerified */
                               echo $child['title'] ?>" href="<?php /* @escapeNotVerified */
                            echo $child['url'] ?>"
                               id="mi-<?php echo (int)$i ?>-<?php echo (int)$j ?><?php if ($m): ?>-<?php echo (int)$m; ?><?php endif; ?>-<?php echo (int)$k ?>">
                                <?php /* @escapeNotVerified */
                                echo $child['title'] ?>
                            </a>
                        <?php else : ?>
                            <span <?php if ($style) : ?>style="<?php echo $block->escapeHtml($style) ?>" <?php endif; ?>
                                  class="<?php /* @escapeNotVerified */
                                  echo $block->returnSettingItselfIfPresented('item_label_class'); ?>"
                                  id="mi-<?php echo (int)$i ?>-<?php echo (int)$j ?><?php if ($m): ?>-<?php echo (int)$m; ?><?php endif; ?>-<?php echo (int)$k ?>">
                                <?php /* @escapeNotVerified */
                                echo $child['title'] ?>
                            </span>
                        <?php endif; ?>
                        <?php if ($have_parent): ?>
                            <div class="<?php /* @escapeNotVerified */
                            echo $block->returnSettingItselfIfPresented('sub_menu_block_class'); ?> -level<?php echo (int)$i ?>"
                                 data-id="mi-<?php echo (int)$i ?>-<?php echo (int)$j ?><?php if ($m): ?>-<?php echo (int)$m; ?><?php endif; ?>-<?php echo (int)$k ?>"
                                 data-level-dip="-level<?php echo (int)$i + 1 ?>">
                                <?php if (isset($child['cms_block_content'])): ?>
                                    <div class="<?php /* @escapeNotVerified */
                                    echo $block->returnSettingItselfIfPresented('cms_block_class_name'); ?>"><?php echo $block->returnIfIsset($child, 'cms_block_content'); ?></div>
                                <?php endif; ?>
                                <?php if (isset($child['children'])) : ?>
                                    <?php $n++;
                                    $m = $n; ?>
                                    <ul class="<?php /* @escapeNotVerified */
                                    echo $block->returnSettingItselfIfPresented('inner_lists_class'); ?>">
                                        <?php $function($child['children'], $i, $j, $m); ?>
                                    </ul>
                                    <?php $m = $v; ?>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </li>
                    <?php $k++; endforeach; ?>
            <?php }; ?>
            <?php if ($have_parent): ?>
                <div class="<?php echo $block->escapeHtml($block->returnSettingItselfIfPresented('sub_menu_block_class')); ?> -level<?php echo (int)$i ?>"
                     data-id="mi-<?php echo (int)$i ?>-<?php echo (int)$j ?>"
                     data-level-dip="-level<?php echo (int)$i + 1 ?>">
                    <?php if (isset($item['cms_block_content'])): ?>
                        <div class="<?php echo $block->escapeHtml($block->returnSettingItselfIfPresented('cms_block_class_name')); ?>"><?php /* @escapeNotVerified */
                            echo $item['cms_block_content'] ?></div>
                    <?php endif; ?>
                    <?php
                    if (isset($item['children'])) : ?>
                        <?php $m = 0; ?>
                        <ul class="<?php echo $block->returnSettingItselfIfPresented('inner_lists_class'); ?>">
                            <?php $function($item['children'], $i, $j, $m); ?>
                        </ul>
                    <?php endif; ?>
                    <?php if (!empty($item['content'])) : ?>
                        <div class="<?php echo $block->escapeHtml($block->returnSettingItselfIfPresented('extra_content_class_name')); ?>"><?php /* @escapeNotVerified */
                            echo $block->returnIfIsset($item, 'content'); ?></div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            </li>
            <?php $j++; endforeach; ?>
    </ul>
</nav>

<script type="text/x-magento-init">
    {
        "*": {
            "navigation": {
                "static": true,
                "action": "hover",
                "area":".<?php /* @escapeNotVerified */echo $block->getSetting('area_selector'); ?>",
                "wrapperClass": ".<?php /* @escapeNotVerified */echo $block->getSetting('wrapper_class'); ?>",
                "horizontal": <?php /* @escapeNotVerified */echo $block->getSetting('horizontal') ? 'true' : 'false' ?>,
                "responsive": <?php /* @escapeNotVerified */echo $block->getSetting('responsive') ? 'true' : 'false' ?>,
                "offCanvasSide" : "<?php /* @escapeNotVerified */echo $block->getSetting('off_canvas_side'); ?>"
            }
        }
    }
</script>
