<?php
/**
 * @var $block \Ewave\SocialSharing\Block\Sharing
 * @var $sharingHelper \Ewave\SocialSharing\Helper\Config\Google
 */
?>
<?php
    $sharingHelper = $this->helper('Ewave\SocialSharing\Helper\Config\Google');
    $product = $block->getProduct();
?>
<?php if ($sharingHelper->isEnabled() || $sharingHelper->isShareEnabled()): ?>
<li class="item">
    <a class="link"
       target="_blank"
       href="https://plus.google.com/share?url=<?php echo $this->escapeUrl($product->getProductUrl()); ?>">
        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -google-plus">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-google-plus"></use>
        </svg>
    </a>
</li>
<?php endif; ?>


