<div class="product-help-box">
    <div class="product-help-icon">
        <span class="icon-warning-penta"></span>
    </div>
    <div class="product-help-content">
        <p><?= $block->escapeHtml(__('Need help? Ask our team')) ?></p>
        <div class="product-help-links">
            <a href="#" class="help-chat" target="_blank" rel="noopener"><?= $block->escapeHtml(__('Chat')) ?></a> |
            <a href="tel:1300 889 148" class="help-call"><?= $block->escapeHtml(__('Call Us')) ?></a> |
            <a href="mailto:support@example.com" class="help-email"><?= $block->escapeHtml(__('Email')) ?></a>
        </div>
    </div>
</div>
