<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
$addToCartUrl = $listBlock->getAddToCartUrl($product);
$seller = $product->getData('marketplacer_seller');
?>

<script defer type="text/javascript" src="https://static.zip.co/lib/js/zm-widget-js/dist/zip-widget.min.js"></script>
<div class="studio19-wrapper"><span class="s19-price-per-period epUolJj2d0jVcRu2MCn3"><span class="s19-price-amount h7ICwjF28idlwSm389Rc">$10.31</span><span class="s19-per-period"> per week</span></span><div class="s19-component FDWCxPTmUNe3GXUrl5uP"><div class="s19-header xQZdXExJFcdsPJZIfIlb"><div class="s19-rentfor JXYm9QAk9A1_rUOnPeAh">Or Rent From</div></div><div class="s19-rental-details msMt0f21L1ZI8nGfzM2Q"><span class="s19-min-period RlmJ4XaCgLpbYcptr4Jr">Return any time after minimum rental agreement</span><div class="s19-actions QRAkDLLcaR9LTaOD25F6"><a class="s19-apply-btn DGtPiJz0mhE4LvS4Nv29" href="https://secure.studio19.com.au/rentnow/digidirect2/584921/">Apply Now</a><a class="s19-learn-btn bx3j1IUBrdP1tNj7yJop" href="https://www.studio19.com.au/p/whyrent/" target="_blank">Learn More</a><a class="s19-purchase-btn xrXqEof6v7jn4mYsi1k0" href="#">+ Apply to Purchase Pricing</a></div></div></div></div>
<div class="payment-gateways">
    <div class="row-first">
        <form action="<?php echo $addToCartUrl; ?>" method="post" id="product_addtocart_form" novalidate="novalidate">
            <?php echo $block->getBlockHtml('formkey')?>
            <button type="submit"
                class="action tocart btn_cart tocart-pdp-btn"
                id="product-addtocart-button"
                data-action="add-to-cart-action"
                >
                <div class="credit-cards">
                    <img src="<?= $block->getViewFileUrl('images/checkout/Visa,Master,AMEX.png'); ?>"/>
                    
                </div>
            </button>
        </form>
        <div id="paypal-custom">
            <!-- <img src="<?= $block->getViewFileUrl('images/checkout/paypal.png'); ?>"/> -->
        </div>
    </div>
    <div class="row-second">
        <div style="cursor:pointer;" 
            id="zip-product-widget"
            data-zm-widget="popup" 
            data-zm-region="au"
            data-env="production"
            data-zm-merchant="5a7e18db-dd65-4502-8814-2d8388807da8"      
            data-zm-price="<?= $product->getData('final_price') ? $product->getData('final_price') : $product->getFinalPrice(); ?>" 
            data-zm-asset="productwidget" 
            data-zm-popup-asset="termsdialog">
        </div>
    </div>
    
    <div class="row-third" style="margin: 10px 0; background: #B2FCE4; border-radius: 25px; text-align: center;">
        <div class="pdp-afterpay-logo">
                <span data-afterpay-modal="en_AU">
                    <img src="<?= $block->getViewFileUrl('images/checkout/afterpay.png'); ?>" alt="Checkout with Afterpay">
                    <span>ⓘ</span>
                </span>
        </div>
    </div>
</div>

<script>
    require([
            'jquery'
        ],
        function ($) {
            $('#paypal-custom').append($('#paypal-smart-button'));
    });
</script>
