<div class="secure-pay">
    <div class="title">Secure ways to pay</div>
    <div class="image-wrapper">
        <img src=" <?= $block->getViewFileUrl('images/visa.svg'); ?>"/>
        <img src=" <?= $block->getViewFileUrl('images/mastercard.svg'); ?>"/>
        <img src=" <?= $block->getViewFileUrl('images/amex.svg'); ?>"/>
        <img src=" <?= $block->getViewFileUrl('images/paypal.svg'); ?>"/>
        <img src=" <?= $block->getViewFileUrl('images/zip.svg'); ?>"/>
<!--        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -visa"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-visa"></use></svg>
        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -mastercard"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-mastercard"></use></svg>
        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -amex"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-amex"></use></svg>
        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -paypal"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-paypal"></use></svg>
        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -zip"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-zip"></use></svg>
        -->
    </div>
</div>