<?php

/**
 * @var \Mirasvit\SeoContent\Block\Adminhtml\Template\Preview $block
 * @var \Mirasvit\SeoContent\Api\Data\TemplateInterface $seoTemplate
 */

$seoTemplate = $block->getSeoTemplate();
$previewData = $block->getPreviewData();

?>

<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js"></script>

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/styles/default.min.css">

<?php if (!$seoTemplate->getRuleType()): ?>
    <p>Please select the rule type</p>
<?php elseif ($seoTemplate->getRuleType() == \Mirasvit\SeoContent\Api\Data\TemplateInterface::RULE_TYPE_NAVIGATION): ?>
    <p>Preview not allowed for Layered Navigation templates</p>
<?php elseif ($seoTemplate->getRuleType() == \Mirasvit\SeoContent\Api\Data\TemplateInterface::RULE_TYPE_BLOG): ?>
    <p>Preview not allowed for Blog templates</p>
<?php elseif ($seoTemplate->getRuleType() == \Mirasvit\SeoContent\Api\Data\TemplateInterface::RULE_TYPE_BRAND): ?>
    <p>Preview not allowed for Brand templates</p>
<?php else: ?>
    <input type="text" id="id" placeholder="<?= $block->escapeHtml(__('URL or Entity IDs separated by comma')) ?>">

    <h4>
        <?= $block->escapeHtml($seoTemplate->getName()) ?>
        <span>(<?= $block->escapeHtml($block->getRuleTypeLabel($seoTemplate)) ?>)</span>
        <sup
            class="<?= $seoTemplate->isActive() ? 'active' : '' ?>"><?= $seoTemplate->isActive() ? 'Enabled' : 'Disabled' ?></sup>
    </h4>

    <?php if (count($previewData)): ?>
        <div>
            <?php foreach ($previewData as $preview): ?>
                <table>
                    <tr class="heading">
                        <th><?= $block->escapeHtml($preview->getType()) ?></th>
                        <td><?= $block->escapeHtml($preview->getItem()->getTitle() ?: $preview->getItem()->getName()) ?>
                            (ID: <?= $block->escapeHtml($preview->getItem()->getId()) ?>)
                        </td>
                    </tr>

                    <?php foreach ($preview->getContent()->getData() as $field => $value): ?>
                        <?php
                        if (
                            $field == 'description_position'
                            || $field == 'applied_template_id'
                            || strpos($field, 'description_template') !== false
                            || strpos($field, 'TOOLBAR') !== false
                            || !$value
                        ) {
                            continue;
                        }
                        ?>
                        <tr>
                            <th><?= /* @noEscape */ $block->prepareFieldOutput($field, $preview->getContent()->getData()) ?></th>
                            <td><?= /* @noEscape */ $block->prepareValueOutput($value) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p>Nothing to display</p>
    <?php endif; ?>
<?php endif; ?>

<?php
    $id = $block->getSeoTemplateId() ?: 'new';
?>
<script>
    $(document).ready(function () {
        $('pre code').each(function (i, block) {
            hljs.highlightBlock(block);
        });
    });
    if ($.cookie("template_<?= $block->escapeHtml($id) ?>_preview_ids")) {
        $('#id').val($.cookie("template_<?= $block->escapeHtml($id) ?>_preview_ids"));
    }
    $('#id').on('change', function () {
        $.cookie("template_<?= $block->escapeHtml($id) ?>_preview_ids", $('#id').val(), {path: '/'});
    });
</script>

<style>
    body {
        padding:     2rem;
        margin:      0;
        color:       #41362f;
        font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-style:  normal;
        font-weight: 400;
        line-height: 1.36;
        font-size:   1.4rem;
    }

    h4 {
        margin-bottom: 2rem;
    }

    input[type="text"] {
        position:         fixed;
        top:              0;
        right:            0;
        min-width:        300px;
        background-color: #fff;
        border-radius:    1px;
        border:           1px solid #adadad;
        color:            #303030;
        font-size:        14px;
        font-weight:      400;
        line-height:      1.36;
        height:           auto;
        width:            auto;
        padding:          6px 10px 6px;
        transition:       border-color .1s linear;
        vertical-align:   baseline;
    }

    input[type="text"]:focus {
        border-color: #007bdb;
        box-shadow:   none;
        outline:      0;
    }

    pre {
        margin-top: 2.5rem;
    }

    sup {
        background-color: #e3e3e3;
        color:            #666;
    }

    sup.active {
        background-color: #bfc;
    }

    table {
        margin-bottom: 1rem;
    }

    table tr.heading {
        font-size: 1.3rem;
        color:     #eb5202;
    }

    table tr.heading td {
        color: #eb5202 !important;
    }

    table th {
        text-align:     right;
        padding-right:  .5rem;
        padding-top:    .3rem;
        vertical-align: top;
        white-space:    nowrap;
    }

    table th sup {
        font-weight:   normal;
        padding:       1px 3px;
        margin-left:   2px;
        border-radius: 4px;
    }

    table th sup.template {
        background-color: #bfc;
    }

    table td {
        padding-top: .3rem;
        color:       #666;
    }

    table i._variable {
        padding:       0 4px;
        border-radius: 2px;
        margin:        1px;
        background:    #FEF49C;
        font-style:    normal;
        font-weight:   normal;
    }

    h4 sup {
        padding:       2px 4px;
        border-radius: 2px;
    }

    h4 span {
        color: #999;
    }
</style>
