<?php
    $brandData = $block->getData();
    $brandId = $brandData['data']['brandId'];
    $brandName = $block->getBrandName($brandId);
?>
<div id="shop-by-category-container" class="shop-by-category-container"> 
    <?php if ($block->getProductCollectionCountWithBrand(17, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("brands/" . $brandName . "/filters/cat/cameras?_aa=222&_option=" . $brandId)?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-cameras.jpg"/>
                <div class="product-count" id="cameras-count">Cameras(<?php echo $block->getProductCollectionCountWithBrand(17, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(18, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("brands/" . $brandName . "/filters/cat/lenses?_aa=222&_option=" . $brandId)?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-lens.jpg"/>
                <div class="product-count"  id="lenses-count">Lenses(<?php echo $block->getProductCollectionCountWithBrand(18, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(21, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("brands/" . $brandName . "/filters/cat/drones?_aa=222&_option=" . $brandId)?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-drones.jpg"/>
                <div class="product-count"  id="drones-count">Drones(<?php echo $block->getProductCollectionCountWithBrand(21, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(19, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("brands/" . $brandName . "/filters/cat/lighting-and-studio?_aa=222&_option=" . $brandId)?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-lights-and-studio.jpg"/>
                <div class="product-count"  id="lighting-and-studio-count">Lighting & Studio(<?php echo $block->getProductCollectionCountWithBrand(19, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(71, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("brands/" . $brandName . "/filters/cat/photo-accessories?_aa=222&_option=" . $brandId)?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-photomemories.jpg"/>
                <div class="product-count"  id="photo-accessories-count">Photo Accessories(<?php echo $block->getProductCollectionCountWithBrand(71, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(22, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("brands/" . $brandName . "/filters/cat/optics?_aa=222&_option=" . $brandId)?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-optics.jpg"/>
                <div class="product-count"  id="optics-count">Optics(<?php echo $block->getProductCollectionCountWithBrand(22, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(73, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("brands/" . $brandName . "/filters/cat/audio-and-visual?_aa=222&_option=" . $brandId)?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-audio-and-visual.jpg"/>
                <div class="product-count"  id="audio-and-visual-count">Audio & Visual(<?php echo $block->getProductCollectionCountWithBrand(73, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(77, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("brands/" . $brandName . "/filters/cat/pro-video?_aa=222&_option=" . $brandId)?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-provideo.jpg"/>
                <div class="product-count"  id="pro-video-count">Pro Video(<?php echo $block->getProductCollectionCountWithBrand(77, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(75, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("brands/" . $brandName . "/filters/cat/smart-home?_aa=222&_option=" . $brandId)?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-smarthome.jpg"/>
                <div class="product-count"  id="smart-home-count">Smart Home(<?php echo $block->getProductCollectionCountWithBrand(75, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(999, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("brands/" . $brandName . "/filters/cat/computers-mobile?_aa=222&_option=" . $brandId)?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-pcandlaptop.jpg"/>
                <div class="product-count"  id="computers-mobile-count">Computers & Mobile(<?php echo $block->getProductCollectionCountWithBrand(999, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
</div>











