<?php
    $brandData = $block->getData();
    $brandId = $brandData['data']['brandId'];
    $brandName = $block->getBrandName($brandId);
?>
<div id="shop-by-category-container" class="shop-by-category-container"> 
    <?php if ($block->getProductCollectionCountWithBrand(17, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("cameras")?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-cameras.jpg"/>
                <div class="product-count" id="cameras-count">Cameras(<?php echo $block->getProductCollectionCountWithBrand(17, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(18, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("lenses")?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-lens.jpg"/>
                <div class="product-count"  id="lenses-count">Lenses(<?php echo $block->getProductCollectionCountWithBrand(18, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(21, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("drones")?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-drones.jpg"/>
                <div class="product-count"  id="drones-count">Drones(<?php echo $block->getProductCollectionCountWithBrand(21, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(19, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("lighting-and-studio")?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-lights-and-studio.jpg"/>
                <div class="product-count"  id="lighting-and-studio-count">Lighting & Studio(<?php echo $block->getProductCollectionCountWithBrand(19, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(71, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("photo-accessories")?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-photomemories.jpg"/>
                <div class="product-count"  id="photo-accessories-count">Photo Accessories(<?php echo $block->getProductCollectionCountWithBrand(71, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(22, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("optics")?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-optics.jpg"/>
                <div class="product-count"  id="optics-count">Optics(<?php echo $block->getProductCollectionCountWithBrand(22, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(73, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("audio-and-visual")?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-audio-and-visual.jpg"/>
                <div class="product-count"  id="audio-and-visual-count">Audio & Visual(<?php echo $block->getProductCollectionCountWithBrand(73, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(77, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("pro-video")?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-provideo.jpg"/>
                <div class="product-count"  id="pro-video-count">Pro Video(<?php echo $block->getProductCollectionCountWithBrand(77, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(704, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("home/smart-home")?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-smarthome.jpg"/>
                <div class="product-count"  id="smart-home-count">Smart Home(<?php echo $block->getProductCollectionCountWithBrand(704, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
    <?php if ($block->getProductCollectionCountWithBrand(662, $brandId)) :?>
        <div class="shop-by-category-category">
            <a href="<?php echo $block->getUrl("computers-mobile")?>">
                <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-pcandlaptop.jpg"/>
                <div class="product-count"  id="computers-mobile-count">Computers & Mobile(<?php echo $block->getProductCollectionCountWithBrand(662, $brandId); ?>)</div>
            </a>
        </div>
    <?php endif; ?>
</div>











