<?php
$files = $block->getAllFiles();
?>

<?php foreach ($files as $file): ?>
    <div><?= $file?></div>
<?php endforeach; ?>

<div class="send-invoice-container">
    <select name="send-invoice-type" id="send-invoice-type" class="input-text">
        <option value="transfer">TRANSFER</option>
        <option value="tax-invoice">TAX INVOICE</option>
        <option value="quotation">QUOTATION</option>
        <option value="picking-slip">PICKING SLIP</option>
        <option value="credit-note">CREDIT NOTE</option>
        <option value="backorder">BACKORDER</option>
    </select>
    <input id="send-invoice-number" type="text" placeholder="Invoice Number" class="input-text" maxlength="128" autocomplete="off">
    <input id="send-invoice-email" type="text" placeholder="Email" class="input-text" maxlength="128" autocomplete="off">
    <span id="send-invoice-button">Send</span>
</div>
<div id="send-result"></div>
    
<script>
    require(['jquery'],function($){

        $('#send-invoice-button').on('click',function (){
            sendInvoice();
        });

        function sendInvoice() {
            var url = "<?php echo $block->getBaseUrl().'d1g1_@dm1np@neI/sendpdf/index/send'?>";
            var sendInvoiceType = $("#send-invoice-type :selected").text();
            var sendInvoiceNumber = $("#send-invoice-number").val();
            var sendInvoiceEmail = $("#send-invoice-email").val();

            if (sendInvoiceEmail != ""){
                $.ajax({
                    url: url,
                    type: "POST",
                    data: {
                        invoiceType: sendInvoiceType,
                        invoiceNumber: sendInvoiceNumber,
                        email: sendInvoiceEmail
                    },
                    success: function(data){
                        console.log(data.output);
                        $('#send-result').html("Success!");
                    },
                    error: function(){
                        console.log("Error!");
                    }
                });
             }
        }

    });

</script>
