<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->create('Magento\Customer\Model\Session');

    if ($customerSession->isLoggedIn()) {
        $customerGroupId = $customerSession->getCustomer()->getGroupId();
        if ($customerGroupId == 10) {
            $isDigiClub = 1;
            $isChecked = "checked";
        } else {
            $isDigiClub = 0;
            $isChecked = "";
        }
    } else {
        $isDigiClub = 0;
        $isChecked = "";
    }
?>

<div style="font-size: 33px;font-weight: 700;padding: 30px 30px 10px 30px;">digi<span style="color: #ff3c00;">Club</span></div>

<form class="form form-digiclub-manage block" action="/digiclubmember/customer/save" method="post">
    
    <div style="
        display: grid;
        grid-template-columns: 60% 45%;
        column-gap: 20px;
    ">
        <fieldset class="fieldset">
            <div class="block-title"><span>What benefits will I receive as a digiClub member?</span></div><br> 
            <div class="digiclub-description">
                <div style="margin-bottom: 10px;">As a digiClub member you will gain access to exclusive deals and rewards.</div>
                <ul>
                    <li>Upon joining digiClub, you'll receive a warm welcome in the form of a $10 coupon</li>
                    <li>Enjoy a competitive advantage with early access to our sales</li>
                    <li>Exclusive access to the digiClub Member Deals page, updated regularly</li>
                    <li>You'll get access to exclusive member deals regularly delivered to your inbox</li>
                    <li>Celebrate your special day with a delightful $20 birthday coupon</li>
                    <li>As a loyal member, you'll receive an annual $25 in-store print voucher</li>
                    <li>Our membership also grants you a 10% discount on digiDirect events, whether they're photography workshops, seminars, or other enriching experiences</li>
                </ul>
            </div>
            <div style="
                display: grid;
                grid-template-columns: repeat(2, 1fr);
                column-gap: 20px;
                row-gap: 20px;
                margin-bottom: 20px;
            ">
                
                <div class="field field-name-firstname _required">
                    <label class="label" for="digiclub-firstname"><span>First Name</span></label>
                    <div class="control">
                        <input type="text" id="digiclub-firstname"
                            name="digiclub-firstname"
                            value="<?= $customerSession->getCustomer()->getData("firstname") ?>"
                            title="First Name"
                            class="input-text digiclub-field" required/>
                    </div>
                </div>
                <div class="field field-name-lastname _required">
                    <label class="label" for="digiclub-lastname"><span>Last Name</span></label>
                    <div class="control">
                        <input type="text" id="digiclub-lastname"
                            name="digiclub-lastname"
                            value="<?= $customerSession->getCustomer()->getData("lastname") ?>"
                            title="Last Name"
                            class="input-text digiclub-field" required/>
                    </div>
                </div>
                <div class="field email _required" data-container="change-email">
                    <label class="label" for="digiclub-email"><span>Email</span></label>
                    <div class="control">
                        <input type="email" name="digiclub-email" id="digiclub-email" autocomplete="email" data-input="change-email"
                            value="<?= $customerSession->getCustomer()->getEmail() ?>"
                            title="Email"
                            class="input-text digiclub-field"
                            data-validate="{required:true, 'validate-email':true}" required/>
                    </div>
                </div>
                <div class="field contact-number _required">
                    <label class="label" for="digiclub-contact-number"><span>Contact Number</span></label> 
                    <div class="control">
                        <input type="number" id="digiclub-contact-number" 
                            name="digiclub-contact-number" 
                            value="<?= $customerSession->getCustomer()->getData("contact_number") ?>"
                            title="Contact Number"
                            class="input-text digiclub-field" required/>
                    </div>
                </div>
                <div class="field dob">
                    <label class="label" for="digiclub-dob" style="width: 150%; display: block;">
                        <span>Date of Birth</span>
                        <span style="font-style: italic;color: #ff3c00; font-weight: 400;">(Enter to receive a $20 birthday coupon)</span>
                    </label> 
                    <div class="control">
                        <input type="date" id="digiclub-dob" 
                            name="digiclub-dob" 
                            value="<?= $customerSession->getCustomer()->getData("dob") ?>"
                            title="Date of Birth"
                            class="input-text digiclub-field"
                            style="padding: 22px 12px !important;" <?php echo $customerSession->getCustomer()->getData("dob") ? 'disabled' : ''; ?>/>
                    </div>
                </div>
                
            </div>

            <div class="field choice">
                <input type="checkbox" name="is_digiclub" id="digiclub" value="<?= $isDigiClub ?>" title="Join digiClub" class="checkbox digiclub-field" <?= $isChecked ?>>
                <label for="digiclub" class="label"><span>Join digiClub</span></label>
            </div> 
            <div style="font-size: 12px;">Click SAVE below to acknowledge your agreement to join digiClub in line with our <a href="https://www.digidirect.com.au/terms/">Terms & Conditions</a> and <a href="https://www.digidirect.com.au/privacy">Privacy Policy</a>.</div>
        </fieldset>
        <div><img src="<?= $block->getUrl("media/wysiwyg/digiClub/")?>digiclub-signup-image.png"/></div>
    </div>
    
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Save" class="action save -responsive digiclub-save" style="
                font-family: 'Poppins';
                font-weight: 500;
                background: #F05A25;
                border-radius: 5px;
            "><span>Save</span>
            </button>
        </div>
    </div>
</form>

<script>
    require([
        'jquery'
    ],
    function ($) {
        
        var isDigiclub = <?php echo $isDigiClub; ?>;
        
        console.log("isDigiclub: " + isDigiclub);
        
        $('#digiclub').on('change', function () {
            console.log("digiClub!");
            if ($('#digiclub').is(":checked")) {
                $('#digiclub').attr("value", 1);
            } else {
                $('#digiclub').attr("value", 0);
            }
        });
        
        if (isDigiclub) {
            $('.digiclub-save').addClass('subscribed');
            $('.digiclub-save span').text('Subscribed');
        } else {
            $('.digiclub-save').removeClass('subscribed');
            $('.digiclub-save span').text('Save');
        }
        
        $('.digiclub-field').on('change', function () {
            console.log("digiclub-field onchange");
            $('.digiclub-save').removeClass('subscribed');
            $('.digiclub-save span').text('Save');
        });
        
    });
</script>

