<?php
    $customer = $block->getCustomer();

    if ($customer && $customer->getId()) {
        $customerGroupId = $customer->getGroupId();
        if ($customerGroupId == 10) {
            $isDigiClub = 1;
            $isChecked = "checked";
        } else {
            $isDigiClub = 0;
            $isChecked = "";
        }
    } else {
        $isDigiClub = 0;
        $isChecked = "";
    }

$dobValue = $customer ? $customer->getData("dob") : "";
$dobFormatted = $dobValue ? date("d/m/Y", strtotime($dobValue)) : "";
?>

<!--<div style="font-size: 33px;font-weight: 700;padding: 30px 30px 10px 30px;">digi<span style="color: #ff3c00;">Club</span></div>-->

<form class="form form-digiclub-manage block" action="/digiclubmember/customer/save" method="post">

    <div class='digiclub-content-wrapper'>
        <fieldset class="fieldset">
            <div class="myacount-digiclub-mobile-img"><img src="<?= $block->getUrl("media/wysiwyg/digiClub/")?>digiclub-signup-image-glowup.png"/></div>
            <div class="block-title"><span>As a digiClub member you will gain access to exclusive deals and rewards.</span></div><br>
            <div class="digiclub-description">
                <ul>
                    <li>Upon joining digiClub, you'll receive a warm welcome in the form of a $10 coupon.</li>
                    <li>Enjoy a competitive advantage with early access to our sales.</li>
                    <li>Exclusive access to the digiClub Member Deals page, updated regularly.</li>
                    <li>You'll get access to exclusive member deals regularly delivered to your inbox.</li>
                    <li>Celebrate your special day with a delightful $20 birthday coupon.</li>
                    <li>As a loyal member, you'll receive an annual $25 in-store print voucher.</li>
                    <li>Our membership also grants you a 10% discount on digiDirect events, whether they're photography workshops, seminars, or other enriching experiences.</li>
                </ul>
            </div>
            <div style="
                display: grid;
                grid-template-columns: repeat(2, 1fr);
                column-gap: 20px;
                row-gap: 20px;
                margin-bottom: 20px;
            ">

                <div class="field field-name-firstname _required">
                    <label class="label" for="digiclub-firstname"><span>First Name</span></label>
                    <div class="control">
                        <input type="text" id="digiclub-firstname"
                            name="digiclub-firstname"
                            value="<?= $customer ? $customer->getData("firstname") : "" ?>"
                            title="First Name"
                            class="input-text digiclub-field" required/>
                    </div>
                </div>
                <div class="field field-name-lastname _required">
                    <label class="label" for="digiclub-lastname"><span>Last Name</span></label>
                    <div class="control">
                        <input type="text" id="digiclub-lastname"
                            name="digiclub-lastname"
                            value="<?= $customer ? $customer->getData("lastname") : "" ?>"
                            title="Last Name"
                            class="input-text digiclub-field required" required/>
                    </div>
                </div>
                <div class="field email _required" data-container="change-email">
                    <label class="label" for="digiclub-email"><span>Email</span></label>
                    <div class="control">
                        <input type="email" name="digiclub-email" id="digiclub-email" autocomplete="email" data-input="change-email"
                            value="<?= $customer ? $customer->getEmail() : "" ?>"
                            title="Email"
                            class="input-text digiclub-field"
                            data-validate="{required:true, 'validate-email':true}" required/>
                    </div>
                </div>
                <div class="field contact-number _required">
                    <label class="label" for="digiclub-contact-number"><span>Contact Number</span></label>
                    <div class="control">
                        <input type="number" id="digiclub-contact-number"
                            name="digiclub-contact-number"
                            value="<?= $customer ? $customer->getData("contact_number") : "" ?>"
                            title="Contact Number"
                            class="input-text digiclub-field" required/>
                    </div>
                </div>
                <div class="field dob">
                    <label class="label" for="digiclub-dob" style="width: 150%; display: block;">
                        <span>Date of Birth</span>
                        <span class="digiclub-dob-text-o" style="">(Enter to receive a $20 birthday coupon)</span>
                    </label>
                    <div class="control">
                        <input type="text" id="digiclub-dob"
                            name="digiclub-dob"
                            value="<?= $dobFormatted ?>"
                            title="Date of Birth"
                            class="input-text digiclub-field"
                            style="padding: 22px 12px !important;" <?php echo ($customer && $customer->getData("dob")) ? 'disabled' : ''; ?>/>
                    </div>
                </div>

            </div>

            <div class="field choice">
                <input type="checkbox" name="is_digiclub" id="digiclub" value="<?= $isDigiClub ?>" title="Join digiClub" class="checkbox digiclub-field" <?= $isChecked ?>>
                <label for="digiclub" class="label"><span>Join <span class="join-digi-o">digi</span>Club</span></label>
            </div>
            <div class="digiclub-t-c">Click SAVE below to acknowledge your agreement to join digiClub in line with our <a href="https://www.digidirect.com.au/terms/">Terms & Conditions</a> and <a href="https://www.digidirect.com.au/privacy">Privacy Policy</a>.</div>
        </fieldset>
        <div class="myacount-digiclub-desktop-img"><img src="<?= $block->getUrl("media/wysiwyg/digiClub/")?>digiclub-signup-image-glowup.png"/></div>
    </div>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Save" class="action save -responsive digiclub-save"><span>Save</span>
            </button>
        </div>
    </div>
</form>

<script>
    require([
        'jquery'
    ],
    function ($) {

        var isDigiclub = <?php echo $isDigiClub; ?>;

        console.log("isDigiclub: " + isDigiclub);

        $('#digiclub').on('change', function () {
            console.log("digiClub!");
            if ($('#digiclub').is(":checked")) {
                $('#digiclub').attr("value", 1);
            } else {
                $('#digiclub').attr("value", 0);
            }
        });

        if (isDigiclub) {
            $('.digiclub-save').addClass('subscribed');
            $('.digiclub-save span').text('Subscribed');
        } else {
            $('.digiclub-save').removeClass('subscribed');
            $('.digiclub-save span').text('Save');
        }

        $('.digiclub-field').on('change', function () {
            console.log("digiclub-field onchange");
            $('.digiclub-save').removeClass('subscribed');
            $('.digiclub-save span').text('Save');
        });

    });
</script>
