<div style="text-align: center;">
    <img src="<?php echo $block->getUrl("media/wysiwyg/digiClub/")?>ty-image.png" style="
        width: 100px;
        object-fit: contain;
        margin-top: 80px;
    "/>
    <div style="font-size: 60px;padding: 10px 0;">Thank you</div>
    <div style="font-size: 18px;padding-bottom: 10px;">for signing up to
        <span style="font-weight: 500;">
            <span style="color: #ff3c00;">digi</span><span>Club</span>
        </span>
    </div>
    <div style="font-size: 18px;padding-bottom: 40px;">Stay tuned to hear all the latest.</div>

    <a href="<?= $block->getBaseUrl();?>" class="back-to-website">BACK TO WEBSITE</a>
</div>

<style>
    .digiclubmember-customer-thankyou .column.main {
        width: 100%;
    }
</style>
