<?php
/** @var $block \Magento\Catalog\Block\Product\ProductList\Item\Container */
$product = $block->getProduct();
$helper = $this->helper(\Ewave\OutOfStockNotif\Helper\Data::class);
$isNotificationForBackorder = $helper->isEnabledForBackorder();
$isBackOrderAllow = $helper->isBackOrderAllow($product);
?>
<?php if ($isNotificationForBackorder && $product->isSaleable() && $isBackOrderAllow) : ?>
    <script type="text/x-magento-init">
        {
            "form[data-product-sku='<?= /* @NoEscape */ $product->getSku(); ?>']": {
                "outstockNotification": {
                    "modal": false,
                    "notificationForBackorder": 1,
                    "isBackorderProduct": true,
                    "backorderButtonLabel": "<?php echo $block->escapeHtml(__($block->getBackorderButtonLabel())); ?>",
                    "addToCartFormSelector": "form[data-product-sku='<?= /* @NoEscape */ $product->getSku(); ?>']"
                }
            }
        }
    </script>
<?php endif; ?>
