<div class="plp-banner-widget">
    <div class="plp-banner" style="height: 265px;">
        <img 
            class="banner-web" 
            style="height: 100%; object-fit: cover;" 
            src="<?= $block->getViewFileUrl('images/plp-banner-preloved.png') ?>" 
            alt="Pre-Loved Banner Desktop"
        />

        <img 
            class="banner-mobile" 
            style="height: 100%; object-fit: cover; display: none;" 
            src="<?= $block->getViewFileUrl('images/plp-banner-preloved-mobile.png') ?>" 
            alt="Pre-Loved Banner Mobile"
        />

        <div class="plp-banner-label">
            <div 
                class="banner-main-label" 
                style="text-align: center; justify-content: center; display: flex; flex-direction: column; color: #fff; font-size: 128px; font-family: Inter; font-weight: 600;"
            >
                Pre-Loved
            </div>
            <div 
                class="banner-secondary-label" 
                style="text-align: center; color: #fff; font-size: 32px; font-weight: 600;"
            >
               We purchase reliable Pre-Loved equipment, refurbish it, and price it for you to save.
            </div>
        </div>
    </div>

    <div class="plp-row pa-widget" style="margin: -4px 0 0 0;">
        <div class="pa-digidirect-product-widget preloved-recommended-widget">
            <div class="product-widget-header">
                <div 
                    class="widget-main-label" 
                    style="color: #242426; font-size: 32px; font-family: Inter; font-weight: 500; line-height: 33px; word-wrap: break-word;"
                >
                    Here's our Recommended Pre-Loved products for you
                </div>
            </div>
            <div 
                id="preloved-recommended-widget-desktop" 
                class="pa-digidirect-product-widget-container desktop-widget real-container owl-carousel custom"
            ></div>
        </div>
    </div>
</div>
