<div class="plp-row pa-widget">
    <div class="pa-digidirect-product-widget recommended-for-you-widget">
        <div class="product-widget-header">
            <div class="widget-main-label" style="color: #242426; font-size: 32px; font-family: Inter; font-weight: 500; line-height: 33px; word-wrap: break-word">Recommended based on your search</div>
        </div>
        <div id="recommended-for-you-widget-desktop" class="pa-digidirect-product-widget-container desktop-widget real-container owl-carousel custom"></div>
        <div id="recommended-for-you-widget-mobile" class="pa-digidirect-product-widget-container mobile-widget"></div>
    </div>
</div>