/* eslint one-var: ["error", { const: "never" }] */
export const PLACE_SELECT_PENDING = 'PLACE_SELECT_PENDING';
export const FORM_CHANGE_PENDING = 'FORM_CHANGE_PENDING';
export const FORM_CHANGE_SUCCESS = 'FORM_CHANGE_SUCCESS';

// ERRORS

export const PLACES_DOWNLOAD_ERROR = 'PLACES_DOWNLOAD_ERROR';
export const PLACE_SELECT_ERROR = 'PLACE_SELECT_ERROR';
export const GOOGLE_MAPS_AUTHENTICATION_ERROR = 'GOOGLE_MAPS_AUTHENTICATION_ERROR';

// AU POST
export const POST_INITIALIZED = 'POST_INITIALIZED';
export const POST_DESTROYED = 'POST_DESTROYED';
export const POST_FETCH_DATA_START = 'POST_FETCH_DATA_START';
export const POST_FETCH_DATA_PROGRESS = 'POST_FETCH_DATA_PROGRESS';
export const POST_FETCH_DATA_SUCCESS = 'POST_FETCH_DATA_SUCCESS';
export const POST_FETCH_DATA_ERROR = 'POST_FETCH_DATA_ERROR';
