<?php
    use Magento\Framework\App\Action\Action;
?>
<script>
    
require(['jquery'], function ($) {
    
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }
    
    console.log('PAC: ' + getCookie('PAC'));
    var customerId = getCookie('PAC');
    var customerParam = "";
    
    if (customerId) {
        customerParam = "&customerId=" + customerId;
    }
    
    const getRecommendationsUrl = "https://api-recs.particularaudience.com/3.0/recommendations?currentUrl=https://www.digidirect.com.au/pa-digi-home-page&expandProductDetails=false"+customerParam;
    const accessToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg5MjJCQzYzODc5NjIwMzUzNTE4OTNFODVGODU2MEZCIiwidHlwIjoiSldUIn0.eyJuYmYiOjE3MjI1NzY5NjIsImV4cCI6MTcyMjY2Njk2MiwiaXNzIjoiaHR0cHM6Ly9jb25mLnNocmRzcnZjcy5wLWEuaW8vYXV0aCIsImNsaWVudF9pZCI6IkRCRDZDODRGLTIzMzItRUMxMS1BQUU5LTAyRENBNDRDQ0VFQyIsImp0aSI6IjhGNURCQkMxNjNFRUUyMjg5RjgwRUYxQ0Q0MDBFMTVFIiwiaWF0IjoxNzIyNTc2OTYyLCJzY29wZSI6WyJhcGk6cmVjcyIsImFwaTpzZWFyY2giXX0.Vmiu3wOtj1Ejce0OcE60Ikb4UHYOV9DfXanNJrK40FGUxyPDK9oSc4H8aOmeZmEN4L8x7te7_nxoaqq6eylO5aAzqsMyUAX5Ofriumxjt1Jcy-aEHM__gMqKrdfHoJ4pSZl6ySddW2wH4-VEGfzC8WDZm--viRHTDJKPoIyBhZw2w_En22Xt5qfcALordVdH6Ho0oOyu90eWiPtaYZjahUB3VVt862bXAN5EmVOl0cuMdzzvLzJB-qFnmXQX0uJcoGw3F1eVFrCtlWgFZ2BANcGIKmr8ItseEARDkMoyB1NkUnROr9ZTN-rRFfYmJQpokEpxAJKeaSYO3E0FZUoQaA"; // Replace with your actual access token

    var result;

    $.ajax({
        async: false,
        url: getRecommendationsUrl,
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-Type': "application/json"
        },
        type: "GET",
        success: function(data){
            result = data;
            console.log('success: ' + data);
        },
        error: function(){
            console.log('AJAX Fail!');
        }
    });
    
    console.log('result: ' + JSON.stringify(result));
    var recommendationsResult = result;
    var widgets  = recommendationsResult.recommendations.route.widgets;
    //console.log('routeId: ' + widgets);

    /*Object.keys(widgets).forEach(key => {
      console.log(key, widgets[key]);
    });*/

    var blueWidget = widgets.find(obj => {
        return obj.id === '458d80ed-033e-ec11-aae9-02dca44cceec';
    })

    //console.log(blueWidget);

    var blueWidgetArr = [];
    var blueWidgetSlots = blueWidget.slots;
    Object.keys(blueWidgetSlots).forEach(key => {
        console.log(key, blueWidgetSlots[key].products[0].refId);
        blueWidgetArr.push(blueWidgetSlots[key].products[0].refId);
    });

    console.log(blueWidgetArr);
    
});

</script>

<?php
    $recommendedProductsBlueWidget = $block->getRecommendedProductsBlueWidget();
    $productCount = 0;
?>

<div class="home-main-banners">
    <div class="home-main-banner-left">
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-web-banner')->toHtml(); ?>
    </div>
    <div class="home-main-banner-right">
        <div>
            <?php if ($recommendedProductsBlueWidget): ?>
                <div id="pa-blue-right-side-widget-wrapper">
                    <div id="pa-blue-right-side-widget">
                        <div class="product-widget-header">
                            <h3 class="title">Welcome Back! Continue Shopping!</h3>
                        </div>
                        <div class="pa-product-widget-container">
                            <?php foreach ($recommendedProductsBlueWidget as $_product): ?>
                                <?php $productCount++; ?>
                                <?php if ($productCount < 4): ?>
                                    <div class="product-item-info product-item">
                                        <a href="<?= $_product->getProductUrl(); ?>" class="product photo product-item-photo" tabindex="-1">
                                            <span class="product-image-container" style="width: 240px;">
                                                <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                                    <img class="product-image-photo" src="<?= 'https://www.digidirect.com.au/media/catalog/product' . $_product->getData('thumbnail'); ?>" loading="lazy" width="240" height="300" alt="Product Image">
                                                </span>
                                            </span> 
                                        </a> 
                                        <div class="product details product-item-details">
                                            <strong class="product-item-name">
                                                <a title="<?= $_product->getName(); ?>" href="<?= $_product->getProductUrl(); ?>" class="product-item-link">
                                                    <?= $_product->getName(); ?>
                                                </a>
                                            </strong>
                                            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <div>
            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('lower-right-side-banner')->toHtml(); ?>
        </div>
    </div>
</div>

