<?php
    use Magento\Framework\App\Action\Action;
?>
<script>
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }
    console.log('PAC: ' + getCookie('PAC'));
    var customerId = getCookie('PAC');
    var customerParam = "";
    
    if (customerId) {
        customerParam = "&customerId=" + customerId;
    }
    
    const getRecommendationsUrl = "https://api-recs.particularaudience.com/3.0/recommendations?currentUrl=https://www.digidirect.com.au/pa-digi-home-page&expandProductDetails=false"+customerParam;
    const accessToken = "<?= $block->getBearerToken() ?>"; // Replace with your actual access token
    
    async function getRecommendations() {
        
        try {
            const response = await fetch(getRecommendationsUrl, {
                                        method: 'GET',
                                        headers: {
                                            "Authorization": `Bearer ${accessToken}`,
                                            "Content-Type": "application/json"
                                        }
                                    });
            const data = await response.json();
            console.log(data);
            return data
        } catch(error) {
            console.error(error);
        }
        
        /*fetch(getRecommendationsUrl, {
            method: 'GET',
            headers: {
                "Authorization": `Bearer ${accessToken}`,
                "Content-Type": "application/json"
            }
        })
        .then(response => response.json())
        .then(data => {return data})
        .then(() => console.log('Recommendations:', recommendationsResult))
        .catch(error => console.error('Error fetching recommendations:', error));*/
    }

    var recommendationsResult = getRecommendations();
    //Working fetch, result on console.log()
    /*fetch(getRecommendationsUrl, {
        method: 'GET',
        headers: {
            "Authorization": `Bearer ${accessToken}`,
            "Content-Type": "application/json"
        }
    })
    .then(response => response.json())
    .then(data => console.log('Recommendations:', data))
    .catch(error => console.error('Error fetching recommendations:', error));*/
    
    var parsedData = JSON.stringify(recommendationsResult);
    console.log('parsedData: ' + parsedData);
    /*var widgets = parsedData['recommendations'][0]['route'][0]['name'];
    console.log('widget: ' + widgets);*/
    
</script>
<?php
?>

<div class="home-main-banners">
    <div class="home-main-banner-left">
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-web-banner')->toHtml(); ?>
    </div>
    <div class="home-main-banner-right">
        <div>
            
        </div>
        <div>
            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('lower-right-side-banner')->toHtml(); ?>
        </div>
    </div>
</div>

