<?php
    use Magento\Framework\App\Action\Action;
?>
<script>
    
require(['jquery'], function ($) {
    
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }
    
    console.log('PAC: ' + getCookie('PAC'));
    var customerId = getCookie('PAC');
    var customerParam = "";
    
    if (customerId) {
        customerParam = "&customerId=" + customerId;
    }
    
    const getRecommendationsUrl = "https://api-recs.particularaudience.com/3.0/recommendations?currentUrl=https://www.digidirect.com.au/pa-digi-home-page&expandProductDetails=false"+customerParam;
    const accessToken = "<?= $block->getBearerToken() ?>"; // Replace with your actual access token

    var result;

    $.ajax({
        async: false,
        url: getRecommendationsUrl,
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-Type': "application/json"
        },
        type: "GET",
        success: function(data){
            result = data;
            console.log('success: ' + data);
        },
        error: function(){
            console.log('AJAX Fail!');
        }
    });
    
    console.log('result: ' + JSON.stringify(result));
    var recommendationsResult = result;
    var widgets  = recommendationsResult.recommendations.route.widgets;
    //console.log('routeId: ' + widgets);

    /*Object.keys(widgets).forEach(key => {
      console.log(key, widgets[key]);
    });*/

    var blueWidget = widgets.find(obj => {
        return obj.id === '458d80ed-033e-ec11-aae9-02dca44cceec';
    })
    //function blueWidgetProducts() {
    var blueWidgetArr = [];
    var blueWidgetSlots = blueWidget.slots;
    Object.keys(blueWidgetSlots).forEach(key => {
        console.log(key, blueWidgetSlots[key].products[0].refId);
        blueWidgetArr.push(blueWidgetSlots[key].products[0].refId);
    });
    //return blueWidgetArr;
    //}
    
    function checkProduct(id) {
        var productObj = "";
        var url = "<?php echo $block->getBaseUrl().'particularaudienceapi/index/product'?>";
        $.ajax({
            async: false,
            url: url,
            type: "GET",
            data: {
                id: id
            },
            success: function(data){
                //console.log("checkProduct", JSON.stringify(data));
                productObj = data;
            },
            error: function(){
                console.log("Error!");
            }
        });
        
        return productObj;
    }
    
    blueWidgetArr.forEach(function (id) {
        let product = checkProduct(id);
        console.log("blueWidgetArr", JSON.stringify(product));
        $('.pa-product-widget-container').append(`<div class="row">`product.name`</div>`);
    });
    
});

</script>

<div class="home-main-banners">
    <div class="home-main-banner-left">
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-web-banner')->toHtml(); ?>
    </div>
    <div class="home-main-banner-right">
        <div>
            <div id="pa-blue-right-side-widget-wrapper">
                <div id="pa-blue-right-side-widget">
                    <div class="product-widget-header">
                        <h3 class="title">Welcome Back! Continue Shopping!</h3>
                    </div>
                    <div class="pa-product-widget-container">
                    </div>
                </div>
            </div>
        </div>
        <div>
            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('lower-right-side-banner')->toHtml(); ?>
        </div>
    </div>
</div>

