<?php
/** @var \Digidirect\MyOrderItemsGroups\Block\Customer\MyOrderItems\Group\ItemsList\Groups $block */
$filterParams = $block->collectFilterParams();
?>
<div class="group-manage">
    <div class="title" data-toggle="dropdown" data-mage-init='{"dropdown": {}}'><?php echo $block->escapeHtml(__('Manage Group')) ?></div>
    <div class="list" data-target="dropdown">
        <a class="item" title="<?= $block->escapeHtml(__('Create New Group')) ?>" href="<?= $block->escapeUrl($block->getUrl('myorderitems/myorderitems/addgroup')) ?>"><?= $block->escapeHtml(__('Create New Group')) ?></a>
        <?php if (!$block->isEmptyGroup()): ?>
            <!-- Rename should be a fake link just showing hidden rename form -->
            <a class="item" title="<?= $block->escapeHtml(__('Rename Group')) ?>" href="" data-role="rename-group"><?= $block->escapeHtml(__('Rename Group')) ?></a>
            <!-- Clear Items should be a fake link showing hidden checkboxes and submit button -->
            <a class="item" title="<?= $block->escapeHtml(__('Clear Item(s)')) ?>" href="" data-role="clear-button"><?= $block->escapeHtml(__('Clear Item(s)')) ?></a>
            <a class="item" title="<?= $block->escapeHtml(__('Delete Group')) ?>" data-role="delete-group" href="<?= $block->escapeUrl($block->getUrl('myorderitems/myorderitems/delete', ['group_id' => $block->getCurrentGroupId()])) ?>"><?= $block->escapeHtml(__('Delete Group')) ?></a>
        <?php else: ?>
            <?= $block->escapeHtml(__('Rename Group')) ?>
            <?= $block->escapeHtml(__('Clear Item(s)')) ?>
            <?= $block->escapeHtml(__('Delete Group')) ?>
        <?php endif; ?>
    </div>
</div>