<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <?php $startBlock = $block->getLayout()->getBlock('order.items.table.body.start'); ?>
    <?php if ($startBlock) :?>
        <?php /* @escapeNotVerified */ echo $startBlock->setItem($_item->getOrderItem())->toHtml(); ?>
    <?php endif; ?>
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
        <dl class="item options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
            <?php if (!$block->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                    <div class="tooltip content">
                        <dl class="item options">
                            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                            <dd><?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?></dd>
                        </dl>
                    </div>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd><?php echo $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('Product Code')); ?>"><?= $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>"><?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getPrice()) ?></td>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>"><?= __('Ordered: '.$_item->getOrderItem()->getQtyOrdered()*1) ?><br><?= __('Shipped: '.$_item->getOrderItem()->getQtyShipped()*1) ?></td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>"><?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getQty()*$_item->getPrice()) ?></td>
</tr>
