<?php
/**
 * @var \Ewave\AbstractGiftCard\Block\Check $block
 * @see \Magento\GiftCardAccount\Block\Check
 */
$card = $block->getCard();
$helper = $this->helper('Ewave\Vii\Helper\Data');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<?php if ($card): ?>
    <?php $status = $helper->getCardStatusLabel($card->getCardStatus()); ?>
    <?php $dataExpires = strtotime($card->getDateExpires()); ?>
    <div class="giftcard-info table-wrapper">
        <table class="data table">
            <thead>
                <tr>
                    <th class="col giftcard-info"><?php echo $block->escapeHtml(__('Gift Card'));?></th>
                    <th class="col giftcard-info"><?php echo $block->escapeHtml(__('Current Balance')); ?></th>
                    <th class="col giftcard-info"><?php echo $block->escapeHtml(__('Expiry Date')); ?></th>
                    <th class="col giftcard-info"><?php echo $block->escapeHtml(__('Card Status')); ?></th>
                </tr>
            </thead>
            <tbody class="tbody">
                <tr>
                    <td class="col giftcard-info" data-th="<?php echo $block->escapeHtml(__('Gift Card')); ?>">
                        <?php echo $block->escapeHtml($card->getCode()); ?>
                    </td>
                    <td class="col giftcard-info" data-th="<?php echo $block->escapeHtml(__('Current Balance')); ?>">
                        <?php /* @noEscape */ echo $priceHelper->currency($card->getBalance()); ?>
                    </td>
                    <td class="col giftcard-info" data-th="<?php echo $block->escapeHtml(__('Expiry Date')); ?>">
                        <?php if (!empty($dataExpires)): ?>
                            <?php echo $block->escapeHtml(date('d/m/Y', $dataExpires)); ?>
                        <?php endif; ?>
                    </td>
                    <td class="col giftcard-info" data-th="<?php echo $block->escapeHtml(__('Card Status')); ?>">
                        <?php echo $block->escapeHtml($status); ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <?php if ($message = $block->getMesssages()->getLastAddedMessage()): ?>
        <div class="message error">
            <span><?php echo $block->escapeHtml(__($message->getText())); ?></span>
        </div>
    <?php else: ?>
        <div class="message error">
            <span><?php echo $block->escapeHtml(__('Please enter a valid gift card code.')); ?></span>
        </div>
    <?php endif;?>
<?php endif; ?>
