<?php
/**
 * @var $block \Ewave\SocialSharing\Block\Sharing
 * @var $sharingHelper \Ewave\SocialSharing\Helper\Config\Pinterest
 */
?>
<?php
$sharingHelper = $this->helper('Ewave\SocialSharing\Helper\Config\Pinterest');
$product = $block->getProduct();
?>
<div class="pinit_button social_button">
    <a href="//www.pinterest.com/pin/create/button/?url=<?php echo $this->escapeUrl($product->getProductUrl()); ?>&description=<?php echo $this->escapeUrl($product->getProductUrl()); ?>"
       data-pin-do="buttonPin" data-pin-color="red" data-pin-height="20"
       <?php if ($sharingHelper->isPinDisplayCountSettings()): ?> data-pin-count="beside"<?php endif; ?>>pinit</a>
</div>
<script type="text/javascript" async defer src="//assets.pinterest.com/js/pinit.js"></script>
