<?php
/**
 * @var $block \Digidirect\SocialSharing\Block\Sharing
 * @var $sharingHelper \Digidirect\SocialSharing\Helper\Config\Facebook
 */
?>
<?php
$sharingHelper = $this->helper('Digidirect\SocialSharing\Helper\Config\Facebook');
$facebookID = $sharingHelper->getFacebookId();
$countButton = ($sharingHelper->isDisplayCountSettings()) ? 'button_count' : 'button';
$likeButton = !$sharingHelper->isDisplayLikeSettings();
?>
<div class="button-social -facebook">
    <li class="item">
        <a class="link"
           title="Facebook link"
           target="_blank"
           href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $block->escapeUrl($block->getSharingUrl()); ?>">
            <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -facebook">
                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-facebook"></use>
            </svg>
        </a>
    </li>
</div>
