<?php
/* @var $block \Ewave\RelatedProduct\Block\ProductList\Related */

use Ewave\RelatedProduct\Block\ProductList\Related;
use Magento\Framework\App\Action\Action;

if ($exist = $block->getItems()->getSize()) {
    $type = 'related';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Recommended Accessories');
    $items = $block->getItems();

    $categoryCollection = $block->getCategoriesAssignedRelatedProducts();
    $helper = $this->helper('\Ewave\RelatedProduct\Helper\Data');
    $_quickViewHelper = $this->helper('Ewave\QuickView\Helper\Data');

    $initialFilter = '';
    $isShowFilterContent = false;
    $showQuickView = $_quickViewHelper->isModuleEnabled();
    $quickViewUseForMobile = true;
    $quickViewLabel = __('Quick View');
}
?>

<?php if ($exist):?>
    <div class="products-widget _full-width-background <?= $block->escapeHtml($class); ?>">
        <div class="related-header">
            <div class="title">
                <strong id="block-<?php $block->escapeHtml($class); ?>-heading" role="heading" aria-level="2">
                    <?= $block->escapeHtml($title); ?>
                </strong>
            </div>

            <?php if ($helper->isFilterTabEnabled()) : ?>
                <div class="related-filters" data-role="related-filters">
                    <?php $i = 1; ?>
                    <?php if ($block->getDisplayAllCategory()): ?>
                        <?php $i++; $initialFilter = Related::ALL_CATEGORY_ID; ?>
                        <span class="item -active" role="button" data-group="<?= $block->escapeHtml(Related::ALL_CATEGORY_ID); ?>" title="<?= $block->escapeHtml(__('All')); ?>">
                            <?= $block->escapeHtml(__('All')); ?>
                        </span>
                    <?php endif; ?>
                    <?php foreach ($categoryCollection as $category) : ?>
                        <?php if ($i == 1): ?>
                            <?php $initialFilter = $category->getId(); ?>
                        <?php endif; ?>
                        <span class="item<?php if ($i == 1): ?> -active<?php endif; ?>" role="button" data-group="<?= $block->escapeHtml($category->getId()); ?>" title="<?= $block->escapeHtml($category->getName()); ?>">
                            <?= $block->escapeHtml($category->getName()); ?>
                        </span>
                    <?php $i++; endforeach; ?>
                    <?php if ($isShowFilterContent): ?>
                        <?php $i = 1; foreach ($categoryCollection as $category) : ?>
                            <?php if ($category->getDescription()): ?>
                                <div class="content<?php if ($i == 1): ?> -active<?php endif; ?>" data-category-id="<?= $block->escapeHtml($category->getId()); ?>"><?= /* @escapeNotVerified */ $category->getDescription(); ?></div>
                            <?php endif; ?>
                        <?php $i++; endforeach; ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
        
        <div class="block-content content" aria-labelledby="block-<?php $block->escapeHtml($class); ?>-heading">      
            <div class="products wrapper grid products-grid -related products-<?= $block->escapeHtml($type); ?>">
                <div id="related-grid"
                     class="related-grid product-items products list items"
                     data-mage-init='{
                    "relatedInfo": {
                        "initialFilter": "<?= $block->escapeHtml($initialFilter); ?>",
                        "itemSelector": ".product-item"
                    },
                    "productTile": {
                        <?php if ($block->isRedirectToCartEnabled()): ?>
                        "isRedirectToCartEnabled": true,
                        <?php endif; ?>
                        "type":"filteredSlider"
                    }
                    }'>
                    <?php /** @var $_item \Magento\Catalog\Model\Product */ ?>
                    <?php $iterator = 1; $i = 0; foreach ($items as $_item): ?>
                    <?php
                        $productId = $_item->getId();
                        $productName = $_item->getName();
                        $productUrl = $_item->getProductUrl();
                        $ruleMessage = $block->getChildBlock('product.related.extended.catalog.rule');
                    ?>
                        <?php if ($iterator++ != 1) : ?></div><?php endif; ?>
                        <div data-groups='<?= /* @escapeNotVerified */ json_encode($block->getVisibleProductCategories($_item)); ?>'
                             data-sort-order="<?= $block->escapeHtml(implode(',', $block->getProductPositionsInCategories($_item))); ?>"
                             class=" item product product-item">
                            <div class="product-item-info" data-parent-product-id="<?= $productId; ?>">
                                <?= '<!-- ' . $block->escapeHtml($image) . '-->' ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)); ?>"
                                   title="<?= $block->escapeHtml($productName); ?>"
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml(); ?>
                                </a>

                                <strong class="product name product-item-name">
                                    <a href="<?= $block->escapeUrl($productUrl); ?>"
                                       title="<?= $block->escapeHtml($productName); ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($productName); ?>
                                    </a>
                                </strong>

                                <div class="product details product-item-details">
                                    <?php if ($ruleMessage): ?>
                                        <?= /* @escapeNotVerified */ $ruleMessage->setProduct($_item)->toHtml(); ?>
                                    <?php endif; ?>
                                    <?= /* @escapeNotVerified */ $block->getProductPrice($_item); ?>

                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions">
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php $addToCartUrl = $block->getAddToCartUrl($_item); ?>
                                                        <form data-role="tocart-form"
                                                              data-product-sku="<?=  /* @escapeNotVerified */ $_item->getSku(); ?>"
                                                              data-mage-init='{"validation": {}}'
                                                              action="<?= $block->escapeUrl($addToCartUrl); ?>"
                                                              method="post">
                                                            <input type="hidden"
                                                                   name="product"
                                                                   value="<?= /* @escapeNotVerified */ (int)$_item->getEntityId(); ?>"/>
                                                            <input type="hidden"
                                                                   name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                   value="<?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Url\Helper\Data')->getEncodedUrl($addToCartUrl); ?>"/>
                                                            <?= $block->getBlockHtml('formkey'); ?>
                                                            <?php if ($toCartFormBlock = $block->getChildBlock('tocart_form')): ?>
                                                                <?= /* @escapeNotVerified */ $toCartFormBlock->setProduct($_item)->getChildHtml(); ?>
                                                            <?php endif; ?>
                                                            <button class="action tocart"
                                                                    type="submit" title="<?= /* @escapeNotVerified */ __('Add to Cart'); ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Cart'); ?></span>
                                                            </button>
                                                        </form>
                                                        <?php
                                                            $outOfStockNotifHelper = $this->helper(\Ewave\OutOfStockNotif\Helper\Data::class);
                                                            $isNotificationForBackorder = $outOfStockNotifHelper->isEnabledForBackorder();
                                                            $isBackOrderAllow = $outOfStockNotifHelper->isBackOrderAllow($_item);
                                                        ?>
                                                        <?php if ($isNotificationForBackorder && $isBackOrderAllow) : ?>
                                                            <script type="text/x-magento-init">
                                                                {
                                                                    "form[data-product-sku='<?= /* @escapeNotVerified */ $_item->getSku(); ?>']": {
                                                                        "outstockNotification": {
                                                                            "modal": false,
                                                                            "notificationForBackorder": true,
                                                                            "isBackorderProduct": true,
                                                                            "backorderButtonLabel": "<?= /* @escapeNotVerified */ __('Back-order'); ?>",
                                                                            "addToCartFormSelector": "form[data-product-sku='<?= /* @escapeNotVerified */ $_item->getSku(); ?>']",
                                                                            "outofstockHideContainer": false
                                                                        }
                                                                    }
                                                                }
                                                            </script>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock'); ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock'); ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                    <a href="#"
                                                        data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item); ?>'
                                                        class="action towishlist" data-action="add-to-wishlist"
                                                        title="<?= /* @escapeNotVerified */ __('Add to Wish List'); ?>">
                                                        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-heart"></use></svg>
                                                    </a>
                                                </div>
                                                <?php if ($showQuickView): ?>
                                                    <span role="button"
                                                          data-role="quickview-button"
                                                          data-url="<?= $block->escapeUrl($block->getProductUrl($_item)) . '?quickview=1'; ?>"
                                                          class="quickview-button"
                                                          title="<?= $block->escapeHtml($quickViewLabel); ?>">
                                                        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon">
                                                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-quick"></use>
                                                        </svg>
                                                        <span class="title"><?= $block->escapeHtml($quickViewLabel); ?></span>
                                                    </span>
                                                <?php endif; ?>
                                        </div>
                                        <?php if ($rentBlock = $block->getChildBlock('product.related.rent')): ?>
                                            <?= $rentBlock->toHtml(); ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <?= /* @escapeNotVerified */ ($iterator == count($items) + 1) ? '</div>' : '' ?>
                    <?php $i++; endforeach ?>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>
