<?php
/* @var $block \Ewave\RelatedProduct\Block\ProductList\Related */

use Ewave\RelatedProduct\Block\ProductList\Related;
use Magento\Framework\App\Action\Action;

if ($exist = $block->getItems()->getSize()) {
    $type = 'related';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Recommended Accessories');
    $items = $block->getItems();

    $categoryCollection = $block->getCategoriesAssignedRelatedProducts();
    $helper = $this->helper('\Ewave\RelatedProduct\Helper\Data');
    $initialFilter = '';
    $isShowFilterContent = false;
}
?>

<?php if ($exist):?>
    <div class="products-widget _full-width-background <?php echo $block->escapeHtml($class); ?>">
        <div class="related-header">
            <div class="title">
                <strong id="block-<?php $block->escapeHtml($class); ?>-heading" role="heading" aria-level="2">
                    <?php echo $block->escapeHtml($title); ?>
                </strong>
            </div>

            <?php if ($helper->isFilterTabEnabled()) : ?>
                <div class="related-filters" data-role="related-filters">
                    <?php $i = 1; ?>
                    <?php if ($block->getDisplayAllCategory()): ?>
                        <?php $i++; $initialFilter = Related::ALL_CATEGORY_ID; ?>
                        <span class="item -active" role="button" data-group="<?php echo $block->escapeHtml(Related::ALL_CATEGORY_ID); ?>" title="<?php echo $block->escapeHtml(__('All')); ?>">
                            <?php echo $block->escapeHtml(__('All')); ?>
                        </span>
                    <?php endif; ?>
                    <?php foreach ($categoryCollection as $category) : ?>
                        <?php if ($i == 1): ?>
                            <?php $initialFilter = $category->getId(); ?>
                        <?php endif; ?>
                        <span class="item<?php if ($i == 1): ?> -active<?php endif; ?>" role="button" data-group="<?php echo $block->escapeHtml($category->getId()); ?>" title="<?php echo $block->escapeHtml($category->getName()); ?>">
                            <?php echo $block->escapeHtml($category->getName()); ?>
                        </span>
                    <?php $i++; endforeach; ?>
                    <?php if ($isShowFilterContent): ?>
                        <?php $i = 1; foreach ($categoryCollection as $category) : ?>
                            <?php if ($category->getDescription()): ?>
                                <div class="content<?php if ($i == 1): ?> -active<?php endif; ?>" data-category-id="<?php echo $block->escapeHtml($category->getId()); ?>"><?php /* @escapeNotVerified */ echo $category->getDescription(); ?></div>
                            <?php endif; ?>
                        <?php $i++; endforeach; ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
        
        <div class="block-content content" aria-labelledby="block-<?php $block->escapeHtml($class); ?>-heading">      
            <div class="products wrapper grid products-grid -related products-<?php echo $block->escapeHtml($type); ?>">
                <div id="related-grid"
                     class="related-grid product-items products list items"
                     data-mage-init='{
                    "relatedInfo": {
                        "initialFilter": "<?php echo $block->escapeHtml($initialFilter); ?>",
                        "itemSelector": ".product-item"
                    },
                    "productTile": {
                        <?php if ($block->isRedirectToCartEnabled()): ?>
                        "isRedirectToCartEnabled": true,
                        <?php endif; ?>
                        "type":"filteredSlider"
                    }
                    }'>
                    <?php $iterator = 1; $i = 0; foreach ($items as $_item): ?>
                    <?php /** @var Ewave\RelatedProduct\Model\Product $_item */ ?>
                        <?php if ($iterator++ != 1) : ?></div><?php endif; ?><div data-groups='<?php /* @escapeNotVerified */ echo json_encode($block->getVisibleProductCategories($_item)); ?>' data-sort-order="<?php echo $block->escapeHtml(implode(',', $block->getProductPositionsInCategories($_item))); ?>"  class=" item product product-item">
                            <div class="product-item-info">
                                <?php echo '<!-- ' . $block->escapeHtml($image) . '-->' ?>
                                <a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)); ?>" class="product photo product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                            href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>">
                                                <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>

                                    <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>                              
                                </div>                             

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php $addToCartUrl = $block->getAddToCartUrl($_item); ?>
                                                    <form data-role="tocart-form" data-mage-init='{"validation": {}}' action="<?= $block->escapeUrl($addToCartUrl); ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ (int)$_item->getEntityId(); ?>">
                                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Url\Helper\Data')->getEncodedUrl($addToCartUrl); ?>">
                                                        <?php echo $block->getBlockHtml('formkey')?>
                                                        <?php if ($toCartFormBlock = $block->getChildBlock('tocart_form')): ?>
                                                            <?php /* @escapeNotVerified */ echo $toCartFormBlock->setProduct($_item)->getChildHtml(); ?>
                                                        <?php endif; ?>
                                                        <button class="action tocart"
                                                                type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>

                                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                <a href="#"
                                                    data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item) ?>'
                                                    class="action towishlist" data-action="add-to-wishlist"
                                                    title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-heart"></use></svg>
                                                </a>
                                            </div>
                                    </div>
                                    <?php if ($rentBlock = $block->getChildBlock('product.related.rent')): ?>
                                        <?php echo $rentBlock->toHtml(); ?>
                                    <?php endif; ?> 
                                </div>
                            </div>
                        <?php echo($iterator == count($items)+1) ? '</div>' : '' ?>
                    <?php $i++; endforeach ?>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>
