// OFFCANVAS CONSTANTS

export const
    OFFCANVAS_INITIALIZED = 'OFFCANVAS_INITIALIZED',
    OFFCANVAS_TOOGLE = 'OFFCANVAS_TOOGLE',
    OFFCANVAS_OPEN = 'OFFCANVAS_OPEN',
    OFFCANVAS_OPENED = 'OFFCANVAS_OPENED',
    OFFCANVAS_CLOSE = 'OFFCANVAS_CLOSE',
    OFFCANVAS_CLOSED = 'OFFCANVAS_CLOSED',
    KEYCODE_ESC = 27;
