<?php
/**
 * @var $block \Digidirect\SocialSharing\Block\Sharing
 * @var $sharingHelper \Digidirect\SocialSharing\Helper\Config\Pinterest
 */
?>
<?php
    $sharingHelper = $this->helper('Digidirect\SocialSharing\Helper\Config\Pinterest');
    $product = $block->getProduct();
?>
<li class="item">
    <script type="text/javascript" async defer src="//assets.pinterest.com/js/pinit.js"></script>
    <a class="link"
       href="https://www.pinterest.com/pin/create/button/"
       data-pin-do="buttonBookmark"
       data-pin-custom="true"
       data-no-stop-propagation="true">
        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -pinterest">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-pinterest"></use>
        </svg>
    </a>
</li>