<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$cmsPaymentsBlock = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('secure-pay')->toHtml();
$quoteHelper = $helper = $this->helper('Digidirect\Digi\Helper\Quote');
$hasWebOnly = $quoteHelper->isQuoteHasWebOnlyProducts();
?>

<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
        window.cmsPayments = {"content": <?php echo json_encode(str_replace(array("\r", "\n"), "",
            $cmsPaymentsBlock))?>};
                    
        login_state = window.isCustomerLoggedIn;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader',
        ], function(url, blockLoader) {
            blockLoader("<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>");
            return url.setBaseUrl('<?= /* @escapeNotVerified */ $block->getBaseUrl() ?>');
        })
    </script>
    
    <script type="text/javascript">
        require(['jquery', 
                 'accordionStep',
                 'qantasLoader'], 
        function($, accordionStep, qantasLoader) {
            $("body").on("click", ".extension-action", function(){
                console.log("Triggered");
                
                $(".checkout-shipping-address .accordion-step").addClass("active");
                $(".checkout-shipping-method .accordion-step").addClass("active");
                
                $(".checkout-shipping-address .step-content").removeClass("hide");
                $(".checkout-shipping-method .step-content").removeClass("hide");
                
                $("#shipping-method-buttons-container .continue").trigger("click");
            });
        });
    </script>
    <!--End-->
    <?php $pickUpStoreCmsBlock = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('pick-up-store')->toHtml() ?>
    <?php $oneHourPickUpAvailable = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('one-hour-pickup-available')->toHtml() ?>
    <script type="text/javascript">
        window.pickUpStoreCmsBlock = <?php echo json_encode($pickUpStoreCmsBlock)?>;
        window.oneHourPickUpAvailable = <?php echo json_encode($oneHourPickUpAvailable)?>
    </script>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Checkout/js/order-field": {}
        }
    }
    </script>
</div>

<?php if ($hasWebOnly) : ?>
<script>
    window.hasWebOnly = <?= $hasWebOnly ?>;
</script>
<?php endif; ?>
