<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="registration" class="registration" data-bind="scope:'registration'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#registration": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "registration": {
                            "component": "Magento_Checkout/js/view/registration",
                            "config": {
                                "registrationUrl": "<?= /* @escapeNotVerified */ $block->getCreateAccountUrl() ?>",
                                "email": "<?= /* @escapeNotVerified */ $block->getEmailAddress() ?>"
                            },
                            "children": {
                                "errors": {
                                    "component": "Magento_Ui/js/view/messages",
                                    "sortOrder": 0,
                                    "displayArea": "messages",
                                    "config": {
                                        "autoHideTimeOut": -1
                                     }
                                }
                            }
                        }
                    }
                }
            }
        }
    </script>
</div>
