<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$faceBookPixel = $this->helper('Digidirect\Digi\Helper\FaceBookPixel');
$googleAnalytic = $this->helper('Digidirect\Digi\Helper\GoogleAnalytics');
$googleConversion = $this->helper('Digidirect\Digi\Helper\GoogleConversion');
$orderBlock= $block->getLayout()->createBlock('Digidirect\ParticularAudienceAPI\Block\Order');
$order = $orderBlock->getOrderById($block->getOrderId());
$orderedItems = $order->getAllItems();
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<script>
    <?php
        foreach ($orderedItems as $item) { ?>
            console.log("refId", <?=$item->getProductId() ?>);
            console.log("quantity", <?=$item->getQuantityOrdered() ?>);
            console.log("price", <?=$item->getPrice() ?>);
    <?php }
?>
</script>
<div class="checkout-success">
    <?php if ($block->getOrderId()): ?>
        <?php if ($block->getShippingDetails() == "Pick Up in Store - Click and Collect Shipping"): ?>
            <span class="header"><?= /* @escapeNotVerified */__('YOUR CLICK & COLLECT HAS BEEN RECEIVED') ?></span>
            <span class="title"><?= /* @escapeNotVerified */__('Thank you for your purchase') ?></span>
            <?php if ($block->getCanViewOrder()) : ?>
                <span class="title -addition"><?= __('Your order no # %1', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></span>
            <?php else : ?>
                <span class="title -addition"><?= __('Your order # <span>%1</span>', $block->escapeHtml($block->getOrderId())) ?></span>
            <?php endif; ?>
            <div class="contentcontainer">
                <p class="importantnote"><?= /* @escapeNotVerified */__('IMPORTANT!') ?></p>
                <br/>
                <p class="content"><?= /* @escapeNotVerified */__('You will receive an order confirmation email with details of your order. Then you will receive a second email notifying you that your order is ready for pick-up.') ?></p>
                <br/>
                <p class="secondcontent"><?= /* @escapeNotVerified */__('NOTE: You must wait for the email notifying you that your order is ready for pick-up before making your way to your chosen Click & Collect location.') ?></p>

            </div>

        <?php else : ?>
            <span class="header"><?= /* @escapeNotVerified */__('Your order has been received') ?></span>
            <span class="title"><?= /* @escapeNotVerified */__('Thank you for your purchase') ?></span>
            <?php if ($block->getCanViewOrder()) : ?>
                <span class="title -addition"><?= __('Your order no # %1', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></span>
            <?php else : ?>
                <span class="title -addition"><?= __('Your order # <span>%1</span>', $block->escapeHtml($block->getOrderId())) ?></span>
            <?php endif; ?>
            <p class="content"><?= /* @escapeNotVerified */__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
        <?php endif; ?>

    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" title="Continue Shopping" href="<?= /* @escapeNotVerified */$block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */__('Continue Shopping') ?></span></a>
        </div>
    </div>
    <div class="init _hidden">
        <script>
            if (typeof fbq !== undefined) {
                fbq('trackCustom', 'Purchase', <?php echo $faceBookPixel->getPurchaseData() ?>);
            }
        </script>
    </div>
</div>
<!--comment out clint Jan 11 2024 -->
<!--<script>-->
<!--    ga('require', 'ecommerce');-->
<!---->
<!--    ga('ecommerce:addTransaction', --><?php //echo $googleAnalytic->getPurchaseData() ?>// );
//
//    ga('ecommerce:send');
//</script>
<!-- clint 10-20-23 -->
<!--<script>-->
<!--    dataLayer.push( --><?php //echo $googleConversion->getPurchaseData() ?>//);
</script>

<!--comment out clint Jan 11 2024 -->
<!-- FeedOps - Dynamic Remarketing - Version 2 START -->
<?php
//$order_id = $block->getRealOrderDetail()->getIncrementId();
//$total = $block->getRealOrderDetail()->getGrandTotal();
//$items = $block->getRealOrderDetail()->getAllVisibleItems();
//$email = $block->getRealOrderDetail()->getCustomerEmail();
//
//$shipaddress = $block->getRealOrderDetail()->getBillingAddress();
//$shipstrt = $shipaddress->getStreet();
//if(is_array($shipstrt))
//{
//    $shipstreet = implode(",", $shipstrt);
//
//}
//
//$firstname = $shipaddress->getFirstName();
//$lastname = $shipaddress->getLastName();
//
//$shipcity = $shipaddress->getCity();
//$shipregion = $shipaddress->getRegion();
//$shippostcode = $shipaddress->getPostcode();
//$shipcountrycode = $shipaddress->getCountryId();
//$shipphone = $shipaddress->getTelephone();
//
//$product_ids = array();
//foreach($items as $item) {
//    array_push($product_ids, $item->getProductId());
//}
//?>

<!--<script type="text/javascript">-->
<!--    dataLayer.push({-->
<!--        'event': 'DynamicRemarketing',-->
<!--        'user_email': --><?php //echo "\"$email\"" ?>//,
//        'user_phone': <?php //echo "\"$shipphone\"" ?>//,
//        'ecomm_pagetype': 'purchase',
//        'order_id': <?php //echo "\"$order_id\"" ?>//,
//        'ecomm_totalvalue': <?php //echo $total ?>//,
//        'currency': 'AUD',
//        'order_user_first_name': <?php //echo "\"$firstname\"" ?>//,
//        'order_user_last_name': <?php //echo "\"$lastname\"" ?>//,
//        'order_shipping_street': <?php //echo "\"$shipstreet\"" ?>//,
//        'order_shipping_city': <?php //echo "\"$shipcity\"" ?>//,
//        'order_shipping_region': <?php //echo "\"$shipregion\"" ?>//,
//        'order_shipping_postal_code': <?php //echo "\"$shippostcode\"" ?>//,
//        'order_shipping_country_code': <?php //echo "\"$shipcountrycode\"" ?>//,
//        'ecomm_prodid': <?php //echo json_encode($product_ids) ?>
//    });
//</script>
<!-- FeedOps - Dynamic Remarketing - Version 2 END -->
