<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $faceBookPixel = $this->helper('Digidirect\Digi\Helper\FaceBookPixel');
    $googleAnalytic = $this->helper('Digidirect\Digi\Helper\GoogleAnalytics');
    $googleConversion = $this->helper('Digidirect\Digi\Helper\GoogleConversion');
    $lastOrder = $block->getRealOrderDetail();
    $items = $lastOrder->getAllItems();
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<script>
    
    require(['jquery'], function ($) {

        function getCookie(name) {
            const value = `; ${document.cookie}`;
            const parts = value.split(`; ${name}=`);
            if (parts.length === 2) return parts.pop().split(';').shift();
        }

        var customerId = getCookie('PAC');
        var sessionId = getCookie('pa_session_id');
        var currentUrl = window.location.href;

        var configCustomerId;
        var configSessionId;

        configCustomerId = customerId;
        configSessionId = sessionId;

        var date = new Date();
        var now_utc = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(),
                date.getUTCDate(), date.getUTCHours(),
                date.getUTCMinutes(), date.getUTCSeconds());
        var products = [];
        
        <?php

            foreach ($items as $item) { ?>
                var productItem;

                var refId = <?= $item->getProductId(); ?>; 
                var quantity = <?= $item->getQtyOrdered(); ?>; 
                var price = <?= $item->getPrice(); ?>;

                productItem = {"refId": refId, "quantity": quantity, "price": price};
                products.push(productItem);
                
        <?php       
            }
        ?>

        var orderId = <?= $lastOrder->getIncrementId(); ?>;
        var paymentMethod = "<?= $lastOrder->getPayment()->getMethod(); ?>";

        const orderData = {
            customerId: configCustomerId,
            sessionId: configSessionId,
            events: [
                {
                    currentUrl: currentUrl,
                    eventTime: date.toISOString(),
                    products: products,
                    orderId: orderId,
                    paymentMethod: paymentMethod,
                    currencyCode: "AUD"
                }
            ]
        };

        console.log("orderData", JSON.stringify(orderData));
        
    });

</script>
<div class="checkout-success">
    <?php if ($block->getOrderId()): ?>
        <?php if ($block->getShippingDetails() == "Pick Up in Store - Click and Collect Shipping"): ?>
            <span class="header"><?= /* @escapeNotVerified */__('YOUR CLICK & COLLECT HAS BEEN RECEIVED') ?></span>
            <span class="title"><?= /* @escapeNotVerified */__('Thank you for your purchase') ?></span>
            <?php if ($block->getCanViewOrder()) : ?>
                <span class="title -addition"><?= __('Your order no # %1', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></span>
            <?php else : ?>
                <span class="title -addition"><?= __('Your order # <span>%1</span>', $block->escapeHtml($block->getOrderId())) ?></span>
            <?php endif; ?>
            <div class="contentcontainer">
                <p class="importantnote"><?= /* @escapeNotVerified */__('IMPORTANT!') ?></p>
                <br/>
                <p class="content"><?= /* @escapeNotVerified */__('You will receive an order confirmation email with details of your order. Then you will receive a second email notifying you that your order is ready for pick-up.') ?></p>
                <br/>
                <p class="secondcontent"><?= /* @escapeNotVerified */__('NOTE: You must wait for the email notifying you that your order is ready for pick-up before making your way to your chosen Click & Collect location.') ?></p>
            </div>
        <?php else : ?>
            <span class="header"><?= /* @escapeNotVerified */__('Your order has been received') ?></span>
            <span class="title"><?= /* @escapeNotVerified */__('Thank you for your purchase') ?></span>
            <?php if ($block->getCanViewOrder()) : ?>
                <span class="title -addition"><?= __('Your order no # %1', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></span>
            <?php else : ?>
                <span class="title -addition"><?= __('Your order # <span>%1</span>', $block->escapeHtml($block->getOrderId())) ?></span>
            <?php endif; ?>
            <p class="content"><?= /* @escapeNotVerified */__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
        <?php endif; ?>

    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" title="Continue Shopping" href="<?= /* @escapeNotVerified */$block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */__('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
