<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$faceBookPixel = $this->helper('Digidirect\Digi\Helper\FaceBookPixel');
$googleAnalytic = $this->helper('Digidirect\Digi\Helper\GoogleAnalytics');

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()): ?>
        <?php if ($block->getShippingDetails() == "Pick Up in Store - Click and Collect Shipping"): ?>
            <span class="header"><?= /* @escapeNotVerified */__('YOUR CLICK & COLLECT HAS BEEN RECEIVED') ?></span>
            <span class="title"><?= /* @escapeNotVerified */__('Thank you for your purchase') ?></span>
            <?php if ($block->getCanViewOrder()) : ?>
                <span class="title -addition"><?= __('Your order no # %1', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></span>
            <?php else : ?>
                <span class="title -addition"><?= __('Your order # <span>%1</span>', $block->escapeHtml($block->getOrderId())) ?></span>
            <?php endif; ?>
            <div class="contentcontainer">
                <p class="importantnote"><?= /* @escapeNotVerified */__('IMPORTANT!') ?></p>
                <br/>
                <p class="content"><?= /* @escapeNotVerified */__('You will receive an order confirmation email with details of your order. Then you will receive a second email notifying you that your order is ready for pick-up.') ?></p>
                <br/>
                <p class="secondcontent"><?= /* @escapeNotVerified */__('NOTE: You must wait for the email notifying you that your order is ready for pick-up before making your way to your chosen Click & Collect location.') ?></p>

            </div>

        <?php else : ?>
            <span class="header"><?= /* @escapeNotVerified */__('Your order has been received') ?></span>
            <span class="title"><?= /* @escapeNotVerified */__('Thank you for your purchase') ?></span>
            <?php if ($block->getCanViewOrder()) : ?>
                <span class="title -addition"><?= __('Your order no # %1', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></span>
            <?php else : ?>
                <span class="title -addition"><?= __('Your order # <span>%1</span>', $block->escapeHtml($block->getOrderId())) ?></span>
            <?php endif; ?>
            <p class="content"><?= /* @escapeNotVerified */__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
        <?php endif; ?>

    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" title="Continue Shopping" href="<?= /* @escapeNotVerified */$block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */__('Continue Shopping') ?></span></a>
        </div>
    </div>
<!--    <div class="init _hidden">
        <script>
            if (typeof fbq !== undefined) {
                fbq('trackCustom', 'Purchase', <?php echo $faceBookPixel->getPurchaseData() ?>);
            }
        </script>
    </div>-->
</div>

<script>
    ga('require', 'ecommerce');

    ga('ecommerce:addTransaction', <?php echo $googleAnalytic->getPurchaseData() ?> );

    ga('ecommerce:send');
</script>

<!-- FeedOps - Dynamic Remarketing - Version 1 START -->
<?php
    $order_id = $block->getOrderId();
    $total = $block->getGrandTotal();
    $items = $block->getAllVisibleItems();
    $email = $block->getCustomerEmail();
    
    $product_ids = array();
    foreach($items as $item) {
        array_push($product_ids, $item->getProductId());
    }
?>

<script>
    dataLayer.push({
        'event': 'DynamicRemarketing',
        'user_email': <?php echo $email ?>,
        'ecomm_pagetype': 'purchase',
        'order_id': <?php echo $order_id ?>,
        'ecomm_totalvalue': <?php echo $total ?>,
        'currency': 'AUD',
        'ecomm_prodid': <?php echo json_encode($product_ids) ?>
    });
</script>
<!-- FeedOps - Dynamic Remarketing - Version 1 END -->