<?php
// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="block newsletter">
    <form class="form subscribe"
        novalidate
        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
        id="newsletter-validate-detail">
        <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('For latest news &amp; updates')) ?></span></label>
        <div class="field newsletter">
            <div class="control">
                <input name="email" type="email" id="newsletter" class="input-text"
                       placeholder="<?= $block->escapeHtml(__('Your email')) ?>"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
            <div class="actions">
                <button class="action subscribe -color-type-3" title="<?= $block->escapeHtmlAttr(__('Sign Up')) ?>" type="submit">
                    <span><?= $block->escapeHtml(__('Sign Up')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
