
<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<?php
    // Init script for Lasoo Catalogue
?>
<script>
!function(a,b,c,d,e,f,g){var h=d+"publications/redpepper.min.js",
i=b.createElement(c),j=b.getElementsByTagName(c)[0],k=function(){
redpepper.init(d,"red-pepper-catalog",e,f,g)};i.async=1,
i.onload=k, i.src=h,j.parentNode.insertBefore(i,j)}
(window,document,"script","https://nexuspublications.com.au/",3711 );
</script>

<div id="red-pepper-catalog"> </div>
