<?php
/**
 * @var $block \Digidirect\Faq\Block\Question
 * @var $helper \Digidirect\Faq\Helper\Question
 */
$helper = $this->helper(\Digidirect\Faq\Helper\Question::class);
?>
<div class="faq-questions" data-role="question-container">
    <div class="form-box faq-block">
        <form data-role="question-form" class="form faq question question-form" action="<?php echo $block->escapeUrl($block->getFormAction()); ?>" id="faq-question-form" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Ask a Question') ?></span></legend><br />
                <div class="field question required">
                    <label class="label" for="question"><span><?php /* @escapeNotVerified */ echo __('If you did not find the answer to your question, please ask us here:') ?></span></label>
                    <div class="control">
                        <textarea name="question" id="question" title="<?php /* @escapeNotVerified */ echo __('If you did not find the answer to your question, please ask us here:') ?>" class="input-text -question" cols="5" rows="3" data-validate="{required:true}"><?php echo $block->escapeHtml($helper->getPostValue('question')) ?></textarea>
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="customer_email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                    <div class="control">
                        <input name="customer_email" id="customer_email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($helper->getPostValue('email') ?: $helper->getPostValue('email')) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="field name required">
                    <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
                    <div class="control">
                        <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($helper->getPostValue('name') ?: '') ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <?php echo $block->getChildHtml('faq.question.form.additional.info'); ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value="" />
                    <button data-role="question-submit" type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit Question') ?>" class="action submit -responsive">
                        <?php /* @escapeNotVerified */ echo __('Submit Question') ?>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
