<?php $_items = $this->getItems() ?>
<table class="email-items">
    <thead>
    <tr>
        <th class="item-image" style="width:70px;">&nbsp;</th>
        <th class="item-info" style="vertical-align: middle; !important; text-align: center;">
            <?= /* @escapeNotVerified */  __('Product'); ?>
        </th>
        <th class="item-qty" style="vertical-align: middle; !important; text-align: center;">
            <?= /* @escapeNotVerified */  __('Qty'); ?>
        </th>
        <th class="item-qty" style="vertical-align: middle; !important; text-align: center;">
            <?= /* @escapeNotVerified */  __('Each'); ?>
        </th>
        <th class="item-price" style="vertical-align: middle; !important; text-align: center;">
            <?= /* @escapeNotVerified */  __('Subtotal'); ?>
            <?= /* @escapeNotVerified */  __('(ex. GST)'); ?>
        </th>
        <th class="item-price" style="vertical-align: middle; !important; text-align: center;">
            <?= /* @escapeNotVerified */  __('GST'); ?>
            <?= /* @escapeNotVerified */  __('Amount'); ?>
        </th>
        <th class="item-price" style="vertical-align: middle; !important; text-align: center;">
            <?= /* @escapeNotVerified */  __('Total'); ?>
            <?= /* @escapeNotVerified */  __('(incl. GST)'); ?>
        </th>
    </tr>
    </thead>
    <tbody>
    <?php
    /** @var \Digidirect\InvoiceEmail\Helper\InvoiceEmail $helper */
    $helper = $this->helper(\Digidirect\InvoiceEmail\Helper\InvoiceEmail::class);
    $mediaBaseUrl = $helper->getMediaBaseUrl();
    $productRepository = $helper->getProductRepository();
    $totalAmount = 0;
    $currencySymbol = $helper->getCurrencySymbol();
    $gstRate = $helper->getGstRate();
    ?>
    <?php foreach ($_items as $_item): ?>
        <?php $_product = $productRepository->getById($_item->getProductId()); ?>
        <tr>
            <td class="item-image" style="vertical-align:top;padding:6px 8px;">
                <?php
                    $imagePath = '';
                    try {
                        $imagePath = $_product->getSmallImage();
                    } catch (\Throwable $e) {
                        $imagePath = '';
                    }
                    if ($imagePath && $imagePath !== 'no_selection') {
                        //$imgUrl = $thumbNail . $imagePath;
                        $imgUrl = $mediaBaseUrl . 'catalog/product' . $imagePath;
                    } else {
                        $imgUrl = $mediaBaseUrl . 'wysiwyg/no-product-image.png';
                    }
                ?>
                <img src="<?php echo $imgUrl ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" style="width:60px;height:auto;display:block;border:0;" />
            </td>
             <td>
                 <a href="<?php echo $this->getBaseUrl() . $_item->getProduct()->getUrlKey(); ?>">
                     <p class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></p>
                 </a>
                 <p class="sku">
                     <b><?php /* @escapeNotVerified */ echo  __('SKU') . ' : '  ?></b>
                     <a href="<?php echo $this->getBaseUrl() . $_item->getProduct()->getUrlKey(); ?>">
                         <?php echo $this->escapeHtml($_item->getSku()); ?>
                     </a>
                 </p>
             </td>
             <td class="item-qty" style="text-align: center;">
                 <span><?php echo floor($_item->getQtyOrdered()) ?></span> <!--qty-->
             </td>
             <td class="item-price" style="text-align: center;">
                 <span><?php echo $currencySymbol.round($_item->getPrice(), 2) ?></span> <!--each-->
             </td>
            <?php
                $itemPriceInclGst = $_item->getPrice();
                $itemPriceExclGst = $itemPriceInclGst * 100 / (100 + $gstRate);
                $gstPerItem = $itemPriceExclGst * $gstRate/100;
            ?>
            <td class="item-price" style="text-align: center;">
                <span><?php echo $currencySymbol.round($itemPriceExclGst * $_item->getQtyOrdered(), 2) ?></span> <!--subtotal excl GST-->
            </td>
            <td class="item-price" style="text-align: center;">
                <span><?php echo $currencySymbol.round($gstPerItem*$_item->getQtyOrdered(), 2) ?></span> <!--GST amount-->
            </td>
            <td class="item-price" style="text-align: center;">
                <span><?php echo $currencySymbol.round($itemPriceExclGst*$_item->getQtyOrdered(), 2) ?></span><!--total incl GST-->
            </td>
             <?php
             $tAmount = $_item->getQtyOrdered() * $_item->getPrice();
             $totalAmount += $tAmount;
             ?>
         </tr>
     <?php endforeach; ?>
         <tr style="display: none;">
             <td colspan="4" style="text-align: right;font-size: 16px;font-weight: bold;">
                 <span>Total: </span>
             </td>
             <td style="text-align: right;font-size: 16px;font-weight: bold;">
                <span><?php echo $currencySymbol.round($totalAmount, 2) ?></span>
             </td>
         </tr>
     </tbody>
 </table>
