<?php
/** @var \Ewave\ExtendedCatalogPriceRule\Block\ExtendedRule $block */

$product = $block->getParentBlock()->getProduct();
$productType = $product->getTypeId();
?>

<?php if ($product && $product->hasData('show_msg_extended_rule')) : ?>
    <?php foreach ($product->getData('show_msg_extended_rule') as $rule): ?>
        <?php $id = 'rule-' . $rule['rule_id'] . '-' . $product->getId();
            $priceClass = (!empty($rule['action_amount'])) ? '-cashback' : '';
        ?>

        <div class="block-extendedrule -plp <?= /* @noEscape */ $priceClass?>" id="<?= /* @noEscape */ $id ?>">
            <div class="name" data-mage-init='{"catalogPriceRuleModal": {"ruleId": "<?= /* @noEscape */ 'rule-' . $rule['rule_id']; ?>"}}'>
                <?php if(!empty($rule['plp_label'])): ?>
                    <?= $block->escapeHtml($rule['plp_label']); ?>
                <?php endif; ?>
            </div>

            <?php if(!empty($rule['action_amount']) && $rule['action_amount'] > 0): ?>
                <?php
                    $fromLabel = __('Before Cashback');
                    $afterLabel = __('After Cashback');
                    $beforeClass = 'before-cashback';
                    $afterClass = 'after-cashback';
                    $fromPrice = $product->getPrice();
                    $afterPrice = 0;
                    switch ($productType) {
                        case Magento\Catalog\Model\Product\Type::TYPE_BUNDLE:
                            $fromLabel = __('From');
                            $afterLabel = __('Cashback available');
                            $fromPrice = $product->getMinimalPrice();
                            $beforeClass = 'price-from';
                            $afterClass = 'price-to';
                            break;
                        default:
                            $afterPrice = $fromPrice - $rule['action_amount'];
                    }
                ?>
                <div class="price-box">
                    <div class="price-container">
                        <span class="<?= /* @escapeNotVerified */ $beforeClass; ?>">
                            <?php if ($fromLabel): ?>
                                <span class="price-label"><?= /* @noEscape */  $fromLabel; ?></span>
                            <?php endif; ?>
                            <?php if ($fromPrice): ?>
                                <span class="price-wrapper"><span class="price"><?= /* @noEscape */ $block->formatDiscountAmount($fromPrice); ?></span></span>
                            <?php endif; ?>
                        </span>
                        <span class="<?= /* @escapeNotVerified */ $afterClass; ?>">
                            <?php if ($afterLabel): ?>
                                <span class="price-label"><?= /* @noEscape */  $afterLabel; ?></span>
                            <?php endif; ?>
                            <?php if ($afterPrice): ?>
                                <span class="price-wrapper"><span class="price"><?= /* @noEscape */  $block->formatDiscountAmount($afterPrice); ?></span></span>
                            <?php endif; ?>
                        </span>
                    </div>
                </div>
            <?php endif; ?>

            <?php if(!empty($rule['pdp_description']) || !empty($rule['url_promotion'])): ?>
                <div class="details-extendedrule no-display" data-rule="<?= /* @noEscape */ 'rule-' . $rule['rule_id']; ?>">
                    <?php if(!empty($rule['pdp_description'])): ?>
                        <div class="description"><?=  /* @noEscape */ $rule['pdp_description']; ?></div>
                    <?php endif; ?>

                    <?php if(!empty($rule['url_promotion'])): ?>
                        <a class="link" href="<?= $block->escapeUrl($rule['url_promotion']); ?>" title="<?= /* @noEscape */ __('Promotion URL'); ?>">
                            <?= /* @noEscape */ __('Promotion URL'); ?>
                        </a>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
