<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Item\Price\Renderer */
?>
<?php 
    $_item = $block->getItem(); 
    $qty = $_item->getQty();   
?>
<div class="price-container">
    <span class="price-label"><?= $block->escapeHtml(__('Price')) ?></span>
    <span class="price-wrapper">
        <?= $block->escapeHtml(
            $this->helper(Magento\Checkout\Helper\Data::class)->formatPrice($_item->getCalculationPrice()),
            ['span']
        ) ?>
    </span>
    <span class="subtotal-label"><?= $block->escapeHtml(__('Sub Total')) ?></span>
    <span class="subtotal-wrapper">
        <?= $block->escapeHtml(
            $this->helper(Magento\Checkout\Helper\Data::class)->formatPrice($_item->getCalculationPrice() * $qty),
            ['span']
        ) ?>
    </span>
</div>

