<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\GiftCardAccount\Block\Checkout\Cart\Giftcardaccount $block
 * @see \Magento\GiftCardAccount\Block\Checkout\Cart\Giftcardaccount
 */
?>
<div class="block giftcard" id="block-giftcard">
    <div id="giftcard-balance-lookup"></div>
    <span id="gc-please-wait" class="please-wait load indicator" style="display: none;"
          data-text="<?= $block->escapeHtml(__('This won\'t take long . . .')) ?>">
        <span><?= $block->escapeHtml(__('This won\'t take long . . .')) ?></span>
    </span>
    <form class="form giftcard add" id="giftcard-form"
          action="<?= $block->escapeUrl($block->getUrl('magento_giftcardaccount/cart/add')) ?>" method="post"
          data-mage-init='{"validation": {},"giftCard": {
            "giftCardCodeSelector": "#giftcard-code",
            "giftCardFormSelector": "#giftcard-form",
            "checkStatus": ".action.check",
            "giftCardStatusUrl": "<?= $block->escapeHtml($block->getUrl('magento_giftcardaccount/cart/quickCheck',  ['_secure' => true])) ?>",
            "giftCardStatusId": "#giftcard-balance-lookup",
            "giftCardSpinnerId": "#gc-please-wait",
            "messages": ".page.messages .messages"
          }}'>
        <div class="fieldset">
            <div class="field">
                <label class="label" for="giftcard-code">
                    <span><?= $block->escapeHtml(__('Gift Card')) ?></span>
                </label>
                <div class="control">
                    <input class="input-text" type="text" id="giftcard-code" name="giftcard_code"
                           data-validate="{'required-entry':true}" value=""/>
                </div>
            </div>
            <div class="actions-toolbar">
                <div>
                    <button class="action add primary" type="submit" value="<?= $block->escapeHtml(__('Add Gift Card')) ?>">
                        <span><?= $block->escapeHtml(__('Apply')) ?></span>
                    </button>
                </div>
            </div>
        </div>
        <div class="fieldset">
            <?= $block->getChildHtml('captcha') ?>
        </div>
    </form>
</div>
