<nav data-action="navigation" class="footer-nav" id="footer_nav">
    <ul class="footer-menu footer-categories">
        <li class="category-item item">
            <span class="link">Support</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="#">FAQ</a></li>
                    <li><a class="link" title="" href="#">Shipping</a></li>
                    <li><a class="link" title="" href="#">Returns & Refunds</a></li>
                    <li><a class="link" title="" href="#">Terms & Conditions</a></li>
                    <li><a class="link" title="" href="#">Contact Us</a></li>
                    <li><a class="link" title="" href="#">Price Match</a></li>
                    <li><a class="link" title="" href="#">digiDirect Business</a></li>
                    <li><a class="link" title="" href="#">Become a digiDirect Seller</a></li>
                    <li><a class="link" title="" href="#">digiMarket Customer</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-top-brands">
        <li class="category-item">
            <span class="link">About</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="#">About digiDirect</a></li>
                    <li><a class="link" title="" href="#">Store Locations</a></li>
                    <li><a class="link" title="" href="#">Click & Collect</a></li>
                    <li><a class="link" title="" href="#">In-Store Pickup</a></li>
                    <li><a class="link" title="" href="#">Sustainability</a></li>
                    <li><a class="link" title="" href="#">Tourist Refund</a></li>
                    <li><a class="link" title="" href="#">digiClub</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-partners">
        <li class="category-item  item">
            <span class="link">More Services</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="#">digiPrint</a></li>
                    <li><a class="link" title="" href="#">PhotoKing Pro Lab</a></li>
                    <li><a class="link" title="" href="#">digiRent</a></li>
                    <li><a class="link" title="" href="#">digiProtect</a></li>
                    <li><a class="link" title="" href="#">Events</a></li>
                    <li><a class="link" title="" href="#">Passport Photos</a></li>
                    <li><a class="link" title="" href="#">Trade Up Program</a></li>
                    <li><a class="link" title="" href="#">Gift Card</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-service-info">
        <li class="category-item item">
            <span class="link">Popular Links</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="#">Photo Contest</a></li>
                    <li><a class="link" title="" href="#">Blog Article</a></li>
                    <li><a class="link" title="" href="#">Competitions</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-service-info">
        <li class="category-item item">
            <span class="link">Major Partner</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="#">zip</a></li>
                    <li><a class="link" title="" href="#">digiRent</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-service-info">
        <li class="category-item item">
            <span class="link">Social Media</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a target="_blank" class="link" title="" href="https://www.facebook.com/digiDirect/"><img src="<?= $block->getViewFileUrl('images/icons/iconsax-facebook.svg') ?>"/> Facebook</a></li>
                    <li><a target="_blank" class="link" title="" href="https://www.youtube.com/channel/UC2U81WY87pyzcYYdBHpWWlg"><img src="<?= $block->getViewFileUrl('images/icons/iconsax-youtube.svg') ?>"/> Youtube</a></li>
                    <li><a target="_blank" class="link" title="" href="https://www.instagram.com/digidirect/"><img src="<?= $block->getViewFileUrl('images/icons/iconsax-instagram.svg') ?>"/> Instagram</a></li>
                    <li><a target="_blank" class="link" title="" href="https://www.tiktok.com/@digidirect"><img src="<?= $block->getViewFileUrl('images/icons/tiktok.png') ?>" style="width: 24px;filter: invert(35%) sepia(0%) saturate(0%) hue-rotate(137deg) brightness(90%) contrast(87%);"/> Tiktok</a></li>
                    <li><a target="_blank" class="link" title="" href="https://au.linkedin.com/company/digidirectau"><img src="<?= $block->getViewFileUrl('images/icons/linkedin.png') ?>" style="width: 24px;filter: invert(35%) sepia(0%) saturate(0%) hue-rotate(137deg) brightness(90%) contrast(87%);"/> LinkedIn</a></li>
                </ul>
            </div>
        </li>
    </ul>
</nav>
