<?php
/** @var \Magento\Framework\View\Element\Template $block */
$viewModel = $block->getViewModel();
$isLoggedIn = $viewModel->isLoggedIn();
?>

<nav data-action="navigation" class="footer-nav" id="footer_nav">
    <ul class="footer-menu footer-categories">
        <li class="category-item item">
            <span class="link">Support</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="#">FAQ</a></li>
                    <li><a class="link" title="" href="#">Shipping</a></li>
                    <li><a class="link" title="" href="#">Returns & Refunds</a></li>
                    <li><a class="link" title="" href="#">Terms & Conditions</a></li>
                    <li><a class="link" title="" href="#">Contact Us</a></li>
                    <li><a class="link" title="" href="#">Price Match</a></li>
                    <li><a class="link" title="" href="#">digiDirect Business</a></li>
                    <li><a class="link" title="" href="#">Become a digiDirect Seller</a></li>
                    <li><a class="link" title="" href="#">digiMarket Customer</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-top-brands">
        <li class="category-item">
            <span class="link">About</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="#">About digiDirect</a></li>
                    <li><a class="link" title="" href="#">Store Locations</a></li>
                    <li><a class="link" title="" href="#">Click & Collect</a></li>
                    <li><a class="link" title="" href="#">In-Store Pickup</a></li>
                    <li><a class="link" title="" href="#">Sustainability</a></li>
                    <li><a class="link" title="" href="#">Tourist Refund</a></li>
                    <li><a class="link" title="" href="#">digiClub</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-partners">
        <li class="category-item  item">
            <span class="link">More Services</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="#">digi-print</a></li>
                    <li><a class="link" title="" href="#">PhotoKing Pro Lab</a></li>
                    <li><a class="link" title="" href="#">digiRent</a></li>
                    <li><a class="link" title="" href="#">digiProtect</a></li>
                    <li><a class="link" title="" href="#">Events</a></li>
                    <li><a class="link" title="" href="#">Passport Photos</a></li>
                    <li><a class="link" title="" href="#">Trade Up Program</a></li>
                    <li><a class="link" title="" href="#">Gift Card</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-service-info">
        <li class="category-item item">
            <span class="link">Popular Links</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="#">Photo Contest</a></li>
                    <li><a class="link" title="" href="#">Blog Article</a></li>
                    <li><a class="link" title="" href="#">Competitions</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-service-info">
        <li class="category-item item">
            <span class="link">Major Partners</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="#">Zip</a></li>
                    <li><a class="link" title="" href="#">digiRent</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-service-info social-media">
        <li class="category-item item">
            <span class="link">Social Media</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a target="_blank" class="link" title="" href="https://www.facebook.com/digiDirect/"><img src="<?= $block->getViewFileUrl('images/icons/iconsax-facebook.svg') ?>"/> <span>Facebook</span></a></li>
                    <li><a target="_blank" class="link" title="" href="https://www.youtube.com/channel/UC2U81WY87pyzcYYdBHpWWlg"><img src="<?= $block->getViewFileUrl('images/icons/iconsax-youtube.svg') ?>"/> <span>Youtube</span></a></li>
                    <li><a target="_blank" class="link" title="" href="https://www.instagram.com/digidirect/"><img src="<?= $block->getViewFileUrl('images/icons/iconsax-instagram.svg') ?>"/> <span>Instagram</span></a></li>
                    <li><a target="_blank" class="link" title="" href="https://www.tiktok.com/@digidirect"><img src="<?= $block->getViewFileUrl('images/icons/tiktok.png') ?>" style="width: 24px;filter: invert(35%) sepia(0%) saturate(0%) hue-rotate(137deg) brightness(90%) contrast(87%);"/> <span>Tiktok</span></a></li>
                    <li><a target="_blank" class="link" title="" href="https://au.linkedin.com/company/digidirectau"><img src="<?= $block->getViewFileUrl('images/icons/linkedin.png') ?>" style="width: 24px;filter: invert(35%) sepia(0%) saturate(0%) hue-rotate(137deg) brightness(90%) contrast(87%);"/> <span>LinkedIn</span></a></li>
                </ul>
            </div>
        </li>
    </ul>
</nav>

<nav class="mobile-footer-nav">
    <button onclick="window.location.href='<?php echo $block->getBaseUrl(); ?>'" class="footer-nav-item active">
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="23" viewBox="0 0 22 23" fill="none">
            <path d="M8.11729 3.17133L3.27044 6.94811C2.46113 7.57757 1.80469 8.91742 1.80469 9.93355V16.5969C1.80469 18.6831 3.50424 20.3916 5.59045 20.3916H16.0036C18.0898 20.3916 19.7893 18.6831 19.7893 16.6059V10.0594C19.7893 8.97138 19.0609 7.57757 18.1707 6.9571L12.6135 3.06343C11.3545 2.18218 9.33126 2.22714 8.11729 3.17133Z" stroke="white" stroke-width="1.34885" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M10.7969 16.7954V14.0977" stroke="white" stroke-width="1.34885" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <span class="nav-label">Home</span>
    </button>

    <button class="footer-nav-item footer-mobile-menu-icon" >
        <svg xmlns="http://www.w3.org/2000/svg" width="23" height="21" viewBox="0 0 23 21" fill="none">
            <line x1="4.12579" y1="4.25702" x2="18.5135" y2="4.25702" stroke="#545456" stroke-width="1.79846" stroke-linecap="round"/>
            <line x1="4.12579" y1="10.5539" x2="18.5135" y2="10.5539" stroke="#545456" stroke-width="1.79846" stroke-linecap="round"/>
            <line x1="4.12579" y1="16.8469" x2="18.5135" y2="16.8469" stroke="#545456" stroke-width="1.79846" stroke-linecap="round"/>
        </svg>
        <span class="nav-label">Menu</span>
    </button>

    <button class="footer-nav-item footer-search">
        <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 19 19" fill="none">
            <path d="M17.7799 17.5006L13.9583 13.6722M16.0761 8.55563C16.0761 10.4761 15.3132 12.3179 13.9552 13.6759C12.5972 15.0339 10.7554 15.7968 8.83493 15.7968C6.91445 15.7968 5.07263 15.0339 3.71464 13.6759C2.35666 12.3179 1.59375 10.4761 1.59375 8.55563C1.59375 6.63515 2.35666 4.79333 3.71464 3.43535C5.07263 2.07736 6.91445 1.31445 8.83493 1.31445C10.7554 1.31445 12.5972 2.07736 13.9552 3.43535C15.3132 4.79333 16.0761 6.63515 16.0761 8.55563Z" stroke="#545456" stroke-width="1.79846" stroke-linecap="round"/>
        </svg>
        <span class="nav-label">Search</span>
    </button>

    <button onclick="window.location.href='/#digiservices'" class="footer-nav-item">
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="21" viewBox="0 0 22 21" fill="none">
            <path d="M3.35156 6.7832L10.9061 10.9469L18.4093 6.80765" stroke="#545456" stroke-width="1.34885" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M10.9141 18.3318V10.9414" stroke="#545456" stroke-width="1.34885" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M9.13839 2.74175L4.56972 5.1536C3.5345 5.69952 2.6875 7.06841 2.6875 8.19286V12.7966C2.6875 13.921 3.5345 15.2899 4.56972 15.8358L9.13839 18.2558C10.1137 18.7692 11.7136 18.7692 12.6889 18.2558L17.2576 15.8358C18.2928 15.2899 19.1398 13.921 19.1398 12.7966V8.19286C19.1398 7.06841 18.2928 5.69952 17.2576 5.1536L12.6889 2.7336C11.7051 2.22026 10.1137 2.22026 9.13839 2.74175Z" stroke="#545456" stroke-width="1.34885" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <span class="nav-label">Services</span>
    </button>

    <button data-bind="scope: 'minicart_content'" class="footer-nav-item showcart">
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" viewBox="0 0 21 21" fill="none">
            <g clip-path="url(#clip0_7798_148413)">
                <mask id="mask0_7798_148413" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="0" y="0" width="21" height="21">
                    <path d="M20.0409 0.515625H0.257812V20.2987H20.0409V0.515625Z" fill="white"/>
                </mask>
                <g mask="url(#mask0_7798_148413)">
                    <path d="M15.2526 15.1478H6.47387C5.65782 15.1478 4.87474 14.8015 4.32246 14.1998C3.77018 13.5981 3.48993 12.7903 3.55588 11.9742L4.24004 3.76423C4.26477 3.5087 4.17409 3.26142 4.00099 3.07183C3.82788 2.88224 3.58885 2.78332 3.33332 2.78332H1.90728C1.56932 2.78332 1.28906 2.50306 1.28906 2.1651C1.28906 1.82714 1.56932 1.54688 1.90728 1.54688H3.34157C3.9433 1.54688 4.51205 1.80241 4.91596 2.23928C5.13851 2.48657 5.30338 2.77508 5.39405 3.09655H15.6895C16.522 3.09655 17.2886 3.42627 17.8492 4.01976C18.4014 4.6215 18.6817 5.40458 18.6158 6.23712L18.1706 12.4193C18.08 13.9278 16.7611 15.1478 15.2526 15.1478ZM5.43527 4.32475L4.79232 12.0731C4.7511 12.5512 4.90772 13.0046 5.2292 13.359C5.55067 13.7135 5.99578 13.9031 6.47387 13.9031H15.2526C16.1099 13.9031 16.8847 13.1777 16.9507 12.3204L17.3958 6.13821C17.4288 5.65188 17.2722 5.19027 16.9507 4.85231C16.6292 4.5061 16.1841 4.3165 15.6978 4.3165H5.43527V4.32475Z" fill="#545456"/>
                    <path d="M13.6486 19.2718C12.7419 19.2718 12 18.5299 12 17.6232C12 16.7165 12.7419 15.9746 13.6486 15.9746C14.5553 15.9746 15.2972 16.7165 15.2972 17.6232C15.2972 18.5299 14.5553 19.2718 13.6486 19.2718ZM13.6486 17.2111C13.4178 17.2111 13.2364 17.3924 13.2364 17.6232C13.2364 17.854 13.4178 18.0353 13.6486 18.0353C13.8794 18.0353 14.0607 17.854 14.0607 17.6232C14.0607 17.3924 13.8794 17.2111 13.6486 17.2111Z" fill="#545456"/>
                    <path d="M7.07047 19.2718C6.16374 19.2718 5.42188 18.5299 5.42188 17.6232C5.42188 16.7165 6.16374 15.9746 7.07047 15.9746C7.97719 15.9746 8.71906 16.7165 8.71906 17.6232C8.71906 18.5299 7.97719 19.2718 7.07047 19.2718ZM7.07047 17.2111C6.83966 17.2111 6.65832 17.3924 6.65832 17.6232C6.65832 17.854 6.83966 18.0353 7.07047 18.0353C7.30127 18.0353 7.48261 17.854 7.48261 17.6232C7.48261 17.3924 7.30127 17.2111 7.07047 17.2111Z" fill="#545456"/>
                    <path d="M17.5723 7.73058H7.68072C7.34276 7.73058 7.0625 7.45032 7.0625 7.11236C7.0625 6.7744 7.34276 6.49414 7.68072 6.49414H17.5723C17.9102 6.49414 18.1905 6.7744 18.1905 7.11236C18.1905 7.45032 17.9102 7.73058 17.5723 7.73058Z" fill="#545456"/>
                </g>
            </g>
            <defs>
                <clipPath id="clip0_7798_148413">
                    <rect width="19.7831" height="19.7831" fill="white" transform="translate(0.257812 0.515625)"/>
                </clipPath>
            </defs>
        </svg>
        <span class="nav-label">Cart</span>
    </button>

    <button class="footer-nav-item" <?php if ($isLoggedIn) echo 'id="open-account-popup"'; else echo 'onclick="window.location.href=\'' . $block->getUrl('customer/account') . '\'"'; ?>>
        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" viewBox="0 0 21 21" fill="none">
            <g clip-path="url(#clip0_7798_148425)">
                <mask id="mask0_7798_148425" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="0" y="0" width="21" height="21">
                    <path d="M20.5018 0.507812H0.71875V20.2909H20.5018V0.507812Z" fill="white"/>
                </mask>
                <g mask="url(#mask0_7798_148425)">
                    <path d="M10.6225 11.0224C8.00949 11.0224 5.88281 8.89568 5.88281 6.28267C5.88281 3.66965 8.00949 1.54297 10.6225 1.54297C13.2355 1.54297 15.3622 3.66965 15.3622 6.28267C15.3622 8.89568 13.2355 11.0224 10.6225 11.0224ZM10.6225 2.77941C8.69366 2.77941 7.11926 4.35382 7.11926 6.28267C7.11926 8.21152 8.69366 9.78592 10.6225 9.78592C12.5514 9.78592 14.1258 8.21152 14.1258 6.28267C14.1258 4.35382 12.5514 2.77941 10.6225 2.77941Z" fill="#545456"/>
                    <path d="M17.7093 19.2682C17.3713 19.2682 17.091 18.988 17.091 18.65C17.091 15.8062 14.1896 13.4982 10.6286 13.4982C7.06764 13.4982 4.16613 15.8062 4.16613 18.65C4.16613 18.988 3.88587 19.2682 3.54791 19.2682C3.20995 19.2682 2.92969 18.988 2.92969 18.65C2.92969 15.1303 6.38348 12.2617 10.6286 12.2617C14.8738 12.2617 18.3275 15.1303 18.3275 18.65C18.3275 18.988 18.0472 19.2682 17.7093 19.2682Z" fill="#545456"/>
                </g>
            </g>
            <defs>
                <clipPath id="clip0_7798_148425">
                    <rect width="19.7831" height="19.7831" fill="white" transform="translate(0.71875 0.513672)"/>
                </clipPath>
            </defs>
        </svg>
        <span class="nav-label">Account</span>
    </button>
</nav>

<!-- Account Popup Overlay -->
<div id="mobile-account-popup" class="account-popup">
    <div class="account-popup-header">
        <span class="signout">Sign Out</span>
        <button class="close-popup" aria-label="Close">&times;</button>
    </div>
    <ul class="account-menu">
        <div class="block-collapsible-nav navigation">
            <div class="content block-collapsible-nav-content active" id="block-collapsible-nav">
                <ul class="nav items">
                    <li class="nav item"><a href="<?= $block->getUrl('customer/account/')?>">Account</a></li>
                    <li class="nav item -icon -account"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('customer/account/edit/')?>">Profile</a></li>
                    <li class="nav item -icon -profile"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('customer/address/')?>">Address Book</a></li>
                    <li class="nav item -icon -address"><!-- li--></li>
                    <li class="nav item -icon -orders"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('review/customer/')?>">Product Reviews</a></li>
                    <li class="nav item -icon -reviews"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('wishlist/')?>">Wishlist</a></li>
                    <li class="nav item -icon -account-wishlist"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('sales/order/history/')?>">My Orders</a></li>
                    <li class="nav item"><a href="http://digistaging.dev.local/giftcard/customer/">Gift Card</a></li>
                    <li class="nav item -icon -account-gift"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('newsletter/manage')?>">Newsletter Subscription</a></li>
                    <li class="nav item -icon -newsletter"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('company/')?>">Company Structure</a></li>
                    <li class="nav item">
                        <span class="delimiter"></span>
                    </li>
                    <li class="nav item"><a href="<?= $block->getUrl('digiclubmember/customer/index/')?>" class="digiclub-icon">digiClub</a></li><li class="nav item -icon -digiclub"></li></ul>    </div>
        </div>

    </ul>
</div>
