<div class="footer-line">
    <div class="footer-top">
        <img src="<?= $block->getViewFileUrl('images/digi-footer-logo-darker.png') ?>" />
        <div class="footer-black-gradient-div"></div>
    </div>
    <div class="footer-bottom">
        <nav class="nav-extra">
            <ul class=" menu">
                <li class=" item -level1">
                    © digiDirect 2025. All Rights Reserved.<a class="" title="Privacy Policy" href="/privacy" id="fi-1-1"> Privacy Policy</a> | <a class="" title="Terms of Use" href="/terms-and-conditions" id="fi-1-2">Terms of Use</a>
                </li>
            </ul>
        </nav>
    </div>
</div>
