<?php
/** @var \Magento\Framework\View\Element\Template $block */
$viewModel = $block->getViewModel();
$quoteHelper = $helper = $this->helper('Digidirect\Digi\Helper\Quote');
$isCustomerLoggedIn = $quoteHelper->isCustomerLoggedIn();
?>

<nav data-action="navigation" class="footer-nav" id="footer_nav">
    <ul class="footer-menu footer-categories">
        <li class="category-item item">
            <span class="link">Support</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="/faqs">FAQ</a></li>
                    <li><a class="link" title="" href="/shipping-delivery">Shipping</a></li>
                    <li><a class="link" title="" href="/returns-and-refund">Returns & Refunds</a></li>
                    <li><a class="link" title="" href="/terms">Terms & Conditions</a></li>
                    <li><a class="link" title="" href="/contact">Contact Us</a></li>
                    <li><a class="link" title="" href="/price-match">Price Match</a></li>
                    <li><a class="link" title="" href="/b2b">digiDirect Business</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-top-brands">
        <li class="category-item">
            <span class="link">About</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="/about-us">About digiDirect</a></li>
                    <li><a class="link" title="" href="/store-locator-list">Store Locations</a></li>
                    <li><a class="link" title="" href="/click-and-collect">Click & Collect</a></li>
                    <li><a class="link" title="" href="/click-and-collect">In-Store Pickup</a></li>
                    <li><a class="link" title="" href="/sustainability">Sustainability</a></li>
                    <li><a class="link" title="" href="/tourist-refund-scheme">Tourist Refund</a></li>
                    <li><a class="link" title="" href="/digiclub">digiClub</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-partners">
        <li class="category-item  item">
            <span class="link">More Services</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="/digi-print">digiPrint</a></li>
                    <li><a class="link" title="" href="https://www.photoking.com/" target="_blank">PhotoKing Pro Lab</a></li>
                    <li><a class="link" title="" href="/digirent">digiRent</a></li>
                    <li><a class="link" title="" href="/digiprotect">digiProtect</a></li>
                    <li><a class="link" title="" href="/events">Events</a></li>
                    <li><a class="link" title="" href="/passport-photos">Passport Photos</a></li>
                    <li><a class="link" title="" href="/digiseconds-trade-up">Trade Up Program</a></li>
                    <li><a class="link" title="" href="https://digidirectgiftcards.viisolutions.com.au/" target="_blank">Gift Card</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-service-info">
        <li class="category-item item">
            <span class="link">Popular Links</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="/photocontest">Photo Contest</a></li>
<!--                    <li><a class="link" title="" href="/blog">Blog Article</a></li>-->
                    <li><a class="link" title="" href="/competitions">Competitions</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-service-info">
        <li class="category-item item">
            <span class="link">Major Partners</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="" href="/zip-money">Zip</a></li>
                    <li><a class="link" title="" href="/digirent">digiRent</a></li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="footer-menu footer-service-info social-media">
        <li class="category-item item">
            <span class="link">Social Media</span>
            <div class="sub-items">
                <ul class="menu">
                    <li><a target="_blank" class="link" title="" href="https://www.facebook.com/digiDirect/"><img src="<?= $block->getViewFileUrl('images/icons/iconsax-facebook.svg') ?>"/> <span>Facebook</span></a></li>
                    <li><a target="_blank" class="link" title="" href="https://www.youtube.com/channel/UC2U81WY87pyzcYYdBHpWWlg"><img src="<?= $block->getViewFileUrl('images/icons/iconsax-youtube.svg') ?>"/> <span>Youtube</span></a></li>
                    <li><a target="_blank" class="link" title="" href="https://www.instagram.com/digidirect/"><img src="<?= $block->getViewFileUrl('images/icons/iconsax-instagram.svg') ?>"/> <span>Instagram</span></a></li>
                    <li><a target="_blank" class="link" title="" href="https://www.tiktok.com/@digidirect"><img src="<?= $block->getViewFileUrl('images/icons/tiktok.png') ?>" style="width: 24px;filter: invert(35%) sepia(0%) saturate(0%) hue-rotate(137deg) brightness(90%) contrast(87%);"/> <span>Tiktok</span></a></li>
                    <li><a target="_blank" class="link" title="" href="https://au.linkedin.com/company/digidirectau"><img src="<?= $block->getViewFileUrl('images/icons/linkedin.png') ?>" style="width: 24px;filter: invert(35%) sepia(0%) saturate(0%) hue-rotate(137deg) brightness(90%) contrast(87%);"/> <span>LinkedIn</span></a></li>
                </ul>
            </div>
        </li>
    </ul>
</nav>

<nav class="mobile-footer-nav">
    <button onclick="window.location.href='<?php echo $block->getBaseUrl(); ?>'" class="footer-nav-item active">
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 22 22" fill="none">
            <path d="M8.10948 2.55415L3.26262 6.33092C2.45331 6.96038 1.79688 8.30024 1.79688 9.31637V15.9797C1.79688 18.0659 3.49642 19.7744 5.58264 19.7744H15.9957C18.082 19.7744 19.7815 18.0659 19.7815 15.9887V9.44226C19.7815 8.35419 19.0531 6.96038 18.1629 6.33991L12.6056 2.44624C11.3467 1.56499 9.32344 1.60995 8.10948 2.55415Z" stroke="#545456" stroke-width="1.34885" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M10.7891 16.1782V13.4805" stroke="#545456" stroke-width="1.34885" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <span class="nav-label">Home</span>
    </button>

    <button class="footer-nav-item footer-mobile-menu-icon" >
        <svg xmlns="http://www.w3.org/2000/svg" width="23" height="21" viewBox="0 0 23 21" fill="none">
            <line x1="4.12579" y1="4.25702" x2="18.5135" y2="4.25702" stroke="#545456" stroke-width="1.79846" stroke-linecap="round"/>
            <line x1="4.12579" y1="10.5539" x2="18.5135" y2="10.5539" stroke="#545456" stroke-width="1.79846" stroke-linecap="round"/>
            <line x1="4.12579" y1="16.8469" x2="18.5135" y2="16.8469" stroke="#545456" stroke-width="1.79846" stroke-linecap="round"/>
        </svg>
        <span class="nav-label">Menu</span>
    </button>

    <button class="footer-nav-item footer-search">
        <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 19 19" fill="none">
            <path d="M17.7799 17.5006L13.9583 13.6722M16.0761 8.55563C16.0761 10.4761 15.3132 12.3179 13.9552 13.6759C12.5972 15.0339 10.7554 15.7968 8.83493 15.7968C6.91445 15.7968 5.07263 15.0339 3.71464 13.6759C2.35666 12.3179 1.59375 10.4761 1.59375 8.55563C1.59375 6.63515 2.35666 4.79333 3.71464 3.43535C5.07263 2.07736 6.91445 1.31445 8.83493 1.31445C10.7554 1.31445 12.5972 2.07736 13.9552 3.43535C15.3132 4.79333 16.0761 6.63515 16.0761 8.55563Z" stroke="#545456" stroke-width="1.79846" stroke-linecap="round"/>
        </svg>
        <span class="nav-label">Search</span>
    </button>

    <button class="footer-nav-item" data-modal-trigger="digiSevicesModal">
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="21" viewBox="0 0 22 21" fill="none">
            <path d="M3.35156 6.7832L10.9061 10.9469L18.4093 6.80765" stroke="#545456" stroke-width="1.34885" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M10.9141 18.3318V10.9414" stroke="#545456" stroke-width="1.34885" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M9.13839 2.74175L4.56972 5.1536C3.5345 5.69952 2.6875 7.06841 2.6875 8.19286V12.7966C2.6875 13.921 3.5345 15.2899 4.56972 15.8358L9.13839 18.2558C10.1137 18.7692 11.7136 18.7692 12.6889 18.2558L17.2576 15.8358C18.2928 15.2899 19.1398 13.921 19.1398 12.7966V8.19286C19.1398 7.06841 18.2928 5.69952 17.2576 5.1536L12.6889 2.7336C11.7051 2.22026 10.1137 2.22026 9.13839 2.74175Z" stroke="#545456" stroke-width="1.34885" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <span class="nav-label">Services</span>
    </button>

    <button  class="footer-nav-item showcart-footer">
        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M1.64844 1.64844H3.08249C3.97259 1.64844 4.67313 2.41491 4.59896 3.29677L3.9149 11.5055C3.79951 12.8489 4.86268 14.0027 6.21432 14.0027H14.9917C16.1785 14.0027 17.2169 13.0302 17.3076 11.8516L17.7526 5.67038C17.8515 4.30226 16.8131 3.18963 15.4367 3.18963H4.79676" stroke="#545456" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M13.3896 18.1307C13.9586 18.1307 14.4198 17.6695 14.4198 17.1005C14.4198 16.5316 13.9586 16.0703 13.3896 16.0703C12.8206 16.0703 12.3594 16.5316 12.3594 17.1005C12.3594 17.6695 12.8206 18.1307 13.3896 18.1307Z" stroke="#545456" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M6.79583 18.1307C7.3648 18.1307 7.82604 17.6695 7.82604 17.1005C7.82604 16.5316 7.3648 16.0703 6.79583 16.0703C6.22686 16.0703 5.76562 16.5316 5.76562 17.1005C5.76562 17.6695 6.22686 18.1307 6.79583 18.1307Z" stroke="#545456" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M7.41406 6.59375H17.3041" stroke="#545456" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <span class="nav-label">Cart</span>
    </button>

    <button class="footer-nav-item" <?php if ($isCustomerLoggedIn) echo 'id="open-account-popup"'; else echo 'onclick="window.location.href=\'' . $block->getUrl('customer/account') . '\'"'; ?>>
        <svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M4.87083 8.99167C7.14671 8.99167 8.99167 7.14671 8.99167 4.87083C8.99167 2.59496 7.14671 0.75 4.87083 0.75C2.59496 0.75 0.75 2.59496 0.75 4.87083C0.75 7.14671 2.59496 8.99167 4.87083 8.99167Z" stroke="#545456" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <svg width="16" height="8" viewBox="0 0 16 8" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M14.9092 6.51917C14.9092 3.32964 11.7361 0.75 7.82959 0.75C3.92304 0.75 0.75 3.32964 0.75 6.51917" stroke="#545456" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>

        <span class="nav-label"><?php if ($isCustomerLoggedIn) echo 'Account'; else echo 'Login'; ?></span>
    </button>
</nav>

<!-- Account Popup Overlay -->
<div id="mobile-account-popup" class="account-popup">
<!--    <div class="account-popup-header">-->
<!--        <span class="signout">Sign Out</span>-->
<!--        <button class="close-popup" aria-label="Close">&times;</button>-->
<!--    </div>-->
    <div class="account-popup-header-in-pages">
        <span class="signout">Sign Out</span>
        <div class="close-popup">
            <img src="<?= $block->getViewFileUrl('images/mobile-menu-close.png') ?>">
        </div>
    </div>
    <ul class="account-menu">
        <div class="block-collapsible-nav navigation">
            <div class="content block-collapsible-nav-content active" id="block-collapsible-nav">
                <ul class="nav items">
                    <li class="nav item"><a href="<?= $block->getUrl('customer/account/')?>">Account</a></li>
                    <li class="nav item -icon -account"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('customer/account/edit/')?>">Profile</a></li>
                    <li class="nav item -icon -profile"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('customer/address/')?>">Address Book</a></li>
                    <li class="nav item -icon -address"><!-- li--></li>
                    <li class="nav item -icon -orders"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('review/customer/')?>">Product Reviews</a></li>
                    <li class="nav item -icon -reviews"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('wishlist/')?>">Wishlist</a></li>
                    <li class="nav item -icon -account-wishlist"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('sales/order/history/')?>">My Orders</a></li>
                    <li class="nav item"><a href="<?= $block->getUrl('giftcard/customer/')?>">Gift Card</a></li>
                    <li class="nav item -icon -account-gift"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('newsletter/manage')?>">Newsletter Subscription</a></li>
                    <li class="nav item -icon -newsletter"><!-- li--></li>
                    <li class="nav item"><a href="<?= $block->getUrl('company/')?>">Company Structure</a></li>
                    <li class="nav item">
                        <span class="delimiter"></span>
                    </li>
                    <li class="nav item"><a href="<?= $block->getUrl('digiclubmember/customer/index/')?>" class="digiclub-icon">digiClub</a></li><li class="nav item -icon -digiclub"></li></ul>    </div>
        </div>

    </ul>
</div>


<!-- Services Modal -->
<div class="service-mobile-modal" id="digiSevicesModal" data-modal="digiSevicesModal">
    <div class="mobile-modal-overlay" data-modal-close="digiSevicesModal"></div>
    <div class="mobile-modal-container">
        <div class="mobile-modal-header">
            <h2 class="mobile-modal-title">Services</h2>
            <button type="button"
                    class="mobile-services-close"
                    data-modal-close="digiSevicesModal"
                    aria-label="Close">
                <img src="<?= $block->getViewFileUrl('images/mobile-menu-close.png') ?>"/>
            </button>
        </div>
        <div class="mobile-modal-body">
            <div class="service-card">
                <?php
                $digiClubmediaUrl = $block->getUrl('media') . 'wysiwyg/glowup-digiservices/digiClub_footer_services.png';
                ?>
                <img src="<?php echo $digiClubmediaUrl; ?>" alt="Happy people taking a selfie" class="service-image">
                <div class="service-content">
                    <h2 class="service-title"><span class="digi">digi</span><span class="suffix">Club®</span></h2>
                    <p class="service-description">
                        Introducing digiClub, the brand new loyalty program from digiDirect that opens the door to an array of fantastic rewards.
                    </p>
                    <button class="cta-button" onclick="window.location.href='/digiClub'">Join Now</button>
                </div>
            </div>

            <div class="service-card">
                <?php
                $digiPrintbmediaUrl = $block->getUrl('media') . 'wysiwyg/glowup-digiservices/2_footer_services.png';
                ?>
                <img src="<?php echo $digiPrintbmediaUrl; ?>" alt="Color printing samples" class="service-image">
                <div class="service-content">
                    <h2 class="service-title"><span class="digi">digi</span><span class="suffix">Print</span></h2>
                    <p class="service-description">
                        digiDirect offers an easy to use online printing service which you can access through the digiPrint app or in-store kiosk.
                    </p>
                    <button class="cta-button" onclick="window.location.href='/digi-print'">Print Now</button>
                </div>
            </div>

            <div class="service-card">
                <?php
                $digi3mediaUrl = $block->getUrl('media') . 'wysiwyg/glowup-digiservices/3_footer_services.png';
                ?>
                <img src="<?php echo $digi3mediaUrl; ?>" alt="Professional camera lenses" class="service-image">
                <div class="service-content">
                    <h2 class="service-title"><span class="digi">digi</span><span class="suffix">Seconds</span></h2>
                    <p class="service-description">
                        Created to offer an excellent selection of secondhand products at incredible value for money, digiSeconds is the best destination for all your photo, video, and digital imaging needs.
                    </p>
                    <button class="cta-button" onclick="window.location.href='/digiseconds'">Shop Now</button>
                </div>
            </div>

            <div class="service-card">
                <?php
                $digi4bmediaUrl = $block->getUrl('media') . 'wysiwyg/glowup-digiservices/4_footer_services.png';
                ?>
                <img src="<?php echo $digi4bmediaUrl; ?>" alt="Professional camera lenses" class="service-image">
                <div class="service-content">
                    <h2 class="service-title"><span class="digi">digi</span><span class="suffix">Rent</span></h2>
                    <p class="service-description">
                        At digiDirect we believe that everyone should have the opportunity to follow their passion, find hidden talents and realise their full potential.
                    </p>
                    <button class="cta-button" onclick="window.location.href='/digirent'">Rent Now</button>
                </div>
            </div>

            <div class="service-card">
                <?php
                $digi5mediaUrl = $block->getUrl('media') . 'wysiwyg/glowup-digiservices/5_footer_services.png';
                ?>
                <img src="<?php echo $digi5mediaUrl; ?>" alt="Professional camera lenses" class="service-image">
                <div class="service-content">
                    <h2 class="service-title"><span class="digi">digi</span><span class="suffix">Deals</span></h2>
                    <p class="service-description">
                        Endless aisle of products & categories. Discover everything you need in one place. Shop with ease, anytime, anywhere.
                    </p>
                    <button class="cta-button" onclick="window.location.href='/deals'">Shop Now</button>
                </div>
            </div>

            <div class="service-card">
                <?php
                $digi6mediaUrl = $block->getUrl('media') . 'wysiwyg/glowup-digiservices/6_footer_services.png';
                ?>
                <img src="<?php echo $digi6mediaUrl; ?>" alt="Professional camera lenses" class="service-image">
                <div class="service-content">
                    <h2 class="service-title"><span class="digi">Price</span> <span class="suffix">Match</span></h2>
                    <p class="service-description">
                        digiDirect will price match Authorised Australian competitors which include both physical stores and online retailers.
                    </p>
                    <button class="cta-button" onclick="window.location.href='/price-match-guarantee'">Learn More</button>
                </div>
            </div>

            <div class="service-card">
                <?php
                $digi7mediaUrl = $block->getUrl('media') . 'wysiwyg/glowup-digiservices/7_footer_services.png';
                ?>
                <img src="<?php echo $digi7mediaUrl; ?>" alt="Professional camera lenses" class="service-image">
                <div class="service-content">
                    <h2 class="service-title"><span class="digi">Trade </span><span class="suffix">Up Program</span></h2>
                    <p class="service-description">
                        Are you looking to upgrade your tech equipment and take your creative skills to the next level? Look no further than digiDirect's
                        Trade-In Program! </p>
                    <button class="cta-button" onclick="window.location.href='/digiseconds-trade-up'">Learn More</button>
                </div>
            </div>

            <div class="service-card">
                <?php
                $digi8mediaUrl = $block->getUrl('media') . 'wysiwyg/glowup-digiservices/8_footer_services.png';
                ?>
                <img src="<?php echo $digi8mediaUrl; ?>" alt="Professional camera lenses" class="service-image">
                <div class="service-content">
                    <h2 class="service-title"><span class="digi">digi</span><span class="suffix">Direct Business</span></h2>
                    <p class="service-description">
                        Specially designed to meet each customer's needs as our team goes beyond a one-size-fits-all
                        approach.</p>
                    <button class="cta-button" onclick="window.location.href='/b2b'">Learn More</button>
                </div>
            </div>

            <div class="service-card">
                <?php
                $digi9mediaUrl = $block->getUrl('media') . 'wysiwyg/glowup-digiservices/9_footer_services.png';
                ?>
                <img src="<?php echo $digi9mediaUrl; ?>" alt="Professional camera lenses" class="service-image">
                <div class="service-content">
                    <h2 class="service-title"><span class="digi">digi</span><span class="suffix">Protect</span></h2>
                    <p class="service-description">
                        When you've spent hours researching products and significantly invested in a new camera or other equipment, you often plan for it to last a
                        long time.
                    </p>
                    <button class="cta-button" onclick="window.location.href='/digiprotect'">Learn More</button>
                </div>
            </div>

        </div>
    </div>
</div>
