<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

$isDigiClub = 0;

if ($customerSession->isLoggedIn()) {
    $customerGroupId = $customerSession->getCustomer()->getGroupId();
    if ($customerGroupId == 10) {
        $isDigiClub = 1;
    }
}
?>

<div id="header-mobile-menu-only">
    <div class="top-header-wrapper">
        <div class="panel wrapper">
            <div class="panel header">
                <div class="header-links header-link-left" style="margin-left: 50px;">
                    <a class="free-delivery-link" href="/free-shipping" title="Free Shipping Over $99"><i class="fas fa-box"></i> Free Shipping Over $99</a>
                    <a class="next-day-shipping-link" href="/free-shipping" title="Express Next Day Shipping" style="display: none;"><i class="fas fa-shipping-fast"></i> Express Next Day Shipping</a>
                    <a class="click-and-collect-link" href="/pickup-instore" title="Click & Collect"><i class="fas fa-hand-point-up"></i> Click & Collect</a>
                    <a class="store-locator-link" href="/store-locator" title="Store Locator"><i class="fas fa-map-marker-alt"></i> Store Locator</a>
                    <a class="faq-link" href="/faq" title="FAQ"><i class="fas fa-question-circle"></i> Questions?</a>
                    <a class="call-us-link" href="tel:1300 889 148" title="call-us"><i class="fas fa-headset"></i> CALL US <span class="company-number">1300 889 148</span></a>
                    <a class="gift-cards-link" href="https://digidirectgiftcards.viisolutions.com.au/" title="GIFT CARDS"><i class="fas fa-gift"></i> GIFT CARDS</a>
                    <a class="digiservices-link" href="/#digiservices" title="digiServices"><i class="fas fa-film"></i></i> SERVICES</a>
                </div>
                <div class="header-links header-link-right" style="position: absolute; right: 0; margin-right: 50px;">
                    <div class="header-links-account">
                        <a class="digiclub-link" href="/digiclub" title="digiClub">digiClub</a>
                        <?php
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $customerSession = $objectManager->get('Magento\Customer\Block\Account\AuthorizationLink');

                        if ($customerSession->isLoggedIn() == true) { ?>
                            <a class="register-link" href="/customer/account" title="Account">My Account</a>
                            <a class="login-link" href="/customer/account/logout" title="Logout">Logout</a>
                        <?php } else { ?>
                            <a class="register-link" href="/customer/account/create" title="Register">Register</a>
                            <a class="login-link" href="/customer/account/login" title="Login">Login</a>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <span id="mobile-menu-only-header">
    <i class="fas fa-times mobile-menu-main-exit"></i>
    <a class="digi-link" href="https://www.digidirect.com.au/">
        <img id="digi-white-logo" src="https://www.digidirect.com.au/media/wysiwyg/logo.svg">
    </a>
    <span id="menu-mobile-span-signin">
        <a class="mobile-menu-signin" href="/customer/account" title="Account"><i class="fas fa-user"></i></a>
        <a id="mobile-menu-minicart" class="mobile-menu-minicart" href="#" title="Cart"><i class="fas fa-shopping-bag"></i></a>
    </span>
  </span>

    <div class="block block-search"><div class="block block-content"><form class="form minisearch" id="search_mini_form" action="https://www.digidirect.com.au/find" method="get"><div class="field search"><label class="label" for="search" data-role="minisearch-label"><svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -search"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-search" fill="white"></use></svg><span>Search</span></label> <div class="control"><input id="search" type="text" name="q" value="" placeholder="Search our store" class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off"><!-- <div id="search_autocomplete" class="search-autocomplete"></div>--></div></div><div class="actions"><button type="submit" title="Search" class="action search"><i class="fas fa-search" style="font-size: 21px; color: #fff; padding: 5px 12px 0 0;"></i></button></div></form></div></div>

</div>

<div class="navbar">
    <div class="navbar-content">

        <div id="submenu-shopbycategory" class="item-submenu submenu-active" onclick="checkActiveMenuItem(event, 'submenu-shopbycategory')">
            <div class="shop-by-category-menu">
                <div class="dropdown category-tabs">
                    <button class="dropbtn"><i class="fas fa-list"></i> SHOP BY CATEGORY <i class="fas fa-angle-down"></i></button>
                    <i class="fas fa-angle-right"></i>
                    <div class="dropdown-content mgz-tabs mgz-element-tab-align-left mgz-element-tab-position-left" onclick="event.stopPropagation()" onmouseleave="resetMenu()">

                        <div class="shop-by-category-tabs">
                            <div id="shop-by-category-tabs" class="mgz-tabs-nav">

                                <div id="cameras-tab-menu" class="mgz-tabs-tab-title cameras-tab-menu" onclick="openSecondLevel(event, 'second-level-cameras', 'top-brands-cameras', 'cameras-tab-menu')">
                                    <a><span class="first-menu-tab-title">Cameras</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="lenses-tab-menu" class="mgz-tabs-tab-title lenses-tab-menu" onclick="openSecondLevel(event, 'second-level-lenses', 'top-brands-lenses', 'lenses-tab-menu')">
                                    <a><span class="first-menu-tab-title">Lenses</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="lightstudio-tab-menu" class="mgz-tabs-tab-title lightstudio-tab-menu" onclick="openSecondLevel(event, 'second-level-lightstudio', 'top-brands-lightingandstudio', 'lightstudio-tab-menu')">
                                    <a><span class="first-menu-tab-title">Lighting &amp; Studio</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="photoacce-tab-menu" class="mgz-tabs-tab-title photoacce-tab-menu" onclick="openSecondLevel(event, 'second-level-photoacce', 'top-brands-photoaccessories', 'photoacce-tab-menu')">
                                    <a><span class="first-menu-tab-title">Photo Accessories</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="optics-tab-menu" class="mgz-tabs-tab-title optics-tab-menu" onclick="openSecondLevel(event, 'second-level-optics', 'top-brands-optics', 'optics-tab-menu')">
                                    <a><span class="first-menu-tab-title">Optics</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="audiovisual-tab-menu" class="mgz-tabs-tab-title audiovisual-tab-menu" onclick="openSecondLevel(event, 'second-level-audiovisual', 'top-brands-audiovisual', 'audiovisual-tab-menu')">
                                    <a><span class="first-menu-tab-title">Audio &amp; Visual</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="provideo-tab-menu" class="mgz-tabs-tab-title provideo-tab-menu" onclick="openSecondLevel(event, 'second-level-provideo', 'top-brands-provideo', 'provideo-tab-menu')">
                                    <a><span class="first-menu-tab-title">Pro Video</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="smarthome-tab-menu" class="mgz-tabs-tab-title smarthome-tab-menu" onclick="openSecondLevel(event, 'second-level-smarthome', 'top-brands-smarthome', 'smarthome-tab-menu')">
                                    <a><span class="first-menu-tab-title">Smart Home</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="computersmobile-tab-menu" class="mgz-tabs-tab-title computersmobile-tab-menu" onclick="openSecondLevel(event, 'second-level-computersmobile', 'top-brands-computersandmobile', 'computersmobile-tab-menu')">
                                    <a><span class="first-menu-tab-title">Computers &amp; Mobile</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="drones-tab-menu" class="mgz-tabs-tab-title drones-tab-menu" onclick="openSecondLevel(event, 'second-level-drones', 'top-brands-drones', 'drones-tab-menu')">
                                    <a><span class="first-menu-tab-title">Drones</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="electronic-tab-menu" class="mgz-tabs-tab-title electronic-tab-menu" onclick="openSecondLevel(event, 'second-level-electronic', 'top-brands-electronic', 'electronic-tab-menu')">
                                    <a><span class="first-menu-tab-title">Electronic Toys</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="home-tab-menu" class="mgz-tabs-tab-title home-tab-menu" onclick="openSecondLevel(event, 'second-level-home', 'top-brands-home', 'home-tab-menu')">
                                    <a><span class="first-menu-tab-title">Home</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="collectibles-tab-menu" class="mgz-tabs-tab-title">
                                    <a href="https://www.digidirect.com.au/collectables-merchandise-digital" style="display:flex;background:none;border:none;">
                                        <img src="https://www.digidirect.com.au/media/wysiwyg/main-menu/icons/collectibles.png" style="width: 30px; display: none;">
                                        <span>Collectibles & Merchandise Digital</span>
                                    </a>
                                    <i class="fas mgz-fa-angle-right" style="position: absolute;top: 10px;"></i>
                                </div>

                                <div id="fitness-tab-menu" class="mgz-tabs-tab-title fitness-tab-menu" onclick="openSecondLevel(event, 'second-level-fitness', 'top-brands-fitness', 'fitness-tab-menu')">
                                    <a><span class="first-menu-tab-title">Fitness & Well-being Tech</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="seasonal-tab-menu" class="mgz-tabs-tab-title seasonal-tab-menu" onclick="openSecondLevel(event, 'second-level-seasonal', 'top-brands-seasonal', 'seasonal-tab-menu')">
                                    <a><span class="first-menu-tab-title">Seasonal Tech</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="music-tab-menu" class="mgz-tabs-tab-title music-tab-menu" onclick="openSecondLevel(event, 'second-level-music', 'top-brands-music', 'music-tab-menu')">
                                    <a><span class="first-menu-tab-title">Music Instruments</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="sbc-giftcards" class="mgz-tabs-tab-title">
                                    <a href="https://digidirectgiftcards.viisolutions.com.au/" style="display:flex;background:none;border:none;">
                                        <img src="https://www.digidirect.com.au/media/wysiwyg/main-menu/icons/gift-card.png" style="width: 30px; display: none;">
                                        <span>Gift Cards</span>
                                    </a>
                                    <i class="fas mgz-fa-angle-right" style="position: absolute;top: 10px;"></i>
                                </div>

                            </div>

                            <div id="second-level-menu" class="mgz-tabs-content slide-left-to-right">

                                <div id="return-to-first-level" onclick="returnToFirstLevel()"><i class="fas fa-angle-left" style="margin-right: 10px"></i>Previous</div>

                                <div id="second-level-cameras" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Cameras</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'dslr-cameras')">DSLR Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'mirrorless-cameras')">Mirrorless Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'action-cameras')">Action Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'compact-cameras')">Compact Cameras</button>
                                            </div>

                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Cameras</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'film-cameras')">Film Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'medium-format-cameras')">Medium Format Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'instant-cameras')">Instant Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'specialty-cameras')">Specialty Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'rangefinder-cameras')">Rangefinder Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'waterproof-cameras')">Waterproof Cameras</button>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-lenses" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">
                                            <h3>Lenses</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'slr-lenses')">SLR Lenses</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'mirrorless-lenses')">Mirrorless Lenses</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'rangefinder-lenses')">Rangefinder Lenses</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'digital-cine-lenses')">Digital Cine Lenses</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Lenses</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'medium-format-lenses')">Medium Format Lenses</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'special-effect-lenses')">Special Effect Lenses</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'lense-filter')">Lens Filter</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'lens-accessories')">Lens Accessories</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-lightstudio" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Lighting & Studio</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'camera-flashes')">Camera Flashes</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'monolights-and-strobes')">Monolights & Strobes</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'continuous-lights')">Continuous Lights</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'light-modifiers-and-reflectors')">Light Modifiers & Reflectors</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Lighting & Studio</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'radio-and-optical-slaves')">Radio & Optical Slaves</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'flash-accessories')">Flash Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'on-camera-lighting')">On Camera Lighting</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'backgrounds-and-supports')">Backgrounds & Supports</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-photoacce" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Photo Accessories</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'tripods-and-stabilizers')">Tripods & Stabilizers</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'bags-and-cases')">Bags & Cases</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'memory-cards-and-drives')">Memory Cards & Drives</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Photo Accessories</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'camera-system-accessories')">Camera System Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'batteries-and-power-supplies')">Batteries & Power Supplies</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'printers-and-scanners')">Printers & Scanners</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'albums-and-frames')">Albums & Frames</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'film-darkroom-and-video-tapes')">Film Darkroom & Video Tapes</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'usb-cables-and-adapters')">USB Cables & Adapters</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'travel-accessories')">Travel Accessories</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-optics" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Optics</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'binoculars-and-accessories')">Binoculars & Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'spotting-scopes-and-accessories')">Spotting Scopes & Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'laser-rangefinders')">Laser Rangefinders</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'monoculars')">Monoculars</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Optics</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'telescopes')">Telescopes</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-audiovisual" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Audio & Visual</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'microphones')">Microphones</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'audio-recorders')">Audio Recorders</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'headphones')">Headphones</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'cables')">Cables</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Audio & Visual</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'projection-screens')">Projection Screens</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'speakers')">Speakers</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'audio-interfaces-and-mixers')">Audio Interface & Mixers</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'software')">Software</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'monitors')">Monitors</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'drawing-tablets')">Drawing Tablets</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-provideo" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Pro Video</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'pro-video-cameras')">Pro Video Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'video-monitors-and-recorders')">Video Monitors & Recorders</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'white-balance-and-calibration')">White Balance & Calibration</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'video-rigs')">Video Rigs</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Pro Video</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'live-streaming')">Live Streaming</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'tools-and-consumables')">Tools & Consumables</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-smarthome" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Smart Home</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'security-cameras')">Security Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'home-automation')">Home Automation</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'small-appliances')">Small Appliances</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'health-fitness-and-wearables')">Health Fitness & Wearables</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Smart Home</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'lighting')">Lighting</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'lifestyle-gadgets')">Lifestyle Gadgets</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-computersmobile" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Computers & Mobile</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'laptops-and-notebooks')">Laptops & Notebooks</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'mobile-phones-and-accessories')">Mobile Phones & Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'gaming')">Gaming</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'tablets-ipads-and-surface')">Tablets IPads & Surface</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'printers-and-scanners2')">Printers & Scanners</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'monitors-and-accessories')">Monitors & Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'desktop-and-parts')">Desktop & Parts</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Computers & Mobile</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'computer-accessories')">Computer Accessories</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-drones" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Drones</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'drones-uav')">Drones UAV</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'drone-cameras')">Drone Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'drone-gimbals')">Drone Gimbals</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'drone-accessories')">Drone Accessories</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Drones</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'underwater-rovs')">Underwater ROVs</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'robotics')">Robotics</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-electronic" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Electronic Toys</h3>

                                            <div class="tab">
                                                <a class="tablinks" href="https://www.digidirect.com.au/electronic-toys/rc-toys">RC Toys</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/electronic-toys/toys-ride-on">Toys Ride-On</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/electronic-toys/electronic">Electronic</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-home" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Home</h3>

                                            <div class="tab">
                                                <a class="tablinks" href="https://www.digidirect.com.au/home-category/homeware">Homeware</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/home-category/small-appliances">Small Appliances</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-fitness" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Fitness & Well-being Tech</h3>

                                            <div class="tab">
                                                <a class="tablinks" href="https://www.digidirect.com.au/fitness-wellbeing-tech/baby">Baby</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/fitness-wellbeing-tech/wearables">Wearables</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-seasonal" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Seasonal Tech</h3>

                                            <div class="tab">
                                                <a class="tablinks" href="https://www.digidirect.com.au/seasonal-tech/christmas">Christmas</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-music" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Music Instruments</h3>

                                            <div class="tab">
                                                <a class="tablinks" href="https://www.digidirect.com.au/music-intruments/music-drums">Music - Drums</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </div>

                            <div id="third-level-menu" class="slide-left-to-right">
                                <div class="menu-third-level">
                                    <span class="return-to-second-layer" onclick="returnToSecondLayer();"><i class="fas fa-angle-left"></i><h3>Previous</h3></span>

                                    <div id="dslr-cameras" class="tabcontent">
                                        <h3>DSLR Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/cameras/cameras-dslr-cameras">View All DSLR Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/cameras/cameras-dslr-cameras/canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/cameras/cameras-dslr-cameras/nikon">Nikon</a>
                                        </div>

                                    </div>

                                    <div id="mirrorless-cameras" class="tabcontent">
                                        <h3>Mirrorless Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/cameras/mirrorless-cameras">View All Mirrorless Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/cameras/mirrorless-cameras/sony">Sony</a>
                                            <a class href="https://www.digidirect.com.au/cameras/mirrorless-cameras/sigma">Sigma</a>
                                            <a class href="https://www.digidirect.com.au/cameras/mirrorless-cameras/canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/cameras/mirrorless-cameras/fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/cameras/mirrorless-cameras/leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/cameras/mirrorless-cameras/nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/cameras/mirrorless-cameras/olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/cameras/mirrorless-cameras/panasonic">Panasonic</a>
                                        </div>

                                    </div>

                                    <div id="action-cameras" class="tabcontent">
                                        <h3>Action Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/cameras/action-cameras">View All Action Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/cameras/action-cameras/dji">DJI</a>
                                            <a class href="https://www.digidirect.com.au/cameras/action-cameras/gopro">GoPro</a>
                                            <a class href="https://www.digidirect.com.au/cameras/action-cameras/insta360">Insta360</a>
                                        </div>

                                    </div>

                                    <div id="compact-cameras" class="tabcontent">
                                        <h3>Compact Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/cameras/compact-cameras">View All Compact Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/cameras/compact-cameras/sony">Sony</a>
                                            <a class href="https://www.digidirect.com.au/cameras/compact-cameras/panasonic">Panasonic</a>
                                            <a class href="https://www.digidirect.com.au/cameras/compact-cameras/canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/cameras/compact-cameras/leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/cameras/compact-cameras/nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/cameras/compact-cameras/olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/cameras/compact-cameras/ricoh">Ricoh</a>
                                            <a class href="https://www.digidirect.com.au/cameras/compact-cameras/fujifilm">Fujifilm</a>
                                        </div>

                                    </div>


                                    <div id="film-cameras" class="tabcontent">
                                        <h3>Film Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/cameras/film-cameras">View All Film Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/cameras/film-cameras/lomography">LOMOGRAPHY</a>
                                            <a class href="https://www.digidirect.com.au/cameras/film-cameras/ilford">ILFORD</a>
                                            <a class href="https://www.digidirect.com.au/cameras/film-cameras/kodak">Kodak</a>
                                            <a class href="https://www.digidirect.com.au/cameras/film-cameras/leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/cameras/film-cameras/polaroid">Polaroid</a>
                                        </div>

                                    </div>

                                    <div id="medium-format-cameras" class="tabcontent">
                                        <h3>Medium Format Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/cameras/medium-format-cameras">View All Medium Format Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/cameras/medium-format-cameras/fujifilm">Fujifilm</a>
                                        </div>

                                    </div>

                                    <div id="instant-cameras" class="tabcontent">
                                        <h3>Instant Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/cameras/instant-cameras">View All Instant Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/cameras/instant-cameras/fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/cameras/instant-cameras/lomography">LOMOGRAPHY</a>
                                            <a class href="https://www.digidirect.com.au/cameras/instant-cameras/polaroid">Polaroid</a>
                                            <a class href="https://www.digidirect.com.au/cameras/instant-cameras/kodak">Kodak</a>
                                        </div>

                                    </div>

                                    <div id="specialty-cameras" class="tabcontent">
                                        <h3>Specialty Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/cameras/specialty-cameras">View All Specialty Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/cameras/specialty-cameras/insta360">Insta360</a>
                                            <a class href="https://www.digidirect.com.au/cameras/specialty-cameras/gerber">Gerber</a>
                                            <a class href="https://www.digidirect.com.au/cameras/specialty-cameras/boly">Boly</a>
                                            <a class href="https://www.digidirect.com.au/cameras/specialty-cameras/bushnell">Bushnell</a>
                                            <a class href="https://www.digidirect.com.au/cameras/specialty-cameras/minox">Minox</a>
                                            <a class href="https://www.digidirect.com.au/cameras/specialty-cameras/stealth-cam">Stealth Cam</a>
                                            <a class href="https://www.digidirect.com.au/cameras/specialty-cameras/sionyx">SiOnyx</a>
                                            <a class href="https://www.digidirect.com.au/cameras/specialty-cameras/leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/cameras/specialty-cameras/ricoh">Ricoh</a>
                                        </div>

                                    </div>

                                    <div id="rangefinder-cameras" class="tabcontent">
                                        <h3>Rangefinder Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/cameras/rangefinder-cameras">View All Rangefinder Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/cameras/rangefinder-cameras/leica">Leica</a>
                                        </div>

                                    </div>

                                    <div id="waterproof-cameras" class="tabcontent">
                                        <h3>Waterproof Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/cameras/waterproof-cameras">View All Waterproof Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/cameras/waterproof-cameras/olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/cameras/waterproof-cameras/gopro">GoPro</a>
                                        </div>

                                    </div>


                                    <div id="slr-lenses" class="tabcontent">
                                        <h3>SLR Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/lenses/slr-lenses">View All SLR Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lenses/slr-lenses/nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/lenses/slr-lenses/sigma">Sigma</a>
                                            <a class href="https://www.digidirect.com.au/lenses/slr-lenses/samyang">SAMYANG</a>
                                            <a class href="https://www.digidirect.com.au/lenses/slr-lenses/canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/lenses/slr-lenses/zeiss">Zeiss</a>
                                            <a class href="https://www.digidirect.com.au/lenses/slr-lenses/laowa">Laowa</a>
                                            <a class href="https://www.digidirect.com.au/lenses/slr-lenses/tamron">Tamron</a>
                                            <a class href="https://www.digidirect.com.au/lenses/slr-lenses/tokina">Tokina</a>
                                            <a class href="https://www.digidirect.com.au/lenses/slr-lenses/lensbaby">LensBaby</a>
                                        </div>

                                    </div>

                                    <div id="mirrorless-lenses" class="tabcontent">
                                        <h3>Mirrorless Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses">View All Mirrorless Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/sony">Sony</a>
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/laowa">Laowa</a>
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/lensbaby">LensBaby</a>
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/samyang">SAMYANG</a>
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/panasonic">Panasonic</a>
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/sigma">Sigma</a>
                                            <a class href="https://www.digidirect.com.au/lenses/mirrorless-lenses/zeiss">Zeiss</a>
                                        </div>

                                    </div>

                                    <div id="rangefinder-lenses" class="tabcontent">
                                        <h3>Rangefinder Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/lenses/rangefinder-lenses">View All Rangefinder Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lenses/rangefinder-lenses/laowa">Laowa</a>
                                            <a class href="https://www.digidirect.com.au/lenses/rangefinder-lenses/leica">Leica</a>
                                        </div>

                                    </div>

                                    <div id="digital-cine-lenses" class="tabcontent">
                                        <h3>Digital Cine Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/lenses/digital-cine-lenses">View All Digital Cine Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lenses/digital-cine-lenses/samyang">SAMYANG</a>
                                            <a class href="https://www.digidirect.com.au/lenses/digital-cine-lenses/slr-magic">SLR Magic</a>
                                            <a class href="https://www.digidirect.com.au/lenses/digital-cine-lenses/tokina">Tokina</a>
                                            <a class href="https://www.digidirect.com.au/lenses/digital-cine-lenses/laowa">Laowa</a>
                                            <a class href="https://www.digidirect.com.au/lenses/digital-cine-lenses/sigma">Sigma</a>
                                            <a class href="https://www.digidirect.com.au/lenses/digital-cine-lenses/canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/lenses/digital-cine-lenses/fujifilm">Fujifilm</a>
                                        </div>

                                    </div>


                                    <div id="medium-format-lenses" class="tabcontent">
                                        <h3>Medium Format Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/lenses/medium-format-lenses">View All Medium Format Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lenses/medium-format-lenses/fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/lenses/medium-format-lenses/leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/lenses/medium-format-lenses/laowa">Laowa</a>
                                        </div>

                                    </div>

                                    <div id="special-effect-lenses" class="tabcontent">
                                        <h3>Special Effect Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/lenses/special-effects-lenses">View All Special Effect Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lenses/special-effects-lenses/lensbaby">LensBaby</a>
                                            <a class href="https://www.digidirect.com.au/lenses/special-effects-lenses/laowa">Laowa</a>
                                            <a class href="https://www.digidirect.com.au/lenses/special-effects-lenses/slr-magic">SLR Magic</a>
                                        </div>

                                    </div>

                                    <div id="lense-filter" class="tabcontent">
                                        <h3>Lens Filter</h3>
                                        <span><a class href="https://www.digidirect.com.au/lenses/lens-filters">View All Lens Filter</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/uv-clear-skylight-filters">UV Clear & Skylight Filters</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/polarising-filters">Polarising Filters</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/neutral-density-filters">Neutral Density Filters</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/filter-kits">Filter Kits</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/close-up-filters">Close Up Filters</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/drone-filters">Drone Filters</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/special-effect-filters">Special Effect Filters</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/black-and-white-contrast-filters">Black & White Contrast Filters</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/ir-filters">IR Filters</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/cokin-system">Cokin System</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/haida-system">Haida System</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-filters/filter-accessories">Filter Accessories</a>
                                        </div>

                                    </div>

                                    <div id="lens-accessories" class="tabcontent">
                                        <h3>Lens Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/lenses/lens-accessories">View All Lens Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lenses/lens-accessories/lens-adapters">Lens Adapters</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-accessories/teleconverters">Teleconverters</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-accessories/lens-caps">Lens Caps</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-accessories/lens-hoods">Lens Hoods</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-accessories/lens-cap-savers">Lens Cap Savers</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-accessories/extension-tubes">Extension Tubes</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-accessories/lens-supports">Lens Supports</a>
                                            <a class href="https://www.digidirect.com.au/lenses/lens-accessories/conversion-lenses">Conversion Lenses</a>

                                        </div>
                                    </div>


                                    <div id="camera-flashes" class="tabcontent">
                                        <h3>Camera Flashes</h3>
                                        <span><a class href="https://www.digidirect.com.au/lighting-and-studio/camera-flashes">View All Camera Flashes</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/camera-flashes/godox">Godox</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/camera-flashes/hahnel">Hahnel</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/camera-flashes/nissin">Nissin</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/camera-flashes/canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/camera-flashes/nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/camera-flashes/voking">Voking</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/camera-flashes/sony">Sony</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/camera-flashes/nanlite">Nanlite</a>
                                        </div>

                                    </div>

                                    <div id="monolights-and-strobes" class="tabcontent">
                                        <h3>Monolights & Strobes</h3>
                                        <span><a class href="https://www.digidirect.com.au/lighting-and-studio/monolights-and-strobes">View All Monolights & Strobes</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/monolights-and-strobes/elinchrom">Elinchrom</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/monolights-and-strobes/jinbei">Jinbei</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/monolights-and-strobes/godox">Godox</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/monolights-and-strobes/phottix">PHOTTIX</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/monolights-and-strobes/aputure">Aputure</a>
                                        </div>

                                    </div>

                                    <div id="continuous-lights" class="tabcontent">
                                        <h3>Continuous Lights</h3>
                                        <span><a class href="https://www.digidirect.com.au/lighting-and-studio/continuous-lights">View All Continuous Lights</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/continuous-lights/nanlite">Nanlite</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/continuous-lights/godox">Godox</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/continuous-lights/aputure">Aputure</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/continuous-lights/smallrig">SmallRig</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/continuous-lights/phottix">PHOTTIX</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/continuous-lights/lupo">Lupo</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/continuous-lights/glanz">Glanz</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/continuous-lights/rotolight">RotoLight</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/continuous-lights/pixel">Pixel</a>
                                        </div>

                                    </div>

                                    <div id="light-modifiers-and-reflectors" class="tabcontent">
                                        <h3>Light Modifiers & Reflectors</h3>
                                        <span><a class href="https://www.digidirect.com.au/lighting-and-studio/light-modifiers-and-reflectors">View All Light Modifiers & Reflectors</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/light-modifiers-and-reflectors/softboxes">Softboxes</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/light-modifiers-and-reflectors/umbrellas">Umbrellas</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/light-modifiers-and-reflectors/reflectors">Reflectors</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/light-modifiers-and-reflectors/snoots-grids-and-light-shapers">Snoots Grids & Light Shapers</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/light-modifiers-and-reflectors/beauty-dishes">Beauty Dishes</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/light-modifiers-and-reflectors/speed-rings">Speed Rings</a>
                                        </div>

                                    </div>


                                    <div id="radio-and-optical-slaves" class="tabcontent">
                                        <h3>Radio & Optical Slaves</h3>
                                        <span><a class href="">View All Radio & Optical Slaves</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/radio-and-optical-slaves/radio-and-infrared-transmitters">Radio & Infrared Transmitters</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/radio-and-optical-slaves/radio-slave-cables">Radio Slave Cables</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/radio-and-optical-slaves/slave-accessories">Slave Accessories</a>
                                        </div>

                                    </div>

                                    <div id="flash-accessories" class="tabcontent">
                                        <h3>Flash Accessories</h3>
                                        <span><a class href="">View All Flash Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/flash-accessories/flash-modifiers">Flash Modifiers</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/flash-accessories/ttl-cords-and-accessories">TTL Cords & Accessories</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/flash-accessories/macro-and-ringlight-accessories">Macro & Ringlight Accessories</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/flash-accessories/pc-sync-and-hot-shoe-adapters">PC Sync & Hot Shoe Adapters</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/flash-accessories/pc-sync-cords">PC Sync Cords</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/flash-accessories/shoe-mount-adapters">Shoe Mount Adapters</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/flash-accessories/other-flash-accessories">Other Flash Accessories</a>
                                        </div>

                                    </div>

                                    <div id="on-camera-lighting" class="tabcontent">
                                        <h3>On Camera Lighting</h3>
                                        <span><a class href="">View All On Camera Lighting</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/on-camera-lighting/batteries-and-power">Batteries & Power</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/on-camera-lighting/mounts-and-brackets">Mounts & Brackets</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/on-camera-lighting/articulating-arms">Articulating Arms</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/on-camera-lighting/shoe-mount-adapters">Shoe Mount Adapters</a>
                                        </div>

                                    </div>

                                    <div id="backgrounds-and-supports" class="tabcontent">
                                        <h3>Backgrounds & Supports</h3>
                                        <span><a class href="">View All Backgrounds & Supports</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/backgrounds-and-supports/lastolite">Lastolite</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/backgrounds-and-supports/superior">Superior</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/backgrounds-and-supports/glanz">Glanz</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/backgrounds-and-supports/xlite">XLITE</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/backgrounds-and-supports/manfrotto">Manfrotto</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/backgrounds-and-supports/phottix">PHOTTIX</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/backgrounds-and-supports/haldex">Haldex</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/backgrounds-and-supports/elgato">Elgato</a>
                                            <a class href="https://www.digidirect.com.au/lighting-and-studio/backgrounds-and-supports/jinbei">Jinbei</a>
                                        </div>

                                    </div>

                                    <div id="tripods-and-stabilizers" class="tabcontent">
                                        <h3>Tripods & Stabilizers</h3>
                                        <span><a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers">View All Tripods & Stabilizers</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/tripods">Tripods</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/tripod-legs">Tripod Legs</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/tripod-accessories">Tripod Accessories</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/monopods">Monopods</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/ball-heads">Ball Heads</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/pan-and-tilt-heads">Pan & Tilt Heads</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/pistol-grip-heads">Pistol Grip Heads</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/video-heads">Video Heads</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/tripod-cases">Tripod Cases</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/camera-mounts">Camera Mounts</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/quick-release-plates">Quick Release Plates</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/camera-stabilizers">Camera Stabilizers</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/tripods-and-stabilizers/dollies-and-sliders">Dollies & Sliders</a>
                                        </div>

                                    </div>

                                    <div id="bags-and-cases" class="tabcontent">
                                        <h3>Bags & Cases</h3>
                                        <span><a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases">View All Bags & Cases</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/shoulder-bags">Shoulder Bags</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/holster-cases">Holster Cases</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/backpacks">Backpacks</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/rolling-cases">Rolling Cases</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/fashion-camera-bags">Fashion Camera Bags</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/waist-packs">Waist Packs</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/sling-bags">Sling Bags</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/pouches">Pouches</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/hard-cases">Hard Cases</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/lens-cases">Lens Cases</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/gear-protection">Gear Protection</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/camera-straps-and-harnesses">Camera Straps & Harnesses</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/inserts-and-compartments">Inserts & Compartments</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/bags-and-cases/bag-and-case-accessories">Bag & Case Accessories</a>
                                        </div>

                                    </div>

                                    <div id="memory-cards-and-drives" class="tabcontent">
                                        <h3>Memory Cards & Drives</h3>
                                        <span><a class href="https://www.digidirect.com.au/photo-accessories/memory-cards-and-drives">View All Memory Cards & Drives</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/photo-accessories/memory-cards-and-drives/memory-cards">Memory Cards</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/memory-cards-and-drives/memory-card-readers">Memory Card Readers</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/memory-cards-and-drives/memory-card-cases">Memory Card Cases</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/memory-cards-and-drives/usb-drives">USB Drives</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/memory-cards-and-drives/solid-state-drives">Solid State Drives</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/memory-cards-and-drives/hdds">HDDs</a>
                                        </div>

                                    </div>

                                    <div id="camera-system-accessories" class="tabcontent">
                                        <h3>Camera System Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories">View All Camera System Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/battery-grips">Battery Grips</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/remote-controls">Remote Controls</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/lcd-and-viewfinders-accessories">LCD & Viewfinders Accessories</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/light-meters">Light Meters</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/camera-cleaning">Camera Cleaning</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/gps-and-wireless-equipment">GPS & Wireless Equipment</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/hand-grips">Hand Grips</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/camera-cables-and-adapters">Camera Cables & Adapters</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/body-caps">Body Caps</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/action-cameras-accessories">Action Cameras Accessories</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/underwater-housings">Underwater Housings</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/camera-system-accessories/photo-gifts">Photo Gifts</a>
                                        </div>

                                    </div>

                                    <div id="batteries-and-power-supplies" class="tabcontent">
                                        <h3>Batteries & Power Supplies</h3>
                                        <span><a class href="https://www.digidirect.com.au/photo-accessories/batteries-and-power-supplies">View All Batteries & Power Supplies</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/photo-accessories/batteries-and-power-supplies/camera-batteries">Camera Batteries</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/batteries-and-power-supplies/camera-battery-chargers">Camera Battery Chargers</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/batteries-and-power-supplies/camera-ac-dc-adapters">Camera AC DC Adapters</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/batteries-and-power-supplies/power-banks">Power Banks</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/batteries-and-power-supplies/power-boards">Power Boards</a>
                                        </div>

                                    </div>

                                    <div id="printers-and-scanners" class="tabcontent">
                                        <h3>Printers & Scanners</h3>
                                        <span><a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners">View All Printers & Scanners</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/printers">Printers</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/scanners">Scanners</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/ink">Ink</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/printer-accessories">Printer Accessories</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/scanner-accessories">Scanner Accessories</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/paper">Paper</a>
                                        </div>

                                    </div>

                                    <div id="albums-and-frames" class="tabcontent">
                                        <h3>Albums & Frames</h3>
                                        <span><a class href="https://www.digidirect.com.au/photo-accessories/albums-and-frames">View All Albums & Frames</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/photo-accessories/albums-and-frames/profile">Profile</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/albums-and-frames/ur1">UR1</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/albums-and-frames/polaroid">Polaroid</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/albums-and-frames/hama">Hama</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/albums-and-frames/glanz">Glanz</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/albums-and-frames/fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/albums-and-frames/ap">AP</a>
                                        </div>

                                    </div>

                                    <div id="film-darkroom-and-video-tapes" class="tabcontent">
                                        <h3>Film Darkroom & Video Tapes</h3>
                                        <span><a class href="https://www.digidirect.com.au/photo-accessories/film-darkroom-and-video-tapes">View All Film Darkroom & Video Tapes</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/photo-accessories/film-darkroom-and-video-tapes/paterson">PATERSON</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/film-darkroom-and-video-tapes/ilford">ILFORD</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/film-darkroom-and-video-tapes/kodak">Kodak</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/film-darkroom-and-video-tapes/fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/film-darkroom-and-video-tapes/lomography">LOMOGRAPHY</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/film-darkroom-and-video-tapes/polaroid">Polaroid</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/film-darkroom-and-video-tapes/foma">Foma</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/film-darkroom-and-video-tapes/ap">AP</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/film-darkroom-and-video-tapes/cinestill">Cinestill</a>
                                        </div>

                                    </div>

                                    <div id="usb-cables-and-adapters" class="tabcontent">
                                        <h3>USB Cables & Adapters</h3>
                                        <span><a class href="https://www.digidirect.com.au/photo-accessories/usb-cables-and-adapters">View All USB Cables & Adapters</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/photo-accessories/usb-cables-and-adapters/tether-tools">Tether Tools</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/usb-cables-and-adapters/klik">Klik</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/usb-cables-and-adapters/glanz">Glanz</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/usb-cables-and-adapters/olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/usb-cables-and-adapters/leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/usb-cables-and-adapters/sigma">Sigma</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/usb-cables-and-adapters/angelbird">Angelbird</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/usb-cables-and-adapters/klarus">Klarus</a>
                                        </div>

                                    </div>

                                    <div id="travel-accessories" class="tabcontent">
                                        <h3>Travel Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/photo-accessories/travel-accessories">View All Travel Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/photo-accessories/travel-accessories/case-and-luggage-locks">Case & Luggage Locks</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/travel-accessories/travel-adaptors">Travel Adaptors</a>
                                            <a class href="https://www.digidirect.com.au/photo-accessories/travel-accessories/travel-essentials">Travel Essentials</a>
                                        </div>

                                    </div>

                                    <div id="binoculars-and-accessories" class="tabcontent">
                                        <h3>Binoculars & Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/optics/binoculars-and-accessories">View All Binoculars & Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/optics/binoculars-and-accessories/binoculars">Binoculars</a>
                                            <a class href="https://www.digidirect.com.au/optics/binoculars-and-accessories/binocular-accessories">Binocular Accessories</a>
                                        </div>

                                    </div>

                                    <div id="spotting-scopes-and-accessories" class="tabcontent">
                                        <h3>Spotting Scopes & Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/optics/spotting-scopes-and-accessories">View All Spotting Scopes & Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/optics/spotting-scopes-and-accessories/spotting-scopes">Spotting Scopes</a>
                                            <a class href="https://www.digidirect.com.au/optics/spotting-scopes-and-accessories/eyepieces">Eyepieces</a>
                                            <a class href="https://www.digidirect.com.au/optics/spotting-scopes-and-accessories/spotting-scopes-accessories">Spotting Scopes Accessories</a>
                                        </div>

                                    </div>

                                    <div id="laser-rangefinders" class="tabcontent">
                                        <h3>Laser Rangefinders</h3>
                                        <span><a class href="https://www.digidirect.com.au/optics/laser-rangefinders">View All Laser Rangefinders</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/optics/laser-rangefinders/nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/optics/laser-rangefinders/leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/optics/laser-rangefinders/bushnell">Bushnell</a>
                                            <a class href="https://www.digidirect.com.au/optics/laser-rangefinders/simmons">Simmons</a>
                                        </div>

                                    </div>

                                    <div id="monoculars" class="tabcontent">
                                        <h3>Monoculars</h3>
                                        <span><a class href="https://www.digidirect.com.au/optics/monoculars">View All Monoculars</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/optics/monoculars/zeiss">Zeiss</a>
                                            <a class href="https://www.digidirect.com.au/optics/monoculars/sionyx">SiOnyx</a>
                                            <a class href="https://www.digidirect.com.au/optics/monoculars/konus">Konus</a>
                                            <a class href="https://www.digidirect.com.au/optics/monoculars/bushnell">Bushnell</a>
                                            <a class href="https://www.digidirect.com.au/optics/monoculars/celestron">Celestron</a>
                                            <a class href="https://www.digidirect.com.au/optics/monoculars/leica">Leica</a>
                                        </div>

                                    </div>


                                    <div id="telescopes" class="tabcontent">
                                        <h3>Telescopes</h3>
                                        <span><a class href="https://www.digidirect.com.au/optics/telescopes">View All Telescopes</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/optics/telescopes/skywatcher">Skywatcher</a>
                                            <a class href="https://www.digidirect.com.au/optics/telescopes/zeiss">Zeiss</a>
                                            <a class href="https://www.digidirect.com.au/optics/telescopes/meade">Meade</a>
                                            <a class href="https://www.digidirect.com.au/optics/telescopes/celestron">Celestron</a>
                                        </div>

                                    </div>

                                    <div id="microphones" class="tabcontent">
                                        <h3>Microphones</h3>
                                        <span><a class href="https://www.digidirect.com.au/audio-and-visual/microphones">View All Microphones</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/microphones/wireless-microphones">Wireless Microphones</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/microphones/directional-microphones">Directional Microphones</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/microphones/stereo-microphones">Stereo Microphones</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/microphones/lavalier-microphones">Lavalier Microphones</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/microphones/specialty-microphones">Specialty Microphones</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/microphones/microphone-accessories">Microphone Accessories</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/microphones/studio-and-broadcast-microphones">Studio & Broadcast Microphones</a>
                                        </div>

                                    </div>

                                    <div id="audio-recorders" class="tabcontent">
                                        <h3>Audio Recorders</h3>
                                        <span><a class href="https://www.digidirect.com.au/audio-and-visual/audio-recorders">View All Audio Recorders</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/audio-recorders/zoom">ZOOM</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/audio-recorders/olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/audio-recorders/saramonic">Saramonic</a>
                                        </div>

                                    </div>

                                    <div id="headphones" class="tabcontent">
                                        <h3>Headphones</h3>
                                        <span><a class href="https://www.digidirect.com.au/audio-and-visual/headphones">View All Headphones</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/headphones/beats">Beats</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/headphones/panasonic">Panasonic</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/headphones/apple">Apple</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/headphones/sennheiser">SENNHEISER</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/headphones/boya">Boya</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/headphones/logitech">Logitech</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/headphones/satechi">Satechi</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/headphones/rode">Rode</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/headphones/samsung">Samsung</a>
                                        </div>

                                    </div>

                                    <div id="cables" class="tabcontent">
                                        <h3>Cables</h3>
                                        <span><a class href="https://www.digidirect.com.au/audio-and-visual/cables">View All Cables</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/cables/rode">Rode</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/cables/tether-tools">Tether Tools</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/cables/atomos">Atomos</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/cables/kondor-blue">Kondor Blue</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/cables/zoom">ZOOM</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/cables/boya">Boya</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/cables/olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/cables/otterbox">Otterbox</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/cables/sennheiser">SENNHEISER</a>
                                        </div>

                                    </div>

                                    <div id="speakers" class="tabcontent">
                                        <h3>Speakers</h3>
                                        <span><a class href="https://www.digidirect.com.au/audio-and-visual/speakers">View All Speakers</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/speakers/audioengine">Audioengine</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/speakers/ultimate-ears">Ultimate Ears</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/speakers/creative">Creative</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/speakers/logitech">Logitech</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/speakers/boya">Boya</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/speakers/mbeat">mbeat</a>
                                        </div>

                                    </div>

                                    <div id="audio-interfaces-and-mixers" class="tabcontent">
                                        <h3>Audio Interfaces & Mixers</h3>
                                        <span><a class href="https://www.digidirect.com.au/audio-and-visual/audio-interfaces-and-mixers">View All Audio Interfaces & Mixers</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/audio-interfaces-and-mixers/zoom">ZOOM</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/audio-interfaces-and-mixers/saramonic">Saramonic</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/audio-interfaces-and-mixers/rode">Rode</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/audio-interfaces-and-mixers/astro-gaming">Astro Gaming</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/audio-interfaces-and-mixers/boya">Boya</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/audio-interfaces-and-mixers/azden">Azden</a>
                                        </div>

                                    </div>

                                    <div id="software" class="tabcontent">
                                        <h3>Software</h3>
                                        <span><a class href="https://www.digidirect.com.au/audio-and-visual/software">View All Software</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/software/x-rite">X-Rite</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/software/datacolor">Datacolor</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/software/loupedeck">Loupedeck</a>
                                        </div>

                                    </div>

                                    <div id="monitors" class="tabcontent">
                                        <h3>Monitors</h3>
                                        <span><a class href="https://www.digidirect.com.au/computers-mobile/monitors/monitors">View All Monitors</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/computers-mobile/monitors/monitors/monitors-home-business">Home & Business</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/monitors/monitors/monitors-gaming">Gaming</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/monitors/monitors/monitors-curved-screen">Curved Screen</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/monitors/monitors/monitors-touchscreen">Touchscreen</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/monitors/monitors/monitors-professional">Professional</a>
                                        </div>

                                    </div>

                                    <div id="drawing-tablets" class="tabcontent">
                                        <h3>Drawing Tablets</h3>
                                        <span><a class href="https://www.digidirect.com.au/audio-and-visual/drawing-tablets">View All Drawing Tablets</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/drawing-tablets/wacom">Wacom</a>
                                            <a class href="https://www.digidirect.com.au/audio-and-visual/drawing-tablets/huion">Huion</a>
                                        </div>

                                    </div>

                                    <div id="pro-video-cameras" class="tabcontent">
                                        <h3>Pro Video Cameras</h3>
                                        <span><a class href="">View All Pro Video Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/pro-video/pro-video-cameras/sony">Sony</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/pro-video-cameras/panasonic">Panasonic</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/pro-video-cameras/canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/pro-video-cameras/z-cam">Z Cam</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/pro-video-cameras/dji">DJI</a>
                                        </div>

                                    </div>

                                    <div id="video-monitors-and-recorders" class="tabcontent">
                                        <h3>Video Monitors & Recorders</h3>
                                        <span><a class href="https://www.digidirect.com.au/pro-video/video-monitors-and-recorders">View All Video Monitors & Recorders</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/pro-video/video-monitors-and-recorders/accessories">Accessories</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/video-monitors-and-recorders/sunhoods">Sunhoods</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/video-monitors-and-recorders/stands-and-mounts">Stands & Mounts</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/video-monitors-and-recorders/video-cables">Video Cables</a>
                                        </div>

                                    </div>

                                    <div id="white-balance-and-calibration" class="tabcontent">
                                        <h3>White Balance & Calibration</h3>
                                        <span><a class href="https://www.digidirect.com.au/pro-video/white-balance-and-calibration">View All White Balance & Calibration</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/pro-video/white-balance-and-calibration/calibrite">Calibrite</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/white-balance-and-calibration/datacolor">Datacolor</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/white-balance-and-calibration/x-rite">X-Rite</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/white-balance-and-calibration/danes-picta">Danes-Picta</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/white-balance-and-calibration/lastolite">Lastolite</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/white-balance-and-calibration/eizo">Eizo</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/white-balance-and-calibration/lensalign">LENSALIGN</a>
                                        </div>

                                    </div>

                                    <div id="video-rigs" class="tabcontent">
                                        <h3>Video Rigs</h3>
                                        <span><a class href="https://www.digidirect.com.au/pro-video/video-rigs">View All Video Rigs</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/pro-video/video-rigs/cages">Cages</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/video-rigs/shoulder-rigs">Shoulder Rigs</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/video-rigs/follow-focus-systems">Follow Focus Systems</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/video-rigs/parts">Parts</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/video-rigs/magic-arms">Magic Arms</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/video-rigs/matte-box">Matte Box</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/video-rigs/monitor-mount">Monitor Mount</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/video-rigs/top-handle">Top Handle</a>
                                        </div>

                                    </div>


                                    <div id="live-streaming" class="tabcontent">
                                        <h3>Live Streaming</h3>
                                        <span><a class href="https://www.digidirect.com.au/pro-video/live-streaming">View All Live Streaming</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/pro-video/live-streaming/elgato">Elgato</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/live-streaming/rode">Rode</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/live-streaming/aten">Aten</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/live-streaming/logitech">Logitech</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/live-streaming/boya">Boya</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/live-streaming/desview">Desview</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/live-streaming/z-cam">Z Cam</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/live-streaming/panasonic">Panasonic</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/live-streaming/blue">Blue</a>
                                        </div>

                                    </div>

                                    <div id="tools-and-consumables" class="tabcontent">
                                        <h3>Tools & Consumables</h3>
                                        <span><a class href="https://www.digidirect.com.au/pro-video/tools-and-consumables">View All Tools & Consumables</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/pro-video/tools-and-consumables/smallrig">SmallRig</a>
                                            <a class href="https://www.digidirect.com.au/pro-video/tools-and-consumables/fve">FVE</a>
                                        </div>

                                    </div>

                                    <div id="security-cameras" class="tabcontent">
                                        <h3>Security Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/smart-home/security-camera-systems">View All Security Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/smart-home/security-camera-systems/swann">Swann</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/security-camera-systems/tp-link">TP-LINK</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/security-camera-systems/eufy">Eufy</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/security-camera-systems/ring">Ring</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/security-camera-systems/uniview">Uniview</a>
                                        </div>

                                    </div>

                                    <div id="home-automation" class="tabcontent">
                                        <h3>Home Automation</h3>
                                        <span><a class href="https://www.digidirect.com.au/smart-home/home-automation">View All Home Automation</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/smart-home/home-automation/tp-link">TP-LINK</a>
                                        </div>

                                    </div>

                                    <div id="small-appliances" class="tabcontent">
                                        <h3>Small Appliances</h3>
                                        <span><a class href="https://www.digidirect.com.au/smart-home/small-appliances">View All Small Appliances</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/smart-home/small-appliances/medisaint">Medisaint</a>
                                        </div>

                                    </div>

                                    <div id="health-fitness-and-wearables" class="tabcontent">
                                        <h3>Health Fitness & Wearables</h3>
                                        <span><a class href="https://www.digidirect.com.au/smart-home/health-fitness-and-wearables">View All Health Fitness & Wearables</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/smart-home/health-fitness-and-wearables/activity-trackers-smart-watches">Activity Trackers</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/health-fitness-and-wearables/smart-watches">Smart Watches</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/health-fitness-and-wearables/smart-watch-accessories">Smart Watch Accessories</a>
                                        </div>

                                    </div>


                                    <div id="lighting" class="tabcontent">
                                        <h3>Lighting</h3>
                                        <span><a class href="https://www.digidirect.com.au/smart-home/lighting">View All Lighting</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/smart-home/lighting/nitecore">Nitecore</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/lighting/nanoleaf">Nanoleaf</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/lighting/klarus">Klarus</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/lighting/mbeat">mbeat</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/lighting/olight">Olight</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/lighting/litra">Litra</a>
                                        </div>

                                    </div>

                                    <div id="lifestyle-gadgets" class="tabcontent">
                                        <h3>Lifestyle Gadgets</h3>
                                        <span><a class href="https://www.digidirect.com.au/smart-home/lifestyle-gadgets">View All Lifestyle Gadgets</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/smart-home/lifestyle-gadgets/off-grid-power">Off Grid Power</a>
                                            <a class href="https://www.digidirect.com.au/smart-home/lifestyle-gadgets/outdoor-equipment">Outdoor Equipment</a>
                                        </div>

                                    </div>

                                    <div id="laptops-and-notebooks" class="tabcontent">
                                        <h3>Laptops & Notebooks</h3>
                                        <span><a class href="https://www.digidirect.com.au/computers-mobile/laptops-notebooks">View All Laptops & Notebooks</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/computers-mobile/laptops-notebooks/gaming-laptops">Gaming Laptops</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/laptops-notebooks/business">Business</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/laptops-notebooks/home-student">Home & Student</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/laptops-notebooks/apple-macbooks">Apple MacBooks</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/laptops-notebooks/microsoft-surface">Microsoft Surface</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/laptops-notebooks/professional-laptops">Professional Laptops</a>
                                        </div>

                                    </div>

                                    <div id="mobile-phones-and-accessories" class="tabcontent">
                                        <h3>Mobile Phones & Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/computers-mobile/mobile-phones-and-accessories">View All Mobile Phones & Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/computers-mobile/mobile-phones-and-accessories/mobile-phones">Mobile Phones</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/mobile-phones-and-accessories/mobile-accessories">Mobile Accessories</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/mobile-phones-and-accessories/sim-plans">Sim Cards & Prepaid Recharge</a>
                                        </div>

                                    </div>

                                    <div id="gaming" class="tabcontent">
                                        <h3>Gaming</h3>
                                        <span><a class href="https://www.digidirect.com.au/computers-mobile/gaming">View All Gaming</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/computers-mobile/gaming/console-accessories">Console Accessories</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/gaming/consoles">Consoles</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/gaming/games">Games</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/gaming/gaming-chairs">Gaming Chairs</a>
                                        </div>

                                    </div>

                                    <div id="tablets-ipads-and-surface" class="tabcontent">
                                        <h3>Tablets IPads & Surface</h3>
                                        <span><a class href="https://www.digidirect.com.au/computers-mobile/tablets-ipads-surface">View All Tablets IPads & Surface</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/computers-mobile/tablets-ipads-surface/apple-ipads">Apple IPads</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/tablets-ipads-surface/accessories">Tablet Accessories</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/tablets-ipads-surface/samsung-galaxy-tablets">Samsung Galaxy Tablets</a>
                                        </div>

                                    </div>


                                    <div id="printers-and-scanners2" class="tabcontent">
                                        <h3>Printers & Scanners</h3>
                                        <span><a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners">View All Printers & Scanners</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/printers">Printers</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/scanners">Scanners</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/ink">Ink</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/printer-accessories">Printer Accessories</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/scanner-accessories">Scanner Accessories</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/printers-and-scanners/paper">Paper</a>
                                        </div>

                                    </div>

                                    <div id="monitors-and-accessories" class="tabcontent">
                                        <h3>Monitors & Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/computers-mobile/monitors">View All Monitors & Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/computers-mobile/monitors/monitors">Monitors</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/monitors/monitor-mounts-stands">Monitor Mounts & Stands</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/monitors/monitor-accessories">Monitor Accessories</a>
                                        </div>

                                    </div>

                                    <div id="desktop-and-parts" class="tabcontent">
                                        <h3>Desktop & Parts</h3>
                                        <span><a class href="https://www.digidirect.com.au/computers-mobile/desktops">View All Desktop & Parts</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/computers-mobile/desktops/apple-imac-desktops">Apple iMac Desktops</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/desktops/apple-imac-desktops">All in One PCs</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/desktops/nuc-mini-pcs">NUC & Mini PCs</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/desktops/apple-tv">Apple TV</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/desktops/desktop-pcs">Desktop PCs</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/desktops/apple-mac-studio">Apple Mac Studio</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/desktops/apple-mac-pros">Apple Mac Pros</a>
                                        </div>

                                    </div>

                                    <div id="computer-accessories" class="tabcontent">
                                        <h3>Computer Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/computers-mobile/computer-accessories">View All Computer Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/computers-mobile/computer-accessories/mouse-keyboard">Keyboards & Combos</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/computer-accessories/mice-mousemats">Mice & Mousemats</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/computer-accessories/cases-covers-bags">Case Covers & Bags</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/computer-accessories/hubs-docks">Hubs & Docks</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/computer-accessories/webcams">Webcams</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/computer-accessories/cables">Cables & Adaptors</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/computer-accessories/chargers">Chargers</a>
                                            <a class href="https://www.digidirect.com.au/computers-mobile/computer-accessories/headsets">Headsets</a>
                                        </div>

                                    </div>

                                    <div id="drones-uav" class="tabcontent">
                                        <h3>Drones UAV</h3>
                                        <span><a class href="https://www.digidirect.com.au/drones/drones/dji">View All Drones UAV</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/drones/drones/dji">DJI</a>
                                        </div>

                                    </div>

                                    <div id="drone-cameras" class="tabcontent">
                                        <h3>Drone Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/drones/drone-cameras">View All Drone Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/drones/drone-cameras/dji">DJI</a>
                                            <a class href="https://www.digidirect.com.au/drones/drone-cameras/autel">Autel</a>
                                        </div>

                                    </div>

                                    <div id="drone-gimbals" class="tabcontent">
                                        <h3>Drone Gimbals</h3>
                                        <span><a class href="https://www.digidirect.com.au/drones/drone-gimbals">View All Drone Gimbals</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/drones/drone-gimbals">DJI</a>
                                        </div>

                                    </div>

                                    <div id="drone-accessories" class="tabcontent">
                                        <h3>Drone Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/drones/drone-accessories">View All Drone Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/drones/drone-accessories/drone-chargers">Drone Chargers</a>
                                            <a class href="https://www.digidirect.com.au/drones/drone-accessories/drone-batteries">Drone Batteries</a>
                                            <a class href="https://www.digidirect.com.au/drones/drone-accessories/mounts-and-others">Mounts & Others</a>
                                            <a class href="https://www.digidirect.com.au/drones/drone-accessories/drone-cables">Drone Cables</a>
                                            <a class href="https://www.digidirect.com.au/drones/drone-accessories/drone-propellers">Drone Propellers</a>
                                            <a class href="https://www.digidirect.com.au/drones/drone-accessories/bags-and-cases">Drone Bags & Cases</a>
                                            <a class href="https://www.digidirect.com.au/drones/drone-accessories/remotes">Drone Remotes</a>
                                        </div>

                                    </div>

                                    <div id="underwater-rovs" class="tabcontent">
                                        <h3>Underwater ROVs</h3>
                                        <span><a class href="https://www.digidirect.com.au/drones/underwater-rovs">View All Underwater ROVs</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/drones/underwater-rovs/gladius">Gladius</a>
                                        </div>

                                    </div>

                                    <div id="robotics" class="tabcontent">
                                        <h3>Robotics</h3>
                                        <span><a class href="https://www.digidirect.com.au/drones/robotics">View All Robotics</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/drones/robotics/dji">DJI</a>
                                            <a class href="https://www.digidirect.com.au/drones/robotics/makeblock">MakeBlock</a>
                                            <a class href="https://www.digidirect.com.au/drones/robotics/ubtech">UBTech</a>
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>

                        <div id="menu-top-brands">
                            <div id="top-brands-title">TOP BRANDS</div>
                            <div id="top-brands-cameras" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/canon/filters/cat/cameras?_aa=222&_option=120"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/canon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/fujifilm/filters/cat/cameras?_aa=222&_option=8253"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/fujifilm.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/leica/filters/cat/cameras?_aa=222&_option=139"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/leica.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/nikon/filters/cat/cameras?_aa=222&_option=134"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/nikon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/panasonic/filters/cat/cameras?_aa=222&_option=138"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/panasonic.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/olympus/filters/cat/cameras?_aa=222&_option=135"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/olympus.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/ricoh/filters/cat/cameras?_aa=222&_option=245"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/ricoh.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/insta360/filters/cat/cameras?_aa=222&_option=483"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/insta360.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/sony/filters/cat/cameras?_aa=222&_option=137"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sony.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/gopro/filters/cat/cameras?_aa=222&_option=291"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/gopro.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-lenses" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/sony/filters/cat/lenses?_aa=222&_option=137"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sony.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/canon/filters/cat/lenses?_aa=222&_option=120"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/canon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/fujifilm/filters/cat/lenses?_aa=222&_option=8253"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/fujifilm.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/sigma/filters/cat/lenses?_aa=222&_option=221"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sigma.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/nikon/filters/cat/lenses?_aa=222&_option=134"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/nikon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/tamron/filters/cat/lenses?_aa=222&_option=223"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/tamron.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/olympus/filters/cat/lenses?_aa=222&_option=135"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/olympus.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/leica/filters/cat/lenses?_aa=222&_option=139"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/leica.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/panasonic/filters/cat/lenses?_aa=222&_option=138"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/panasonic.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/laowa/filters/cat/lenses?_aa=222&_option=517"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/laowa.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-lightingandstudio" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/godox/filters/cat/lighting-studio?_aa=222&_option=495"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/godox.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/aputure/filters/cat/lighting-studio?_aa=222&_option=7105"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/aputure.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/nanlite/filters/cat/lighting-studio?_aa=222&_option=13345"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/nanlite.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/sekonic/filters/cat/lighting-studio?_aa=222&_option=271"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sekonic.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/elinchrom/filters/cat/lighting-studio?_aa=222&_option=293"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/elinchrom.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/manfrotto/filters/cat/lighting-studio?_aa=222&_option=231"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/manfrotto.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/magmod/filters/cat/lighting-studio?_aa=222&_option=463"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/magmod.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-photoaccessories" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/sandisk/filters/cat/photo-accessories?_aa=222&_option=215"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sandisk.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/manfrotto/filters/cat/photo-accessories?_aa=222&_option=231"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/manfrotto.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/peak-design/filters/cat/photo-accessories?_aa=222&_option=323"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/peakdesign.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/lacie/filters/cat/photo-accessories?_aa=222&_option=431"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/lacie.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/lowepro/filters/cat/photo-accessories?_aa=222&_option=217"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/lowepro.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/dji/filters/cat/photo-accessories?_aa=222&_option=353"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/dji.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/joby/filters/cat/photo-accessories?_aa=222&_option=233"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/joby.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/pelican/filters/cat/photo-accessories?_aa=222&_option=321"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/pelican.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/jupio/filters/cat/photo-accessories?_aa=222&_option=379"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/jupio.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/benro/filters/cat/photo-accessories?_aa=222&_option=459"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/benro.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-optics" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/nikon/filters/cat/optics?_aa=222&_option=134"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/nikon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/leica/filters/cat/optics?_aa=222&_option=139"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/leica.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/sionyx/filters/cat/optics?_aa=222&_option=13321"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sionyx.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/bushnell/filters/cat/optics?_aa=222&_option=273"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/bushnell.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/steiner/filters/cat/optics?_aa=222&_option=355"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/steiner.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/zeiss/filters/cat/optics?_aa=222&_option=243"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/zeiss.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/fujifilm/filters/cat/optics?_aa=222&_option=8253"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/fujifilm.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/olympus/filters/cat/optics?_aa=222&_option=135"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/olympus.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/kowa/filters/cat/optics?_aa=222&_option=507"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/kowa.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/celestron/filters/cat/optics?_aa=222&_option=567"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/celestron.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-audiovisual" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/rode/filters/cat/audio-visual?_aa=222&_option=281"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/rode.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/blue/filters/cat/audio-visual?_aa=222&_option=18988"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/blue.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/audioengine/filters/cat/audio-visual?_aa=222&_option=19465"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/audioengine.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/sennheiser/filters/cat/audio-visual?_aa=222&_option=7095"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sennheiser.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/sony/filters/cat/audio-visual?_aa=222&_option=137"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sony.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/boya/filters/cat/audio-visual?_aa=222&_option=9405"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/boya.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/wacom/filters/cat/audio-visual?_aa=222&_option=9370"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/wacom.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/atomos/filters/cat/audio-visual?_aa=222&_option=315"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/atomos.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/olympus/filters/cat/audio-visual?_aa=222&_option=135"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/olympus.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-provideo" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/atomos/filters/cat/pro-video?_aa=222&_option=315"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/atomos.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/canon/filters/cat/pro-video?_aa=222&_option=120"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/canon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/sony/filters/cat/pro-video?_aa=222&_option=137"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sony.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/panasonic/filters/cat/pro-video?_aa=222&_option=138"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/panasonic.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/x-rite/filters/cat/pro-video?_aa=222&_option=333"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/xrite.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/elgato/filters/cat/pro-video?_aa=222&_option=10265"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/elgato.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/datacolor/filters/cat/pro-video?_aa=222&_option=305"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/datacolor.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/smallrig/filters/cat/pro-video?_aa=222&_option=19569"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/smallrig.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/z-cam/filters/cat/pro-video?_aa=222&_option=10179"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/zcam.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-smarthome" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/fitbit/filters/cat/smart-home?_aa=222&_option=9256"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/fitbit.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/ecoflow/filters/cat/smart-home?_aa=222&_option=19563"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/ecoflow.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/nitecore/filters/cat/smart-home?_aa=222&_option=7153"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/nitecore.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/medisaint/filters/cat/smart-home?_aa=222&_option=12347"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/medisaint.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/tp-link/filters/cat/smart-home?_aa=222&_option=20138"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/tplink.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/enabot/filters/cat/smart-home?_aa=222&_option=18775"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/enabot.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/eve/filters/cat/smart-home?_aa=222&_option=9284"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/eve.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-computersandmobile" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/samsung/filters/cat/computers-mobile?_aa=222&_option=433"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/samsung.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/apple/filters/cat/computers-mobile?_aa=222&_option=9214"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/apple.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/logitech/filters/cat/computers-mobile?_aa=222&_option=10346"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/logitech.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/asus/filters/cat/computers-mobile?_aa=222&_option=14420"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/asus.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/microsoft/filters/cat/computers-mobile?_aa=222&_option=13465"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/microsoft.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/aoc/filters/cat/computers-mobile?_aa=222&_option=19533"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/aoc.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/belkin/filters/cat/computers-mobile?_aa=222&_option=19830"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/belkin.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/epson/filters/cat/computers-mobile?_aa=222&_option=583"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/epson.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/eizo/filters/cat/computers-mobile?_aa=222&_option=7159"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/eizo.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/lenovo/filters/cat/computers-mobile?_aa=222&_option=9241"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/lenovo.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-drones" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/dji/filters/cat/drones?_aa=222&_option=353"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/dji.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/autel/filters/cat/drones?_aa=222&_option=19521"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/autel.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/polar-pro/filters/cat/drones?_aa=222&_option=535"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/polarpro.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/pgytech/filters/cat/drones?_aa=222&_option=9307"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/pgtech.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/brands/swellpro/filters/cat/drones?_aa=222&_option=7177"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/swellpro.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-electronic" class="top-brands-brand">
                            </div>

                            <div id="top-brands-home" class="top-brands-brand">
                            </div>

                            <div id="top-brands-collectibles" class="top-brands-brand">
                            </div>

                            <div id="top-brands-fitness" class="top-brands-brand">
                            </div>

                            <div id="top-brands-seasonal" class="top-brands-brand">
                            </div>

                            <div id="top-brands-music" class="top-brands-brand">
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>

        <?php
        if ($isDigiClub == 1) { ?>
            <a id="submenu-digiclub-member-deals" class="submenu-link item-submenu"
               href="https://www.digidirect.com.au/digiclub-member-deals"
               onclick="checkActiveMenuItem(event, 'submenu-digiclub-member-deals')">
                <span class="dc-digi">digi</span><span class="dc-club">Club</span> MEMBER DEALS
            </a>
        <?php } ?>
        <a id="submenu-digideals" class="submenu-link item-submenu" href="https://www.digidirect.com.au/deals" onclick="checkActiveMenuItem(event, 'submenu-digideals')">
            <span class="dc-digi">digi</span><span class="dc-club">Deals</span>
        </a>

        <div id="submenu-digiseconds" class="item-submenu" onclick="checkActiveMenuItem(event, 'submenu-digiseconds')">
            <div class="digiseconds-mobile-menu">
                <div class="dropdown">
                    <a class="digiseconds-nav">
                        <button class="dropbtn" style="display: flex;">
                            <span class="dc-digi">digi</span>
                            <span class="dc-club">Seconds</span>
                            <i class="fas fa-angle-down"></i>
                        </button>
                    </a>
                    <i class="fas fa-angle-right"></i>
                    <div class="dropdown-content" onclick="event.stopPropagation()" style="flex-direction: column;">
                        <div class="digiseconds-listing" style="display: grid; grid-auto-rows: 100px;width: 100%;max-width: 430px;">
                            <a href="https://digidirect.com.au/digiseconds/openbox">
                                <div class="digiseconds-menu">
                                    <div role="img" class="digiseconds-menu-img" style="background-image: url('https://www.digidirect.com.au/media/wysiwyg/digiseconds/nav-demo.png'); background-repeat: no-repeat; background-size: contain;" alt="Open Box">
                                    </div>
                                    <span class="digiseconds-menu-description-wrapper"><span class="digiseconds-menu-title">OPEN BOX</span><br>
                    <span class="digiseconds-menu-description">Package opended but product inside appears unused.</span>
                    <span class="digiseconds-get-started" style="color: #ff3c00; font-size: 12px; font-weight: 400;">Get Started</span></span>
                                </div></a>

                            <a href="https://digidirect.com.au/digiseconds/preloved">
                                <div class="digiseconds-menu">
                                    <div role="img" class="digiseconds-menu-img" style="background-image: url('https://www.digidirect.com.au/media/wysiwyg/digiseconds/nav-pre-loved.png'); background-repeat: no-repeat; background-size: contain;" alt="Pre-Loved">
                                    </div>
                                    <span class="digiseconds-menu-description-wrapper"><span class="digiseconds-menu-title">PRE-LOVED</span><br>
                    <span class="digiseconds-menu-description">We buy used gears from our customers, fix and clean them up, then sell them back to you for a lower price.</span>
                    <span class="digiseconds-get-started" style="color: #ff3c00; font-size: 12px; font-weight: 400;">Get Started</span></span></div></a>

                            <a href="https://digidirect.com.au/digiseconds/refurb">
                                <div class="digiseconds-menu"><div role="img" class="digiseconds-menu-img" style="background-image: url('https://www.digidirect.com.au/media/wysiwyg/digiseconds/nav-refurbished.png'); background-repeat: no-repeat; background-size: contain;" alt="Refurbished">
                                    </div>
                                    <span class="digiseconds-menu-description-wrapper"><span class="digiseconds-menu-title">REFURBISHED</span><br>
                  <span class="digiseconds-menu-description">We repaired it and restored it to it's original glory and beyond!</span>
                  <span class="digiseconds-get-started" style="color: #ff3c00; font-size: 12px; font-weight: 400;">Get Started</span></span></div></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <a id="submenu-digimarket" class="submenu-link item-submenu" href="https://www.digidirect.com.au/digimarket" onclick="checkActiveMenuItem(event, 'submenu-digimarket')">
            <span class="dc-digi">digi</span><span class="dc-club">Market</span>
        </a>

        <div id="submenu-photolab" class="item-submenu" onclick="checkActiveMenuItem(event, 'submenu-photolab')">
            <div class="photolab-mobile-menu">
                <div class="dropdown">
                    <a class="digiprint-link" href="https://www.digidirect.com.au/digiprint">
                        <button class="dropbtn" style="display: flex;">
                            <span class="dc-digi">digi</span>
                            <span class="dc-club">Print</span>
                            <i class="fas fa-angle-down"></i>
                        </button>
                    </a>
                    <i class="fas fa-angle-right"></i>
          <div class="dropdown-content" onclick="event.stopPropagation()" onmouseleave="resetDigiPrintSecondLevel()">
            <div id="photolab-listing" class="photolab-listing" style="display: grid; grid-auto-rows: 100px;border: 1px solid #cacaca;">

                            <div class="reason-list" onclick="openDigiPrintSecondLevel(event, 'digiprint-second-level-printing-services')">
                <span>
                    <img src="https://www.digidirect.com.au/media/digiprint-digitalprints.png">
                </span>
                                <div class="content">
                                    <h3 class="protect-title">Printing Services</h3>
                                    <p>Turn your digital photos in to beautiful prints.</p>
                                </div>
                <i class="fas mgz-fa-angle-right"></i>
                            </div>

                            <div class="reason-list" onclick="openDigiPrintSecondLevel(event, 'digiprint-second-level-photo-books')">
                <span>
                    <img src="https://www.digidirect.com.au/media/digiprint-photobooks.png">
                </span>
                                <div class="content">
                                    <h3 class="protect-title">Photo Books</h3>
                                    <p>Customize Photo Books in different size and number pages</p>
                                </div>
                <i class="fas mgz-fa-angle-right"></i>
                            </div>
                
                            <div class="reason-list">
                <span>
                    <a href="https://www.digidirect.com.au/digi-print/calendar">
                        <img src="https://www.digidirect.com.au/media/digiprint-calendar.png">
                    </a>
                </span>
                                <div class="content">
                                    <a href="https://www.digidirect.com.au/digi-print/calendar">
                                        <h3 class="protect-title">Calendar</h3>
                                        <p>Customize your wall and desk calendar</p>
                                    </a>
                                </div>
                            </div>

                        </div>
              
            
            <div id="digiprint-second-level" class="mgz-tabs-content slide-left-to-right">
                <div id="return-to-first-level-digiprint" onclick="returnToFirstLevelDigiPrint()" style="display: none;"><i class="fas fa-angle-left" style="margin-right: 10px"></i>Previous</div>
                <div id="digiprint-second-level-printing-services" class="second-level-content">
                    <div class="menu-raw-content">
                        <div class="menu-second-level">
                            <span>Printing Services</span>
                            <div class="tab">
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/photo-prints">Photo Prints</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/canvas-prints">Canvas Prints</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/metal-prints">Metal Prints</a> 
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/glass-prints">Glass Prints</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/framed-prints">Framed Prints</a> 
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/framed-metal-prints">Framed Metal Prints</a> 
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/framed-canvas-prints">Framed Canvas Prints</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="digiprint-second-level-photo-books" class="second-level-content">
                    <div class="menu-raw-content">
                        <div class="menu-second-level">
                            <span>Photo Books</span>
                            <div class="tab">
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/photo-books/standard-cover-photo-books">Standard Cover Photo Books</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/photo-books/personalised-cover-photo-books">Personalised Cover Photo Books</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/photo-books/premium-cover-photo-books">Premium Cover Photo Books</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/photo-books/flip-books">Flip Books</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
</div>
    </div>

    </div>
  </div>
</div>

<script>

    function openSecondLevel(evt, className, topBrands, firstLevel) {

        var x;
        firstcategories = document.getElementsByClassName("mgz-tabs-tab-title");

        var y;
        firstcategoriestitle = document.getElementsByClassName("first-menu-tab-title");

        if (document.getElementById(firstLevel).classList.contains("active-category")) {
            document.getElementById(firstLevel).classList.remove("active-category");
            for (x = 0; x < firstcategories.length; x++) {
                firstcategories[x].removeAttribute('style');
            }
            for (y = 0; y < firstcategoriestitle.length; y++) {
                firstcategoriestitle[y].removeAttribute('style');
            }
            document.getElementById("second-level-menu").style.display = "none";
            document.getElementById("third-level-menu").style.display = "none";
            document.getElementById("menu-top-brands").style.display = "none";
            document.getElementById("shop-by-category-tabs").style.removeProperty("width");
        } else {
            for (x = 0; x < firstcategories.length; x++) {
                firstcategories[x].setAttribute('style', 'width: 100px !important');
                firstcategories[x].classList.remove("active-category");
            }
            document.getElementById(firstLevel).classList.add("active-category");

            for (y = 0; y < firstcategoriestitle.length; y++) {
                firstcategoriestitle[y].style.display = "none";
            }

            var i;
            tabcontent = document.getElementsByClassName("second-level-content");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }

            document.getElementById("second-level-menu").style.width= "330px";
            document.getElementById("second-level-menu").style.display = "block";
            document.getElementById(className).style.display = "block";
            document.getElementById("third-level-menu").style.display = "none";

            var z;
            topbrands = document.getElementsByClassName("top-brands-brand");
            for (z = 0; z < topbrands.length; z++) {
                topbrands[z].style.display = "none";
            }

            document.getElementById("menu-top-brands").style.width= "100px";
            document.getElementById("menu-top-brands").style.display = "block";

            if (screen.width < 1281) {
                document.getElementById(topBrands).style.display = "grid";
            } else {
                document.getElementById(topBrands).style.display = "block";
            }

            if (screen.width < 1281) {
                document.getElementById("shop-by-category-tabs").style.width = "auto";
            }
        }

        for (x = 0; x < firstcategories.length; x++) {
            firstcategories[x].classList.add("hide-first-level");
        }

        window.scrollTo(0, 0);

    }

    function resetMenu() {

        var x;
        firstcategories = document.getElementsByClassName("mgz-tabs-tab-title");
        for (x = 0; x < firstcategories.length; x++) {
            firstcategories[x].removeAttribute('style');
            firstcategories[x].classList.remove("active-category");
        }

        var y;
        firstcategoriestitle = document.getElementsByClassName("first-menu-tab-title");
        for (y = 0; y < firstcategoriestitle.length; y++) {
            firstcategoriestitle[y].removeAttribute('style');
        }

        document.getElementById("second-level-menu").style.display = "none";
        document.getElementById("third-level-menu").style.display = "none";
        document.getElementById("menu-top-brands").style.display = "none";
        document.getElementById("shop-by-category-tabs").style.removeProperty("width");

        for (x = 0; x < firstcategories.length; x++) {
            firstcategories[x].classList.remove("hide-first-level");
        }
    }

    function openThirdLevel(evt, category) {

        document.getElementById("third-level-menu").style.width= "330px";
        document.getElementById("third-level-menu").style.display = "block";

        var i, tabcontent, tablinks, secondLevel;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }

        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }

        document.getElementById(category).style.display = "block";
        evt.currentTarget.className += " active";

        secondLevel = document.getElementsByClassName("menu-second-level");
        if (screen.width < 1281) {
            for (i = 0; i < secondLevel.length; i++) {
                //secondLevel[i].style.display = "none";
            }
        }

        if (screen.width < 1281) {
            document.getElementById("second-level-menu").style.display = "none";
        }
    }

    function openServiceMenu(event, serviceMenu) {
        var i,x;
        menu = document.getElementsByClassName("menu-services");
        for (i = 0; i < menu.length; i++) {
            menu[i].classList.remove("menu-active");
        }
        menuTitle = document.getElementsByClassName("menu-services-title");
        for (x = 0; x < menuTitle.length; x++) {
            menuTitle[x].classList.remove("title-active");
        }
        event.currentTarget.className += " title-active";
        document.getElementById(serviceMenu).classList.add("menu-active");
    }

    function checkActiveMenuItem(event, itemSubMenu) {
        var i;
        if (screen.width < 1281) {

            if (document.getElementById(itemSubMenu).classList.contains("submenu-active")) {
                document.getElementById(itemSubMenu).classList.remove("submenu-active");
            } else {
                document.getElementById(itemSubMenu).classList.add("submenu-active");
            }

            subMenu = document.getElementsByClassName("item-submenu");
            for (i = 0; i < subMenu.length; i++) {
                if (subMenu[i].id != itemSubMenu) {
                    subMenu[i].classList.remove("submenu-active");
                }
                //subMenu[i].classList.remove("submenu-active");
            }


            //document.getElementById(itemSubMenu).scrollIntoView();
        }

    }

    function returnToSecondLayer() {
        document.getElementById("second-level-menu").style.display = "block";
        document.getElementById("third-level-menu").style.display = "none";
    }

    function returnToFirstLevel() {
        resetMenu();
    }


    function openDigiPrintSecondLevel(evt, className) {
        var i;
        tabcontent = document.getElementsByClassName("second-level-content");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].removeAttribute('style');
        }
        document.getElementById("digiprint-second-level").removeAttribute('style');
        document.getElementById(className).removeAttribute('style');
        document.getElementById("digiprint-second-level").style.display = "block";
        document.getElementById(className).style.display = "block";
        
        if (window.innerWidth < 1280) {
            document.getElementById("photolab-listing").style.display = "none";
        } else {
            document.getElementById("photolab-listing").style.display = "block";
        }
        
    }

    function resetDigiPrintSecondLevel() {
        document.getElementById("digiprint-second-level").removeAttribute('style');
    }
    
    function returnToFirstLevelDigiPrint() {
        document.getElementById("photolab-listing").style.display = "grid";
        document.getElementById("digiprint-second-level").removeAttribute('style');
    }

</script>

<script>
    require(['jquery'],function($){
        $('#mobile-menu-minicart').on('click', function(){
            $('#show-cart').trigger("click");
            console.log("Mobile Navigation Minicart!");
        });
    });
</script>
