<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

$isDigiClub = 0;

if ($customerSession->isLoggedIn()) {
    $customerGroupId = $customerSession->getCustomer()->getGroupId();
    if ($customerGroupId == 10) {
        $isDigiClub = 1;
    }
}
?>

<div id="header-mobile-menu-only">
    <div class="top-header-wrapper">
        <div class="panel wrapper">
            <div class="panel header">
                <div class="header-links header-link-left" style="margin-left: 50px;">
                    <a class="next-day-shipping-link" href="/free-shipping" title="Express Next Day Shipping" style="display: none;"><i class="fas fa-shipping-fast"></i> Express Next Day Shipping</a>
                    <a class="click-and-collect-link" href="/pickup-instore" title="Click & Collect"><i class="fas fa-hand-point-up"></i> Click & Collect</a>
                    <a class="store-locator-link" href="/store-locator" title="Store Locator"><i class="fas fa-map-marker-alt"></i> Store Locator</a>
                    <a class="faq-link" href="/faq" title="FAQ"><i class="fas fa-question-circle"></i> Questions?</a>
                    <a class="call-us-link" href="tel:1300 889 148" title="call-us"><i class="fas fa-headset"></i> CALL US <span class="company-number">1300 889 148</span></a>
                    <a class="gift-cards-link" href="https://digidirectgiftcards.viisolutions.com.au/" title="GIFT CARDS"><i class="fas fa-gift"></i> GIFT CARDS</a>
                    <a class="digiservices-link" href="/#digiservices" title="digiServices"><i class="fas fa-film"></i></i> SERVICES</a>
                </div>
                <div class="header-links header-link-right" style="position: absolute; right: 0; margin-right: 50px;">
                    <div class="header-links-account">
                        <a class="digiclub-link" href="/digiclub" title="digiClub">digiClub</a>
                        <?php
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $customerSession = $objectManager->get('Magento\Customer\Block\Account\AuthorizationLink');

                        if ($customerSession->isLoggedIn() == true) { ?>
                            <a class="register-link" href="/customer/account" title="Account">My Account</a>
                            <a class="login-link" href="/customer/account/logout" title="Logout">Logout</a>
                        <?php } else { ?>
                            <a class="register-link" href="/customer/account/create" title="Register">Register</a>
                            <a class="login-link" href="/customer/account/login" title="Login">Login</a>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <span id="mobile-menu-only-header">
    <i class="fas fa-times mobile-menu-main-exit"></i>
    <a class="digi-link" href="https://www.digidirect.com.au/">
        <img id="digi-white-logo" src="https://www.digidirect.com.au/media/wysiwyg/logo.svg">
    </a>
    <span id="menu-mobile-span-signin">
        <a class="mobile-menu-signin" href="/customer/account" title="Account"><i class="fas fa-user"></i></a>
        <a id="mobile-menu-minicart" class="mobile-menu-minicart" href="#" title="Cart"><i class="fas fa-shopping-bag"></i></a>
    </span>
  </span>

    <div class="block block-search"><div class="block block-content"><form class="form minisearch" id="search_mini_form" action="https://www.digidirect.com.au/find" method="get"><div class="field search"><label class="label" for="search" data-role="minisearch-label"><svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -search"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-search" fill="white"></use></svg><span>Search</span></label> <div class="control"><input id="search" type="text" name="q" value="" placeholder="Search our store" class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off"><!-- <div id="search_autocomplete" class="search-autocomplete"></div>--></div></div><div class="actions"><button type="submit" title="Search" class="action search"><i class="fas fa-search" style="font-size: 21px; color: #fff; padding: 5px 12px 0 0;"></i></button></div></form></div></div>

</div>

<div class="navbar">
    <div class="navbar-content">

        <div id="submenu-shopbycategory" class="item-submenu submenu-active" onclick="checkActiveMenuItem(event, 'submenu-shopbycategory')">
            <div class="shop-by-category-menu">
                <div class="dropdown category-tabs">
                    <button class="dropbtn"><i class="fas fa-list"></i> SHOP BY CATEGORY <i class="fas fa-angle-down"></i></button>
                    <i class="fas fa-angle-right"></i>
                    <div class="dropdown-content mgz-tabs mgz-element-tab-align-left mgz-element-tab-position-left" onclick="event.stopPropagation()" onmouseleave="resetMenu()">

                        <div class="shop-by-category-tabs">
                            <div id="shop-by-category-tabs" class="mgz-tabs-nav">

                                <div id="cameras-tab-menu" class="mgz-tabs-tab-title cameras-tab-menu" onclick="openSecondLevel(event, 'second-level-cameras', 'top-brands-cameras', 'cameras-tab-menu')">
                                    <a><span class="first-menu-tab-title">Cameras</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="lenses-tab-menu" class="mgz-tabs-tab-title lenses-tab-menu" onclick="openSecondLevel(event, 'second-level-lenses', 'top-brands-lenses', 'lenses-tab-menu')">
                                    <a><span class="first-menu-tab-title">Lenses</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="lightstudio-tab-menu" class="mgz-tabs-tab-title lightstudio-tab-menu" onclick="openSecondLevel(event, 'second-level-lightstudio', 'top-brands-lightingandstudio', 'lightstudio-tab-menu')">
                                    <a><span class="first-menu-tab-title">Lighting &amp; Studio</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="photoacce-tab-menu" class="mgz-tabs-tab-title photoacce-tab-menu" onclick="openSecondLevel(event, 'second-level-photoacce', 'top-brands-photoaccessories', 'photoacce-tab-menu')">
                                    <a><span class="first-menu-tab-title">Photo Accessories</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="optics-tab-menu" class="mgz-tabs-tab-title optics-tab-menu" onclick="openSecondLevel(event, 'second-level-optics', 'top-brands-optics', 'optics-tab-menu')">
                                    <a><span class="first-menu-tab-title">Optics</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="audiovisual-tab-menu" class="mgz-tabs-tab-title audiovisual-tab-menu" onclick="openSecondLevel(event, 'second-level-audiovisual', 'top-brands-audiovisual', 'audiovisual-tab-menu')">
                                    <a><span class="first-menu-tab-title">Audio &amp; Visual</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="provideo-tab-menu" class="mgz-tabs-tab-title provideo-tab-menu" onclick="openSecondLevel(event, 'second-level-provideo', 'top-brands-provideo', 'provideo-tab-menu')">
                                    <a><span class="first-menu-tab-title">Pro Video</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="smarthome-tab-menu" class="mgz-tabs-tab-title smarthome-tab-menu" onclick="openSecondLevel(event, 'second-level-smarthome', 'top-brands-smarthome', 'smarthome-tab-menu')">
                                    <a><span class="first-menu-tab-title">Smart Home</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="computersmobile-tab-menu" class="mgz-tabs-tab-title computersmobile-tab-menu" onclick="openSecondLevel(event, 'second-level-computersmobile', 'top-brands-computersandmobile', 'computersmobile-tab-menu')">
                                    <a><span class="first-menu-tab-title">Computers &amp; Mobile</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="drones-tab-menu" class="mgz-tabs-tab-title drones-tab-menu" onclick="openSecondLevel(event, 'second-level-drones', 'top-brands-drones', 'drones-tab-menu')">
                                    <a><span class="first-menu-tab-title">Drones</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="electronic-tab-menu" class="mgz-tabs-tab-title electronic-tab-menu" onclick="openSecondLevel(event, 'second-level-electronic', 'top-brands-electronic', 'electronic-tab-menu')">
                                    <a><span class="first-menu-tab-title">Electronic Toys</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="home-tab-menu" class="mgz-tabs-tab-title home-tab-menu" onclick="openSecondLevel(event, 'second-level-home', 'top-brands-home', 'home-tab-menu')">
                                    <a><span class="first-menu-tab-title">Home</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="collectibles-tab-menu" class="mgz-tabs-tab-title">
                                    <a href="https://www.digidirect.com.au/find?q=collectables+merchandise+digital" style="display:flex;background:none;border:none;">
                                        <img src="https://www.digidirect.com.au/media/wysiwyg/main-menu/icons/collectibles.png" style="width: 30px; display: none;">
                                        <span>Collectibles & Merchandise Digital</span>
                                    </a>
                                    <i class="fas mgz-fa-angle-right" style="position: absolute;top: 10px;"></i>
                                </div>

                                <div id="fitness-tab-menu" class="mgz-tabs-tab-title fitness-tab-menu" onclick="openSecondLevel(event, 'second-level-fitness', 'top-brands-fitness', 'fitness-tab-menu')">
                                    <a><span class="first-menu-tab-title">Fitness & Well-being Tech</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="seasonal-tab-menu" class="mgz-tabs-tab-title seasonal-tab-menu" onclick="openSecondLevel(event, 'second-level-seasonal', 'top-brands-seasonal', 'seasonal-tab-menu')">
                                    <a><span class="first-menu-tab-title">Seasonal Tech</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="music-tab-menu" class="mgz-tabs-tab-title music-tab-menu" onclick="openSecondLevel(event, 'second-level-music', 'top-brands-music', 'music-tab-menu')">
                                    <a><span class="first-menu-tab-title">Music Instruments</span> <i class="fas mgz-fa-angle-right"></i> <span class="tabs-opener" style="display: none;"></span></a>
                                </div>

                                <div id="sbc-giftcards" class="mgz-tabs-tab-title">
                                    <a href="https://digidirectgiftcards.viisolutions.com.au/" style="display:flex;background:none;border:none;">
                                        <img src="https://www.digidirect.com.au/media/wysiwyg/main-menu/icons/gift-card.png" style="width: 30px; display: none;">
                                        <span>Gift Cards</span>
                                    </a>
                                    <i class="fas mgz-fa-angle-right" style="position: absolute;top: 10px;"></i>
                                </div>

                            </div>

                            <div id="second-level-menu" class="mgz-tabs-content slide-left-to-right">

                                <div id="return-to-first-level" onclick="returnToFirstLevel()"><i class="fas fa-angle-left" style="margin-right: 10px"></i>Previous</div>

                                <div id="second-level-cameras" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Cameras</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'dslr-cameras')">DSLR Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'mirrorless-cameras')">Mirrorless Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'action-cameras')">Action Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'compact-cameras')">Compact Cameras</button>
                                            </div>

                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Cameras</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'film-cameras')">Film Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'medium-format-cameras')">Medium Format Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'instant-cameras')">Instant Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'specialty-cameras')">Specialty Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'rangefinder-cameras')">Rangefinder Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'waterproof-cameras')">Waterproof Cameras</button>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-lenses" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">
                                            <h3>Lenses</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'slr-lenses')">SLR Lenses</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'mirrorless-lenses')">Mirrorless Lenses</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'rangefinder-lenses')">Rangefinder Lenses</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'digital-cine-lenses')">Digital Cine Lenses</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Lenses</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'medium-format-lenses')">Medium Format Lenses</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'special-effect-lenses')">Special Effect Lenses</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'lense-filter')">Lens Filter</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'lens-accessories')">Lens Accessories</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-lightstudio" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Lighting & Studio</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'camera-flashes')">Camera Flashes</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'monolights-and-strobes')">Monolights & Strobes</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'continuous-lights')">Continuous Lights</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'light-modifiers-and-reflectors')">Light Modifiers & Reflectors</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Lighting & Studio</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'radio-and-optical-slaves')">Radio & Optical Slaves</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'flash-accessories')">Flash Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'on-camera-lighting')">On Camera Lighting</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'backgrounds-and-supports')">Backgrounds & Supports</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-photoacce" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Photo Accessories</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'tripods-and-stabilizers')">Tripods & Stabilizers</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'bags-and-cases')">Bags & Cases</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'memory-cards-and-drives')">Memory Cards & Drives</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Photo Accessories</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'camera-system-accessories')">Camera System Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'batteries-and-power-supplies')">Batteries & Power Supplies</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'printers-and-scanners')">Printers & Scanners</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'albums-and-frames')">Albums & Frames</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'film-darkroom-and-video-tapes')">Film Darkroom & Video Tapes</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'usb-cables-and-adapters')">USB Cables & Adapters</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'travel-accessories')">Travel Accessories</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-optics" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Optics</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'binoculars-and-accessories')">Binoculars & Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'spotting-scopes-and-accessories')">Spotting Scopes & Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'laser-rangefinders')">Laser Rangefinders</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'monoculars')">Monoculars</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Optics</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'telescopes')">Telescopes</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-audiovisual" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Audio & Visual</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'microphones')">Microphones</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'audio-recorders')">Audio Recorders</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'headphones')">Headphones</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'cables')">Cables</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Audio & Visual</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'projection-screens')">Projection Screens</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'speakers')">Speakers</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'audio-interfaces-and-mixers')">Audio Interface & Mixers</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'software')">Software</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'monitors')">Monitors</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'drawing-tablets')">Drawing Tablets</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-provideo" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Pro Video</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'pro-video-cameras')">Pro Video Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'video-monitors-and-recorders')">Video Monitors & Recorders</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'white-balance-and-calibration')">White Balance & Calibration</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'video-rigs')">Video Rigs</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Pro Video</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'live-streaming')">Live Streaming</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'tools-and-consumables')">Tools & Consumables</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-smarthome" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Smart Home</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'security-cameras')">Security Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'home-automation')">Home Automation</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'small-appliances')">Small Appliances</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'health-fitness-and-wearables')">Health Fitness & Wearables</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Smart Home</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'lighting')">Lighting</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'lifestyle-gadgets')">Lifestyle Gadgets</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-computersmobile" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Computers & Mobile</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'laptops-and-notebooks')">Laptops & Notebooks</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'mobile-phones-and-accessories')">Mobile Phones & Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'gaming')">Gaming</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'tablets-ipads-and-surface')">Tablets IPads & Surface</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'printers-and-scanners2')">Printers & Scanners</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'monitors-and-accessories')">Monitors & Accessories</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'desktop-and-parts')">Desktop & Parts</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Computers & Mobile</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'computer-accessories')">Computer Accessories</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-drones" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Drones</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'drones-uav')">Drones UAV</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'drone-cameras')">Drone Cameras</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'drone-gimbals')">Drone Gimbals</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'drone-accessories')">Drone Accessories</button>
                                            </div>


                                            <h3 style="font-size: 14px; font-weight: 600; color: #000; margin-top: 40px;">Also In Drones</h3>

                                            <div class="tab">
                                                <button class="tablinks" onclick="openThirdLevel(event, 'underwater-rovs')">Underwater ROVs</button>
                                                <button class="tablinks" onclick="openThirdLevel(event, 'robotics')">Robotics</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-electronic" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Electronic Toys</h3>
                                            <span><a class href="https://www.digidirect.com.au/find?q=electronic+toys">View All Electronic Toys</a></span>
                                            <div class="tab">
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=rc+toys">RC Toys</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=toys+ride+on">Toys Ride-On</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=electronic">Electronic</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-home" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Home</h3>
                                            <span><a class href="https://www.digidirect.com.au/find?q=home+category">View All Home</a></span>
                                            <div class="tab">
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=homeware">Homeware</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=small+appliances">Small Appliances</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-fitness" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Fitness & Well-being Tech</h3>
                                            <span><a class href="https://www.digidirect.com.au/find?q=fitness+wellbeing+tech">View All Fitness & Well-being Tech</a></span>
                                            <div class="tab">
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=baby">Baby</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=wearables">Wearables</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-seasonal" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Seasonal Tech</h3>

                                            <div class="tab">
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=seasonal+tech">Christmas</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="second-level-music" class="second-level-content">
                                    <div class="menu-raw-content">

                                        <div class="menu-second-level">

                                            <h3>Music Instruments</h3>
                                            <span><a class href="https://www.digidirect.com.au/find?q=music+instruments">View All Music Instruments</a></span>
                                            <div class="tab">
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=guitars">Guitars</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=guitars+acoustic">Guitars - Acoustic</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=guitars+children">Guitars - Children</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=guitars+electric">Guitars - Electric</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=music+drums">Music - Drums</a>
                                                <a class="tablinks" href="https://www.digidirect.com.au/find?q=music+keyboards">Music - Keyboards</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </div>

                            <div id="third-level-menu" class="slide-left-to-right">
                                <div class="menu-third-level">
                                    <span class="return-to-second-layer" onclick="returnToSecondLayer();"><i class="fas fa-angle-left"></i><h3>Previous</h3></span>

                                    <div id="dslr-cameras" class="tabcontent">
                                        <h3>DSLR Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=cameras-dslr-cameras">View All DSLR Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=cameras-dslr-cameras/canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cameras-dslr-cameras/nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cameras-dslr-cameras/fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cameras-dslr-cameras/pentax">Pentax</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cameras-dslr-cameras/ruggard">Ruggard</a>
                                        </div>

                                    </div>

                                    <div id="mirrorless-cameras" class="tabcontent">
                                        <h3>Mirrorless Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=mirrorless+cameras">View All Mirrorless Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+cameras+sony">Sony</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+cameras+sigma">Sigma</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+cameras+canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+cameras+fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+cameras+leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+cameras+nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+cameras+olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+cameras+panasonic">Panasonic</a>
                                        </div>

                                    </div>

                                    <div id="action-cameras" class="tabcontent">
                                        <h3>Action Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=action+cameras">View All Action Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=action+cameras+dji">DJI</a>
                                            <a class href="https://www.digidirect.com.au/find?q=action+cameras+gopro">GoPro</a>
                                            <a class href="https://www.digidirect.com.au/find?q=action+cameras+insta360">Insta360</a>
                                        </div>

                                    </div>

                                    <div id="compact-cameras" class="tabcontent">
                                        <h3>Compact Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=compact+cameras">View All Compact Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=compact+cameras+sony">Sony</a>
                                            <a class href="https://www.digidirect.com.au/find?q=compact+cameras+panasonic">Panasonic</a>
                                            <a class href="https://www.digidirect.com.au/find?q=compact+cameras+canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=compact+cameras+leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/find?q=compact+cameras+nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=compact+cameras+olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/find?q=compact+cameras+ricoh">Ricoh</a>
                                            <a class href="https://www.digidirect.com.au/find?q=compact+cameras+fujifilm">Fujifilm</a>
                                        </div>

                                    </div>


                                    <div id="film-cameras" class="tabcontent">
                                        <h3>Film Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=film+cameras">View All Film Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=film+cameras+lomography">LOMOGRAPHY</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+cameras+ilford">ILFORD</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+cameras+kodak">Kodak</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+cameras+leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+cameras+polaroid">Polaroid</a>
                                        </div>

                                    </div>

                                    <div id="medium-format-cameras" class="tabcontent">
                                        <h3>Medium Format Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=medium+format+cameras">View All Medium Format Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=medium+format+cameras+fujifilm">Fujifilm</a>
                                        </div>

                                    </div>

                                    <div id="instant-cameras" class="tabcontent">
                                        <h3>Instant Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=instant+cameras">View All Instant Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=instant+cameras+fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/find?q=instant+cameras+lomography">LOMOGRAPHY</a>
                                            <a class href="https://www.digidirect.com.au/find?q=instant+cameras+polaroid">Polaroid</a>
                                            <a class href="https://www.digidirect.com.au/find?q=instant+cameras+kodak">Kodak</a>
                                        </div>

                                    </div>

                                    <div id="specialty-cameras" class="tabcontent">
                                        <h3>Specialty Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=specialty+cameras">View All Specialty Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=specialty+cameras+insta360">Insta360</a>
                                            <a class href="https://www.digidirect.com.au/find?q=specialty+cameras+gerber">Gerber</a>
                                            <a class href="https://www.digidirect.com.au/find?q=specialty+cameras+boly">Boly</a>
                                            <a class href="https://www.digidirect.com.au/find?q=specialty+cameras+bushnell">Bushnell</a>
                                            <a class href="https://www.digidirect.com.au/find?q=specialty+cameras+minox">Minox</a>
                                            <a class href="https://www.digidirect.com.au/find?q=specialty+cameras+stealth+cam">Stealth Cam</a>
                                            <a class href="https://www.digidirect.com.au/find?q=specialty+cameras+sionyx">SiOnyx</a>
                                            <a class href="https://www.digidirect.com.au/find?q=specialty+cameras+leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/find?q=specialty+cameras+ricoh">Ricoh</a>
                                        </div>

                                    </div>

                                    <div id="rangefinder-cameras" class="tabcontent">
                                        <h3>Rangefinder Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=rangefinder+cameras">View All Rangefinder Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=rangefinder+cameras+leica">Leica</a>
                                        </div>

                                    </div>

                                    <div id="waterproof-cameras" class="tabcontent">
                                        <h3>Waterproof Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=waterproof+cameras">View All Waterproof Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=waterproof+cameras+olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/find?q=waterproof+cameras+gopro">GoPro</a>
                                        </div>

                                    </div>


                                    <div id="slr-lenses" class="tabcontent">
                                        <h3>SLR Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=slr+lenses">View All SLR Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=slr+lenses+nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=slr+lenses+sigma">Sigma</a>
                                            <a class href="https://www.digidirect.com.au/find?q=slr+lenses+samyang">SAMYANG</a>
                                            <a class href="https://www.digidirect.com.au/find?q=slr+lenses+canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=slr+lenses+zeiss">Zeiss</a>
                                            <a class href="https://www.digidirect.com.au/find?q=slr+lenses+laowa">Laowa</a>
                                            <a class href="https://www.digidirect.com.au/find?q=slr+lenses+tamron">Tamron</a>
                                            <a class href="https://www.digidirect.com.au/find?q=slr+lenses+tokina">Tokina</a>
                                            <a class href="https://www.digidirect.com.au/find?q=slr+lenses+lensbaby">LensBaby</a>
                                        </div>

                                    </div>

                                    <div id="mirrorless-lenses" class="tabcontent">
                                        <h3>Mirrorless Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses">View All Mirrorless Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+sony">Sony</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+laowa">Laowa</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+lensbaby">LensBaby</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+samyang">SAMYANG</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+panasonic">Panasonic</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+sigma">Sigma</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mirrorless+lenses+zeiss">Zeiss</a>
                                        </div>

                                    </div>

                                    <div id="rangefinder-lenses" class="tabcontent">
                                        <h3>Rangefinder Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=rangefinder+lenses">View All Rangefinder Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=rangefinder+lenses+laowa">Laowa</a>
                                            <a class href="https://www.digidirect.com.au/find?q=rangefinder+lenses+leica">Leica</a>
                                        </div>

                                    </div>

                                    <div id="digital-cine-lenses" class="tabcontent">
                                        <h3>Digital Cine Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=/digital+cine+lenses">View All Digital Cine Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=digital+cine+lenses+samyang">SAMYANG</a>
                                            <a class href="https://www.digidirect.com.au/find?q=digital+cine+lenses+slr-magic">SLR Magic</a>
                                            <a class href="https://www.digidirect.com.au/find?q=digital+cine+lenses+tokina">Tokina</a>
                                            <a class href="https://www.digidirect.com.au/find?q=digital+cine+lenses+laowa">Laowa</a>
                                            <a class href="https://www.digidirect.com.au/find?q=digital+cine+lenses+sigma">Sigma</a>
                                            <a class href="https://www.digidirect.com.au/find?q=digital+cine+lenses+canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=digital+cine+lenses+fujifilm">Fujifilm</a>
                                        </div>

                                    </div>


                                    <div id="medium-format-lenses" class="tabcontent">
                                        <h3>Medium Format Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=medium+format+lenses">View All Medium Format Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=medium+format+lenses+fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/find?q=medium+format+lenses+leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/find?q=medium+format+lenses+laowa">Laowa</a>
                                        </div>

                                    </div>

                                    <div id="special-effect-lenses" class="tabcontent">
                                        <h3>Special Effect Lenses</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=special+effects+lenses">View All Special Effect Lenses</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=special+effects+lenses+lensbaby">LensBaby</a>
                                            <a class href="https://www.digidirect.com.au/find?q=special+effects+lenses+laowa">Laowa</a>
                                            <a class href="https://www.digidirect.com.au/find?q=special+effects+lenses+slr-magic">SLR Magic</a>
                                        </div>

                                    </div>

                                    <div id="lense-filter" class="tabcontent">
                                        <h3>Lens Filter</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=lens+filters">View All Lens Filter</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=uv+clear+skylight+filters">UV Clear & Skylight Filters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=polarising+filters">Polarising Filters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=neutral+density+filters">Neutral Density Filters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=filter+kits">Filter Kits</a>
                                            <a class href="https://www.digidirect.com.au/find?q=close+up+filters">Close Up Filters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drone+filters">Drone Filters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=special+effect+filters">Special Effect Filters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=black+and+white+contrast+filters">Black & White Contrast Filters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=ir+filters">IR Filters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cokin+system">Cokin System</a>
                                            <a class href="https://www.digidirect.com.au/find?q=haida+system">Haida System</a>
                                            <a class href="https://www.digidirect.com.au/find?q=filter+accessories">Filter Accessories</a>
                                        </div>

                                    </div>

                                    <div id="lens-accessories" class="tabcontent">
                                        <h3>Lens Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=lens+accessories">View All Lens Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=lens+adapters">Lens Adapters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=teleconverters">Teleconverters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=lens+caps">Lens Caps</a>
                                            <a class href="https://www.digidirect.com.au/find?q=lens+hoods">Lens Hoods</a>
                                            <a class href="https://www.digidirect.com.au/find?q=lens+cap+savers">Lens Cap Savers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=extension+tubes">Extension Tubes</a>
                                            <a class href="https://www.digidirect.com.au/find?q=lens+supports">Lens Supports</a>
                                            <a class href="https://www.digidirect.com.au/find?q=conversion+lenses">Conversion Lenses</a>

                                        </div>
                                    </div>


                                    <div id="camera-flashes" class="tabcontent">
                                        <h3>Camera Flashes</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=camera+flashes">View All Camera Flashes</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=camera+flashes+godox">Godox</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+flashes+hahnel">Hahnel</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+flashes+nissin">Nissin</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+flashes+canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+flashes+nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+flashes+voking">Voking</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+flashes+sony">Sony</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+flashes+nanlite">Nanlite</a>
                                        </div>

                                    </div>

                                    <div id="monolights-and-strobes" class="tabcontent">
                                        <h3>Monolights & Strobes</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=monolights-and-strobes">View All Monolights & Strobes</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=monolights+and+strobes+elinchrom">Elinchrom</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monolights+and+strobes+jinbei">Jinbei</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monolights+and+strobes+godox">Godox</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monolights+and+strobes+phottix">PHOTTIX</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monolights+and+strobes+aputure">Aputure</a>
                                        </div>

                                    </div>

                                    <div id="continuous-lights" class="tabcontent">
                                        <h3>Continuous Lights</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=continuous+lights">View All Continuous Lights</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=continuous+lights+nanlite">Nanlite</a>
                                            <a class href="https://www.digidirect.com.au/find?q=continuous+lights+godox">Godox</a>
                                            <a class href="https://www.digidirect.com.au/find?q=continuous+lights+aputure">Aputure</a>
                                            <a class href="https://www.digidirect.com.au/find?q=continuous+lights+smallrig">SmallRig</a>
                                            <a class href="https://www.digidirect.com.au/find?q=continuous+lights+phottix">PHOTTIX</a>
                                            <a class href="https://www.digidirect.com.au/find?q=continuous+lights+lupo">Lupo</a>
                                            <a class href="https://www.digidirect.com.au/find?q=continuous+lights+glanz">Glanz</a>
                                            <a class href="https://www.digidirect.com.au/find?q=continuous+lights+rotolight">RotoLight</a>
                                            <a class href="https://www.digidirect.com.au/find?q=continuous+lights+pixel">Pixel</a>
                                        </div>

                                    </div>

                                    <div id="light-modifiers-and-reflectors" class="tabcontent">
                                        <h3>Light Modifiers & Reflectors</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=light+modifiers+and+reflectors">View All Light Modifiers & Reflectors</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=light+modifiers+and+reflectors+softboxes">Softboxes</a>
                                            <a class href="https://www.digidirect.com.au/find?q=light+modifiers+and+reflectors+umbrellas">Umbrellas</a>
                                            <a class href="https://www.digidirect.com.au/find?q=light+modifiers+and+reflectors+reflectors">Reflectors</a>
                                            <a class href="https://www.digidirect.com.au/find?q=light+modifiers+and+reflectors+snoots+grids+and+light+shapers">Snoots Grids & Light Shapers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=light+modifiers+and+reflectors+beauty+dishes">Beauty Dishes</a>
                                            <a class href="https://www.digidirect.com.au/find?q=light+modifiers+and+reflectors+speed+rings">Speed Rings</a>
                                        </div>

                                    </div>


                                    <div id="radio-and-optical-slaves" class="tabcontent">
                                        <h3>Radio & Optical Slaves</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=radio-and-optical-slaves">View All Radio & Optical Slaves</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=radio+and+infrared+transmitters">Radio & Infrared Transmitters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=radio+slave+cables">Radio Slave Cables</a>
                                            <a class href="https://www.digidirect.com.au/find?q=slave+accessories">Slave Accessories</a>
                                        </div>

                                    </div>

                                    <div id="flash-accessories" class="tabcontent">
                                        <h3>Flash Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=flash-accessories">View All Flash Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=flash-modifiers">Flash Modifiers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=ttl-cords-and-accessories">TTL Cords & Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=macro-and-ringlight-accessories">Macro & Ringlight Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=pc-sync-and-hot-shoe-adapters">PC Sync & Hot Shoe Adapters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=pc-sync-cords">PC Sync Cords</a>
                                            <a class href="https://www.digidirect.com.au/find?q=shoe-mount-adapters">Shoe Mount Adapters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=other-flash-accessories">Other Flash Accessories</a>
                                        </div>

                                    </div>

                                    <div id="on-camera-lighting" class="tabcontent">
                                        <h3>On Camera Lighting</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=on-camera-lighting">View All On Camera Lighting</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=batteries-and-power">Batteries & Power</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mounts-and-brackets">Mounts & Brackets</a>
                                            <a class href="https://www.digidirect.com.au/find?q=articulating-arms">Articulating Arms</a>
                                            <a class href="https://www.digidirect.com.au/find?q=shoe-mount-adapters">Shoe Mount Adapters</a>
                                        </div>

                                    </div>

                                    <div id="backgrounds-and-supports" class="tabcontent">
                                        <h3>Backgrounds & Supports</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=backgrounds-and-supports">View All Backgrounds & Supports</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=backgrounds+and+supports+lastolite">Lastolite</a>
                                            <a class href="https://www.digidirect.com.au/find?q=backgrounds+and+supports+superior">Superior</a>
                                            <a class href="https://www.digidirect.com.au/find?q=backgrounds+and+supports+glanz">Glanz</a>
                                            <a class href="https://www.digidirect.com.au/find?q=backgrounds+and+supports+xlite">XLITE</a>
                                            <a class href="https://www.digidirect.com.au/find?q=backgrounds+and+supports+manfrotto">Manfrotto</a>
                                            <a class href="https://www.digidirect.com.au/find?q=backgrounds+and+supports+phottix">PHOTTIX</a>
                                            <a class href="https://www.digidirect.com.au/find?q=backgrounds+and+supports+haldex">Haldex</a>
                                            <a class href="https://www.digidirect.com.au/find?q=backgrounds+and+supports+elgato">Elgato</a>
                                            <a class href="https://www.digidirect.com.au/find?q=backgrounds+and+supports+jinbei">Jinbei</a>
                                        </div>

                                    </div>

                                    <div id="tripods-and-stabilizers" class="tabcontent">
                                        <h3>Tripods & Stabilizers</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=tripods+and+stabilizers">View All Tripods & Stabilizers</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=tripods">Tripods</a>
                                            <a class href="https://www.digidirect.com.au/find?q=tripod+legs">Tripod Legs</a>
                                            <a class href="https://www.digidirect.com.au/find?q=tripod+accessories">Tripod Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monopods">Monopods</a>
                                            <a class href="https://www.digidirect.com.au/find?q=ball+heads">Ball Heads</a>
                                            <a class href="https://www.digidirect.com.au/find?q=pan+and+tilt+heads">Pan & Tilt Heads</a>
                                            <a class href="https://www.digidirect.com.au/find?q=pistol+grip+heads">Pistol Grip Heads</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+heads">Video Heads</a>
                                            <a class href="https://www.digidirect.com.au/find?q=tripod+cases">Tripod Cases</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+mounts">Camera Mounts</a>
                                            <a class href="https://www.digidirect.com.au/find?q=quick+release+plates">Quick Release Plates</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+stabilizers">Camera Stabilizers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=dollies+and+sliders">Dollies & Sliders</a>
                                        </div>

                                    </div>

                                    <div id="bags-and-cases" class="tabcontent">
                                        <h3>Bags & Cases</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=bags+and+cases">View All Bags & Cases</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=shoulder+bags">Shoulder Bags</a>
                                            <a class href="https://www.digidirect.com.au/find?q=holster+cases">Holster Cases</a>
                                            <a class href="https://www.digidirect.com.au/find?q=backpacks">Backpacks</a>
                                            <a class href="https://www.digidirect.com.au/find?q=rolling+cases">Rolling Cases</a>
                                            <a class href="https://www.digidirect.com.au/find?q=fashion+camera+bags">Fashion Camera Bags</a>
                                            <a class href="https://www.digidirect.com.au/find?q=waist+packs">Waist Packs</a>
                                            <a class href="https://www.digidirect.com.au/find?q=sling+bags">Sling Bags</a>
                                            <a class href="https://www.digidirect.com.au/find?q=pouches">Pouches</a>
                                            <a class href="https://www.digidirect.com.au/find?q=hard+cases">Hard Cases</a>
                                            <a class href="https://www.digidirect.com.au/find?q=lens+cases">Lens Cases</a>
                                            <a class href="https://www.digidirect.com.au/find?q=gear+protection">Gear Protection</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+straps+and+harnesses">Camera Straps & Harnesses</a>
                                            <a class href="https://www.digidirect.com.au/find?q=inserts+and+compartments">Inserts & Compartments</a>
                                            <a class href="https://www.digidirect.com.au/find?q=bag+and+case+accessories">Bag & Case Accessories</a>
                                        </div>

                                    </div>

                                    <div id="memory-cards-and-drives" class="tabcontent">
                                        <h3>Memory Cards & Drives</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=memory+cards+and+drives">View All Memory Cards & Drives</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=memory+cards">Memory Cards</a>
                                            <a class href="https://www.digidirect.com.au/find?q=memory+card+readers">Memory Card Readers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=usb+drives">USB Drives</a>
                                            <a class href="https://www.digidirect.com.au/find?q=solid+state+drives">Solid State Drives</a>
                                            <a class href="https://www.digidirect.com.au/find?q=hdds">HDDs</a>
                                        </div>

                                    </div>

                                    <div id="camera-system-accessories" class="tabcontent">
                                        <h3>Camera System Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=camera+system+accessories">View All Camera System Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=battery+grips">Battery Grips</a>
                                            <a class href="https://www.digidirect.com.au/find?q=remote+controls">Remote Controls</a>
                                            <a class href="https://www.digidirect.com.au/find?q=lcd+and+viewfinders+accessories">LCD & Viewfinders Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=light+meters">Light Meters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+cleaning">Camera Cleaning</a>
                                            <a class href="https://www.digidirect.com.au/find?q=gps+and+wireless+equipment">GPS & Wireless Equipment</a>
                                            <a class href="https://www.digidirect.com.au/find?q=hand+grips">Hand Grips</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+cables+and+adapters">Camera Cables & Adapters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=body+caps">Body Caps</a>
                                            <a class href="https://www.digidirect.com.au/find?q=action+cameras+accessories">Action Cameras Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=underwater+housings">Underwater Housings</a>
                                            <a class href="https://www.digidirect.com.au/find?q=photo+gifts">Photo Gifts</a>
                                        </div>

                                    </div>

                                    <div id="batteries-and-power-supplies" class="tabcontent">
                                        <h3>Batteries & Power Supplies</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=batteries+and-power+supplies">View All Batteries & Power Supplies</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=camera+batteries">Camera Batteries</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+battery+chargers">Camera Battery Chargers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=camera+ac+dc+adapters">Camera AC DC Adapters</a>
                                            <a class href="https://www.digidirect.com.au/find?q=power+banks">Power Banks</a>
                                            <a class href="https://www.digidirect.com.au/find?q=power+boards">Power Boards</a>
                                        </div>

                                    </div>

                                    <div id="printers-and-scanners" class="tabcontent">
                                        <h3>Printers & Scanners</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=printers+and+scanners">View All Printers & Scanners</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=printers">Printers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=scanners">Scanners</a>
                                            <a class href="https://www.digidirect.com.au/find?q=ink">Ink</a>
                                            <a class href="https://www.digidirect.com.au/find?q=printer+accessories">Printer Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=scanner+accessories">Scanner Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=paper">Paper</a>
                                        </div>

                                    </div>

                                    <div id="albums-and-frames" class="tabcontent">
                                        <h3>Albums & Frames</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=albums+and+frames">View All Albums & Frames</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=albums+and+frames+profile">Profile</a>
                                            <a class href="https://www.digidirect.com.au/find?q=albums+and+frames+ur1">UR1</a>
                                            <a class href="https://www.digidirect.com.au/find?q=albums+and+frames+polaroid">Polaroid</a>
                                            <a class href="https://www.digidirect.com.au/find?q=albums+and+frames+hama">Hama</a>
                                            <a class href="https://www.digidirect.com.au/find?q=albums+and+frames+glanz">Glanz</a>
                                            <a class href="https://www.digidirect.com.au/find?q=albums+and+frames+fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/find?q=albums+and+frames+ap">AP</a>
                                        </div>

                                    </div>

                                    <div id="film-darkroom-and-video-tapes" class="tabcontent">
                                        <h3>Film Darkroom & Video Tapes</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=film+darkroom+and+video+tapes">View All Film Darkroom & Video Tapes</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=film+darkroom+and+video+tapes+paterson">PATERSON</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+darkroom+and+video+tapes+ilford">ILFORD</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+darkroom+and+video+tapes+kodak">Kodak</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+darkroom+and+video+tapes+fujifilm">Fujifilm</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+darkroom+and+video+tapes+lomography">LOMOGRAPHY</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+darkroom+and+video+tapes+polaroid">Polaroid</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+darkroom+and+video+tapes+foma">Foma</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+darkroom+and+video+tapes+ap">AP</a>
                                            <a class href="https://www.digidirect.com.au/find?q=film+darkroom+and+video+tapes+cinestill">Cinestill</a>
                                        </div>

                                    </div>

                                    <div id="usb-cables-and-adapters" class="tabcontent">
                                        <h3>USB Cables & Adapters</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=usb+cables+and+adapters">View All USB Cables & Adapters</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=usb+cables+and+adapters+tether+tools">Tether Tools</a>
                                            <a class href="https://www.digidirect.com.au/find?q=usb+cables+and+adapters+klik">Klik</a>
                                            <a class href="https://www.digidirect.com.au/find?q=usb+cables+and+adapters+glanz">Glanz</a>
                                            <a class href="https://www.digidirect.com.au/find?q=usb+cables+and+adapters+olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/find?q=usb+cables+and+adapters+leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/find?q=usb+cables+and+adapters+sigma">Sigma</a>
                                            <a class href="https://www.digidirect.com.au/find?q=usb+cables+and+adapters+angelbird">Angelbird</a>
                                            <a class href="https://www.digidirect.com.au/find?q=usb+cables+and+adapters+klarus">Klarus</a>
                                        </div>

                                    </div>

                                    <div id="travel-accessories" class="tabcontent">
                                        <h3>Travel Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=travel+accessories">View All Travel Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=case+and+luggage+locks">Case & Luggage Locks</a>
                                            <a class href="https://www.digidirect.com.au/find?q=travel+adaptors">Travel Adaptors</a>
                                            <a class href="https://www.digidirect.com.au/find?q=travel+essentials">Travel Essentials</a>
                                        </div>

                                    </div>

                                    <div id="binoculars-and-accessories" class="tabcontent">
                                        <h3>Binoculars & Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=binoculars+and+accessories">View All Binoculars & Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=binoculars">Binoculars</a>
                                            <a class href="https://www.digidirect.com.au/find?q=binocular+accessories">Binocular Accessories</a>
                                        </div>

                                    </div>

                                    <div id="spotting-scopes-and-accessories" class="tabcontent">
                                        <h3>Spotting Scopes & Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=spotting+scopes+and+accessories">View All Spotting Scopes & Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=spotting+scopes">Spotting Scopes</a>
                                            <a class href="https://www.digidirect.com.au/find?q=eyepieces">Eyepieces</a>
                                            <a class href="https://www.digidirect.com.au/find?q=spotting+scopes+accessories">Spotting Scopes Accessories</a>
                                        </div>

                                    </div>

                                    <div id="laser-rangefinders" class="tabcontent">
                                        <h3>Laser Rangefinders</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=laser+rangefinders">View All Laser Rangefinders</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=laser+rangefinders+nikon">Nikon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=laser+rangefinders+leica">Leica</a>
                                            <a class href="https://www.digidirect.com.au/find?q=laser+rangefinders+bushnell">Bushnell</a>
                                            <a class href="https://www.digidirect.com.au/find?q=laser+rangefinders+simmons">Simmons</a>
                                        </div>

                                    </div>

                                    <div id="monoculars" class="tabcontent">
                                        <h3>Monoculars</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=monoculars">View All Monoculars</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=monoculars+zeiss">Zeiss</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monoculars+sionyx">SiOnyx</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monoculars+konus">Konus</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monoculars+bushnell">Bushnell</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monoculars+celestron">Celestron</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monoculars+leica">Leica</a>
                                        </div>

                                    </div>


                                    <div id="telescopes" class="tabcontent">
                                        <h3>Telescopes</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=telescopes">View All Telescopes</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=telescopes+skywatcher">Skywatcher</a>
                                            <a class href="https://www.digidirect.com.au/find?q=telescopes+zeiss">Zeiss</a>
                                            <a class href="https://www.digidirect.com.au/find?q=telescopes+meade">Meade</a>
                                            <a class href="https://www.digidirect.com.au/find?q=telescopes+celestron">Celestron</a>
                                        </div>

                                    </div>

                                    <div id="microphones" class="tabcontent">
                                        <h3>Microphones</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=microphones">View All Microphones</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=microphones+wireless+microphones">Wireless Microphones</a>
                                            <a class href="https://www.digidirect.com.au/find?q=microphones+directional+microphones">Directional Microphones</a>
                                            <a class href="https://www.digidirect.com.au/find?q=microphones+stereo+microphones">Stereo Microphones</a>
                                            <a class href="https://www.digidirect.com.au/find?q=microphones+lavalier+microphones">Lavalier Microphones</a>
                                            <a class href="https://www.digidirect.com.au/find?q=microphones+specialty+microphones">Specialty Microphones</a>
                                            <a class href="https://www.digidirect.com.au/find?q=microphones+microphone+accessories">Microphone Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=microphones+studio+and+broadcast+microphones">Studio & Broadcast Microphones</a>
                                        </div>

                                    </div>

                                    <div id="audio-recorders" class="tabcontent">
                                        <h3>Audio Recorders</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=audio-recorders">View All Audio Recorders</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=audio+recorders+zoom">ZOOM</a>
                                            <a class href="https://www.digidirect.com.au/find?q=audio+recorders+olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/find?q=audio+recorders+saramonic">Saramonic</a>
                                        </div>

                                    </div>

                                    <div id="headphones" class="tabcontent">
                                        <h3>Headphones</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=headphones">View All Headphones</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=headphones+beats">Beats</a>
                                            <a class href="https://www.digidirect.com.au/find?q=headphones+panasonic">Panasonic</a>
                                            <a class href="https://www.digidirect.com.au/find?q=headphones+apple">Apple</a>
                                            <a class href="https://www.digidirect.com.au/find?q=headphones+sennheiser">SENNHEISER</a>
                                            <a class href="https://www.digidirect.com.au/find?q=headphones+boya">Boya</a>
                                            <a class href="https://www.digidirect.com.au/find?q=headphones+logitech">Logitech</a>
                                            <a class href="https://www.digidirect.com.au/find?q=headphones+satechi">Satechi</a>
                                            <a class href="https://www.digidirect.com.au/find?q=headphones+rode">Rode</a>
                                            <a class href="https://www.digidirect.com.au/find?q=headphones+samsung">Samsung</a>
                                        </div>

                                    </div>

                                    <div id="cables" class="tabcontent">
                                        <h3>Cables</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=cables">View All Cables</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=cables+rode">Rode</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cables+tether+tools">Tether Tools</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cables+atomos">Atomos</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cables+kondor+blue">Kondor Blue</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cables+zoom">ZOOM</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cables+boya">Boya</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cables+olympus">Olympus</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cables+otterbox">Otterbox</a>
                                            <a class href="https://www.digidirect.com.au/find?q=cables+sennheiser">SENNHEISER</a>
                                        </div>

                                    </div>

                                    <div id="speakers" class="tabcontent">
                                        <h3>Speakers</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=speakers">View All Speakers</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=speakers+audioengine">Audioengine</a>
                                            <a class href="https://www.digidirect.com.au/find?q=speakers+ultimate+ears">Ultimate Ears</a>
                                            <a class href="https://www.digidirect.com.au/find?q=speakers+creative">Creative</a>
                                            <a class href="https://www.digidirect.com.au/find?q=speakers+logitech">Logitech</a>
                                            <a class href="https://www.digidirect.com.au/find?q=speakers+boya">Boya</a>
                                            <a class href="https://www.digidirect.com.au/find?q=speakers+mbeat">mbeat</a>
                                        </div>

                                    </div>

                                    <div id="audio-interfaces-and-mixers" class="tabcontent">
                                        <h3>Audio Interfaces & Mixers</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=audio+interfaces+and+mixers">View All Audio Interfaces & Mixers</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=audio+interfaces+and+mixers+zoom">ZOOM</a>
                                            <a class href="https://www.digidirect.com.au/find?q=audio+interfaces+and+mixers+saramonic">Saramonic</a>
                                            <a class href="https://www.digidirect.com.au/find?q=audio+interfaces+and+mixers+rode">Rode</a>
                                            <a class href="https://www.digidirect.com.au/find?q=audio+interfaces+and+mixers+astro+gaming">Astro Gaming</a>
                                            <a class href="https://www.digidirect.com.au/find?q=audio+interfaces+and+mixers+boya">Boya</a>
                                            <a class href="https://www.digidirect.com.au/find?q=audio+interfaces+and+mixers+azden">Azden</a>
                                        </div>

                                    </div>

                                    <div id="software" class="tabcontent">
                                        <h3>Software</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=audio+and+visual+software">View All Software</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=audio+and+visual+software+x-rite">X-Rite</a>
                                            <a class href="https://www.digidirect.com.au/find?q=audio+and+visual+software+datacolor">Datacolor</a>
                                            <a class href="https://www.digidirect.com.au/find?q=audio+and+visual+software+loupedeck">Loupedeck</a>
                                        </div>

                                    </div>

                                    <div id="monitors" class="tabcontent">
                                        <h3>Monitors</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=computers+mobile+monitors">View All Monitors</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=computers+mobile+monitors+monitors+home+business">Home & Business</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computers+mobile+monitors+monitors+gaming">Gaming</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computers+mobile+monitors+monitors+curved+screen">Curved Screen</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computers+mobile+monitors+monitors+touchscreen">Touchscreen</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computers+mobile+monitors+monitors+professional">Professional</a>
                                        </div>

                                    </div>

                                    <div id="drawing-tablets" class="tabcontent">
                                        <h3>Drawing Tablets</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=drawing+tablets">View All Drawing Tablets</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=drawing+tablets+wacom">Wacom</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drawing+tablets+huion">Huion</a>
                                        </div>

                                    </div>

                                    <div id="pro-video-cameras" class="tabcontent">
                                        <h3>Pro Video Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=pro+video+cameras">View All Pro Video Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=pro+video+cameras+sony">Sony</a>
                                            <a class href="https://www.digidirect.com.au/find?q=pro+video+cameras+panasonic">Panasonic</a>
                                            <a class href="https://www.digidirect.com.au/find?q=pro+video+cameras+canon">Canon</a>
                                            <a class href="https://www.digidirect.com.au/find?q=pro+video+cameras+z-cam">Z Cam</a>
                                            <a class href="https://www.digidirect.com.au/find?q=pro+video+cameras+dji">DJI</a>
                                        </div>

                                    </div>

                                    <div id="video-monitors-and-recorders" class="tabcontent">
                                        <h3>Video Monitors & Recorders</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=video+monitors+and+recorders">View All Video Monitors & Recorders</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=video+monitors+and+recorders+accessories">Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+monitors+and+recorders+sunhoods">Sunhoods</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+monitors+and+recorders+stands+and+mounts">Stands & Mounts</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+monitors+and+recorders+video+cables">Video Cables</a>
                                        </div>

                                    </div>

                                    <div id="white-balance-and-calibration" class="tabcontent">
                                        <h3>White Balance & Calibration</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=white+balance+and+calibration">View All White Balance & Calibration</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=white+balance+and+calibration+calibrite">Calibrite</a>
                                            <a class href="https://www.digidirect.com.au/find?q=white+balance+and+calibration+datacolor">Datacolor</a>
                                            <a class href="https://www.digidirect.com.au/find?q=white+balance+and+calibration+x+rite">X-Rite</a>
                                            <a class href="https://www.digidirect.com.au/find?q=white+balance+and+calibration+danes+picta">Danes-Picta</a>
                                            <a class href="https://www.digidirect.com.au/find?q=white+balance+and+calibration+lastolite">Lastolite</a>
                                            <a class href="https://www.digidirect.com.au/find?q=white+balance+and+calibration+eizo">Eizo</a>
                                            <a class href="https://www.digidirect.com.au/find?q=white+balance+and+calibration+lensalign">LENSALIGN</a>
                                        </div>

                                    </div>

                                    <div id="video-rigs" class="tabcontent">
                                        <h3>Video Rigs</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=video+rigs">View All Video Rigs</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=video+rigs+cages">Cages</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+rigs+shoulder+rigs">Shoulder Rigs</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+rigs+follow+focus+systems">Follow Focus Systems</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+rigs+parts">Parts</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+rigs+magic+arms">Magic Arms</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+rigs+matte+box">Matte Box</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+rigs+monitor+mount">Monitor Mount</a>
                                            <a class href="https://www.digidirect.com.au/find?q=video+rigs+top+handle">Top Handle</a>
                                        </div>

                                    </div>


                                    <div id="live-streaming" class="tabcontent">
                                        <h3>Live Streaming</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=live+streaming">View All Live Streaming</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=live+streaming+elgato">Elgato</a>
                                            <a class href="https://www.digidirect.com.au/find?q=live+streaming+rode">Rode</a>
                                            <a class href="https://www.digidirect.com.au/find?q=live+streaming+aten">Aten</a>
                                            <a class href="https://www.digidirect.com.au/find?q=live+streaming+logitech">Logitech</a>
                                            <a class href="https://www.digidirect.com.au/find?q=live+streaming+boya">Boya</a>
                                            <a class href="https://www.digidirect.com.au/find?q=live+streaming+desview">Desview</a>
                                            <a class href="https://www.digidirect.com.au/find?q=live+streaming+z-cam">Z Cam</a>
                                            <a class href="https://www.digidirect.com.au/find?q=live+streaming+panasonic">Panasonic</a>
                                            <a class href="https://www.digidirect.com.au/find?q=live+streaming+blue">Blue</a>
                                        </div>

                                    </div>

                                    <div id="tools-and-consumables" class="tabcontent">
                                        <h3>Tools & Consumables</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=tools+and+consumables">View All Tools & Consumables</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=tools+and+consumables+smallrig">SmallRig</a>
                                            <a class href="https://www.digidirect.com.au/find?q=tools+and+consumables+fve">FVE</a>
                                        </div>

                                    </div>

                                    <div id="security-cameras" class="tabcontent">
                                        <h3>Security Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=security+camera+systems">View All Security Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=security+camera+systems+swann">Swann</a>
                                            <a class href="https://www.digidirect.com.au/find?q=security+camera+systems+tp-link">TP-LINK</a>
                                            <a class href="https://www.digidirect.com.au/find?q=security+camera+systems+eufy">Eufy</a>
                                            <a class href="https://www.digidirect.com.au/find?q=security+camera+systems+ring">Ring</a>
                                            <a class href="https://www.digidirect.com.au/find?q=security+camera+systems+uniview">Uniview</a>
                                        </div>

                                    </div>

                                    <div id="home-automation" class="tabcontent">
                                        <h3>Home Automation</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=home+automation">View All Home Automation</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=home+automation+tp+link">TP-LINK</a>
                                        </div>

                                    </div>

                                    <div id="small-appliances" class="tabcontent">
                                        <h3>Small Appliances</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=small+appliances">View All Small Appliances</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=small+appliances+medisaint">Medisaint</a>
                                        </div>

                                    </div>

                                    <div id="health-fitness-and-wearables" class="tabcontent">
                                        <h3>Health Fitness & Wearables</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=health+fitness+and+wearables">View All Health Fitness & Wearables</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=health+fitness+and+wearables+activity+trackers+smart+watches">Activity Trackers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=health+fitness+and+wearables+smart+watches">Smart Watches</a>
                                            <a class href="https://www.digidirect.com.au/find?q=health+fitness+and+wearables+smart+watch+accessories">Smart Watch Accessories</a>
                                        </div>

                                    </div>


                                    <div id="lighting" class="tabcontent">
                                        <h3>Lighting</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=smart+home+lighting">View All Lighting</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=smart+home+lighting+nitecore">Nitecore</a>
                                            <a class href="https://www.digidirect.com.au/find?q=smart+home+lighting+nanoleaf">Nanoleaf</a>
                                            <a class href="https://www.digidirect.com.au/find?q=smart+home+lighting+klarus">Klarus</a>
                                            <a class href="https://www.digidirect.com.au/find?q=smart+home+lighting+mbeat">mbeat</a>
                                            <a class href="https://www.digidirect.com.au/find?q=smart+home+lighting+olight">Olight</a>
                                            <a class href="https://www.digidirect.com.au/find?q=smart+home+lighting+litra">Litra</a>
                                        </div>

                                    </div>

                                    <div id="lifestyle-gadgets" class="tabcontent">
                                        <h3>Lifestyle Gadgets</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=lifestyle+gadgets">View All Lifestyle Gadgets</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=lifestyle+gadgets+off+grid+power">Off Grid Power</a>
                                            <a class href="https://www.digidirect.com.au/find?q=lifestyle+gadgets+outdoor+equipment">Outdoor Equipment</a>
                                        </div>

                                    </div>

                                    <div id="laptops-and-notebooks" class="tabcontent">
                                        <h3>Laptops & Notebooks</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=laptops+notebooks">View All Laptops & Notebooks</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=laptops+notebooks+gaming+laptops">Gaming Laptops</a>
                                            <a class href="https://www.digidirect.com.au/find?q=laptops+notebooks+business">Business</a>
                                            <a class href="https://www.digidirect.com.au/find?q=laptops+notebooks+home+student">Home & Student</a>
                                            <a class href="https://www.digidirect.com.au/find?q=laptops+notebooks+apple+macbooks">Apple MacBooks</a>
                                            <a class href="https://www.digidirect.com.au/find?q=laptops+notebooks+microsoft+surface">Microsoft Surface</a>
                                            <a class href="https://www.digidirect.com.au/find?q=laptops+notebooks+professional+laptops">Professional Laptops</a>
                                        </div>

                                    </div>

                                    <div id="mobile-phones-and-accessories" class="tabcontent">
                                        <h3>Mobile Phones & Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=mobile+phones+and+accessories">View All Mobile Phones & Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=mobile+phones+and+accessories+mobile+phones">Mobile Phones</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mobile+phones+and+accessories+mobile+accessories">Mobile Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=mobile+phones+and+accessories+sim+plans">Sim Cards & Prepaid Recharge</a>
                                        </div>

                                    </div>

                                    <div id="gaming" class="tabcontent">
                                        <h3>Gaming</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=gaming">View All Gaming</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=gaming+console+accessories">Console Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=gaming+consoles">Consoles</a>
                                            <a class href="https://www.digidirect.com.au/find?q=gaming+games">Games</a>
                                            <a class href="https://www.digidirect.com.au/find?q=gaming+gaming+chairs">Gaming Chairs</a>
                                        </div>

                                    </div>

                                    <div id="tablets-ipads-and-surface" class="tabcontent">
                                        <h3>Tablets IPads & Surface</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=tablets+ipads+surface">View All Tablets IPads & Surface</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=tablets+ipads+surface+apple+ipads">Apple IPads</a>
                                            <a class href="https://www.digidirect.com.au/find?q=tablets+ipads+surface+accessories">Tablet Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=tablets+ipads+surface+samsung+galaxy+tablets">Samsung Galaxy Tablets</a>
                                        </div>

                                    </div>


                                    <div id="printers-and-scanners2" class="tabcontent">
                                        <h3>Printers & Scanners</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=printers+and+scanners">View All Printers & Scanners</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=printers">Printers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=scanners">Scanners</a>
                                            <a class href="https://www.digidirect.com.au/find?q=ink">Ink</a>
                                            <a class href="https://www.digidirect.com.au/find?q=printer+accessories">Printer Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=scanner+accessories">Scanner Accessories</a>
                                            <a class href="https://www.digidirect.com.au/find?q=paper">Paper</a>
                                        </div>

                                    </div>

                                    <div id="monitors-and-accessories" class="tabcontent">
                                        <h3>Monitors & Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=monitors">View All Monitors & Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=monitors+monitors">Monitors</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monitors+monitor+mounts+stands">Monitor Mounts & Stands</a>
                                            <a class href="https://www.digidirect.com.au/find?q=monitors+monitor+accessories">Monitor Accessories</a>
                                        </div>

                                    </div>

                                    <div id="desktop-and-parts" class="tabcontent">
                                        <h3>Desktop & Parts</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=desktops">View All Desktop & Parts</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=desktops+apple+imac+desktops">Apple iMac Desktops</a>
                                            <a class href="https://www.digidirect.com.au/find?q=desktops+apple+imac+desktops">All in One PCs</a>
                                            <a class href="https://www.digidirect.com.au/find?q=desktops+nuc+mini+pcs">NUC & Mini PCs</a>
                                            <a class href="https://www.digidirect.com.au/find?q=desktops+apple+tv">Apple TV</a>
                                            <a class href="https://www.digidirect.com.au/find?q=desktops+desktop+pcs">Desktop PCs</a>
                                            <a class href="https://www.digidirect.com.au/find?q=desktops+apple+mac+studio">Apple Mac Studio</a>
                                            <a class href="https://www.digidirect.com.au/find?q=desktops+apple+mac+pros">Apple Mac Pros</a>
                                        </div>

                                    </div>

                                    <div id="computer-accessories" class="tabcontent">
                                        <h3>Computer Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=computer+accessories">View All Computer Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=computer+accessories+mouse-keyboard">Keyboards & Combos</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computer+accessories+mice-mousemats">Mice & Mousemats</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computer+accessories+cases-covers-bags">Case Covers & Bags</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computer+accessories+hubs-docks">Hubs & Docks</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computer+accessories+webcams">Webcams</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computer+accessories+cables">Cables & Adaptors</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computer+accessories+chargers">Chargers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=computer+accessories+headsets">Headsets</a>
                                        </div>

                                    </div>

                                    <div id="drones-uav" class="tabcontent">
                                        <h3>Drones UAV</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=drones+dji">View All Drones UAV</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=drones+dji">DJI</a>
                                        </div>

                                    </div>

                                    <div id="drone-cameras" class="tabcontent">
                                        <h3>Drone Cameras</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=drones+drone+cameras">View All Drone Cameras</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=drones+drone+cameras+dji">DJI</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drones+drone+cameras+autel">Autel</a>
                                        </div>

                                    </div>

                                    <div id="drone-gimbals" class="tabcontent">
                                        <h3>Drone Gimbals</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=drones+drone+gimbals">View All Drone Gimbals</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=drones+drone+gimbals">DJI</a>
                                        </div>

                                    </div>

                                    <div id="drone-accessories" class="tabcontent">
                                        <h3>Drone Accessories</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=drones+drone+accessories">View All Drone Accessories</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=drones+drone+accessories+drone+chargers">Drone Chargers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drones+drone+accessories+drone+batteries">Drone Batteries</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drones+drone+accessories+mounts+and+others">Mounts & Others</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drones+drone+accessories+drone+cables">Drone Cables</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drones+drone+accessories+drone+propellers">Drone Propellers</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drones+drone+accessories+bags+and+cases">Drone Bags & Cases</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drones+drone+accessories+remotes">Drone Remotes</a>
                                        </div>

                                    </div>

                                    <div id="underwater-rovs" class="tabcontent">
                                        <h3>Underwater ROVs</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=drones+underwater-rovs">View All Underwater ROVs</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=drones+underwater+rovs+gladius">Gladius</a>
                                        </div>

                                    </div>

                                    <div id="robotics" class="tabcontent">
                                        <h3>Robotics</h3>
                                        <span><a class href="https://www.digidirect.com.au/find?q=drones+robotics">View All Robotics</a></span>

                                        <div class="menu-third-level-links">
                                            <a class href="https://www.digidirect.com.au/find?q=drones+robotics+dji">DJI</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drones+robotics+makeblock">MakeBlock</a>
                                            <a class href="https://www.digidirect.com.au/find?q=drones+robotics+ubtech">UBTech</a>
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>

                        <div id="menu-top-brands">
                            <div id="top-brands-title">TOP BRANDS</div>
                            <div id="top-brands-cameras" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=canon+cameras"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/canon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=fujifilm+cameras"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/fujifilm.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=leica+cameras"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/leica.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=nikon+cameras><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/nikon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=panasonic+cameras"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/panasonic.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=olympus+cameras"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/olympus.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=ricoh+cameras"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/ricoh.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=insta360+cameras"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/insta360.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=sony+cameras"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sony.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=gopro+cameras"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/gopro.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-lenses" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=sony+lenses"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sony.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=canon+lenses"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/canon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=fujifilm+lenses"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/fujifilm.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=sigma+lenses"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sigma.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=nikon+lenses"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/nikon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=tamron+lenses"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/tamron.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=olympus+lenses"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/olympus.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=leica+lenses"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/leica.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=panasonic+lenses"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/panasonic.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=laowa+lenses"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/laowa.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-lightingandstudio" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=godox+lighting+and+studio"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/godox.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=aputure+lighting+and+studio"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/aputure.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=nanlite+lighting+and+studio"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/nanlite.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=sekonic+lighting+and+studio"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sekonic.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=elinchrom+lighting+and+studio"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/elinchrom.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=manfrotto+lighting+and+studio"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/manfrotto.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=magmod+lighting+and+studio"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/magmod.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-photoaccessories" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=sandisk+photo+accessories"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sandisk.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=manfrotto+photo+accessories"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/manfrotto.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=peak-design+photo+accessories"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/peakdesign.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=lacie+photo+accessories"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/lacie.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=lowepro+photo+accessories"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/lowepro.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=dji+photo+accessories"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/dji.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=joby+photo+accessories"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/joby.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=pelican+photo+accessories"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/pelican.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=jupio+photo+accessories"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/jupio.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=benro+photo+accessories"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/benro.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-optics" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=nikon+optics"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/nikon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=leica+optics"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/leica.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=sionyx+optics"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sionyx.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=bushnell+optics"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/bushnell.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=steiner+optics"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/steiner.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=zeiss+optics"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/zeiss.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=fujifilm+optics"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/fujifilm.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=olympus+optics"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/olympus.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=kowa+optics"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/kowa.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=celestron+optics"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/celestron.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-audiovisual" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=rode+audio+visual"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/rode.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=blue+audio+visual"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/blue.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=audioengine+audio+visual"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/audioengine.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=sennheiser+audio+visual"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sennheiser.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=sony+audio+visual"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sony.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=boya+audio+visual"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/boya.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=wacom+audio+visual"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/wacom.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=atomos+audio+visual"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/atomos.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=olympus+audio+visual"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/olympus.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-provideo" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=atomos+pro-video"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/atomos.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=canon+pro-video"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/canon.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=sony+pro-video"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/sony.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=panasonic+pro-video"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/panasonic.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=x-rite+pro-video"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/xrite.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=elgato+pro-video"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/elgato.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=datacolor+pro-video"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/datacolor.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=smallrig+pro-video"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/smallrig.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=z-cam+pro-video"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/zcam.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-smarthome" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=fitbit+smart+home"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/fitbit.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=ecoflow+smart+home"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/ecoflow.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=nitecore+smart+home"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/nitecore.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=medisaint+smart+home"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/medisaint.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=tp-link+smart+home"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/tplink.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=enabot+smart+home"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/enabot.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=eve+smart+home"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/eve.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-computersandmobile" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=samsung+computers+and+mobile"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/samsung.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=apple+computers+and+mobile"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/apple.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=logitech+computers+and+mobile"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/logitech.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=asus+computers+and+mobile"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/asus.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=microsoft+computers+and+mobile"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/microsoft.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=aoc+computers+and+mobile"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/aoc.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=belkin+computers+and+mobile"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/belkin.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=epson+computers+and+mobile"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/epson.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=eizo+computers+and+mobile"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/eizo.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=lenovo+computers+and+mobile"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/lenovo.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-drones" class="top-brands-brand">
                                <div class="top-brands-title">TOP BRANDS</div>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=dji+drones"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/dji.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=autel+drones"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/autel.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=polar-pro+drones"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/polarpro.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=pgytech+drones"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/pgtech.jpg" alt=""></a>
                                <a class="top-brands-link" href="https://www.digidirect.com.au/find?q=swellpro+drones"><img src="https://www.digidirect.com.au/media/wysiwyg/brand-logos/swellpro.jpg" alt=""></a>
                            </div>

                            <div id="top-brands-electronic" class="top-brands-brand">
                            </div>

                            <div id="top-brands-home" class="top-brands-brand">
                            </div>

                            <div id="top-brands-collectibles" class="top-brands-brand">
                            </div>

                            <div id="top-brands-fitness" class="top-brands-brand">
                            </div>

                            <div id="top-brands-seasonal" class="top-brands-brand">
                            </div>

                            <div id="top-brands-music" class="top-brands-brand">
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>

        <?php
        if ($isDigiClub == 1) { ?>
            <a id="submenu-digiclub-member-deals" class="submenu-link item-submenu"
               href="https://www.digidirect.com.au/digiclub-member-deals"
               onclick="checkActiveMenuItem(event, 'submenu-digiclub-member-deals')">
                <span class="dc-digi">digi</span><span class="dc-club">Club</span> MEMBER DEALS
            </a>
        <?php } ?>
        <a id="submenu-digideals" class="submenu-link item-submenu" href="https://www.digidirect.com.au/deals" onclick="checkActiveMenuItem(event, 'submenu-digideals')">
            <span class="dc-digi">digi</span><span class="dc-club">Deals</span>
        </a>

        <div id="submenu-digiseconds" class="item-submenu" onclick="checkActiveMenuItem(event, 'submenu-digiseconds')">
            <div class="digiseconds-mobile-menu">
                <div class="dropdown">
                    <a class="digiseconds-nav">
                        <button class="dropbtn" style="display: flex;">
                            <span class="dc-digi">digi</span>
                            <span class="dc-club">Seconds</span>
                            <i class="fas fa-angle-down"></i>
                        </button>
                    </a>
                    <i class="fas fa-angle-right"></i>
                    <div class="dropdown-content" onclick="event.stopPropagation()" style="flex-direction: column;">
                        <div class="digiseconds-listing" style="display: grid; grid-auto-rows: 100px;width: 100%;max-width: 430px;">
                            <a href="https://digidirect.com.au/digiseconds/openbox">
                                <div class="digiseconds-menu">
                                    <div role="img" class="digiseconds-menu-img" style="background-image: url('https://www.digidirect.com.au/media/wysiwyg/digiseconds/nav-demo.png'); background-repeat: no-repeat; background-size: contain;" alt="Open Box">
                                    </div>
                                    <span class="digiseconds-menu-description-wrapper"><span class="digiseconds-menu-title">OPEN BOX</span><br>
                    <span class="digiseconds-menu-description">Package opended but product inside appears unused.</span>
                    <span class="digiseconds-get-started" style="color: #ff3c00; font-size: 12px; font-weight: 400;">Get Started</span></span>
                                </div></a>

                            <a href="https://digidirect.com.au/digiseconds/preloved">
                                <div class="digiseconds-menu">
                                    <div role="img" class="digiseconds-menu-img" style="background-image: url('https://www.digidirect.com.au/media/wysiwyg/digiseconds/nav-pre-loved.png'); background-repeat: no-repeat; background-size: contain;" alt="Pre-Loved">
                                    </div>
                                    <span class="digiseconds-menu-description-wrapper"><span class="digiseconds-menu-title">PRE-LOVED</span><br>
                    <span class="digiseconds-menu-description">We buy used gears from our customers, fix and clean them up, then sell them back to you for a lower price.</span>
                    <span class="digiseconds-get-started" style="color: #ff3c00; font-size: 12px; font-weight: 400;">Get Started</span></span></div></a>

                            <a href="https://digidirect.com.au/digiseconds/refurb">
                                <div class="digiseconds-menu"><div role="img" class="digiseconds-menu-img" style="background-image: url('https://www.digidirect.com.au/media/wysiwyg/digiseconds/nav-refurbished.png'); background-repeat: no-repeat; background-size: contain;" alt="Refurbished">
                                    </div>
                                    <span class="digiseconds-menu-description-wrapper"><span class="digiseconds-menu-title">REFURBISHED</span><br>
                  <span class="digiseconds-menu-description">We repaired it and restored it to it's original glory and beyond!</span>
                  <span class="digiseconds-get-started" style="color: #ff3c00; font-size: 12px; font-weight: 400;">Get Started</span></span></div></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <a id="submenu-digimarket" class="submenu-link item-submenu" href="https://www.digidirect.com.au/digimarket" onclick="checkActiveMenuItem(event, 'submenu-digimarket')">
            <span class="dc-digi">digi</span><span class="dc-club">Market</span>
        </a>

        <div id="submenu-photolab" class="item-submenu" onclick="checkActiveMenuItem(event, 'submenu-photolab')">
            <div class="photolab-mobile-menu">
                <div class="dropdown">
                    <a class="digiprint-link" href="https://www.digidirect.com.au/digiprint">
                        <button class="dropbtn" style="display: flex;">
                            <span class="dc-digi">digi</span>
                            <span class="dc-club">Print</span>
                            <i class="fas fa-angle-down"></i>
                        </button>
                    </a>
                    <i class="fas fa-angle-right"></i>
          <div class="dropdown-content" onclick="event.stopPropagation()" onmouseleave="resetDigiPrintSecondLevel()">
            <div id="photolab-listing" class="photolab-listing" style="display: grid; grid-auto-rows: 100px;border: 1px solid #cacaca;">

                            <div class="reason-list" onclick="openDigiPrintSecondLevel(event, 'digiprint-second-level-printing-services')">
                <span>
                    <a>
                        <img src="https://www.digidirect.com.au/media/digiprint-digitalprints.png">
                    </a>
                </span>
                                <div class="content">
                                    <a>
                                        <h3 class="protect-title">Printing Services</h3>
                                        <p>Turn your digital photos in to beautiful prints.</p>
                                    </a>
                                </div>
                <i class="fas mgz-fa-angle-right"></i>
                            </div>

                            <div class="reason-list" onclick="openDigiPrintSecondLevel(event, 'digiprint-second-level-photo-books')">
                <span>
                    <a>
                        <img src="https://www.digidirect.com.au/media/digiprint-photobooks.png">
                    </a>
                </span>
                                <div class="content">
                                    <a>
                                        <h3 class="protect-title">Photo Books</h3>
                                        <p>Customise Photo Books in different size and number pages</p>
                                    </a>
                                </div>
                <i class="fas mgz-fa-angle-right"></i>
                            </div>
                
                            <div class="reason-list">
                <span>
                    <a href="https://www.digidirect.com.au/digi-print/calendar">
                        <img src="https://www.digidirect.com.au/media/digiprint-calendar.png">
                    </a>
                </span>
                                <div class="content">
                                    <a href="https://www.digidirect.com.au/digi-print/calendar">
                                        <h3 class="protect-title">Calendar</h3>
                                        <p>Customise your wall and desk calendar</p>
                                    </a>
                                </div>
                            </div>

                        </div>
              
            
            <div id="digiprint-second-level" class="mgz-tabs-content slide-left-to-right">
                <div id="return-to-first-level-digiprint" onclick="returnToFirstLevelDigiPrint()" style="display: none;"><i class="fas fa-angle-left" style="margin-right: 10px"></i>Previous</div>
                <div id="digiprint-second-level-printing-services" class="second-level-content">
                    <div class="menu-raw-content">
                        <div class="menu-second-level">
                            <span>Printing Services</span>
                            <a href="https://www.digidirect.com.au/digi-print/printing-services">View All Printing Services</a>
                            <div class="tab">
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/photo-prints">Photo Prints</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/wide-format-fine-art-printing">Wide Format & Fine Art Printing</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/canvas-prints">Canvas Prints</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/metal-prints">Metal Prints</a> 
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/glass-prints">Glass Prints</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/in-store-framed-prints">In Store Framed Prints</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/framed-prints">Framed Prints</a> 
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/framed-metal-prints">Framed Metal Prints</a> 
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/printing-services/framed-canvas-prints">Framed Canvas Prints</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="digiprint-second-level-photo-books" class="second-level-content">
                    <div class="menu-raw-content">
                        <div class="menu-second-level">
                            <span>Photo Books</span>
                            <a href="https://www.digidirect.com.au/digi-print/photo-books">View All Photo Books</a>
                            <div class="tab">
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/photo-books/standard-cover-photo-books">Standard Cover Photo Books</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/photo-books/personalised-cover-photo-books">Personalised Cover Photo Books</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/photo-books/premium-cover-photo-books">Premium Cover Photo Books</a>
                                <a class="tablinks" href="https://www.digidirect.com.au/digi-print/photo-books/flip-books">Flip Books</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
</div>
    </div>

    </div>
  </div>
</div>

<script>

    function openSecondLevel(evt, className, topBrands, firstLevel) {

        var x;
        firstcategories = document.getElementsByClassName("mgz-tabs-tab-title");

        var y;
        firstcategoriestitle = document.getElementsByClassName("first-menu-tab-title");

        if (document.getElementById(firstLevel).classList.contains("active-category")) {
            document.getElementById(firstLevel).classList.remove("active-category");
            for (x = 0; x < firstcategories.length; x++) {
                firstcategories[x].removeAttribute('style');
            }
            for (y = 0; y < firstcategoriestitle.length; y++) {
                firstcategoriestitle[y].removeAttribute('style');
            }
            document.getElementById("second-level-menu").style.display = "none";
            document.getElementById("third-level-menu").style.display = "none";
            document.getElementById("menu-top-brands").style.display = "none";
            document.getElementById("shop-by-category-tabs").style.removeProperty("width");
        } else {
            for (x = 0; x < firstcategories.length; x++) {
                firstcategories[x].setAttribute('style', 'width: 100px !important');
                firstcategories[x].classList.remove("active-category");
            }
            document.getElementById(firstLevel).classList.add("active-category");

            for (y = 0; y < firstcategoriestitle.length; y++) {
                firstcategoriestitle[y].style.display = "none";
            }

            var i;
            tabcontent = document.getElementsByClassName("second-level-content");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }

            document.getElementById("second-level-menu").style.width= "330px";
            document.getElementById("second-level-menu").style.display = "block";
            document.getElementById(className).style.display = "block";
            document.getElementById("third-level-menu").style.display = "none";

            var z;
            topbrands = document.getElementsByClassName("top-brands-brand");
            for (z = 0; z < topbrands.length; z++) {
                topbrands[z].style.display = "none";
            }

            document.getElementById("menu-top-brands").style.width= "100px";
            document.getElementById("menu-top-brands").style.display = "block";

            if (screen.width < 1281) {
                document.getElementById(topBrands).style.display = "grid";
            } else {
                document.getElementById(topBrands).style.display = "block";
            }

            if (screen.width < 1281) {
                document.getElementById("shop-by-category-tabs").style.width = "auto";
            }
        }

        for (x = 0; x < firstcategories.length; x++) {
            firstcategories[x].classList.add("hide-first-level");
        }

        window.scrollTo(0, 0);

    }

    function resetMenu() {

        var x;
        firstcategories = document.getElementsByClassName("mgz-tabs-tab-title");
        for (x = 0; x < firstcategories.length; x++) {
            firstcategories[x].removeAttribute('style');
            firstcategories[x].classList.remove("active-category");
        }

        var y;
        firstcategoriestitle = document.getElementsByClassName("first-menu-tab-title");
        for (y = 0; y < firstcategoriestitle.length; y++) {
            firstcategoriestitle[y].removeAttribute('style');
        }

        document.getElementById("second-level-menu").style.display = "none";
        document.getElementById("third-level-menu").style.display = "none";
        document.getElementById("menu-top-brands").style.display = "none";
        document.getElementById("shop-by-category-tabs").style.removeProperty("width");

        for (x = 0; x < firstcategories.length; x++) {
            firstcategories[x].classList.remove("hide-first-level");
        }
    }

    function openThirdLevel(evt, category) {

        document.getElementById("third-level-menu").style.width= "330px";
        document.getElementById("third-level-menu").style.display = "block";

        var i, tabcontent, tablinks, secondLevel;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }

        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }

        document.getElementById(category).style.display = "block";
        evt.currentTarget.className += " active";

        secondLevel = document.getElementsByClassName("menu-second-level");
        if (screen.width < 1281) {
            for (i = 0; i < secondLevel.length; i++) {
                //secondLevel[i].style.display = "none";
            }
        }

        if (screen.width < 1281) {
            document.getElementById("second-level-menu").style.display = "none";
        }
    }

    function openServiceMenu(event, serviceMenu) {
        var i,x;
        menu = document.getElementsByClassName("menu-services");
        for (i = 0; i < menu.length; i++) {
            menu[i].classList.remove("menu-active");
        }
        menuTitle = document.getElementsByClassName("menu-services-title");
        for (x = 0; x < menuTitle.length; x++) {
            menuTitle[x].classList.remove("title-active");
        }
        event.currentTarget.className += " title-active";
        document.getElementById(serviceMenu).classList.add("menu-active");
    }

    function checkActiveMenuItem(event, itemSubMenu) {
        var i;
        if (screen.width < 1281) {

            if (document.getElementById(itemSubMenu).classList.contains("submenu-active")) {
                document.getElementById(itemSubMenu).classList.remove("submenu-active");
            } else {
                document.getElementById(itemSubMenu).classList.add("submenu-active");
            }

            subMenu = document.getElementsByClassName("item-submenu");
            for (i = 0; i < subMenu.length; i++) {
                if (subMenu[i].id != itemSubMenu) {
                    subMenu[i].classList.remove("submenu-active");
                }
                //subMenu[i].classList.remove("submenu-active");
            }


            //document.getElementById(itemSubMenu).scrollIntoView();
        }

    }

    function returnToSecondLayer() {
        document.getElementById("second-level-menu").style.display = "block";
        document.getElementById("third-level-menu").style.display = "none";
    }

    function returnToFirstLevel() {
        resetMenu();
    }


    function openDigiPrintSecondLevel(evt, className) {
        var i;
        tabcontent = document.getElementsByClassName("second-level-content");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].removeAttribute('style');
        }
        document.getElementById("digiprint-second-level").removeAttribute('style');
        document.getElementById(className).removeAttribute('style');
        document.getElementById("digiprint-second-level").style.display = "block";
        document.getElementById(className).style.display = "block";
        
        if (window.innerWidth < 1280) {
            document.getElementById("photolab-listing").style.display = "none";
        } else {
            document.getElementById("photolab-listing").style.display = "block";
        }
        
    }

    function resetDigiPrintSecondLevel() {
        document.getElementById("digiprint-second-level").removeAttribute('style');
    }
    
    function returnToFirstLevelDigiPrint() {
        document.getElementById("photolab-listing").style.display = "grid";
        document.getElementById("digiprint-second-level").removeAttribute('style');
    }

</script>

<script>
    require(['jquery'],function($){
        $('#mobile-menu-minicart').on('click', function(){
            $('#show-cart').trigger("click");
            console.log("Mobile Navigation Minicart!");
        });
    });
</script>
