<div class="pdp-row" >
    <div class="pa-digidirect-product-widget people-who-viewed-this-item-also-viewed">
        <div class="product-widget-header">
            <div class="widget-main-label" style="color: #242426; font-size: 32px; font-family: Inter; font-weight: 500; line-height: 33px; word-wrap: break-word">People who viewed this item also viewed</div>
        </div>
        <div id="people-who-viewed-this-item-also-viewed-desktop" class="pa-digidirect-product-widget-container desktop-widget real-container owl-carousel custom"></div>
    </div>
</div>
