<div id="pa-digimarket-widget" class="pdp-row">
    <div class="pa-digidirect-product-widget explore-digimarket">
        <div class="product-widget-header">
            <h3 class="title" style="font-size: 18px;font-weight: 650;color: #ff3c00;">Looking for more? Explore digiMarket</h3>
            <a href="https://www.digidirect.com.au/digimarket" class="digimarket-discover-more-widget">Discover More</a>
        </div>
        <div id="explore-digimarket-desktop" class="pa-digidirect-product-widget-container desktop-widget real-container owl-carousel custom"></div>
        <div id="explore-digimarket-mobile" class="pa-digidirect-product-widget-container mobile-widget"></div>
        <div class="pa-digidirect-product-widget-container widget-placeholder mobile-widget">
        <div class="load-more mgz-element mgz-child mgz-element-text product-tab-mobile-widget-load-more grid-toggle-more" onclick="loadMoreProducts('explore-digimarket');"><div class="mgz-element-inner"><p>Load More</p></div></div>
        <div class="view-less mgz-element mgz-child mgz-element-text product-tab-mobile-widget-view-less grid-toggle-more" onclick="viewLessProducts('explore-digimarket');" style="display: none;"><div class="mgz-element-inner"><p>View Less</p></div></div>
        <div class="view-all mgz-element mgz-child mgz-element-text product-tab-mobile-widget-view-all grid-toggle-more" onclick="viewAllProducts('https://www.digidirect.com.au/digimarket');" style="display: none;"><div class="mgz-element-inner"><p>View All</p></div></div>
    </div>
</div>
