<?php
    use Magento\Framework\App\Action\Action;
    $productId = $block->getCurrentProduct()->getId();
    $block->getConfig();
?>

<script>
    
require(['jquery'], function ($) {
    
    let iphone16s = [388575,388578,388581,388584,388587,388590,388593,388596,388599,388602,388605,388608,388611,388614,388623,390369,390372,390375,390378,390381,390384,390387,390390,390393,390396,390399,390402,390405,390408,390411,390414,390417,390420,390447,390453,390456,390459,390462,390465,390468,390471,390474,390477,390480,390483,390486,390489,390492,390495,390498,390501,390504,390507,390510,390513,390516,390519,390522,395268,395271,395274,395277,395280,395283,395286,395289];    
    let isIphone16 = iphone16s.includes(<?= $productId; ?>);
    
    let iphone15s = [92954,92957,92960,92963,92966,92969,92972,92975,92978,92981,92984,92987,92990,92993,92996,92999,93002,93005,93008,93011,93014,93017,93020,93023,93026,93029,93032,93035,93038,93041,93044,93047,93050,93053,93056,93059,93062,93065,93068,93071,93074,93077,93080,93083,93086,93089,93092,93095,93098,93101,93104,93107,93110,93113,94073,94076,94079,98792,238342,238348,238381,315381,315384,315387,315390,315393,315396,315399,315402,315405,315408,315411,315414];    
    let isIphone15 = iphone15s.includes(<?= $productId; ?>);
    
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }
    
    var customerId = getCookie('pa_customer_id');
    var sessionId = getCookie('pa_session_id');
    var currentUrl = window.location.href;
    
    var date = new Date();

    const viewProductData = {
        customerId: customerId,
        sessionId: sessionId,
        events: [
            {
                currentUrl: currentUrl,
                eventTime: date.toISOString(),
                refId: <?= $productId; ?>
            }
        ]
    };
    
    $.ajax({
        url: "https://www.digidirect.com.au/particularaudienceapi/events/viewproduct",
        type: "POST",
        data: {
            eventData: viewProductData
        },
        success: function(data){
            console.log("viewProduct", data);
        },
        error: function(data){
            console.log('AJAX Fail!', data);
        }
    });
    
    var recommendationsResult = <?= json_encode($block->getRecommendations()); ?>;
    console.log(recommendationsResult);
    
    var widgets  = recommendationsResult.recommendations.route.widgets;
    var routeId  = recommendationsResult.recommendations.route.id;
    
    function digiMarketSidePanel(widgetId, appendTo) {
        let productItem = "";
        let priceBlock = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        Object.keys(widgetSlots).forEach(key => {
            let product = widgetSlots[key].products[0];
            let campaignId = widgetSlots[key].campaignId;
            let recommenderId = widgetSlots[key].recommenderId;
            let tacticId = widgetSlots[key].tacticId;
            let retailBoostCollectionCampaignId = widgetSlots[key].retailBoostCollectionCampaignId;
            let adSetId = widgetSlots[key].adSetId;
            let adSetVersion = widgetSlots[key].adSetVersion;
            let costPerClick = widgetSlots[key].costPerClick;
            let timeStamp = widgetSlots[key].timeStamp;
            let hmacSalt = widgetSlots[key].hmacSalt;
            let hmac = widgetSlots[key].hmac;
            let keywordId = widgetSlots[key].keywordId;
            //widgetSlots[key].products[0].refId;
            
            if (product.prices[0].discountPrice) {
                let price = Number(product.prices[0].price);
                let discountPrice = Number(product.prices[0].discountPrice);

                let priceToDisplay = '$' + price.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                let discountPriceToDisplay = '$' + discountPrice.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                priceBlock = '<div class="price-box price-final_price">' +
                                '<div class="final-price">'+ discountPriceToDisplay +'</div>' +
                            '</div>';
            } else {
                let price = Number(product.prices[0].price);
                let priceToDisplay = '$' + price.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                priceBlock = '<div class="price-box price-final_price">' +
                                '<div class="final-price">'+ priceToDisplay +'</div>' +
                            '</div>';
            }
            
            var view = "-digimarket";
            var tileId = widgetId + '-product-' + product.refId + view;
            productItem = '<div id="'+ tileId +'" class="product-item-info product-item" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '" retail-boost-collection-campaign-id="' + retailBoostCollectionCampaignId + '" adset-id="' + adSetId + '" adset-version="' + adSetVersion + '" cost-per-click="' + costPerClick + '" timestamp="' + timeStamp + '" hmac-salt="' + hmacSalt + '" hmac="' + hmac + '" keyword-id="' + keywordId + '">' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                        '</div>'
            $(appendTo).append(productItem);
            //slots(product.refId, recommenderId, campaignId, tacticId);
        });
        $('.product-item-container.widget-placeholder').remove();
    }
    
    function frequentlyBoughtWith(widgetId, prependTo) {
        let productItem = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        var productCtr = 0;
        if (!widgetSlots.length) {
            $(".pa-digidirect-product-widget.pdp-frquently-bought-with").remove();
            return
        }
        Object.keys(widgetSlots).forEach(key => {
            productCtr++;
            let product = widgetSlots[key].products[0];
            let campaignId = widgetSlots[key].campaignId;
            let recommenderId = widgetSlots[key].recommenderId;
            let tacticId = widgetSlots[key].tacticId;
            let retailBoostCollectionCampaignId = widgetSlots[key].retailBoostCollectionCampaignId;
            let adSetId = widgetSlots[key].adSetId;
            let adSetVersion = widgetSlots[key].adSetVersion;
            let costPerClick = widgetSlots[key].costPerClick;
            let timeStamp = widgetSlots[key].timeStamp;
            let hmacSalt = widgetSlots[key].hmacSalt;
            let hmac = widgetSlots[key].hmac;
            let keywordId = widgetSlots[key].keywordId;
            
            let digiDealsLogo = "";
            let priceBlock = "";
            let addToCart = "";
            
            let digiSeconds = "";
            let digiSecondsOverlay = "";
            let digiSecondsRating = "";
            let sellerName = "";
            
            let finalPrice = "";
            
            let categories = product.attributes.find(obj => {
                return obj.name === 'Categories';
            })
            
            let seller = product.attributes.find(obj => {
                return obj.name === 'DDR_Seller_Id';
            })
            
            let digiPrint = product.attributes.find(obj => {
                return obj.name === 'is_digiprint';
            })
            
            let digiPrintLink = product.attributes.find(obj => {
                return obj.name === 'digiprint_customlink';
            })
            
            sellerName = seller.stringValue;
            
            let digiSecondsCategories = ["PRELOVED","OPENBOX","REFURB"];
            let isDigiSeconds = digiSecondsCategories.includes(categories.options[0].value);
            
            if (categories.options[0].value == "PRELOVED") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-pre-loved.png"/>';
            } else if (categories.options[0].value == "OPENBOX") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-demo.png"/>';
            } else if (categories.options[0].value == "REFURB") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-refurbished.png"/>';
            }
            
            digiSeconds = '<div class="digiseconds-overlay">' + digiSecondsOverlay + '<div class="digiseconds-rating">' + digiSecondsRating + '</div></div>';
            //console.log(attribute);

            let digiPrintValue = digiPrint.stringValue;
            let digiPrintLinkValue = digiPrintLink.stringValue;let sponsoredLabel = "";
            if (adSetId || adSetId != null) {
                sponsoredLabel = '<div class="sponsored-container"><div class="sponsored-label"><i class="fas fa-info-circle"></i>Sponsored</div><span class="label-tooltip">This product has been promoted by one of our partners using <a href="https://particularaudience.com/">Particular Audience</a>.</span></div>';
            }
            
            if (digiPrintValue == 1) {
                addToCart = '<a class="ordernow-link" href="' + digiPrintLinkValue + '" target="_blank">' +
                                '<button type="button" title="Order Now" class="action tocart primary">' +
                                    'Order Now <img src="<?= $block->getViewFileUrl('images/icons/cart.png') ?>"/>' +
                                '</button>' +
                            '</a>'
            } else {
                addToCart = '<form data-role="tocart-form"' +
                                'data-product-sku="' + product.sku + '"' +
                                'action="https://www.digidirect.com.au/checkout/cart/add/product/'+ product.refId +'" method="post"><?php echo $block->getBlockHtml("formkey"); ?>' +
                                '<input type="text" name="ref_id" value="'+ product.refId +'" hidden/>' +
                                '<input type="text" name="qty" value="1" hidden/>' +
                                '<input type="text" name="widget_id" value="'+ widgetId +'" hidden/>' +
                                '<input type="text" name="route_id" value="'+ routeId +'" hidden/>' +
                                '<input type="text" name="recommender_id" value="'+ recommenderId +'" hidden/>' +
                                '<input type="text" name="campaign_id" value="'+ campaignId +'" hidden/>' +
                                '<input type="text" name="tactic_id" value="'+ tacticId +'" hidden/>' +
                                '<input type="text" name="retail_boost_collection_campaign_id" value="'+ retailBoostCollectionCampaignId +'" hidden/>' +
                                '<input type="text" name="adset_id" value="'+ adSetId +'" hidden/>' +
                                '<input type="text" name="adset_version" value="'+ adSetVersion +'" hidden/>' +
                                '<input type="text" name="cost_per_click" value="'+ costPerClick +'" hidden/>' +
                                '<input type="text" name="timestamp" value="'+ timeStamp +'" hidden/>' +
                                '<input type="text" name="hmac_salt" value="'+ hmacSalt +'" hidden/>' +
                                '<input type="text" name="hmac" value="'+ hmac +'" hidden/>' +
                                '<input type="text" name="keyword_id" value="'+ keywordId +'" hidden/>' +
                                '<button type="submit" title="Add to Cart" class="action tocart primary" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '" retail-boost-collection-campaign-id="' + retailBoostCollectionCampaignId + '" adset-id="' + adSetId + '" adset-version="' + adSetVersion + '" cost-per-click="' + costPerClick + '" timestamp="' + timeStamp + '" hmac-salt="' + hmacSalt + '" hmac="' + hmac + '" keyword-id="' + keywordId + '">' +
                                '<span>Add to Cart</span><i class="fas fa-cart-plus" style="float: right;color: #fff;"></i>' +
                                '</button>' + sponsoredLabel
                            '</form>'
            }
            //console.log(product.name, sellerName);
            if (!isDigiSeconds) {
                if (sellerName != "20329" && sellerName !== undefined) {
                    digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                } else {
                    digiDealsLogo = '';
                }
            }
            
            if (product.prices[0].discountPrice) {
                if (!isDigiSeconds) {
                    digiDealsLogo = '<div class="ribbon-digideals"><span class="digi">digi</span>Deals</div>';
                    if (sellerName != "20329" && sellerName !== undefined) {
                        digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                    }
                }
                
                let price = Number(product.prices[0].price);
                let discountPrice = Number(product.prices[0].discountPrice);

                let priceToDisplay = '$' + price.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                let discountPriceToDisplay = '$' + discountPrice.toLocaleString('en-AU', { minimumFractionDigits: 2 });

                let discountValue = price - discountPrice;
                let discount = '$' + discountValue.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                
                finalPrice = Number(product.prices[0].discountPrice).toFixed(2);
                
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label">Price Slashed </span>' + 
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span class="digi">digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="discount-price-wrapper"><span class="discount-price">'+ discount +'</span> Off</div>' +
                            '</div>';
            } else {
                let price = Number(product.prices[0].price);
                let priceToDisplay = '$' + price.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                finalPrice = Number(product.prices[0].price).toFixed(2);
                
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span class="digi">digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }
            
            var view = "-fbw";
            var tileId = widgetId + '-product-' + product.refId + view;
            productItem = '<div id="'+ tileId +'" class="product-item-info product-item" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '" retail-boost-collection-campaign-id="' + retailBoostCollectionCampaignId + '" adset-id="' + adSetId + '" adset-version="' + adSetVersion + '" cost-per-click="' + costPerClick + '" timestamp="' + timeStamp + '" hmac-salt="' + hmacSalt + '" hmac="' + hmac + '" keyword-id="' + keywordId + '">' +
                            '<div class="pa-checkbox-container">' +
                                '<label class="pa-checkbox-label">' +
                                    '<input type="checkbox" data-product-id="'+ product.refId +'" data-product-price="'+ finalPrice +'" class="pa-checkbox-input pa-bundle-product"><span><i class="fas fa-clipboard fa-2x"></i></span>' +
                                '</label>' +
                            '</div>' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                digiDealsLogo + digiSeconds +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                            '<div class="product actions product-item-actions">' +
                                '<div class="actions-primary">' +
                                    addToCart +
                                '</div>' +
                            '</div>' +
                        '</div>'
            $(prependTo).prepend(productItem);
            //slots(product.refId, recommenderId, campaignId, tacticId);
        });
        $('.pa-digidirect-product-widget-container.widget-placeholder').remove();
        $('#pdp-frquently-bought-with-desktop').show();
    }
    
    function productTile(widgetId, appendTo, isMobile) {
        let productItem = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        var productCtr = 0;
        Object.keys(widgetSlots).forEach(key => {
            
            let product = widgetSlots[key].products[0];
            let discountTotal = Number(product.prices[0].price - product.prices[0].discountPrice).toFixed(2);
            
            productCtr++;
            let campaignId = widgetSlots[key].campaignId;
            let recommenderId = widgetSlots[key].recommenderId;
            let tacticId = widgetSlots[key].tacticId;
            let retailBoostCollectionCampaignId = widgetSlots[key].retailBoostCollectionCampaignId;
            let adSetId = widgetSlots[key].adSetId;
            let adSetVersion = widgetSlots[key].adSetVersion;
            let costPerClick = widgetSlots[key].costPerClick;
            let timeStamp = widgetSlots[key].timeStamp;
            let hmacSalt = widgetSlots[key].hmacSalt;
            let hmac = widgetSlots[key].hmac;
            let keywordId = widgetSlots[key].keywordId;

            let digiDealsLogo = "";
            let priceBlock = "";
            let addToCart = "";

            let digiSeconds = "";
            let digiSecondsOverlay = "";
            let sellerName = "";

            let categories = product.attributes.find(obj => {
                return obj.name === 'Categories';
            })

            let seller = product.attributes.find(obj => {
                return obj.name === 'DDR_Seller_Id';
            })

            let digiPrint = product.attributes.find(obj => {
                return obj.name === 'is_digiprint';
            })

            let digiPrintLink = product.attributes.find(obj => {
                return obj.name === 'digiprint_customlink';
            })

            let digiSecondsRatingValue = product.attributes.find(obj => {
                return obj.name === 'item_rating';
            })

            let digiSecondsRating = "";            

            if (digiSecondsRatingValue.stringValue == "5") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "4") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "3") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "2") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "1") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            }

            sellerName = seller.stringValue;

            let digiSecondsCategories = ["PRELOVED","OPENBOX","REFURB"];
            let isDigiSeconds = digiSecondsCategories.includes(categories.options[0].value);

            const includesString = (str, searchString) =>
            new RegExp(searchString, 'i').test(str);

            if (categories.options[0].value == "PRELOVED" || includesString(product.name, 'used')) {
                digiSecondsOverlay = '<img src="<?= $block->getBaseUrl(); ?>media/wysiwyg/digiseconds/overlays/badge-pre-loved.png"/>';
            } else if (categories.options[0].value == "OPENBOX" || includesString(product.name, 'open box')) {
                digiSecondsOverlay = '<img src="<?= $block->getBaseUrl(); ?>media/wysiwyg/digiseconds/overlays/badge-demo.png"/>';
            } else if (categories.options[0].value == "REFURB" || includesString(product.name, 'refurb')) {
                digiSecondsOverlay = '<img src="<?= $block->getBaseUrl(); ?>media/wysiwyg/digiseconds/overlays/badge-refurbished.png"/>';
            }

            digiSeconds = '<div class="digiseconds-overlay">' + digiSecondsOverlay + '<div class="digiseconds-rating">' + digiSecondsRating + '</div></div>';
            //console.log("adSetId", adSetId, product.name);

            let digiPrintValue = digiPrint.stringValue;
            let digiPrintLinkValue = digiPrintLink.stringValue;
            let sponsoredLabel = "";
            if (adSetId || adSetId != null) {
                sponsoredLabel = '<div class="sponsored-container"><div class="sponsored-label"><i class="fas fa-info-circle"></i>Sponsored</div><span class="label-tooltip">This product has been promoted by one of our partners using <a href="https://particularaudience.com/">Particular Audience</a>.</span></div>';
            }

            if (digiPrintValue == 1) {
                addToCart =
                    '<div class="ordernow-link" onclick="window.open(\'' + digiPrintLinkValue + '\', \'_blank\')">' +
                      '<button type="button" class="action tocart primary">Order Now <img src="<?= $block->getViewFileUrl('images/icons/cart.png') ?>" />' +
                      '</button>' +
                    '</div>';

            } else {
                addToCart = '<form data-role="tocart-form"' +
                                'data-product-sku="' + product.sku + '"' +
                                'action="<?= $block->getBaseUrl(); ?>checkout/cart/add/product/'+ product.refId +'" method="post"><?php echo $block->getBlockHtml("formkey"); ?>' +
                                '<input type="text" name="ref_id" value="'+ product.refId +'" hidden/>' +
                                '<input type="text" name="qty" value="1" hidden/>' +
                                '<input type="text" name="widget_id" value="'+ widgetId +'" hidden/>' +
                                '<input type="text" name="route_id" value="'+ routeId +'" hidden/>' +
                                '<input type="text" name="recommender_id" value="'+ recommenderId +'" hidden/>' +
                                '<input type="text" name="campaign_id" value="'+ campaignId +'" hidden/>' +
                                '<input type="text" name="tactic_id" value="'+ tacticId +'" hidden/>' +
                                '<input type="text" name="retail_boost_collection_campaign_id" value="'+ retailBoostCollectionCampaignId +'" hidden/>' +
                                '<input type="text" name="adset_id" value="'+ adSetId +'" hidden/>' +
                                '<input type="text" name="adset_version" value="'+ adSetVersion +'" hidden/>' +
                                '<input type="text" name="cost_per_click" value="'+ costPerClick +'" hidden/>' +
                                '<input type="text" name="timestamp" value="'+ timeStamp +'" hidden/>' +
                                '<input type="text" name="hmac_salt" value="'+ hmacSalt +'" hidden/>' +
                                '<input type="text" name="hmac" value="'+ hmac +'" hidden/>' +
                                '<input type="text" name="keyword_id" value="'+ keywordId +'" hidden/>' +
                                '<button type="submit" title="Add to Cart" class="action tocart primary" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '" retail-boost-collection-campaign-id="' + retailBoostCollectionCampaignId + '" adset-id="' + adSetId + '" adset-version="' + adSetVersion + '" cost-per-click="' + costPerClick + '" timestamp="' + timeStamp + '" hmac-salt="' + hmacSalt + '" hmac="' + hmac + '" keyword-id="' + keywordId + '">' +
                                '<span>Add to Cart</span><img src="<?= $block->getViewFileUrl('images/icons/cart.png') ?>"/>' +
                                '</button>' + 
                            '</form>'
            }
            
            let addToWishList;
            
            if (widgetId == '02ed2d33-ee8e-ec11-aae9-02dca44cceec') {
                addToWishList = `<div class="pa-checkbox-container"><label class="pa-checkbox-label"><input type="checkbox" data-product-sku="${product.sku}" class="pa-checkbox-input pa-bundle-product"><i class="fas fa-check" style="display: none;"></i></label></div>`;
            } else {
                addToWishList = `<a href="javascript:void(0);" class="action towishlist" title="<?php echo __('Add to Wishlist') ?>" data-post='{"action":"/wishlist/index/add/","data":{"product":"${product.refId}","uenc":"${product.url}"}}' style="padding:6px;box-shadow:0px .78125px .78125px rgba(150,150,150,.09);border-radius:14px;position:absolute;height:25px;width:25px;right:0;margin:12px;border:none;"></a>`;
            }
            
            if (!isDigiSeconds) {
                if (sellerName != "20329" && sellerName !== undefined) {
                    digiDealsLogo = '<a href="' + product.url + '" class="ribbon-container"><div class="ribbon-online">Online Only</div>'+ addToWishList +'</a>';
                } else {
                    digiDealsLogo = '<a href="' + product.url + '" class="ribbon-container">'+ addToWishList +'</a>';
                }
            } else {
                digiDealsLogo = '<a href="' + product.url + '" class="ribbon-container"><div class="ribbon-digideals digiseconds"><span style="color: #fe4c25;">digi</span>Seconds</div>'+ addToWishList +'</a>';
            }

            let price = Number(product.prices[0].price);
            let discountPrice = Number(product.prices[0].discountPrice);

            let priceToDisplay = '$' + price.toLocaleString('en-AU', { minimumFractionDigits: 2 });
            let discountPriceToDisplay = '$' + discountPrice.toLocaleString('en-AU', { minimumFractionDigits: 2 });

            let discountValue = price - discountPrice;
            let discount = '$' + discountValue.toLocaleString('en-AU', { minimumFractionDigits: 2 });
            
            if (discount === "$NaN") {
                var productInfoBottom = '<div class="product-info-bottom"><div class="discount-price-wrapper-no-price"></div>' + addToCart + '</div>'
            } else {
                var productInfoBottom = '<div class="product-info-bottom black-friday"><div class="discount-price-wrapper"><span class="discount-price">' + discount + '</span> OFF RRP</div>' + addToCart + '</div>'
            }

            if (product.prices[0].discountPrice) {
                if (!isDigiSeconds) {
                    digiDealsLogo = '<a href="' + product.url + '" class="ribbon-container"><div class="ribbon-digideals black-friday"><span class="digi">Flash</span> Deal</div>'+ addToWishList +'</a>';
                    if (sellerName != "20329" && sellerName !== undefined) {
                        digiDealsLogo = '<a href="' + product.url + '" class="ribbon-container"><div class="ribbon-online">Online Only</div>'+ addToWishList +'</a>';
                    }
                } else {
                    digiDealsLogo = '<a href="' + product.url + '" class="ribbon-container"><div class="ribbon-digideals digiseconds"><span style="color: #fe4c25;">digi</span>Seconds</div>'+ addToWishList +'</a>';
                }
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span class="digi">digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                ' <div class="black-friday-deal">Flash <span class="digi">Deal</span></div><span class="price black-friday">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            } else {
                let price = Number(product.prices[0].price);
                let priceToDisplay = '$' + price.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper" style="visibility: hidden;"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span class="digi">digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }

            let hideProductItem = "";
            if (isMobile && productCtr > 4) {
                hideProductItem = "hide-product-item";
            }
            var view = "";
            if (isMobile) {
                view = "mobile";
            } else {
                view = "desktop";
            }
            var tileId = view + '-' + widgetId + '-product-' + product.refId;

            var productItemDiv = '<div id="'+ tileId +'" class="product-item-info product-item black-friday" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '" retail-boost-collection-campaign-id="' + retailBoostCollectionCampaignId + '" adset-id="' + adSetId + '" adset-version="' + adSetVersion + '" cost-per-click="' + costPerClick + '" timestamp="' + timeStamp + '" hmac-salt="' + hmacSalt + '" hmac="' + hmac + '" keyword-id="' + keywordId + '">';
            
            var zip = '<div style="width:100%;height:100%;line-height:13px;font-size:10px;color:#4D4E4E;"><span>Zip Money is only available up to $10,000. <br>Fees apply*. </span><a href="/zip-money" style="color:#FE4C25;"> Learn how.</a></div>';
            
            productItem = productItemDiv + digiDealsLogo +
                        '<a href="' + product.url + '" class="product-image-container">' +
                            '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                            '</span>' +
                        '</a>' + 
                        '<div style="position: relative;">' + sponsoredLabel +
                            '<a href="' + product.url + '" class="product details product-item-details">' +
                                 '<strong class="product-item-name">' +
                                    '<span title="' + product.name + '" class="product-item-link">' +
                                        product.name +
                                    '</span>' +
                                '</strong><div class="s19-rental-price-target"><p style="font-size: 13px; font-weight: 500;">Buy now Pay later</p><p style="font-size: 13px; font-weight: 500;">Options Available</p></div>' +
                                priceBlock + productInfoBottom +
                            '</a>' +
                        '</div>' +
                    '</div>'
            $(appendTo).append(productItem);
            //slots(product.refId, recommenderId, campaignId, tacticId);
        });
        $('.pa-digidirect-product-widget-container.widget-placeholder').remove();
    }
    
    function bundleOverlay(widgetId, prependTo) {
        let productItem = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        var productCtr = 0;
        if (!widgetSlots.length) {
            $("#bundle-overlay-container").remove();
            return
        }
        Object.keys(widgetSlots).forEach(key => {
            productCtr++;
            let product = widgetSlots[key].products[0];
            let campaignId = widgetSlots[key].campaignId;
            let recommenderId = widgetSlots[key].recommenderId;
            let tacticId = widgetSlots[key].tacticId;
            let retailBoostCollectionCampaignId = widgetSlots[key].retailBoostCollectionCampaignId;
            let adSetId = widgetSlots[key].adSetId;
            let adSetVersion = widgetSlots[key].adSetVersion;
            let costPerClick = widgetSlots[key].costPerClick;
            let timeStamp = widgetSlots[key].timeStamp;
            let hmacSalt = widgetSlots[key].hmacSalt;
            let hmac = widgetSlots[key].hmac;
            let keywordId = widgetSlots[key].keywordId;
            
            let digiDealsLogo = "";
            let priceBlock = "";
            let addToCart = "";
            
            let digiSeconds = "";
            let digiSecondsOverlay = "";
            let digiSecondsRating = "";
            let sellerName = "";
            
            let finalPrice = "";
            
            let categories = product.attributes.find(obj => {
                return obj.name === 'Categories';
            })
            
            let seller = product.attributes.find(obj => {
                return obj.name === 'DDR_Seller_Id';
            })
            
            let digiPrint = product.attributes.find(obj => {
                return obj.name === 'is_digiprint';
            })
            
            let digiPrintLink = product.attributes.find(obj => {
                return obj.name === 'digiprint_customlink';
            })
            
            sellerName = seller.stringValue;
            
            let digiSecondsCategories = ["PRELOVED","OPENBOX","REFURB"];
            let isDigiSeconds = digiSecondsCategories.includes(categories.options[0].value);
            
            if (categories.options[0].value == "PRELOVED") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-pre-loved.png"/>';
            } else if (categories.options[0].value == "OPENBOX") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-demo.png"/>';
            } else if (categories.options[0].value == "REFURB") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-refurbished.png"/>';
            }
            
            digiSeconds = '<div class="digiseconds-overlay">' + digiSecondsOverlay + '<div class="digiseconds-rating">' + digiSecondsRating + '</div></div>';
            //console.log(attribute);
            let digiPrintValue = digiPrint.stringValue;
            let digiPrintLinkValue = digiPrintLink.stringValue;let sponsoredLabel = "";
            if (adSetId || adSetId != null) {
                sponsoredLabel = '<div class="sponsored-container"><div class="sponsored-label"><i class="fas fa-info-circle"></i>Sponsored</div><span class="label-tooltip">This product has been promoted by one of our partners using <a href="https://particularaudience.com/">Particular Audience</a>.</span></div>';
            }
            
            if (digiPrintValue == 1) {
                addToCart = '<a class="ordernow-link" href="' + digiPrintLinkValue + '" target="_blank">' +
                                '<button type="button" title="Order Now" class="action tocart primary">' +
                                    'Order Now <img src="<?= $block->getViewFileUrl('images/icons/cart.png') ?>"/>' +
                                '</button>' +
                            '</a>'
            } else {
                addToCart = '<form data-role="tocart-form"' +
                                'data-product-sku="' + product.sku + '"' +
                                'action="https://www.digidirect.com.au/checkout/cart/add/product/'+ product.refId +'" method="post"><?php echo $block->getBlockHtml("formkey"); ?>' +
                                '<input type="text" name="ref_id" value="'+ product.refId +'" hidden/>' +
                                '<input type="text" name="qty" value="1" hidden/>' +
                                '<input type="text" name="widget_id" value="'+ widgetId +'" hidden/>' +
                                '<input type="text" name="route_id" value="'+ routeId +'" hidden/>' +
                                '<input type="text" name="recommender_id" value="'+ recommenderId +'" hidden/>' +
                                '<input type="text" name="campaign_id" value="'+ campaignId +'" hidden/>' +
                                '<input type="text" name="tactic_id" value="'+ tacticId +'" hidden/>' +
                                '<input type="text" name="retail_boost_collection_campaign_id" value="'+ retailBoostCollectionCampaignId +'" hidden/>' +
                                '<input type="text" name="adset_id" value="'+ adSetId +'" hidden/>' +
                                '<input type="text" name="adset_version" value="'+ adSetVersion +'" hidden/>' +
                                '<input type="text" name="cost_per_click" value="'+ costPerClick +'" hidden/>' +
                                '<input type="text" name="timestamp" value="'+ timeStamp +'" hidden/>' +
                                '<input type="text" name="hmac_salt" value="'+ hmacSalt +'" hidden/>' +
                                '<input type="text" name="hmac" value="'+ hmac +'" hidden/>' +
                                '<input type="text" name="keyword_id" value="'+ keywordId +'" hidden/>' +
                                '<button type="submit" title="Add to Cart" class="action tocart primary" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '" retail-boost-collection-campaign-id="' + retailBoostCollectionCampaignId + '" adset-id="' + adSetId + '" adset-version="' + adSetVersion + '" cost-per-click="' + costPerClick + '" timestamp="' + timeStamp + '" hmac-salt="' + hmacSalt + '" hmac="' + hmac + '" keyword-id="' + keywordId + '">' +
                                '<span>Add to Cart</span><i class="fas fa-cart-plus" style="float: right;color: #fff;"></i>' +
                                '</button>' + sponsoredLabel
                            '</form>'
            }
            //console.log(product.name, sellerName);
            if (!isDigiSeconds) {
                if (sellerName != "20329" && sellerName !== undefined) {
                    digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                } else {
                    digiDealsLogo = '';
                }
            }
            
            if (product.prices[0].discountPrice) {
                if (!isDigiSeconds) {
                    digiDealsLogo = '<div class="ribbon-digideals"><span class="digi">digi</span>Deals</div>';
                    if (sellerName != "20329" && sellerName !== undefined) {
                        digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                    }
                }
                
                let price = Number(product.prices[0].price);
                let discountPrice = Number(product.prices[0].discountPrice);

                let priceToDisplay = '$' + price.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                let discountPriceToDisplay = '$' + discountPrice.toLocaleString('en-AU', { minimumFractionDigits: 2 });

                let discountValue = price - discountPrice;
                let discount = '$' + discountValue.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                
                finalPrice = Number(product.prices[0].discountPrice).toFixed(2);
                
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label">Price Slashed </span>' + 
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span class="digi">digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="discount-price-wrapper"><span class="discount-price">'+ discount +'</span> Off</div>' +
                            '</div>';
            } else {
                let price = Number(product.prices[0].price);
                let priceToDisplay = '$' + price.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                finalPrice = Number(product.prices[0].price).toFixed(2);
                
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span class="digi">digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }
            
            let hideProductItem = "";
            var view = "-bundle";
            var tileId = widgetId + '-product-' + product.refId + view;
            productItem = '<div id="'+ tileId +'" class="product-item-info product-item" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '" retail-boost-collection-campaign-id="' + retailBoostCollectionCampaignId + '" adset-id="' + adSetId + '" adset-version="' + adSetVersion + '" cost-per-click="' + costPerClick + '" timestamp="' + timeStamp + '" hmac-salt="' + hmacSalt + '" hmac="' + hmac + '" keyword-id="' + keywordId + '">' +
                            '<div class="pa-checkbox-container">' +
                                '<label class="pa-checkbox-label">' +
                                    '<input type="checkbox" data-product-id="'+ product.refId +'" data-product-price="'+ finalPrice +'" class="pa-checkbox-input pa-bundle-overlay-product"><span><i class="fas fa-clipboard fa-2x"></i></span>' +
                                '</label>' +
                            '</div>' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                digiDealsLogo + digiSeconds +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                            '<div class="product actions product-item-actions">' +
                                '<div class="actions-primary">' +
                                    addToCart +
                                '</div>' +
                            '</div>' +
                        '</div>'
            $(prependTo).prepend(productItem);
            //slots(product.refId, recommenderId, campaignId, tacticId);
        });
    }
    
    function productTileMinicart(widgetId, appendTo, isMobile) {
        let productItem = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        var productCtr = 0;
        Object.keys(widgetSlots).forEach(key => {
            productCtr++;
            let product = widgetSlots[key].products[0];
            let campaignId = widgetSlots[key].campaignId;
            let recommenderId = widgetSlots[key].recommenderId;
            let tacticId = widgetSlots[key].tacticId;
            let retailBoostCollectionCampaignId = widgetSlots[key].retailBoostCollectionCampaignId;
            let adSetId = widgetSlots[key].adSetId;
            let adSetVersion = widgetSlots[key].adSetVersion;
            let costPerClick = widgetSlots[key].costPerClick;
            let timeStamp = widgetSlots[key].timeStamp;
            let hmacSalt = widgetSlots[key].hmacSalt;
            let hmac = widgetSlots[key].hmac;
            let keywordId = widgetSlots[key].keywordId;
            
            let digiDealsLogo = "";
            let priceBlock = "";
            let addToCart = "";
            let s19Label = "";
            
            let digiSeconds = "";
            let digiSecondsOverlay = "";
            let sellerName = "";
            
            let categories = product.attributes.find(obj => {
                return obj.name === 'Categories';
            })
            
            let seller = product.attributes.find(obj => {
                return obj.name === 'DDR_Seller_Id';
            })
            
            let digiPrint = product.attributes.find(obj => {
                return obj.name === 'is_digiprint';
            })
            
            let digiPrintLink = product.attributes.find(obj => {
                return obj.name === 'digiprint_customlink';
            })
            
            let digiSecondsRatingValue = product.attributes.find(obj => {
                return obj.name === 'item_rating';
            })
            
            let digiSecondsRating = "";            
            
            if (digiSecondsRatingValue.stringValue == "5") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "4") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "3") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "2") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "1") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            }
            
            sellerName = seller.stringValue;
            
            let digiSecondsCategories = ["PRELOVED","OPENBOX","REFURB"];
            let isDigiSeconds = digiSecondsCategories.includes(categories.options[0].value);
            
            if (categories.options[0].value == "PRELOVED") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-pre-loved.png"/>';
            } else if (categories.options[0].value == "OPENBOX") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-demo.png"/>';
            } else if (categories.options[0].value == "REFURB") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-refurbished.png"/>';
            }
            
            digiSeconds = '<div class="digiseconds-overlay">' + digiSecondsOverlay + '<div class="digiseconds-rating">' + digiSecondsRating + '</div></div>';
            //console.log(attribute);

            let digiPrintValue = digiPrint.stringValue;
            let digiPrintLinkValue = digiPrintLink.stringValue;let sponsoredLabel = "";
            if (adSetId || adSetId != null) {
                sponsoredLabel = '<div class="sponsored-container"><div class="sponsored-label"><i class="fas fa-info-circle"></i>Sponsored</div><span class="label-tooltip">This product has been promoted by one of our partners using <a href="https://particularaudience.com/">Particular Audience</a>.</span></div>';
            }

            if (digiPrintValue == 1) {
                addToCart = '<a class="ordernow-link" href="' + digiPrintLinkValue + '" target="_blank">' +
                                '<button type="button" title="Order Now" class="action tocart primary">' +
                                    'Order Now <img src="<?= $block->getViewFileUrl('images/icons/cart.png') ?>"/>' +
                                '</button>' +
                            '</a>'
                s19Label = '<div class="s19-rental-price-target"><p style="font-size: 13px; font-weight: 500;">Order Online Today!</p></div>'
            } else {
                addToCart = '<form data-role="tocart-form"' +
                                'data-product-sku="' + product.sku + '"' +
                                'action="https://www.digidirect.com.au/checkout/cart/add/product/'+ product.refId +'" method="post"><?php echo $block->getBlockHtml("formkey"); ?>' +
                                '<input type="text" name="ref_id" value="'+ product.refId +'" hidden/>' +
                                '<input type="text" name="qty" value="1" hidden/>' +
                                '<input type="text" name="widget_id" value="'+ widgetId +'" hidden/>' +
                                '<input type="text" name="route_id" value="'+ routeId +'" hidden/>' +
                                '<input type="text" name="recommender_id" value="'+ recommenderId +'" hidden/>' +
                                '<input type="text" name="campaign_id" value="'+ campaignId +'" hidden/>' +
                                '<input type="text" name="tactic_id" value="'+ tacticId +'" hidden/>' +
                                '<input type="text" name="retail_boost_collection_campaign_id" value="'+ retailBoostCollectionCampaignId +'" hidden/>' +
                                '<input type="text" name="adset_id" value="'+ adSetId +'" hidden/>' +
                                '<input type="text" name="adset_version" value="'+ adSetVersion +'" hidden/>' +
                                '<input type="text" name="cost_per_click" value="'+ costPerClick +'" hidden/>' +
                                '<input type="text" name="timestamp" value="'+ timeStamp +'" hidden/>' +
                                '<input type="text" name="hmac_salt" value="'+ hmacSalt +'" hidden/>' +
                                '<input type="text" name="hmac" value="'+ hmac +'" hidden/>' +
                                '<input type="text" name="keyword_id" value="'+ keywordId +'" hidden/>' +
                                '<button type="submit" title="Add to Cart" class="action tocart primary" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '" retail-boost-collection-campaign-id="' + retailBoostCollectionCampaignId + '" adset-id="' + adSetId + '" adset-version="' + adSetVersion + '" cost-per-click="' + costPerClick + '" timestamp="' + timeStamp + '" hmac-salt="' + hmacSalt + '" hmac="' + hmac + '" keyword-id="' + keywordId + '">' +
                                '<span>Add to Cart</span><i class="fas fa-cart-plus" style="float: right;color: #fff;"></i>' +
                                '</button>' + sponsoredLabel
                            '</form>'
                s19Label = '<div class="s19-rental-price-target"><p style="font-size: 13px; font-weight: 500;">Buy now Pay later</p><p style="font-size: 13px; font-weight: 500;">Options Available</p></div>'
            }
            //console.log(product.name, sellerName);
            if (!isDigiSeconds) {
                if (sellerName != "20329" && sellerName !== undefined) {
                    digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                } else {
                    digiDealsLogo = '';
                }
            }
            
            if (product.prices[0].discountPrice) {
                if (!isDigiSeconds) {
                    digiDealsLogo = '<div class="ribbon-digideals"><span class="digi">digi</span>Deals</div>';
                    if (sellerName != "20329" && sellerName !== undefined) {
                        digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                    }
                }
                
                let price = Number(product.prices[0].price);
                let discountPrice = Number(product.prices[0].discountPrice);

                let priceToDisplay = '$' + price.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                let discountPriceToDisplay = '$' + discountPrice.toLocaleString('en-AU', { minimumFractionDigits: 2 });

                let discountValue = price - discountPrice;
                let discount = '$' + discountValue.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label">Price Slashed </span>' + 
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span class="digi">digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="discount-price-wrapper"><span class="discount-price">'+ discount +'</span> Off</div>' +
                            '</div>';
            } else {
                let price = Number(product.prices[0].price);
                let priceToDisplay = '$' + price.toLocaleString('en-AU', { minimumFractionDigits: 2 });
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span class="digi">digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }
            
            var view = "-minicart";
            var tileId = widgetId + '-product-' + product.refId + view;
            productItem = '<div id="'+ tileId +'" class="product-item-info product-item" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '" retail-boost-collection-campaign-id="' + retailBoostCollectionCampaignId + '" adset-id="' + adSetId + '" adset-version="' + adSetVersion + '" cost-per-click="' + costPerClick + '" timestamp="' + timeStamp + '" hmac-salt="' + hmacSalt + '" hmac="' + hmac + '" keyword-id="' + keywordId + '">' +
                            '<div class="wish-list-wrapper" data-role="add-to-links">' +
                                '<a href="#"' +
                                'data-post=""' +
                                'class="action towishlist" data-action="add-to-wishlist"' +
                                'title="Add to Wish List">' +
                                '<i class="fas fa-heart" style="font-size: 25px; color: #e6e6e6;"></i>' +
                                '</a>' +
                            '</div>' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                digiDealsLogo + digiSeconds +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                            '<div class="product actions product-item-actions">' +
                                '<div class="actions-primary">' + s19Label +
                                    addToCart +
                                '</div>' +
                            '</div>' +
                        '</div>'
            $(appendTo).append(productItem);
            //slots(product.refId, recommenderId, campaignId, tacticId);
        });
        $('.pa-digidirect-product-widget-container.widget-placeholder').remove();
    }
    
    /*digiMarketSidePanel('011987ea-124e-ef11-abf3-02bf4bf6447c', '#explore-digimarket-side-panel');
    if (isIphone16 && !isIphone15) {
        frequentlyBoughtWith('0a147ac5-047a-ef11-abf3-02bf4bf6447c', '#pdp-frquently-bought-with-desktop');
        bundleOverlay('ff513e77-387a-ef11-abf3-02bf4bf6447c', '#pdp-bundle-overlay-desktop');
    } else if (isIphone15 && !isIphone16) {
        frequentlyBoughtWith('2f97ea24-ed7a-ef11-abf3-02bf4bf6447c', '#pdp-frquently-bought-with-desktop');
        bundleOverlay('b9aeeb4e-ed7a-ef11-abf3-02bf4bf6447c', '#pdp-bundle-overlay-desktop');
    } else {
        frequentlyBoughtWith('ca223b70-fc3d-ec11-aae9-02dca44cceec', '#pdp-frquently-bought-with-desktop');
        bundleOverlay('02ed2d33-ee8e-ec11-aae9-02dca44cceec', '#pdp-bundle-overlay-desktop');
    }*/

    productTile('ca223b70-fc3d-ec11-aae9-02dca44cceec', '#pdp-frequently-bought-with-desktop', false);
    productTile('ca223b70-fc3d-ec11-aae9-02dca44cceec', '#pdp-frequently-bought-with-mobile', true);
    productTile('011987ea-124e-ef11-abf3-02bf4bf6447c', '#explore-digimarket-desktop', false);
    productTile('011987ea-124e-ef11-abf3-02bf4bf6447c', '#explore-digimarket-mobile', true);
    productTile('cecb45e7-043e-ec11-aae9-02dca44cceec', '#people-who-viewed-this-item-also-viewed-desktop', false);
    productTile('cecb45e7-043e-ec11-aae9-02dca44cceec', '#people-who-viewed-this-item-also-viewed-mobile', true);
    productTile('252b5970-293e-ec11-aae9-02dca44cceec', '#you-may-also-like-desktop', false);
    productTile('252b5970-293e-ec11-aae9-02dca44cceec', '#you-may-also-like-mobile', true);
    productTile('02ed2d33-ee8e-ec11-aae9-02dca44cceec', '#upsell-widget-desktop', false);
    
    //Minicart PA Widget
    (function () {
        const config = { childList: true, subtree: true }

        const observer = new MutationObserver((mutations, instance) => {
            const $widget = $('#pa-minicart-widget-desktop')

            // 🟢 Wait for widget container to appear
            if ($widget.length) {
              // Run your product tile builder
                productTile('5576c304-fd3d-ec11-aae9-02dca44cceec', '#pa-minicart-widget-desktop', false)
                setTimeout(() => {
                    const $carousel = $widget.filter('.owl-carousel.pa-minicart')
                    if ($carousel.length && !$carousel.hasClass('owl-loaded')) {
                        console.log('🦉 Initializing OwlCarousel for minicart...')
                        $carousel.owlCarousel({
                            loop: false,
                            nav: true,
                            margin: 15,
                            touchDrag: true,
                            mouseDrag: true,
                            smartSpeed: 800,
                            slideBy: 1,
                            responsive: {
                                0: { items: 2 },
                                768: { items: 3 },
                                1024: { items: 4 },
                                1310: { items: 4 },
                                1366: { items: 4 },
                                1550: { items: 4 }
                            },
                            dots: false,
                            autoplay: false,
                            autoplayTimeout: 3000
                        })
                    }
                }, 800)
                instance.disconnect()
            }
        })

        // 🎯 Observe the minicart container (use document.body as fallback)
        const target = document.querySelector('.block-minicart') || document.body
        observer.observe(target, config)

        // ⏰ Stop after 10s just in case
        setTimeout(() => observer.disconnect(), 10000)
    })()
    
    if (customerId && sessionId) {
        $("#pa-digimarket-side-panel .product-item-info.product-item:not(.slot)").each(function() {
            var element = $(this).attr("id");
            var widgetId = $(this).attr("widget-id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
            var adSetId = $(this).attr("adset-id");
            var adSetVersion = $(this).attr("adset-version");
            var costPerClick = $(this).attr("cost-per-click");
            var timeStamp = $(this).attr("timestamp");
            var hmacSalt = $(this).attr("hmac-salt");
            var hmac = $(this).attr("hmac");
            var keywordId = $(this).attr("keyword-id");
            isElementInViewPortSidePanel(element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
        });
        $(".pa-digidirect-product-widget .owl-item.active .product-item-info.product-item:not(.pa-bundle-container, .slot)").each(function() {
            var element = $(this).attr("id");
            var widgetId = $(this).attr("widget-id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
            var adSetId = $(this).attr("adset-id");
            var adSetVersion = $(this).attr("adset-version");
            var costPerClick = $(this).attr("cost-per-click");
            var timeStamp = $(this).attr("timestamp");
            var hmacSalt = $(this).attr("hmac-salt");
            var hmac = $(this).attr("hmac");
            var keywordId = $(this).attr("keyword-id");
            isElementInViewPort(element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
        });
    }
    
    function slots(widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId) {

        //var widgetId = '631dfdd4-dc01-ef11-abf3-02bf4bf6447c';

        var date = new Date();
        
        var events = {
                currentUrl: currentUrl,
                eventTime: date.toISOString(),
                refId: productId,
                widgetId: widgetId,
                routeId: routeId,              
                recommenderId: recommenderId,
                campaignId: campaignId,
                tacticId: tacticId,
                retailBoostCollectionCampaignId: retailBoostCollectionCampaignId,
                adSetId: adSetId,
                adSetVersion: adSetVersion,
                costPerClick: costPerClick,
                timeStamp: timeStamp,
                hmacSalt: hmacSalt,
                hmac: hmac,
                keywordId: keywordId
            }
            
        if (!retailBoostCollectionCampaignId || retailBoostCollectionCampaignId == "undefined") {
            delete events['retailBoostCollectionCampaignId']; 
        }
        if (!adSetId || adSetId == "undefined") {
            delete events['adSetId']; 
        }
        if (!adSetVersion || adSetVersion == "undefined") {
            delete events['adSetVersion']; 
        }
        if (!costPerClick || costPerClick == "undefined") {
            delete events['costPerClick']; 
        }
        if (!timeStamp || timeStamp == "undefined") {
            delete events['timeStamp']; 
        }
        if (!hmacSalt || hmacSalt == "undefined") {
            delete events['hmacSalt']; 
        }
        if (!hmac || hmac == "undefined") {
            delete events['hmac']; 
        }
        if (!keywordId || keywordId == "undefined") {
            delete events['keywordId']; 
        }

        const slotData = {
            customerId: customerId,
            sessionId: sessionId,
            events: [events]
        };

        console.log(JSON.stringify(slotData));

        $.ajax({
            //async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/events/slots",
            type: "POST",
            data: {
                eventData: slotData
            },
            success: function(data){
                console.log("slots", data);
            },
            error: function(){
                console.log('AJAX Fail!');
            }
        });
    }
    
    function uuidv4() {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'
        .replace(/[xy]/g, function (c) {
            const r = Math.random() * 16 | 0, 
                v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }

    //Product Info Add To Cart
    $(".price-final_price").click(function() {
        $(this).siblings('.product-item-actions').find('.action.tocart.primary').trigger('click');
    });
    
    //Side Panel Click Event
    $("#pa-digimarket-side-panel .product-item-info.product-item").click(function(){
        var widgetId = $(this).attr("widget-id");
        var productId = $(this).attr("product-id");
        var recommenderId = $(this).attr("recommender-id");
        var campaignId = $(this).attr("campaign-id");
        var tacticId = $(this).attr("tactic-id");
        var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
        var adSetId = $(this).attr("adset-id");
        var adSetVersion = $(this).attr("adset-version");
        var costPerClick = $(this).attr("cost-per-click");
        var timeStamp = $(this).attr("timestamp");
        var hmacSalt = $(this).attr("hmac-salt");
        var hmac = $(this).attr("hmac");
        var keywordId = $(this).attr("keyword-id");
        
        //var widgetId = '631dfdd4-dc01-ef11-abf3-02bf4bf6447c';

        var date = new Date();
        
        var events = {
                currentUrl: currentUrl,
                eventTime: date.toISOString(),
                clickId: uuidv4(),
                refId: productId,
                actionType: 1,
                contextType: 1,
                routeId: routeId,
                widgetId: widgetId,
                routeId: routeId,              
                recommenderId: recommenderId,
                campaignId: campaignId,
                tacticId: tacticId,
                retailBoostCollectionCampaignId: retailBoostCollectionCampaignId,
                adSetId: adSetId,
                adSetVersion: adSetVersion,
                costPerClick: costPerClick,
                timeStamp: timeStamp,
                hmacSalt: hmacSalt,
                hmac: hmac,
                keywordId: keywordId
            }
            
        if (!retailBoostCollectionCampaignId || retailBoostCollectionCampaignId == "undefined") {
            delete events['retailBoostCollectionCampaignId']; 
        }
        if (!adSetId || adSetId == "undefined") {
            delete events['adSetId']; 
        }
        if (!adSetVersion || adSetVersion == "undefined") {
            delete events['adSetVersion']; 
        }
        if (!costPerClick || costPerClick == "undefined") {
            delete events['costPerClick']; 
        }
        if (!timeStamp || timeStamp == "undefined") {
            delete events['timeStamp']; 
        }
        if (!hmacSalt || hmacSalt == "undefined") {
            delete events['hmacSalt']; 
        }
        if (!hmac || hmac == "undefined") {
            delete events['hmac']; 
        }
        if (!keywordId || keywordId == "undefined") {
            delete events['keywordId']; 
        }

        const clickData = {
            customerId: customerId,
            sessionId: sessionId,
            events: [events]
        };

        //console.log(JSON.stringify(clickData));

        $.ajax({
            async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/events/clicks",
            type: "POST",
            data: {
                eventData: clickData
            },
            success: function(data){
                console.log("clicks", data);
            },
            error: function(){
                console.log('AJAX Fail!');
            }
        });

    });

    $(".pa-digidirect-product-widget .product-item-info.product-item:not(.pa-bundle-container)").click(function(){
        var widgetId = $(this).attr("widget-id");
        var productId = $(this).attr("product-id");
        var recommenderId = $(this).attr("recommender-id");
        var campaignId = $(this).attr("campaign-id");
        var tacticId = $(this).attr("tactic-id");
        var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
        var adSetId = $(this).attr("adset-id");
        var adSetVersion = $(this).attr("adset-version");
        var costPerClick = $(this).attr("cost-per-click");
        var timeStamp = $(this).attr("timestamp");
        var hmacSalt = $(this).attr("hmac-salt");
        var hmac = $(this).attr("hmac");
        var keywordId = $(this).attr("keyword-id");
        
        //var widgetId = '631dfdd4-dc01-ef11-abf3-02bf4bf6447c';

        var date = new Date();
        
        var events = {
                currentUrl: currentUrl,
                eventTime: date.toISOString(),
                clickId: uuidv4(),
                refId: productId,
                actionType: 1,
                contextType: 1,
                routeId: routeId,
                widgetId: widgetId,
                routeId: routeId,              
                recommenderId: recommenderId,
                campaignId: campaignId,
                tacticId: tacticId,
                retailBoostCollectionCampaignId: retailBoostCollectionCampaignId,
                adSetId: adSetId,
                adSetVersion: adSetVersion,
                costPerClick: costPerClick,
                timeStamp: timeStamp,
                hmacSalt: hmacSalt,
                hmac: hmac,
                keywordId: keywordId
            }
            
        if (!retailBoostCollectionCampaignId || retailBoostCollectionCampaignId == "undefined") {
            delete events['retailBoostCollectionCampaignId']; 
        }
        if (!adSetId || adSetId == "undefined") {
            delete events['adSetId']; 
        }
        if (!adSetVersion || adSetVersion == "undefined") {
            delete events['adSetVersion']; 
        }
        if (!costPerClick || costPerClick == "undefined") {
            delete events['costPerClick']; 
        }
        if (!timeStamp || timeStamp == "undefined") {
            delete events['timeStamp']; 
        }
        if (!hmacSalt || hmacSalt == "undefined") {
            delete events['hmacSalt']; 
        }
        if (!hmac || hmac == "undefined") {
            delete events['hmac']; 
        }
        if (!keywordId || keywordId == "undefined") {
            delete events['keywordId']; 
        }

        const clickData = {
            customerId: customerId,
            sessionId: sessionId,
            events: [events]
        };

        //console.log(JSON.stringify(clickData));

        $.ajax({
            async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/events/clicks",
            type: "POST",
            data: {
                eventData: clickData
            },
            success: function(data){
                console.log("clicks", data);
            },
            error: function(){
                console.log('AJAX Fail!');
            }
        });

    });
    
    $(".pa-digidirect-product-widget .product-item-info.product-item:not(.pa-bundle-container) .action.tocart").click(function(){

        var widgetId = $(this).attr("widget-id");
        var productId = $(this).attr("product-id");
        var recommenderId = $(this).attr("recommender-id");
        var campaignId = $(this).attr("campaign-id");
        var tacticId = $(this).attr("tactic-id");
        var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
        var adSetId = $(this).attr("adset-id");
        var adSetVersion = $(this).attr("adset-version");
        var costPerClick = $(this).attr("cost-per-click");
        var timeStamp = $(this).attr("timestamp");
        var hmacSalt = $(this).attr("hmac-salt");
        var hmac = $(this).attr("hmac");
        var keywordId = $(this).attr("keyword-id");
        
        //var widgetId = '631dfdd4-dc01-ef11-abf3-02bf4bf6447c';

        var date = new Date();
        var product = {"refId": productId, "quantity": 1};
        
        var events = {
                currentUrl: currentUrl,
                eventTime: date.toISOString(),
                product: product,
                widgetId: widgetId,
                routeId: routeId,              
                recommenderId: recommenderId,
                campaignId: campaignId,
                tacticId: tacticId,
                retailBoostCollectionCampaignId: retailBoostCollectionCampaignId,
                adSetId: adSetId,
                adSetVersion: adSetVersion,
                costPerClick: costPerClick,
                timeStamp: timeStamp,
                hmacSalt: hmacSalt,
                hmac: hmac,
                keywordId: keywordId
            }
            
        if (!retailBoostCollectionCampaignId || retailBoostCollectionCampaignId == "undefined") {
            delete events['retailBoostCollectionCampaignId']; 
        }
        if (!adSetId || adSetId == "undefined") {
            delete events['adSetId']; 
        }
        if (!adSetVersion || adSetVersion == "undefined") {
            delete events['adSetVersion']; 
        }
        if (!costPerClick || costPerClick == "undefined") {
            delete events['costPerClick']; 
        }
        if (!timeStamp || timeStamp == "undefined") {
            delete events['timeStamp']; 
        }
        if (!hmacSalt || hmacSalt == "undefined") {
            delete events['hmacSalt']; 
        }
        if (!hmac || hmac == "undefined") {
            delete events['hmac']; 
        }
        if (!keywordId || keywordId == "undefined") {
            delete events['keywordId']; 
        }
        
        const productData = {
            customerId: customerId,
            sessionId: sessionId,
            events: [events]
        };
        
        console.log("productData", JSON.stringify(productData));

        $.ajax({
            async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/events/addtocart",
            type: "POST",
            data: {
                eventData: productData
            },
            success: function(data){
                console.log("addtocart", data);
            },
            error: function(){
                console.log('AJAX Fail!');
            }
        });

    });
    
    $("#product-addtocart-button").click(function(){

        var productId = <?= $productId; ?>;
        var quantity = $("#qty").attr("value");

        var date = new Date();
        
        var events = {
                currentUrl: currentUrl,
                eventTime: date.toISOString(),
                product: {"refId": productId, "quantity": quantity}
            }

        const productData = {
            customerId: customerId,
            sessionId: sessionId,
            events: [events]
        };

        //console.log("productData", JSON.stringify(productData));

        $.ajax({
            async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/events/addtocart",
            type: "POST",
            data: {
                eventData: productData
            },
            success: function(data){
                console.log("addtocart", data);
            },
            error: function(){
                console.log('AJAX Fail!');
            }
        });

    });
    
    function isElementInViewPort(element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId){
        var thisElement = document.getElementById(element);
        let rect = thisElement.getBoundingClientRect();

        // check if element is completely visible inside the viewport
        if ((rect.top <= 600 && rect.top >= 0) && rect.height != 0) {
            //console.log("Product ID id ", element, "The bounding Rect of element is ", rect, "viewPortBottom", viewPortBottom);
            //return (isTopInViewPort && isLeftInViewPort && isBottomInViewPort && isRightInViewPort);
            slots(widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
            $(thisElement).addClass("slot");
        }
    }
    
    function isElementInViewPortSidePanel(element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId){
        var thisElement = document.getElementById(element);
        let rect = thisElement.getBoundingClientRect();

        // check if element is completely visible inside the viewport
        if ((rect.top <= 880 && rect.top >= 0) && rect.height != 0) {
            //console.log("Product ID id ", element, "The bounding Rect of element is ", rect, "viewPortBottom", viewPortBottom);
            //return (isTopInViewPort && isLeftInViewPort && isBottomInViewPort && isRightInViewPort);
            slots(widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
            $(thisElement).addClass("slot");
        }
    }
    
    function isElementInViewPortOwlCarousel(currentElement, element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId){
        var thisElement = document.getElementById(element);
        let rect = thisElement.getBoundingClientRect();
        //console.log("element", element);
        // check if element is completely visible inside the viewport
        if ((rect.top <= 600 && rect.top >= 0) && rect.height != 0) {
            //console.log("Product ID id ", element, "The bounding Rect of element is ", rect, "viewPortBottom", viewPortBottom);
            //return (isTopInViewPort && isLeftInViewPort && isBottomInViewPort && isRightInViewPort);
            slots(widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
            currentElement.addClass("slot");
        }
    }

    window.addEventListener('scroll', function() {
        $("#pa-digimarket-side-panel .product-item-info.product-item:not(.slot)").each(function() {
            var element = $(this).attr("id");
            var widgetId = $(this).attr("widget-id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
            var adSetId = $(this).attr("adset-id");
            var adSetVersion = $(this).attr("adset-version");
            var costPerClick = $(this).attr("cost-per-click");
            var timeStamp = $(this).attr("timestamp");
            var hmacSalt = $(this).attr("hmac-salt");
            var hmac = $(this).attr("hmac");
            var keywordId = $(this).attr("keyword-id");
            isElementInViewPort(element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
        });
        $("#pdp-frquently-bought-with-desktop .product-item-info.product-item:not(.pa-bundle-container, .slot)").each(function() {
            var element = $(this).attr("id");
            var widgetId = $(this).attr("widget-id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
            var adSetId = $(this).attr("adset-id");
            var adSetVersion = $(this).attr("adset-version");
            var costPerClick = $(this).attr("cost-per-click");
            var timeStamp = $(this).attr("timestamp");
            var hmacSalt = $(this).attr("hmac-salt");
            var hmac = $(this).attr("hmac");
            var keywordId = $(this).attr("keyword-id");
            isElementInViewPort(element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
        });
        $(".pa-digidirect-product-widget .owl-item.active .product-item-info.product-item:not(.pa-bundle-container, .slot)").each(function() {
            var element = $(this).attr("id");
            var widgetId = $(this).attr("widget-id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
            var adSetId = $(this).attr("adset-id");
            var adSetVersion = $(this).attr("adset-version");
            var costPerClick = $(this).attr("cost-per-click");
            var timeStamp = $(this).attr("timestamp");
            var hmacSalt = $(this).attr("hmac-salt");
            var hmac = $(this).attr("hmac");
            var keywordId = $(this).attr("keyword-id");
            isElementInViewPortOwlCarousel($(this), element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
        });
        $(".pa-digidirect-product-widget .mobile-widget .product-item-info.product-item:not(.pa-bundle-container, .slot)").each(function() {
            var element = $(this).attr("id");
            var widgetId = $(this).attr("widget-id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
            var adSetId = $(this).attr("adset-id");
            var adSetVersion = $(this).attr("adset-version");
            var costPerClick = $(this).attr("cost-per-click");
            var timeStamp = $(this).attr("timestamp");
            var hmacSalt = $(this).attr("hmac-salt");
            var hmac = $(this).attr("hmac");
            var keywordId = $(this).attr("keyword-id");
            isElementInViewPort(element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
        });
    }, false);
    
    $("#minicart-content-wrapper").on('scroll', function(){
        $("#pa-minicart-desktop .product-item-info.product-item:not(.slot)").each(function() {
            console.log();
            var element = $(this).attr("id");
            var widgetId = $(this).attr("widget-id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
            var adSetId = $(this).attr("adset-id");
            var adSetVersion = $(this).attr("adset-version");
            var costPerClick = $(this).attr("cost-per-click");
            var timeStamp = $(this).attr("timestamp");
            var hmacSalt = $(this).attr("hmac-salt");
            var hmac = $(this).attr("hmac");
            var keywordId = $(this).attr("keyword-id");
            isElementInViewPort(element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
        });
    });
    
    //Frequently Bought With
    $(".select-all-products-on-bundle").change(function() {
        if(this.checked) {
            $('.pa-bundle-product').each(function(){
                if (!$(this).is(":checked")) {
                    $(this).trigger('click');
                }
            });
        } else {
            $('.pa-bundle-product').each(function(){
                if ($(this).is(":checked")) {
                    $(this).trigger('click');
                }
            });
        }
    });

    /*$(".pa-bundle-product").change(function() {
        var bundleTotal = Number($("#pa-bundle-total").text().substring(1));
        var bundleProductPrice = Number($(this).attr("data-product-price"));
        console.log(bundleTotal, bundleProductPrice);
        if(this.checked) {
            var newBundleTotal = bundleTotal + bundleProductPrice;
        } else {
            var newBundleTotal = bundleTotal - bundleProductPrice;
        }
        $("#pa-bundle-total").text('$' + Number(newBundleTotal).toFixed(2));
    });*/
    
    $("#pdp-frquently-bought-with-desktop input").each(function() {
        $(this).prop("checked", true);
    });
    
    var fbwBundleTotal = 0;
    $("#pdp-frquently-bought-with-desktop .pa-bundle-product").each(function() {
        let bundleProductPrice = Number($(this).attr("data-product-price"));
        fbwBundleTotal += bundleProductPrice;
    });
    $("#pa-bundle-total").text('$' + Number(fbwBundleTotal).toFixed(2));
    
    $("#pdp-bundle-overlay-desktop input").each(function() {
        $(this).prop("checked", true);
    });

    var overlayBundleTotal = 0;
    $("#pdp-bundle-overlay-desktop .pa-bundle-overlay-product").each(function() {
        let bundleProductPrice = Number($(this).attr("data-product-price"));
        overlayBundleTotal += bundleProductPrice;
    });
    $("#pa-bundle-overlay-total").text('$' + Number(overlayBundleTotal).toFixed(2));
    
    const observerMinicart = new MutationObserver((mutations) => {
        console.log("MutationObserver!");
        $('.action.showcart').addClass("-active");
        $('#minicartSidebar').addClass("-active");
        $('.minicart-items.item-qty').attr("style", "visibility: hidden !important;");
    }); 

    var miniCart = document.querySelector('.minicart-wrapper');
    const configMinicart = { attributes: false, childList: true, subtree: true }; 

    $("#add-bundle-tocart").click(function(){
        
        /*var productIds = [];

        $('.pa-bundle-product').each(function(){
            if(this.checked) {
                console.log("data-product-id: " + $(this).attr("data-product-id"));
                productIds.push($(this).attr("data-product-id"));
            }
        });

        var url = "https://www.digidirect.com.au/particularaudienceapi/index/frequentlyboughtwith";

        $.ajax({
            url: url,
            type: "POST",
            data: {
                productIds: productIds
            },
            success: function(data){
                console.log("Success!");
                observerMinicart.observe(miniCart, configMinicart);
            },
            error: function(){
                console.log("Fail!");
            }
        });
        observerMinicart.disconnect();*/
        
        $("#pdp-frquently-bought-with-desktop .product-item-info.product-item:not(.pa-bundle-container)").each(function(){
            
            if($(this).find('.pa-bundle-product').is(":checked")) {
                
                $(this).find('.action.tocart.primary').trigger('click');
                
                var widgetId = $(this).attr("widget-id");
                var productId = $(this).attr("product-id");
                var recommenderId = $(this).attr("recommender-id");
                var campaignId = $(this).attr("campaign-id");
                var tacticId = $(this).attr("tactic-id");
                var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
                var adSetId = $(this).attr("adset-id");
                var adSetVersion = $(this).attr("adset-version");
                var costPerClick = $(this).attr("cost-per-click");
                var timeStamp = $(this).attr("timestamp");
                var hmacSalt = $(this).attr("hmac-salt");
                var hmac = $(this).attr("hmac");
                var keywordId = $(this).attr("keyword-id");

                //var widgetId = '631dfdd4-dc01-ef11-abf3-02bf4bf6447c';

                var date = new Date();
                var product = {"refId": productId, "quantity": 1};

                var events = {
                        currentUrl: currentUrl,
                        eventTime: date.toISOString(),
                        product: product,
                        widgetId: widgetId,
                        routeId: routeId,              
                        recommenderId: recommenderId,
                        campaignId: campaignId,
                        tacticId: tacticId,
                        retailBoostCollectionCampaignId: retailBoostCollectionCampaignId,
                        adSetId: adSetId,
                        adSetVersion: adSetVersion,
                        costPerClick: costPerClick,
                        timeStamp: timeStamp,
                        hmacSalt: hmacSalt,
                        hmac: hmac,
                        keywordId: keywordId
                    }

                if (!retailBoostCollectionCampaignId || retailBoostCollectionCampaignId == "undefined") {
                    delete events['retailBoostCollectionCampaignId']; 
                }
                if (!adSetId || adSetId == "undefined") {
                    delete events['adSetId']; 
                }
                if (!adSetVersion || adSetVersion == "undefined") {
                    delete events['adSetVersion']; 
                }
                if (!costPerClick || costPerClick == "undefined") {
                    delete events['costPerClick']; 
                }
                if (!timeStamp || timeStamp == "undefined") {
                    delete events['timeStamp']; 
                }
                if (!hmacSalt || hmacSalt == "undefined") {
                    delete events['hmacSalt']; 
                }
                if (!hmac || hmac == "undefined") {
                    delete events['hmac']; 
                }
                if (!keywordId || keywordId == "undefined") {
                    delete events['keywordId']; 
                }

                const productData = {
                    customerId: customerId,
                    sessionId: sessionId,
                    events: [events]
                };

                //console.log("productData", JSON.stringify(productData));

                $.ajax({
                    async: true,
                    url: "https://www.digidirect.com.au/particularaudienceapi/events/addtocart",
                    type: "POST",
                    data: {
                        eventData: productData
                    },
                    success: function(data){
                        console.log("addtocart", data);
                    },
                    error: function(){
                        console.log('AJAX Fail!');
                    }
                });
            }

        });
    });

    //Bundle Overlay
    $(".select-all-products-on-bundle-overlay").change(function() {
        if(this.checked) {
            $('.pa-bundle-overlay-product').each(function(){
                if (!$(this).is(":checked")) {
                    $(this).trigger('click');
                }
            });
        } else {
            $('.pa-bundle-overlay-product').each(function(){
                if ($(this).is(":checked")) {
                    $(this).trigger('click');
                }
            });
        }
    });

    $(".pa-bundle-overlay-product").change(function() {
        var bundleTotal = Number($("#pa-bundle-overlay-total").text().substring(1));
        var bundleProductPrice = Number($(this).attr("data-product-price"));
        console.log(bundleTotal, bundleProductPrice);
        if(this.checked) {
            var newBundleTotal = bundleTotal + bundleProductPrice;
        } else {
            var newBundleTotal = bundleTotal - bundleProductPrice;
        }
        $("#pa-bundle-overlay-total").text('$' + Number(newBundleTotal).toFixed(2));
    });

    $("#add-bundle-overlay-tocart").click(function(){

        var productIds = [];
        $('.pa-bundle-overlay-product').each(function(){
            if(this.checked) {
                console.log("data-product-id: " + $(this).attr("data-product-id"));
                productIds.push($(this).attr("data-product-id"));
            }
        });

        var url = "https://www.digidirect.com.au/particularaudienceapi/index/frequentlyboughtwith";

        $.ajax({
            url: url,
            type: "POST",
            data: {
                productIds: productIds
            },
            success: function(data){
                console.log("Success!");
                observerMinicart.observe(miniCart, configMinicart);
            },
            error: function(){
                console.log("Fail!");
            }
        });
        observerMinicart.disconnect();
        
        $("#pdp-bundle-overlay-desktop  .product-item-info.product-item:not(.pa-bundle-container, .slot)").each(function(){
            var element = $(this).attr("id");
            var widgetId = $(this).attr("widget-id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
            var adSetId = $(this).attr("adset-id");
            var adSetVersion = $(this).attr("adset-version");
            var costPerClick = $(this).attr("cost-per-click");
            var timeStamp = $(this).attr("timestamp");
            var hmacSalt = $(this).attr("hmac-salt");
            var hmac = $(this).attr("hmac");
            var keywordId = $(this).attr("keyword-id");
            
            //var widgetId = '631dfdd4-dc01-ef11-abf3-02bf4bf6447c';

            var date = new Date();
            var product = {"refId": productId, "quantity": 1};

            var events = {
                    currentUrl: currentUrl,
                    eventTime: date.toISOString(),
                    product: product,
                    widgetId: widgetId,
                    routeId: routeId,              
                    recommenderId: recommenderId,
                    campaignId: campaignId,
                    tacticId: tacticId,
                    retailBoostCollectionCampaignId: retailBoostCollectionCampaignId,
                    adSetId: adSetId,
                    adSetVersion: adSetVersion,
                    costPerClick: costPerClick,
                    timeStamp: timeStamp,
                    hmacSalt: hmacSalt,
                    hmac: hmac,
                    keywordId: keywordId
                }

            if (!retailBoostCollectionCampaignId || retailBoostCollectionCampaignId == "undefined") {
                delete events['retailBoostCollectionCampaignId']; 
            }
            if (!adSetId || adSetId == "undefined") {
                delete events['adSetId']; 
            }
            if (!adSetVersion || adSetVersion == "undefined") {
                delete events['adSetVersion']; 
            }
            if (!costPerClick || costPerClick == "undefined") {
                delete events['costPerClick']; 
            }
            if (!timeStamp || timeStamp == "undefined") {
                delete events['timeStamp']; 
            }
            if (!hmacSalt || hmacSalt == "undefined") {
                delete events['hmacSalt']; 
            }
            if (!hmac || hmac == "undefined") {
                delete events['hmac']; 
            }
            if (!keywordId || keywordId == "undefined") {
                delete events['keywordId']; 
            }

            const productData = {
                customerId: customerId,
                sessionId: sessionId,
                events: [events]
            };

            //console.log("productData", JSON.stringify(productData));

            $.ajax({
                async: false,
                url: "https://www.digidirect.com.au/particularaudienceapi/events/addtocart",
                type: "POST",
                data: {
                    eventData: productData
                },
                success: function(data){
                    console.log("addtocart", data);
                },
                error: function(){
                    console.log('AJAX Fail!');
                }
            });

        });
        
        $("#bundle-overlay-container").hide();
    });

    $("#bundle-overlay-exit").click(function(){
        $("#bundle-overlay-container").hide();
    });

    $("#product-addtocart-button").click(function(){
        $("#bundle-overlay-container").show();
        $("#pdp-bundle-overlay-desktop .product-item-info.product-item:not(.pa-bundle-container, .slot)").each(function(){
            var element = $(this).attr("id");
            var widgetId = $(this).attr("widget-id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
            var adSetId = $(this).attr("adset-id");
            var adSetVersion = $(this).attr("adset-version");
            var costPerClick = $(this).attr("cost-per-click");
            var timeStamp = $(this).attr("timestamp");
            var hmacSalt = $(this).attr("hmac-salt");
            var hmac = $(this).attr("hmac");
            var keywordId = $(this).attr("keyword-id");
            
            //Slots Impression Event
            isElementInViewPort(element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
        });
    });
    
    const observer = new MutationObserver((mutations) => { 
        if ($("#pa-minicart-desktop").length) {
            //console.log("MutationObserver!");
            productTileMinicart('5576c304-fd3d-ec11-aae9-02dca44cceec', '#pa-minicart-desktop', false);
            stopMutationObserver();
        }
    }); 
    
    const config = { attributes: true, childList: true, subtree: true }; 
    observer.observe(document.body, config); 
    
    function stopMutationObserver() {
        observer.disconnect(); 
    }
    
    $(document).ready(function(){
        $(".owl-carousel.custom").owlCarousel({
            loop: false,
            nav: true,
            margin: 15,
            touchDrag: true,
            mouseDrag: true,
            smartSpeed: 800,
            slideBy: 1,
            responsive: {
                0: {
                    items:2
                },
                600: {
                    items: 2
                },
                768: {
                    items: 3
                },
                992: {
                    items: 4               
                 },
                1024: {
                    items: 4
                },
                1310: {
                    items: 5
                },
                1366: {
                    items: 5
                },
                1550: {
                    items: 5
                }
            },
            dots: false,
            autoplay: false,
            autoplayTimeout: 3000
        });
        
        $(".owl-carousel.upsell").owlCarousel({
            loop: false,
            nav: true,
            margin: 15,
            touchDrag: true,
            mouseDrag: true,
            smartSpeed: 800,
            slideBy: 1,
            responsive: {
                0: {
                    items:2
                },
                600: {
                    items: 2
                },
                768: {
                    items: 3
                },
                992: {
                    items: 4               
                 },
                1024: {
                    items: 4
                },
                1310: {
                    items: 4
                },
                1366: {
                    items: 4
                },
                1550: {
                    items: 4
                }
            },
            dots: false,
            autoplay: false,
            autoplayTimeout: 3000
        });
    
        //Owl Nav Slot Observer
        $(".owl-carousel.custom .owl-prev, .owl-carousel.custom .owl-next").click(function() {
            console.log("Owl Nav Button Clicked!");
            $(".pa-digidirect-product-widget .owl-item.active .product-item-info.product-item:not(.slot)").each(function() {
                var element = $(this).attr("id");
                var widgetId = $(this).attr("widget-id");
                var productId = $(this).attr("product-id");
                var recommenderId = $(this).attr("recommender-id");
                var campaignId = $(this).attr("campaign-id");
                var tacticId = $(this).attr("tactic-id");
                var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
                var adSetId = $(this).attr("adset-id");
                var adSetVersion = $(this).attr("adset-version");
                var costPerClick = $(this).attr("cost-per-click");
                var timeStamp = $(this).attr("timestamp");
                var hmacSalt = $(this).attr("hmac-salt");
                var hmac = $(this).attr("hmac");
                var keywordId = $(this).attr("keyword-id");
                isElementInViewPortOwlCarousel($(this), element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
            });
        });
        
        var htmlBody = $("#html-body");

        const minicartObserver = new MutationObserver((mutations) => { 
            if (htmlBody.hasClass("-minicart-opened")) {
                $("#pa-minicart-desktop .product-item-info.product-item:not(.slot)").each(function() {
                    var element = $(this).attr("id");
                    var widgetId = $(this).attr("widget-id");
                    var productId = $(this).attr("product-id");
                    var recommenderId = $(this).attr("recommender-id");
                    var campaignId = $(this).attr("campaign-id");
                    var tacticId = $(this).attr("tactic-id");
                    var retailBoostCollectionCampaignId = $(this).attr("retail-boost-collection-campaign-id");
                    var adSetId = $(this).attr("adset-id");
                    var adSetVersion = $(this).attr("adset-version");
                    var costPerClick = $(this).attr("cost-per-click");
                    var timeStamp = $(this).attr("timestamp");
                    var hmacSalt = $(this).attr("hmac-salt");
                    var hmac = $(this).attr("hmac");
                    var keywordId = $(this).attr("keyword-id");
                    isElementInViewPort(element, widgetId, productId, recommenderId, campaignId, tacticId, retailBoostCollectionCampaignId, adSetId, adSetVersion, costPerClick, timeStamp, hmacSalt, hmac, keywordId);
                });
            }
        }); 

        const minicartConfig = { attributes: true, childList: false, subtree: false }; 
        minicartObserver.observe(htmlBody, minicartConfig); 

    });
    
});
</script>

<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
           "bindSubmit": true
        }
    }
}
</script>

<script>
    
    function loadMoreProducts(widgetClass) {
        var hiddenTiles = document.querySelectorAll('.'+ widgetClass + ' ' + ' .hide-product-item'); 
        var ctr = 0;
        for (let x = 0; x < hiddenTiles.length; x++) {
          ctr++;
          hiddenTiles[x].classList.remove('hide-product-item');
          if (ctr == 4) break;
        }
        var hiddenTilesCount = document.querySelectorAll('.'+ widgetClass + ' ' + ' .hide-product-item'); 
        if (hiddenTilesCount.length == 0) {
            document.querySelectorAll('.'+ widgetClass + ' ' + '.load-more')[0].style.display = "none";    
            document.querySelectorAll('.'+ widgetClass + ' ' + '.view-less')[0].style.display = "block";    
             
            try {
                document.querySelectorAll('.'+ widgetClass + ' ' + '.view-all')[0].style.display = "block"; 
            }
            catch(err) {
            }
        }
    }

    function viewLessProducts(widgetClass) {
        var productTiles = document.querySelectorAll('.'+ widgetClass + ' ' + '.mobile-widget .product-item'); 

        var ctr = 0;
        for (let x = 0; x < productTiles.length; x++) {
          ctr++;
          if (ctr > 4) {
             productTiles[x].classList.add('hide-product-item');
          }
        }
        
        document.querySelectorAll('.'+ widgetClass + ' ' + '.load-more')[0].style.display = "block";    
        document.querySelectorAll('.'+ widgetClass + ' ' + '.view-less')[0].style.display = "none";    
        try {
            document.querySelectorAll('.'+ widgetClass + ' ' + '.view-all')[0].style.display = "none"; 
        }
        catch(err) {
        }
        document.getElementById(widgetClass).scrollIntoView();
    }
    
</script>