<?php /* @var $block Magento\Framework\View\Element\Template */ ?>
<?php $url = $block->getAjaxUrl() ?>
<?php $currentId = $block->getCurrentId() ?>
<?php $currentName = $block->getCurrentName() ?>
<?php $elementName = $block->getElementName() ?>
<?php $elementHtmlId = $block->getElementHtmlId() ?>
<div class="admin__action-multiselect-wrap action-select-wrap auto-complete-wrap"
     data-mage-init='{"ajaxAutoComplete":{"url":"<?php /* @escapeNotVerified */ echo $url ?>"}}'>
    <input type="hidden"
           id="<?php /* @escapeNotVerified */ echo $elementHtmlId ?>"
           name="<?php /* @escapeNotVerified */ echo $elementName ?>"
           data-role="hidden-input"
           value="<?php /* @escapeNotVerified */ echo $currentId ?>">
    <div class="action-select admin__action-multiselect auto-complete-label"
         data-action="open-search"><?php /* @escapeNotVerified */ echo $currentName ?></div>
    <button class="action-close no-display" type="button" data-action="clear"></button>
    <div class="action-menu" data-role="search-block" style="z-index: 2;">
        <div class="admin__action-multiselect-search-wrap">
            <input class="admin__control-text" data-action="input-text" type="text"/>
            <label class="admin__action-multiselect-search-label"></label>
        </div>
    </div>
</div>
