<?php

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<select data-mage-init='{"customSelectInit": {}}' id="sorter" data-role="sorter" class="sorter-options">
    <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
        <?php if ($_order == 'Position'): //Label hardcoded in vendor/magento/module-catalog/Model/Config.php ?>
            <?php $_order = 'Bestsellers'; //according #287685 ?>
        <?php endif; ?>
        <option value="<?= /* @escapeNotVerified */ $_key ?>"
            <?php if ($block->isOrderCurrent($_key)): ?>
                selected="selected"
            <?php endif; ?>
        >
            <?= $block->escapeHtml(__($_order)) ?>
        </option>
    <?php endforeach; ?>
</select>
