<?php

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php $orders = $block->getAvailableOrders(); ?>
<?php $currentOrderName = isset($orders[$this->getCurrentOrder(false)]) ? $orders[$this->getCurrentOrder(false)] : ''; ?>

<div class="heading">
    <span class="label">
        <?php /* @escapeNotVerified */  echo  __('Sort by:'); ?>
    </span>
    <?php echo $currentOrderName; ?>
</div>
<div class="filter-options">
    <ul id="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <?php if ($_order == 'Position'): //Label hardcoded in vendor/magento/module-catalog/Model/Config.php ?>
                <?php $_order = 'Bestsellers'; //according #287685 ?>
            <?php endif; ?>
            <option value="<?= /* @escapeNotVerified */ $_key ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
            >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>    
    </ul>
</div>
