<?php
/** @var \Digidirect\MyOrderItemsGroups\Block\Customer\MyOrderItems\Group\Share $block */
$itemsList = $block->getItems();
$requestParams = $block->collectFilterParams();
$currentGroup = $block->getCurrentGroup();
?>
<?php if ($currentGroup): ?>
    <h3><?= $currentGroup->getName() ?></h3>
<?php endif; ?>
<div class="group-block">
    <div class="items-block">
        <?php foreach ($itemsList as $salesItem): ?>
            <div class="item">
                <?php /** @var \Magento\Sales\Model\Order\Item $salesItem */ ?>
                <?php $product = $block->getProduct($salesItem); ?>
                <h3 class="name"><?php echo $block->escapeHtml($salesItem->getName()); ?></h3>
                <div class="image"><img src="<?php echo $block->escapeUrl($block->getDataHelper()->getImageFilePath($salesItem)) ?>" alt="<?php echo $block->escapeHtml($salesItem->getName()); ?>"></div>
                <?php if ($block->isItemSalable($salesItem)): ?>
                    <a class="add-to-cart-link" href="<?= $block->escapeUrl($block->getAddItemActionUrl($salesItem->getItemId())) ?>" title="<?php echo $block->escapeHtml(__('Add to cart')) ?>"><?php echo $block->escapeHtml(__('Add to cart')) ?></a>
                    <?php if ($block->getWishlistHelper()->isAllow() && $product): ?>
                        <div data-role="add-to-links" class="actions-secondary">
                            <a href="#"
                               class="action towishlist"
                               title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                               aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                               data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($product) ?>'
                               data-action="add-to-wishlist"
                               role="button">
                                <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                            </a>
                        </div>
                    <?php endif; ?>
                    <div class="product details product-item-details">
                        <?php if($product): ?>
                            <?= /* @escapeNotVerified */ $block->getProductPriceHtml($product, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE) ?>
                        <?php endif; ?>
                    </div>
                <?php else: ?>
                    <?= $block->escapeHtml(__('This product is not more available in the store')) ?>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <a class="item" title="<?= $block->escapeHtml(__('Add group to cart')) ?>" href="<?= $block->escapeUrl($block->getAddGroupActionUrl()) ?>"><?= $block->escapeHtml(__('Add group to cart')) ?></a>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "shareGroupCartUpdate": {}
        }
    }
</script>