<?php
/**
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2022 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */

namespace Plumrocket\Newsletterpopup\Plugin;

use Magento\Framework\Stdlib\DateTime\DateTime;
use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\SalesRule\Api\CouponRepositoryInterface;
use Magento\SalesRule\Model\Coupon;
use Magento\SalesRule\Model\Utility;
use Magento\SalesRule\Model\Rule;
use Magento\Quote\Model\Quote\Address;

/**
 * @since 4.5.1
 */
class CouponExpiredPlugin
{
    /**
     * @var CouponRepositoryInterface
     */
    private $couponRepository;

    /**
     * @var SearchCriteriaBuilder
     */
    private $criteriaBuilder;

    /**
     * @var \Magento\Framework\Stdlib\DateTime\DateTime
     */
    private $dateTime;

    /**
     * @param CouponRepositoryInterface                   $couponRepository
     * @param SearchCriteriaBuilder                       $criteriaBuilder
     * @param \Magento\Framework\Stdlib\DateTime\DateTime $dateTime
     */
    public function __construct(
        CouponRepositoryInterface $couponRepository,
        SearchCriteriaBuilder $criteriaBuilder,
        DateTime $dateTime
    ) {
        $this->couponRepository = $couponRepository;
        $this->criteriaBuilder = $criteriaBuilder;
        $this->dateTime = $dateTime;
    }

    /**
     * Check whether coupon code was generated by Newsletter Popup has expired.
     *
     * @param \Magento\SalesRule\Model\Utility   $utility
     * @param \Magento\SalesRule\Model\Rule      $rule
     * @param \Magento\Quote\Model\Quote\Address $address
     * @return void
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function beforeCanProcessRule(Utility $utility, Rule $rule, Address $address): void
    {
        if ((int) $rule->getCouponType() !== Rule::COUPON_TYPE_SPECIFIC
            || ! $rule->getUseAutoGeneration()
            || $rule->getToDate()
        ) {
            return;
        }

        $couponCode = $address->getQuote()->getCouponCode();
        if (! $couponCode) {
            return;
        }

        $couponSearchResult = $this->couponRepository
            ->getList($this->criteriaBuilder->addFilter('code', $couponCode)->create())
            ->getItems();

        if (empty($couponSearchResult)) {
            return;
        }

        /** @var Coupon $coupon */
        $coupon = reset($couponSearchResult);
        $expiresOn = $coupon->getNpExpirationDate();
        if ($expiresOn && $this->dateTime->gmtDate($expiresOn) < $this->dateTime->gmtDate()) {
            $rule->setIsValidForAddress($address, false);
        }
    }
}
