<?php
//@codingStandardsIgnoreFile
/**
 * @var \Digidirect\Feed\Helper\Output $outputHelper
 * @var \Magento\Framework\Json\Helper\Data $jsonHelper
 */
$outputHelper = $this->helper('Digidirect\Feed\Helper\Output');
$jsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');

$libraryInit = [
    'FeedLibrary' => [
        'url' => $this->getUrl('digidirect_feed/feed/library')
    ]
];
?>

<script>
    require([
        'jquery'
    ], function ($) {
        $.attributes = <?php /* @escapeNotVerified */ echo $jsonHelper->jsonEncode($outputHelper->getAttributeOptions()) ?>;
        $.modifiers = <?php /* @escapeNotVerified */ echo $jsonHelper->jsonEncode($outputHelper->getFilterOptions()) ?>;
        $.patternTypes = <?php /* @escapeNotVerified */ echo $jsonHelper->jsonEncode($outputHelper->getPatternTypeOptions()) ?>;
    });
</script>

<button data-mage-init='<?php /* @escapeNotVerified */ echo $jsonHelper->jsonEncode($libraryInit) ?>'
        class="feed__library-button"
        onclick="return false;"><i class="fa fa-graduation-cap"></i> <?php echo $block->escapeHtml(__('Library of patterns')) ?>
</button>

<script type="text/x-magento-init">
    <?php /* @escapeNotVerified */ echo $jsonHelper->jsonEncode($block->getJsConfig()) ?>
</script>

<div data-bind="scope: 'schema_xml'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
