<?php

use Magento\Framework\App\Action\Action;

/**
 * Author: Johnry Valeriano
 */
/** @var \Digidirect\OnSaleProducts\Block\Widget\OnSaleProducts $block */
?>
<?php
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    
    $title = __('On Sale Products');
}
?>

 <?php if ($exist) :?>
    <div class="block widget block-new-products product-home-listing products-widget <?= /* @noEscape */ $mode ?>">
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <div id="on-sale-carousel" 
                    class="product-items product-carousel owl-carousel owl-theme 
                    <?= /* @noEscape */ $type ?>"
                    
                    data-mage-init='{
                      "productTile": {
                          <?php if($block->isRedirectToCartEnabled()): ?>
                          "isRedirectToCartEnabled": true,
                          <?php endif; ?>
                          "type":"<?= /* @escapeNotVerified */ (count($items) > 2) ? 'slider' : 'default'; ?>"
                      }
                     }'>
                    
                    <?php foreach ($items as $_item) :?>
                    
                    <?php
                        $productName = $_item->getName();
                        $productUrl = $block->getProductUrl($_item);
                        $finalProductPrice = $_item->getFinalPrice();
                        $qff_bonus_points = 0;
                        if ($_item->offsetExists("qff_bonus_points") && $_item->offsetExists("qff_base")) {
                            $qff_bonus_points = $_item->getQffBonusPoints();
                            $qff_base_points = $_item->getQffBase();
                            $bonusPlusBase = $qff_bonus_points + $qff_base_points;

                            $points = number_format($finalProductPrice * $bonusPlusBase);
                        }else {
                            if($_item->offsetExists("qff_base")){
                                $qff_base_points = $_item->getQffBase();
                                $points = number_format($finalProductPrice * $qff_base_points);
                            } else {
                                $points = number_format($finalProductPrice * 2);
                            }
                        } 

                        $finalQffPoints = $_item->getPoints();
                    ?>
                    
                    <div class="product-item item">
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <div class="actions-secondary wish-list-wrapper" data-role="add-to-links">
                                    
                                    <div class="tag on-sale">
                                        On Sale
                                    </div>
                                    
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                        <a href="#"
                                        data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item); ?>'
                                        class="action towishlist" data-action="add-to-wishlist"
                                        title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-heart"></use></svg>
                                        </a>
                                    <?php endif; ?>
                                </div>
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?= $block->getProductPriceHtml($_item, $type); ?>
                                
                                <?php if ($templateType) :?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart) :?>
                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart) :?>
                                                <div class="actions-primary">
                                                    <?php $addToCartUrl = $block->getAddToCartUrl($_item); ?>

                                                    <form data-role="tocart-form"
                                                            data-product-sku="<?=  /* @escapeNotVerified */ $_item->getSku(); ?>"
                                                            data-mage-init='{"validation": {}}'
                                                            action="<?= $block->escapeUrl($addToCartUrl); ?>"
                                                            method="post">

                                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ (int)$_item->getEntityId(); ?>">
                                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Url\Helper\Data')->getEncodedUrl($addToCartUrl); ?>">
                                                            <?php echo $block->getBlockHtml('formkey')?>
                                                                    <?php if ($toCartFormBlock = $block->getChildBlock('tocart_form')): ?>
                                                                        <?php /* @escapeNotVerified */ echo $toCartFormBlock->setProduct($_item)->getChildHtml(); ?>
                                                                    <?php endif; ?>
                                                            <button class="action tocart primary"
                                                                    type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                            </button>
                                                      </form>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                
                                <div class="qantas-pts-wrapper">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-qantas"></use></svg>
                                    <span>Earn <?= $points ?> Qantas Points</span>
                                </div>
                                
                                <?php if ($rentBlock = $block->getChildBlock('product.tile.rent')): ?>
                                    <?= $rentBlock->toHtml(); ?>
                                <?php endif; ?>
                                <?php if ($afterToCartFormBlock = $block->getChildBlock('tocart_form.after')): ?>
                                    <?= $afterToCartFormBlock->setProduct($_product)->getChildHtml(); ?>
                                <?php endif; ?>
                            </div>
                        </div>
                     </div>
                    <?php endforeach ?>
                </div>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>

<script>
    require(['jquery', 'owl_carousel'],
        function ($) {
            $(document).ready(function() {
                $('#on-sale-carousel').owlCarousel({
                    loop:false,
                    nav:true,
                    navText:["<div class='nav-btn prev-slide'></div>","<div class='nav-btn next-slide'></div>"],
                    responsive:{
                        0:{
                            items:2,
                            margin: 15,
                            nav:false,
                            loop:true,
                            autoplay: true,
                            autoplayTimeout:3000
                        },
                        600:{
                            items:3,
                            nav:false
                        },
                        1000:{
                            items:4,
                            loop:false
                        },
                        1680:{
                            items:5,
                            loop:false
                        }
                    },
                    dots:false,
                    autoplay:false,
                    autoplayTimeout:3000
                })
            });
        }
    );
</script>