<?php
// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>
<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Compatible Products');
            $items = $block->getAllItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $_quickViewHelper = $this->helper('Digidirect\QuickView\Helper\Data');
            $showQuickView = $_quickViewHelper->isModuleEnabled();
            $quickViewUseForMobile = true;
            $quickViewLabel = __('Quick View');

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Compatible Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $_quickViewHelper = $this->helper('Digidirect\QuickView\Helper\Data');
            $showQuickView = $_quickViewHelper->isModuleEnabled();
            $quickViewUseForMobile = true;
            $quickViewLabel = __('Quick View');

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    default:
        $exist = null;
}
?>
<?php if ($exist):?>

<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<div class="block shelf-related <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
    <?php else: ?>
    <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php endif; ?>
        <?php else: ?>
        <div class="block <?= /* @escapeNotVerified */ $class ?>">
            <?php endif; ?>
            <div class="block-title title">
                <strong id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class ?>-heading">
                <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type ?>">
                    <ol class="products list items product-items related-slider-shelf"  data-mage-init='{
                                "slickInit":{
                                    "arrows": false,
                                    "slidesToShow": 2,
                                    "slidesToScroll": 1,
                                    "mobileFirst": true,
                                    "waitForAnimate": false,
                                    "autoplay": false,
                                    "dots": false,
                                    "responsive": [
                                        {
                                            "breakpoint": 768,
                                            "settings": {"slidesToShow": 3
                                            }
                                        }, {
                                            "breakpoint": 1280,
                                            "settings": {"slidesToShow": 4
                                            }
                                        }, {
                                            "breakpoint": 1440,
                                            "settings": {"slidesToShow": 4,
                                              "arrows": true
                                            }
                                        }, {
                                            "breakpoint": 1800,
                                            "settings": {"slidesToShow": 6,
                                            "arrows": true
                                            }
                                        }
                                    ]
                                }
                            }'>
                        <?php foreach ($items as $_item): ?>
                            <?php
                            $productName = $_item->getName();
                            $productUrl = $block->getProductUrl($_item);
                            ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell'): ?>
                                <li class="item product product-item" style="display: none;">
                            <?php else: ?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info <?= /* @escapeNotVerified */ $available ?>">
                                <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>

                                    <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>

                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($showAddTo || $showCart): ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                            <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <button class="action tocart"
                                                                    data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                    type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($showQuickView): ?>
                                                <span role="button"
                                                      data-role="quickview-button"
                                                      data-url="<?= $block->escapeUrl($block->getProductUrl($_item)) . '?quickview=1'; ?>"
                                                      class="quickview-button 123"
                                                      title="<?= $block->escapeHtml($quickViewLabel); ?>">
                                                        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon">
                                                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-quick"></use>
                                                        </svg>
                                                        <span class="title"><?= $block->escapeHtml($quickViewLabel); ?></span>
                                                    </span>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
<?php if ($showQuickView): ?>
    <div class="quickview-content" data-role="quickview-content">
        <iframe class="quickview-iframe" src="" data-role="quickview-window" frameborder="0" name="quickview"></iframe>
    </div>
    <script type="text/x-magento-init">
            {
                ".shelf-related": {
                    "quickView": {
                        "loaderIcon": "<?= $block->escapeUrl($this->helper('Digidirect\Utilities\Helper\Animation')->getImage()); ?>",
                        "loaderText": "<?= $block->escapeHtml($this->helper('Digidirect\Utilities\Helper\Animation')->getText()); ?>",
                        "isMobileEnabled": "<?= /* @escapeNotVerified */ $quickViewUseForMobile ? true : false ?>"
                    }
                }
            }
    </script>
<?php endif; ?>
<?php endif;?>
