<?php
use Magento\Framework\App\Action\Action;
?>

<?php
/**
 * Product list template
 *
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $_helper \Magento\Catalog\Helper\Output
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$showWishlist = true;

?>
<?= $block->getToolbarHtml() ?>
<?= $block->getAdditionalHtml() ?>
<?php
$currentPage = $this->getRequest()->getFullActionName();
?>

<?php
$categoryName = "";
if ($currentPage != "catalogsearch_result_index") {
    $catalogHelperData = $this->helper('Magento\Catalog\Helper\Data');
    $categoryObject = $catalogHelperData->getCategory();
    $categoryId = $categoryObject->getId();
    $categoryName = $categoryObject->getName();
}
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    
<?php endif; ?>

<script>
    /*require([
            'jquery'
        ],
        function ($) {

            $('.product-category-listing li .product-item-info .product-item-photo').each(function(){
                if ($(this).find('.product-overlay').length) {
                    $(this).find('.overlay-container').append($(this).find('.product-overlay'));
                }
                if ($(this).find('.digiseconds-overlay').length) {
                    $(this).find('.overlay-container').attr("style", "top: 65px;");
                }
            });

    });*/
</script>
