<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
$pricingHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                <div class="control">
                    <input type="number"
                           name="qty"
                           id="qty"
                           value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                           title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                           class="input-text qty"
                           data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                           />
                </div>
            </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action tocart"
                        id="product-addtocart-button"
                        data-action="add-to-cart-action"
                        >
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
                
                <?php echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('secure-pay')
                    ->toHtml();
                ?>
            </div>
        </div>
    </div>

    <div class="btn-wrapper-pdp">
        <div class="price">
            <?php
            $productPrice = (float) $_product->getPrice();
            $productFinalPrice = (float) $_product->getFinalPrice();
            ?>

            <div class="price-full" id="priceFull"><?= /* @escapeNotVerified */  $pricingHelper->currency($productPrice, true, false) ?></div>
            <div class="price-promotional" id="pricePromotional"></div>
            <div class="before" id="beforeCB"></div>
            <div class="after" id="afterCB"></div>
        </div>
        <div class="btn" id="add-cart-btn"></div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Catalog/js/add-to-cart": {}
        }
    }
</script>