<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <?php $childNames = $block->getChildNames();?>
    <?php $detailedInfoGroup = array_intersect($childNames, $detailedInfoGroup); ?>
<div class="product info detailed">
    <?php $layout = $block->getLayout(); ?>
    <div class="product data items details-tab" id="details-tab">
        
        <?php foreach ($detailedInfoGroup as $name): ?>
            <?php
            $html = $layout->renderElement($name);
            if (!trim($html)) {
                continue;
            }
            $alias = $layout->getElementAlias($name);
            $aliasName = $alias;

            if ($alias == 'additionalinfo') {
                $aliasName = $block->escapeHtml(__('Additional Information'));
            }

            if ($alias == 'description') {
                $aliasName = $block->escapeHtml(__('Product Description'));
            }

            if ($alias == 'whatinthebox') {
                $aliasName = $block->escapeHtml(__('What’s In The Box'));
            }

            if ($alias == 'productoverview') {
                $aliasName = $block->escapeHtml(__('Product Overview'));
            }
            
            if ($alias == 'spec') {
                $aliasName = $block->escapeHtml(__('Specs'));
            }
            
            if ($alias == 'reviews') {
                $aliasName = $block->escapeHtml(__('Product Review'));
            }

            $label = $block->getChildData($alias, 'title');
          
            ?>
            <div class="data item title tab-in <?= /* @escapeNotVerified */ $alias ?> tab_check"
                 data-alias="<?= /* @escapeNotVerified */ $alias ?>"
                 aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                 data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                <a class="data switch"
                   tabindex="-1"
                   data-toggle="switch"
                   href="#<?= /* @escapeNotVerified */ $alias ?>"
                   id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                    <?= /* @escapeNotVerified */ $aliasName ?>
                    <div class="arrow">
                       <!--  <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon svgi-action">
                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-left"></use>
                        </svg> -->
                    </div>
                </a>
            </div>
                <div class="data item content tab_details <?= /* @escapeNotVerified */ $alias ?>" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                    <?= /* @escapeNotVerified */ $html; ?>
                    <div class="read-more">
                        <div class="title">
                            <span class="readmore">
                                <?php echo $block->escapeHtml(__('+ Read more')); ?>
                            </span>
                        </div>
                    </div>
                </div>
        <?php endforeach; ?>

    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Catalog/js/read-more": {}
        }
    }
</script>
<?php endif; ?>

<?php $_product = $block->getProduct(); 
    $attr_exists = $_product->getResource()->getAttribute('brand');

    if ($attr_exists){
        $brand_name = $_product->getAttributeText('brand');
    }
    
    $attr2_exists = $_product->getResource()->getAttribute('apn');

    if ($attr2_exists){
        $apn = $_product->getAttributeText('apn');
    }
?>

<script type='text/javascript'>
    var ccs_cc_args = ccs_cc_args || [];

    // 1WS Product Page
    ccs_cc_args.push(['mf', '<?php $brand_name; ?>']);
    ccs_cc_args.push(['pn', '<?php $apn; ?>']);
    ccs_cc_args.push(['lang', 'EN']);
    ccs_cc_args.push(['market', 'AU']);

    (function () {
       var o = ccs_cc_args; o.push(['_SKey', 'caf81995']); o.push(['_ZoneId', 'f38beb7ad7']);
       var sc = document.createElement('script'); sc.type = 'text/javascript'; sc.async = true;
       sc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.cs.1worldsync.com/jsc/h1ws.js';
       var n = document.getElementsByTagName('script')[0]; n.parentNode.insertBefore(sc, n);
    })();
    
</script>
