<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>
<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currencysymbol = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currencyCode = $currencysymbol->getStore()->getCurrentCurrencyCode();
$points = $_product->getFinalPrice();
$finalQffPoints = $_product->getPoints();
$finalProductPrice = $_product->getFinalPrice();
$qff_bonus_points = 0;
if ($_product->offsetExists("qff_bonus_points") && $_product->offsetExists("qff_base")) {
    $qff_bonus_points = $_product->getQffBonusPoints();
    $qff_base_points = $_product->getQffBase();
    $bonusPlusBase = $qff_bonus_points + $qff_base_points;

    $points = number_format($finalProductPrice * $bonusPlusBase);
}else {
    if($_product->offsetExists("qff_base")){
        $qff_base_points = $_product->getQffBase();
        $points = number_format($finalProductPrice * $qff_base_points);
    } else {
        $points = number_format($finalProductPrice * 2);
    }
} 
?>

<div class="product-add-form">
    <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= /* @NoEscape */ $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="item"  value="<?= /* @noEscape */ $block->getRequest()->getParam('id') ?>" />


        <div class="push-block-left qantas-pts-wrapper">
            <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-qantas"></use></svg>
            <span data-sample="<?php  echo $qff_bonus_points?>">Earn <?= $points ?> Qantas Points</span>
        </div>
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top') ?>
        <?php if (!$block->hasOptions()):?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else:?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
            <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?= $block->getChildHtml('form_bottom') ?>
    </form>

    <div class="init _hidden">
        <script>
            if (typeof fbq !== undefined) {
                fbq('track', 'ViewContent', {
                    content_name: '<?php echo $block->escapeHtml($_product->getName()); ?>',
                    content_id: '<?php echo $block->escapeHtml($_product->getSku()); ?>',
                    currency: '<?php echo $block->escapeHtml($currencyCode); ?>',
                    content_type: 'product'
                });
            }
        </script>
    </div>
</div>

<script type="text/x-magento-init">
    {
    "[data-role=priceBox][data-product-id='<?= $block->escapeHtml($_product->getId()) ?>']": {
    "priceBox": {
    "priceConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>
    }
    }
    }
</script>

<?php if ($_product): ?>
    <?php $price = $_product->getData('final_price'); ?>
    <script>
        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push({
            'value': <?= $price ?>,
            'items': [{
                'id':  <?= $_product->getSku(); ?>,
                    'google_business_vertical': 'retail'
                }]
        });
    </script>
<?php endif ?>
