<?php
    $getDescription = $block->getProduct()->getDescription();
?>
<div class="short-desc-container">
    <div class="short-desc-title">Product Description</div>
    <div class="short-desc">
        <?php 
            if (!is_null($getDescription)) {
                echo html_entity_decode($getDescription);
            }
        ?>
    </div>
    <a href="#productoverview"><div class="short-desc-read-more">Read More</div></a>
</div>
