<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Block\Widget\Name;
use Magento\Company\Block\Company\Account\Create;
use Magento\Directory\Helper\Data as DirectoryHelper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;


/**
 * Create account form template
 *
 * @var Create $block
 * @var SecureHtmlRenderer $secureRenderer
 */
?>


<?php
    echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('b2b-registration-header')->toHtml();
?>
<div class="top-image-container">
    <div class="overlay"></div>
    <img src="<?= $block->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'media/wysiwyg/myaccount/signup-bg.png' ?>" alt="Top Banner" class="top-image">
    <div class="text-overlay">
        <span class="sign-up-heading">Sign Up</span>
        <p class="sign-up-text">
            Want a digiDirect Business Account? Complete the below short sign-up form below and we will send you a follow-up email with a link to fill out our customer sign-up form. Once this process is all finalized, we will confirm if your application was successful.
        </p>
    </div>
</div>
<form class="form create account form-create-account"
      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= $block->getBlockHtml('formkey') ?>

    <div class="b2bregbox">
        <h1>Welcome to <span class="title-text-orange">digi</span>Direct Business</h1>
        <fieldset class="fieldset create info  b2b-row">
            <legend class="legend"><span><?= $block->escapeHtml(__('Personal Information')) ?></span></legend><br>


            <?= $block->getLayout()->createBlock(Name::class)
                ->setFieldNameFormat('customer[%s]')
                ->setObject($block->getFormData())
                ->setNoWrap(true)
                ->setForceUseCustomerAttributes(true)
                ->toHtml()
            ?>

            <div class="field legal-name b2b-column p-r">
                <label class="label" for="job_title">
                    <span><?= $block->escapeHtml(__('Job Title')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="company[job_title]" id="job_title"
                        value="" placeholder="Job title*"
                        title="<?= $block->escapeHtmlAttr(__('Job Title')) ?>"
                        class="input-text">
                </div>
            </div>

            <!-- <//?= $block->getLayout()->createBlock(Gender::class)
                ->setFieldNameFormat('customer[%s]')
                ->setGender($block->getFormData()->getGender())
                ->toHtml()
            ?> -->

            <div class="field required b2b-column">
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email" name="customer[email]"
                        placeholder="Email Address*"
                        autocomplete="email"
                        id="email_address"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                        class="input-text"
                        data-async-is-valid="true"
                        data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                                "name": "customer_email",
                                "validateUrl": "<?= $block->escapeUrl($block->getUrl('company/account/validate')) ?>"
                        }}'
                        data-validate="{required:true, 'validate-email':true, 'validate-async-customer-email': true}">
                </div>
            </div>

            <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_user_attributes'); ?>
            <?php if ($userDefinedAttributes): ?>
                <?php $userDefinedAttributes->setFieldNameFormat('customer[%1$s]'); ?>
                <?= $userDefinedAttributes->toHtml() ?>
            <?php endif; ?>

            <?= $block->getChildHtml('form.additional.info') ?>
        </fieldset>

        <fieldset class="fieldset info b2b-row">
            <legend class="legend"><span><?= $block->escapeHtml(__('Company Information')) ?></span></legend><br>
            <div class="field company-name _required">
                <label class="label" for="company_name">
                    <span><?= $block->escapeHtml(__('Company Name')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="company[company_name]" id="company_name"
                        placeholder="Company Name*"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('Company Name')) ?>"
                        class="input-text" data-validate="{required:true}">
                </div>
            </div>
            <div class="field legal-name">
                <label class="label" for="legal_name">
                    <span><?= $block->escapeHtml(__('Company Legal Name')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="company[legal_name]" id="legal_name"
                        placeholder="Company Legal Name*"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('Company Legal Name')) ?>"
                        class="input-text">
                </div>
            </div>
            <div class="field company-email _required b2b-column p-r">
                <label class="label" for="company_email">
                    <span><?= $block->escapeHtml(__('Company Email')) ?></span>
                </label>
                <div class="control">
                    <input type="email" name="company[company_email]" id="company_email"
                        placeholder="Company Email*"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('Company Email')) ?>"
                        class="input-text"
                        data-role="email"
                        data-async-is-valid="true"
                        data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                                "name": "company_email",
                                "validateUrl": "<?= $block->escapeUrl($block->getUrl('company/account/validate')) ?>"
                        }}'
                        data-validate="{required:true, 'validate-email': true, 'validate-async-company-email': true}">
                </div>
            </div>
            <div class="field vat-tax-id b2b-column" style="display: none !important;">
                <label class="label" for="vat_tax_id">
                    <span><?= $block->escapeHtml(__('VAT/TAX ID')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="company[vat_tax_id]" id="vat_tax_id"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('VAT/TAX ID')) ?>"
                        class="input-text">
                </div>
            </div>

            <div class="field abn _required b2b-column">
                <label class="label" for="abn">
                    <span><?= $block->escapeHtml(__('ABN')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="company[abn]" id="abn"
                        placeholder="ABN*"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('ABN')) ?>"
                        class="input-text" data-validate="{required:true}">
                </div>
            </div>

            <div class="field acn _required b2b-column" style="display: none !important;">
                <label class="label" for="acn">
                    <span><?= $block->escapeHtml(__('ACN')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="company[acn]" id="acn"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('ACN')) ?>"
                        class="input-text" data-validate="{required:true}">
                </div>
            </div>

            <div class="field reseller-id" style="display: none !important;">
                <label class="label" for="reseller_id">
                    <span><//?= $block->escapeHtml(__('Re-seller ID')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="company[reseller_id]" id="reseller_id"
                        value=""
                        title="<//?= $block->escapeHtmlAttr(__('Re-seller ID')) ?>"
                        class="input-text">
                </div>
            </div>
        </fieldset>

        <fieldset class="fieldset info b2b-row">
            <legend class="legend"><span><?= $block->escapeHtml(__('Legal Address')) ?></span></legend><br>
            <div class="field street _required">
                <label class="label" for="street0">
                    <span><?= $block->escapeHtml(__('Street Address')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="company[street][0]" id="street0"
                        placeholder="Street Address*"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                        class="input-text" data-validate="{required:true}">
                </div>
            </div>
            <div class="field street" style="display: none !important;">
                <div class="control">
                    <input type="text" name="company[street][1]" id="street1"
                        value=""
                        title="<//?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                        class="input-text">
                </div>
            </div>
            <div class="field city _required">
                <label class="label" for="city">
                    <span><?= $block->escapeHtml(__('City')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="company[city]" id="city"
                        placeholder="City*"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                        class="input-text" data-validate="{required:true}">
                </div>
            </div>
            <div class="field country_id _required b2b-column p-r">
                <label class="label" for="country_id">
                    <span><?= $block->escapeHtml(__('Country')) ?></span>
                </label>
                <div class="control _required">
                    <?php $countryValue = $block->getDefaultCountryId(); ?>
                    <select name="company[country_id]" id="country_id"
                            class="select"
                            title="<?= $block->escapeHtmlAttr(__('Country')) ?>"
                            data-validate="{required:true}">
                        <option value=""><?= $block->escapeHtml(__('Please select an option.')) ?></option>
                        <?php $countries = $block->getCountriesList(); ?>
                        <?php foreach ($countries as $countryCode => $country): ?>
                            <option value="<?= $block->escapeHtmlAttr($countryCode) ?>"
                                <?= ($countryCode == $countryValue) ? ' selected' : '' ;?>>
                                <?= $block->escapeHtml($country) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="field region-id required b2b-column">
                <label class="label" for="region_id">
                    <span><?= $block->escapeHtml(__('State/Province')) ?></span>
                </label>
                <div class="control _required">
                    <?php $message = $block->escapeHtml(__('State')) ?>
                    <select name="company[region_id]" id="region_id" data-validate="{required:true}" class="select">
                        <option value=""><?= /* @noEscape */ $message ?></option>
                    </select>
                    <input type="text" id="region" name="company[region]"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                        class="input-text no-display">
                </div>
            </div>
            <div class="field postcode required b2b-column p-r">
                <label class="label" for="postcode">
                    <span><?= $block->escapeHtml(__('ZIP/Postal Code')) ?></span>
                </label>
                <div class="control">
                    <?php $postcodeClass = $block->escapeHtmlAttr($block->getAttributeValidationClass('postcode')) ?>
                    <input type="text" name="company[postcode]" id="postcode"
                        placeholder="Zip/Postal Code*"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('ZIP/Postal Code')) ?>"
                        class="input-text validate-zip-international <?= /* @noEscape */ $postcodeClass ?>"
                        data-validate="{'required':true, 'validate-zip-international':true}" />
                </div>
            </div>

            <div class="field telephone _required b2b-column">
                <label class="label" for="telephone">
                    <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="company[telephone]" id="telephone"
                        placeholder="Phone Number*"
                        value=""
                        title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                        class="input-text" data-validate="{required:true}">
                </div>
            </div>
        </fieldset>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>

            </div>
        </div>

        <div class="bottom-text">
            <span class="time-approve-text">Please note applications take 1-2 weeks to approve.</span>
            <span class="redirection-login">Already have an account? <a href="/customer/account/login">Login</a></span>
        </div>
    </div>

</form>

<?php $scriptString = <<<script

    require([
        'jquery',
        'mage/mage'
    ], function($) {

        var dataForm = $('#form-validate');
        var ignore = null;

        dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<?php
/** @var DirectoryHelper $directoryDataHelper */
$directoryDataHelper = $block->getData('directoryDataHelper');
$countries = $directoryDataHelper->getCountriesWithOptionalZip(true);
/** @var \Magento\Company\ViewModel\Address\RegionProvider $regionProvider */
$regionProvider = $block->getRegionProvider(); ?>

<script type="text/x-magento-init">
    {
        "#country_id": {
            "directoryRegionUpdater": {
                "optionalRegionAllowed": <?= $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $regionProvider->getRegionJson(); ?>,
                "defaultRegion": "",
                "countriesWithOptionalZip": <?= /* @noEscape */ $countries ?>
            }
        },
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>

<script>
    // alert("Test Company Form");
    document.getElementById("firstname").setAttribute("placeholder", "First Name*");
    document.getElementById("lastname").setAttribute("placeholder", "Last Name*");
</script>
