<?php
/** @var $block \Ewave\StoreLocator\Block\ListStore\DetailPage */
?>
<div class="grid-row store-view">
    <div class="medium-4 column -left">
        <?php echo $block->getChildHtml('abstractentity_additional_info'); ?>
        <?php echo $block->getChildHtml('storelocator.details'); ?>
    </div>
    <div class="medium-8 column -main">
        <?php echo $block->getChildHtml('storelocator.map'); ?>
    </div>
</div>

<div class="grid-bottom">
    <?php echo $block->getChildHtml('storelocator.directions'); ?>
</div>

<?php echo $block->getChildHtml('storelocator.view.after'); ?>