<?php
    use Magento\Framework\App\Action\Action;
?>
<script>
    
require(['jquery'], function ($) {
    
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }
    
    var customerId = getCookie('PAC');
    var sessionId = getCookie('pa_session_id');
    
    console.log("customerId", customerId);
    console.log("sessionId", sessionId);
    
    if (!sessionId) {
        $.ajax({
            async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/index/getconfig",
            type: "POST",
            data: {
                customerId: customerId
            },
            success: function(data){
                console.log(data);
            },
            error: function(){
                console.log('AJAX Get Config Fail!');
            }
        });
    }
    
});

</script>

