<div class="pdp-row" style="margin-bottom: 40px;">
    <div class="pa-digidirect-product-widget people-who-viewed-this-item-also-viewed">
        <div class="product-widget-header">
            <div style="color: #242426; font-size: 32px; font-family: Inter; font-weight: 500; line-height: 33px; word-wrap: break-word">People who viewed this item also viewed</div>
        </div>
        <div id="people-who-viewed-this-item-also-viewed-desktop" class="pa-digidirect-product-widget-container desktop-widget real-container owl-carousel custom"></div>
        <div class="pa-digidirect-product-widget-container widget-placeholder">
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
        </div>
        <div id="people-who-viewed-this-item-also-viewed-mobile" class="pa-digidirect-product-widget-container mobile-widget"></div>
        <div class="pa-digidirect-product-widget-container widget-placeholder mobile-widget">
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
        </div>
        <div class="load-more mgz-element mgz-child mgz-element-text product-tab-mobile-widget-load-more grid-toggle-more" onclick="loadMoreProducts('people-who-viewed-this-item-also-viewed');"><div class="mgz-element-inner"><p>Load More</p></div></div>
        <div class="view-less mgz-element mgz-child mgz-element-text product-tab-mobile-widget-view-less grid-toggle-more" onclick="viewLessProducts('people-who-viewed-this-item-also-viewed');" style="display: none;"><div class="mgz-element-inner"><p>View Less</p></div></div>
    </div>
</div>
