
<div class="pa-digidirect-product-widget pdp-bundle-overlay">
    <i id="bundle-overlay-exit" class="fas fa-times bundle-overlay-exit"></i>
    <div class="product-widget-header">
        <h3 class="title" style="font-size: 17px;font-weight: 500;margin-top: 0;margin-bottom: 20px;">How About Adding These?</h3>
        <div class="pa-checkbox-container pa-select-all-checkbox-container" style="display: none;">
            <span class="pa-select-all-label-text">Select All</span>
            <label class="pa-checkbox-label pa-select-all-pa-checkbox-label">
                <input type="checkbox" class="select-all-products-on-bundle-overlay pa-checkbox-input pa-select-all-pa-checkbox-input"><span><i class="fas fa-clipboard fa-2x"></i></span>
            </label>
        </div>
    </div>
    <div id="pdp-bundle-overlay-desktop" class="pa-digidirect-product-widget-container">
        <div class="product-item-info product-item pa-bundle-container">
            <div class="pa-checkbox-container pa-select-all-checkbox-container">
                <span class="pa-select-all-label-text">Select All</span>
                <label class="pa-checkbox-label pa-select-all-pa-checkbox-label">
                    <input type="checkbox" class="select-all-products-on-bundle-overlay pa-checkbox-input pa-select-all-pa-checkbox-input"><span><i class="fas fa-clipboard fa-2x"></i></span>
                </label>
            </div>
            <a class="product photo product-item-photo" tabindex="-1">
            </a> 
            <div class="product details product-item-details">
                <span name="label">Total Price:</span>
                <span id="pa-bundle-overlay-total" name="value">$0.00</span>
            </div>
            <div class="product actions product-item-actions">
                <div class="actions-primary">
                    <button id="add-bundle-overlay-tocart" type="submit"
                            title="Add Bundle To Cart"
                            class="action tocart primary">
                        <span>Add Bundle To Cart</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>