<?php
    $recommendedProducts = $block->getRecommendedProducts();
?>

<div id="pa-digimarket-side-panel" style="display: none;">
    <?php foreach ($recommendedProducts as $_product): ?>
        <div class="product-item-info">
            <a href="<?= $_product->getProductUrl(); ?>" class="product photo product-item-photo" tabindex="-1">
                <span class="product-image-container" style="width: 240px;">
                    <span class="product-image-wrapper" style="padding-bottom: 125%;">
                        <img class="product-image-photo" src="<?= $_product->getData('thumbnail'); ?>" loading="lazy" width="240" height="300" alt="Product Image">
                    </span>
                </span> 
            </a> 
            <div class="product details product-item-details">
                <strong class="product-item-name">
                    <a title="<?= $_product->getName(); ?>" href="<?= $_product->getProductUrl(); ?>" class="product-item-link">
                        <?= $_product->getName(); ?>
                    </a>
                </strong> 
                <div class="price-box price-final_price">
                    <div class="final-price"><?= $_product->getFinalPrice(); ?></div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

