
<div id="pa-digimarket-side-panel-wrapper">
    <div id="pa-digimarket-side-panel" style="display: none;">
        <h3 class="title">Looking for more? Explore digiMarket</h3>
        <div id="explore-digimarket-side-panel" class="product-item-container"></div>
        <div class="product-item-container widget-placeholder">
            <div class="product-item-info product-item " style="height: 187px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 187px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 187px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 187px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 187px !important;"><div class="loader"></div></div>
        </div>
        <a href="https://www.digidirect.com.au/digimarket" class="digimarket-discover-more">DISCOVER MORE</a>
    </div>
</div>

