<?php
    $recommendedProducts = $block->getRecommendedProducts();
    $productCount = 0;
?>
<?php if ($recommendedProducts): ?>
    <div id="pa-digimarket-side-panel-wrapper">
        <div id="pa-digimarket-side-panel" style="display: none;">
            <h3 class="title">Looking for more? Explore digiMarket</h3>
            <div class="product-item-container"></div>
            <a href="https://www.digidirect.com.au/digimarket" class="digimarket-discover-more">DISCOVER MORE</a>
        </div>
    </div>
<?php endif; ?>

