
<div id="pa-digidirect-product-widget-wrapper" style="display: none;">
    <div id="pa-digidirect-product-widget" class="pdp-frquently-bought-with">
        <div class="product-widget-header">
            <h3 class="title" style="font-size: 18px;font-weight: 650;color: #ff3c00;">Frequently Bought With</h3>
        </div>
        <div id="pdp-frquently-bought-with" class="pa-digidirect-product-widget-container">
            <div class="product-item-info product-item pa-bundle-container">
                <div class="pa-checkbox-container pa-select-all-checkbox-container">
                    <span class="pa-select-all-label-text">Select All</span>
                    <label class="pa-checkbox-label pa-select-all-pa-checkbox-label">
                        <input id="select-all-products-on-bundle" type="checkbox" class="pa-checkbox-input pa-select-all-pa-checkbox-input"><span><i class="fas fa-clipboard fa-2x"></i></span>
                    </label>
                </div>
                <a class="product photo product-item-photo" tabindex="-1">
                </a> 
                <div class="product details product-item-details">
                    <span name="label">Total Price:</span>
                    <span id="pa-bundle-total" name="value">$0.00</span>
                </div>
                <div class="product actions product-item-actions">
                    <div class="actions-primary">
                        <button id="add-bundle-tocart" type="submit"
                                title="Add Bundle To Cart"
                                class="action tocart primary">
                            <span>Add Bundle To Cart</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="pa-digidirect-product-widget-container widget-placeholder">
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item pa-bundle-container" style="height: 381px !important;">
                <div class="pa-checkbox-container pa-select-all-checkbox-container">
                    <span class="pa-select-all-label-text">Select All</span>
                    <label class="pa-checkbox-label pa-select-all-pa-checkbox-label">
                        <input id="select-all-products-on-bundle" type="checkbox" class="pa-checkbox-input pa-select-all-pa-checkbox-input"><span><i class="fas fa-clipboard fa-2x"></i></span>
                    </label>
                </div>
                <a class="product photo product-item-photo" tabindex="-1">
                </a> 
                <div class="product details product-item-details">
                    <span name="label">Total Price:</span>
                    <span id="pa-bundle-total" name="value">$0.00</span>
                </div>
                <div class="product actions product-item-actions">
                    <div class="actions-primary">
                        <button id="add-bundle-tocart" type="submit"
                                title="Add Bundle To Cart"
                                class="action tocart primary">
                            <span>Add Bundle To Cart</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
           "bindSubmit": true
        }
    }
}
</script>
<script>
    require(['jquery'], function ($) {

        $("#select-all-products-on-bundle").change(function() {
            if(this.checked) {
                $('.pa-bundle-product').each(function(){
                    if (!$(this).is(":checked")) {
                        $(this).trigger('click');
                    }
                });
            } else {
                $('.pa-bundle-product').each(function(){
                    if ($(this).is(":checked")) {
                        $(this).trigger('click');
                    }
                });
            }
        });
        
        $(".pa-bundle-product").change(function() {
            var bundleTotal = Number($("#pa-bundle-total").text().substring(1));
            var bundleProductPrice = Number($(this).attr("data-product-price"));
            if(this.checked) {
                var newBundleTotal = bundleTotal + bundleProductPrice;
            } else {
                var newBundleTotal = bundleTotal - bundleProductPrice;
            }
            $("#pa-bundle-total").text('$' + Number(newBundleTotal).toFixed(2));
        });
        
        $("#add-bundle-tocart").click(function(){
            
            var productIds = [];
            
            $('.pa-bundle-product').each(function(){
                if(this.checked) {
                    console.log("data-product-id: " + $(this).attr("data-product-id"));
                    productIds.push($(this).attr("data-product-id"));
                }
            });
            
            var url = "https://www.digidirect.com.au/particularaudienceapi/index/frequentlyboughtwith";

            $.ajax({
                url: url,
                type: "POST",
                data: {
                    productIds: productIds
                },
                success: function(data){
                    console.log("Success!");
                },
                error: function(){
                    console.log("Fail!");
                }
            });
        });
        
        $('[data-block="minicart"]').on('contentLoading', function () {
            $('[data-block="minicart"]').on('contentUpdated', function ()  {
                $('html, body').animate({ scrollTop: 0 }, 'slow');
                $('[data-block="minicart"]').find('[data-role="dropdownDialog"]').dropdownDialog("open");
            });
        });
    });
</script>