<div class="pa-digidirect-product-widget pdp-frquently-bought-with">
    <div class="product-widget-header">
        <h3 class="title" style="font-size: 18px;font-weight: 650;color: #ff3c00;">Frequently Bought With</h3>
        <div class="pa-checkbox-container pa-select-all-checkbox-container" style="display: none;">
            <span class="pa-select-all-label-text">Select All</span>
            <label class="pa-checkbox-label pa-select-all-pa-checkbox-label">
                <input type="checkbox" class="select-all-products-on-bundle pa-checkbox-input pa-select-all-pa-checkbox-input"><span><i class="fas fa-clipboard fa-2x"></i></span>
            </label>
        </div>
    </div>
    <div id="pdp-frquently-bought-with-desktop" class="pa-digidirect-product-widget-container" style="display: none;">
        <div class="product-item-info product-item pa-bundle-container">
            <div class="pa-checkbox-container pa-select-all-checkbox-container">
                <span class="pa-select-all-label-text">Select All</span>
                <label class="pa-checkbox-label pa-select-all-pa-checkbox-label">
                    <input type="checkbox" class="select-all-products-on-bundle pa-checkbox-input pa-select-all-pa-checkbox-input"><span><i class="fas fa-clipboard fa-2x"></i></span>
                </label>
            </div>
            <a class="product photo product-item-photo" tabindex="-1">
            </a> 
            <div class="product details product-item-details">
                <span name="label">Total Price:</span>
                <span id="pa-bundle-total" name="value">$0.00</span>
            </div>
            <div class="product actions product-item-actions">
                <div class="actions-primary">
                    <button id="add-bundle-tocart" type="submit"
                            title="Add Bundle To Cart"
                            class="action tocart primary">
                        <span>Add Bundle To Cart</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="pa-digidirect-product-widget-container widget-placeholder">
        <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
        <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
        <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
        <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
        <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
        <div class="product-item-info product-item pa-bundle-container" style="height: 381px !important;">
            <div class="pa-checkbox-container pa-select-all-checkbox-container">
                <span class="pa-select-all-label-text">Select All</span>
                <label class="pa-checkbox-label pa-select-all-pa-checkbox-label">
                    <input type="checkbox" class="select-all-products-on-bundle pa-checkbox-input pa-select-all-pa-checkbox-input"><span><i class="fas fa-clipboard fa-2x"></i></span>
                </label>
            </div>
            <a class="product photo product-item-photo" tabindex="-1">
            </a> 
            <div class="product details product-item-details">
                <span name="label">Total Price:</span>
                <span id="pa-bundle-total" name="value">$0.00</span>
            </div>
            <div class="product actions product-item-actions">
                <div class="actions-primary">
                    <button id="add-bundle-tocart" type="submit"
                            title="Add Bundle To Cart"
                            class="action tocart primary">
                        <span>Add Bundle To Cart</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>