<div class="pdp-row" style="margin-bottom: 40px;">
    <div class="pa-digidirect-product-widget you-may-also-like">
        <div class="product-widget-header">
            <h3 class="title" style="font-size: 18px;font-weight: 650;color: #ff3c00;">You May Also Like</h3>
        </div>
        <div id="you-may-also-like-desktop" class="pa-digidirect-product-widget-container desktop-widget real-container owl-carousel custom"></div>
        <div class="pa-digidirect-product-widget-container widget-placeholder">
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
        </div>
        <div id="you-may-also-like-mobile" class="pa-digidirect-product-widget-container mobile-widget"></div>
        <div class="pa-digidirect-product-widget-container widget-placeholder mobile-widget">
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
            <div class="product-item-info product-item " style="height: 381px !important;"><div class="loader"></div></div>
        </div>
        <div class="load-more mgz-element mgz-child mgz-element-text product-tab-mobile-widget-load-more grid-toggle-more" onclick="loadMoreProducts('you-may-also-like');"><div class="mgz-element-inner"><p>Load More</p></div></div>
        <div class="view-less mgz-element mgz-child mgz-element-text product-tab-mobile-widget-view-less grid-toggle-more" onclick="viewLessProducts('you-may-also-like');" style="display: none;"><div class="mgz-element-inner"><p>View Less</p></div></div>
    </div>
</div>