<?php
    use Magento\Framework\App\Action\Action;
?>
<script>
    
require(['jquery'], function ($) {
    
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }
    
    var customerId = getCookie('PAC');
    
    console.log('customerId', customerId);
    
    var result;

    $.ajax({
        async: false,
        url: "https://www.digidirect.com.au/particularaudienceapi/index/productpage", //getRecommendationsUrl,
        type: "POST",
        data: {
            customerId: customerId
        },
        success: function(data){
            result = data;
        },
        error: function(){
            console.log('AJAX Fail!');
        }
    });
    console.log('result', result);
    var recommendationsResult = result;
    var widgets  = recommendationsResult.recommendations.route.widgets;

    function digiMarketSidePanel(widgetId, appendTo) {
        let productItem = "";
        let priceBlock = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        Object.keys(widgetSlots).forEach(key => {
            let product = widgetSlots[key].products[0];
            //widgetSlots[key].products[0].refId;
            
            if (product.prices[0].discountPrice) {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                let discountPriceToDisplay = "$" + Number(product.prices[0].discountPrice).toFixed(2);
                priceBlock = '<div class="price-box price-final_price">' +
                                '<div class="final-price">'+ discountPriceToDisplay +'</div>' +
                            '</div>';
            } else {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                priceBlock = '<div class="price-box price-final_price">' +
                                '<div class="final-price">'+ priceToDisplay +'</div>' +
                            '</div>';
            }
            
            productItem = '<div class="product-item-info product-item">' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                        '</div>'
            $(appendTo).append(productItem);
        });
        $('.product-item-container.widget-placeholder').remove();
    }
    
    function productTile(widgetId, appendTo, isMobile) {
        let productItem = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        var productCtr = 0;
        Object.keys(widgetSlots).forEach(key => {
            productCtr++;
            let product = widgetSlots[key].products[0];
            let digiDealsLogo = "";
            let priceBlock = "";
            let addToCart = "";
            
            let digiSeconds = "";
            let digiSecondsOverlay = "";
            let digiSecondsRating = "";
            let sellerName = "";
            
            let categories = product.attributes.find(obj => {
                return obj.name === 'Categories';
            })
            
            let seller = product.attributes.find(obj => {
                return obj.name === 'DDR_Seller_Id';
            })
            
            sellerName = seller.stringValue;
            
            let digiSecondsCategories = ["PRELOVED","OPENBOX","REFURB"];
            let isDigiSeconds = digiSecondsCategories.includes(categories.options[0].value);
            
            if (categories.options[0].value == "PRELOVED") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-pre-loved.png"/>';
            } else if (categories.options[0].value == "OPENBOX") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-demo.png"/>';
            } else if (categories.options[0].value == "REFURB") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-refurbished.png"/>';
            }
            
            digiSeconds = '<div class="digiseconds-overlay">' + digiSecondsOverlay + '<div class="digiseconds-rating">' + digiSecondsRating + '</div></div>';
            //console.log(attribute);

            if (product.is_digiprint) {
                addToCart = '<a class="ordernow-link" href="' + product.digiprint_customlink + '" target="_blank">' +
                                '<button type="button" title="Order Now" class="action btn-ordernow primary">' +
                                    'Order Now <i class="fas fa-cart-plus" style="float: right;"></i>' +
                                '</button>' +
                            '</a>'
            } else {
                addToCart = '<form data-role="tocart-form"' +
                                    'data-product-sku="' + product.sku + '"' +
                                    'action="https://www.digidirect.com.au/checkout/cart/add/uenc/%25uenc%25/product/'+ product.refId +'" method="post"><?php echo $block->getBlockHtml("formkey"); ?>' +
                                '<button type="submit" title="Add to Cart" class="action tocart primary">' +
                                    '<span>Add to Cart</span><i class="fas fa-cart-plus" style="float: right;color: #fff;"></i>' +
                                '</button>' +
                            '</form>'
            }
            //console.log(product.name, sellerName);
            if (!isDigiSeconds) {
                if (sellerName != "20329" && sellerName !== undefined) {
                    digiDealsLogo = '<div class="online-only"><span style="color: #F15923; margin-right: 3px;">Online</span>Only</div>';
                } else {
                    digiDealsLogo = '';
                }
            }
            
            if (product.prices[0].discountPrice) {
                if (!isDigiSeconds) {
                    digiDealsLogo = '<div class="digideals-overlay"><img src="https://www.digidirect.com.au/media/wysiwyg/digidirect/digiDeals-Logo.png"/></div>';
                }
                
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                let discountPriceToDisplay = "$" + Number(product.prices[0].discountPrice).toFixed(2);
                let discount = "$" + Number(product.prices[0].price - product.prices[0].discountPrice).toFixed(2);
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label">Price Slashed </span>' + 
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="discount-price-wrapper"><span class="discount-price">'+ discount +'</span> Off</div>' +
                            '</div>';
            } else {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }
            
            let hideProductItem = "";
            if (isMobile && productCtr > 4) {
                hideProductItem = "hide-product-item";
            }
            productItem = '<div class="product-item-info product-item ' + hideProductItem + '">' +
                            '<div class="wish-list-wrapper" data-role="add-to-links">' +
                                '<a href="#"' +
                                'data-post=""' +
                                'class="action towishlist" data-action="add-to-wishlist"' +
                                'title="Add to Wish List">' +
                                '<i class="fas fa-heart" style="font-size: 25px; color: #e6e6e6;"></i>' +
                                '</a>' +
                            '</div>' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                digiDealsLogo + digiSeconds +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                            '<div class="product actions product-item-actions">' +
                                '<div class="actions-primary">' +
                                    addToCart +
                                '</div>' +
                            '</div>' +
                        '</div>'
            $(appendTo).append(productItem);
        });
        $('.pa-digidirect-product-widget-container.widget-placeholder').remove();
    }
    digiMarketSidePanel('011987ea-124e-ef11-abf3-02bf4bf6447c', '#explore-digimarket-side-panel');
    productTile('011987ea-124e-ef11-abf3-02bf4bf6447c', '#explore-digimarket-desktop', false);
    productTile('011987ea-124e-ef11-abf3-02bf4bf6447c', '#explore-digimarket-mobile', true);
    productTile('cecb45e7-043e-ec11-aae9-02dca44cceec', '#people-who-viewed-this-item-also-viewed-desktop', false);
    productTile('cecb45e7-043e-ec11-aae9-02dca44cceec', '#people-who-viewed-this-item-also-viewed-mobile', true);
    productTile('252b5970-293e-ec11-aae9-02dca44cceec', '#you-may-also-like-desktop', false);
    productTile('252b5970-293e-ec11-aae9-02dca44cceec', '#you-may-also-like-mobile', true);
});
</script>

<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
           "bindSubmit": true
        }
    }
}
</script>

<script>
    
    function loadMoreProducts(widgetClass) {
        var hiddenTiles = document.querySelectorAll('.'+ widgetClass + ' ' + ' .hide-product-item'); 
        var ctr = 0;
        for (let x = 0; x < hiddenTiles.length; x++) {
          ctr++;
          hiddenTiles[x].classList.remove('hide-product-item');
          if (ctr == 4) break;
        }
        var hiddenTilesCount = document.querySelectorAll('.'+ widgetClass + ' ' + ' .hide-product-item'); 
        if (hiddenTilesCount.length == 0) {
            document.querySelectorAll('.'+ widgetClass + ' ' + '.load-more')[0].style.display = "none";    
            document.querySelectorAll('.'+ widgetClass + ' ' + '.view-less')[0].style.display = "block";    
             
            try {
                document.querySelectorAll('.'+ widgetClass + ' ' + '.view-all')[0].style.display = "block"; 
            }
            catch(err) {
            }
        }
    }

    function viewLessProducts(widgetClass) {
        var productTiles = document.querySelectorAll('.'+ widgetClass + ' ' + '.mobile-widget .product-item'); 

        var ctr = 0;
        for (let x = 0; x < productTiles.length; x++) {
          ctr++;
          if (ctr > 4) {
             productTiles[x].classList.add('hide-product-item');
          }
        }
        
        document.querySelectorAll('.'+ widgetClass + ' ' + '.load-more')[0].style.display = "block";    
        document.querySelectorAll('.'+ widgetClass + ' ' + '.view-less')[0].style.display = "none";    
        try {
            document.querySelectorAll('.'+ widgetClass + ' ' + '.view-all')[0].style.display = "none"; 
        }
        catch(err) {
        }
        document.getElementById(widgetClass).scrollIntoView();

    }
    
</script>

<script type="text/x-magento-init">
{
    "[data-block='minicart']" : {
       "Digidirect_ParticularAudienceAPI/js/view/minicartopen" : {}
    }
}
</script>