<?php
    use Magento\Framework\App\Action\Action;
    $productId = $block->getCurrentProduct()->getId();
?>
<script>
    
require(['jquery'], function ($) {
    
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }
    
    var customerId = getCookie('PAC');
    var sessionId = getCookie('pa_session_id');
    
    if (!sessionId || sessionId === undefined) {
        $.ajax({
            async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/index/getconfig",
            type: "POST",
            data: {
                customerId: customerId
            },
            success: function(data){
                console.log(data);
                customerId = data.payload.customerId;
                sessionId = data.payload.session.id
            },
            error: function(){
                console.log('AJAX Get Config Fail!');
            }
        });
    }
    
    var result;

    $.ajax({
        async: false,
        url: "https://www.digidirect.com.au/particularaudienceapi/index/productpage", //getRecommendationsUrl,
        type: "POST",
        data: {
            customerId: customerId,
            productId: <?= $productId; ?>
        },
        success: function(data){
            result = data;
        },
        error: function(){
            console.log('AJAX Fail!');
        }
    });
    
    console.log('result', result);
    var recommendationsResult = result;
    var widgets  = recommendationsResult.recommendations.route.widgets;
    
    var routeId  = recommendationsResult.recommendations.route.id;
    var currentUrl = window.location.href;
    
    var configCustomerId;
    var configSessionId;
    
    var configCustomerId;
    var configSessionId;
    
    configCustomerId = customerId;
    configSessionId = sessionId;
    
    function viewProduct(productId) {
        
        var date = new Date();

        const viewProductData = {
            customerId: configCustomerId,
            sessionId: configSessionId,
            events: [
                {
                    currentUrl: currentUrl,
                    eventTime: date.toISOString(),
                    refId: productId
                }
            ]
        };

        //console.log("viewProductData", JSON.stringify(viewProductData));

        $.ajax({
            async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/events/viewproduct",
            type: "POST",
            data: {
                eventData: viewProductData
            },
            success: function(data){
                console.log(data);
            },
            error: function(){
                console.log('AJAX Fail!');
            }
        });
    }
    
    viewProduct(<?= $productId; ?>);
    
    function digiMarketSidePanel(widgetId, appendTo) {
        let productItem = "";
        let priceBlock = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        Object.keys(widgetSlots).forEach(key => {
            let product = widgetSlots[key].products[0];
            let campaignId = widgetSlots[key].campaignId;
            let recommenderId = widgetSlots[key].recommenderId;
            let tacticId = widgetSlots[key].tacticId;
            //widgetSlots[key].products[0].refId;
            
            if (product.prices[0].discountPrice) {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                let discountPriceToDisplay = "$" + Number(product.prices[0].discountPrice).toFixed(2);
                priceBlock = '<div class="price-box price-final_price">' +
                                '<div class="final-price">'+ discountPriceToDisplay +'</div>' +
                            '</div>';
            } else {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                priceBlock = '<div class="price-box price-final_price">' +
                                '<div class="final-price">'+ priceToDisplay +'</div>' +
                            '</div>';
            }
            
            var view = "-digimarket";
            var tileId = 'product-' + product.refId + view;
            productItem = '<div id="'+ tileId +'" class="product-item-info product-item" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '">' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                        '</div>'
            $(appendTo).append(productItem);
            //slots(product.refId, recommenderId, campaignId, tacticId);
        });
        $('.product-item-container.widget-placeholder').remove();
    }
    
    function frequentlyBoughtWith(widgetId, prependTo) {
        let productItem = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        var productCtr = 0;
        if (!widgetSlots.length) {
            $(".pa-digidirect-product-widget.pdp-frquently-bought-with").remove();
            return
        }
        Object.keys(widgetSlots).forEach(key => {
            productCtr++;
            let product = widgetSlots[key].products[0];
            let campaignId = widgetSlots[key].campaignId;
            let recommenderId = widgetSlots[key].recommenderId;
            let tacticId = widgetSlots[key].tacticId;
            let digiDealsLogo = "";
            let priceBlock = "";
            let addToCart = "";
            
            let digiSeconds = "";
            let digiSecondsOverlay = "";
            let digiSecondsRating = "";
            let sellerName = "";
            
            let finalPrice = "";
            
            let categories = product.attributes.find(obj => {
                return obj.name === 'Categories';
            })
            
            let seller = product.attributes.find(obj => {
                return obj.name === 'DDR_Seller_Id';
            })
            
            let digiPrint = product.attributes.find(obj => {
                return obj.name === 'is_digiprint';
            })
            
            let digiPrintLink = product.attributes.find(obj => {
                return obj.name === 'digiprint_customlink';
            })
            
            sellerName = seller.stringValue;
            
            let digiSecondsCategories = ["PRELOVED","OPENBOX","REFURB"];
            let isDigiSeconds = digiSecondsCategories.includes(categories.options[0].value);
            
            if (categories.options[0].value == "PRELOVED") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-pre-loved.png"/>';
            } else if (categories.options[0].value == "OPENBOX") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-demo.png"/>';
            } else if (categories.options[0].value == "REFURB") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-refurbished.png"/>';
            }
            
            digiSeconds = '<div class="digiseconds-overlay">' + digiSecondsOverlay + '<div class="digiseconds-rating">' + digiSecondsRating + '</div></div>';
            //console.log(attribute);

            let digiPrintValue = digiPrint.stringValue;
            let digiPrintLinkValue = digiPrintLink.stringValue;
            
            if (digiPrintValue == 1) {
                addToCart = '<a class="ordernow-link" href="' + digiPrintLinkValue + '" target="_blank">' +
                                '<button type="button" title="Order Now" class="action tocart primary">' +
                                    'Order Now <i class="fas fa-cart-plus" style="float: right;"></i>' +
                                '</button>' +
                            '</a>'
            } else {
                addToCart = '<form data-role="tocart-form"' +
                                    'data-product-sku="' + product.sku + '"' +
                                    'action="https://www.digidirect.com.au/checkout/cart/add/uenc/%25uenc%25/product/'+ product.refId +'" method="post"><?php echo $block->getBlockHtml("formkey"); ?>' +
                                    '<input type="text" name="ref_id" value="'+ product.refId +'" hidden/>' +
                                    '<input type="text" name="qty" value="1" hidden/>' +
                                    '<input type="text" name="widget_id" value="631dfdd4-dc01-ef11-abf3-02bf4bf6447c" hidden/>' +
                                    '<input type="text" name="route_id" value="'+ routeId +'" hidden/>' +
                                    '<button type="submit" title="Add to Cart" class="action tocart primary" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '">' +
                                    '<span>Add to Cart</span><i class="fas fa-cart-plus" style="float: right;color: #fff;"></i>' +
                                '</button>' +
                            '</form>'
            }
            //console.log(product.name, sellerName);
            if (!isDigiSeconds) {
                if (sellerName != "20329" && sellerName !== undefined) {
                    digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                } else {
                    digiDealsLogo = '';
                }
            }
            
            if (product.prices[0].discountPrice) {
                if (!isDigiSeconds) {
                    digiDealsLogo = '<div class="digideals-overlay"><img src="https://www.digidirect.com.au/media/wysiwyg/digidirect/digiDeals-Logo.png"/></div>';
                }
                
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                let discountPriceToDisplay = "$" + Number(product.prices[0].discountPrice).toFixed(2);
                let discount = "$" + Number(product.prices[0].price - product.prices[0].discountPrice).toFixed(2);
                
                finalPrice = Number(product.prices[0].discountPrice).toFixed(2);
                
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label">Price Slashed </span>' + 
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="discount-price-wrapper"><span class="discount-price">'+ discount +'</span> Off</div>' +
                            '</div>';
            } else {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                
                finalPrice = Number(product.prices[0].price).toFixed(2);
                
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }
            
            var view = "-fbw";
            var tileId = 'product-' + product.refId + view;
            productItem = '<div id="'+ tileId +'" class="product-item-info product-item" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '">' +
                            '<div class="pa-checkbox-container">' +
                                '<label class="pa-checkbox-label">' +
                                    '<input type="checkbox" data-product-id="'+ product.refId +'" data-product-price="'+ finalPrice +'" class="pa-checkbox-input pa-bundle-product"><span><i class="fas fa-clipboard fa-2x"></i></span>' +
                                '</label>' +
                            '</div>' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                digiDealsLogo + digiSeconds +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                            '<div class="product actions product-item-actions">' +
                                '<div class="actions-primary">' +
                                    addToCart +
                                '</div>' +
                            '</div>' +
                        '</div>'
            $(prependTo).prepend(productItem);
            //slots(product.refId, recommenderId, campaignId, tacticId);
        });
        $('.pa-digidirect-product-widget-container.widget-placeholder').remove();
        $('#pdp-frquently-bought-with-desktop').show();
    }
    
    function productTile(widgetId, appendTo, isMobile) {
        let productItem = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        var productCtr = 0;
        Object.keys(widgetSlots).forEach(key => {
            productCtr++;
            let product = widgetSlots[key].products[0];
            let campaignId = widgetSlots[key].campaignId;
            let recommenderId = widgetSlots[key].recommenderId;
            let tacticId = widgetSlots[key].tacticId;
            let digiDealsLogo = "";
            let priceBlock = "";
            let addToCart = "";
            
            let digiSeconds = "";
            let digiSecondsOverlay = "";
            let sellerName = "";
            
            let categories = product.attributes.find(obj => {
                return obj.name === 'Categories';
            })
            
            let seller = product.attributes.find(obj => {
                return obj.name === 'DDR_Seller_Id';
            })
            
            let digiPrint = product.attributes.find(obj => {
                return obj.name === 'is_digiprint';
            })
            
            let digiPrintLink = product.attributes.find(obj => {
                return obj.name === 'digiprint_customlink';
            })
            
            let digiSecondsRatingValue = product.attributes.find(obj => {
                return obj.name === 'item_rating';
            })
            
            let digiSecondsRating = "";            
            
            if (digiSecondsRatingValue.stringValue == "5") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "4") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "3") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "2") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "1") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            }
            
            sellerName = seller.stringValue;
            
            let digiSecondsCategories = ["PRELOVED","OPENBOX","REFURB"];
            let isDigiSeconds = digiSecondsCategories.includes(categories.options[0].value);
            
            if (categories.options[0].value == "PRELOVED") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-pre-loved.png"/>';
            } else if (categories.options[0].value == "OPENBOX") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-demo.png"/>';
            } else if (categories.options[0].value == "REFURB") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-refurbished.png"/>';
}
            
            digiSeconds = '<div class="digiseconds-overlay">' + digiSecondsOverlay + '<div class="digiseconds-rating">' + digiSecondsRating + '</div></div>';
            //console.log(attribute);

            let digiPrintValue = digiPrint.stringValue;
            let digiPrintLinkValue = digiPrintLink.stringValue;

            if (digiPrintValue == 1) {
                addToCart = '<a class="ordernow-link" href="' + digiPrintLinkValue + '" target="_blank">' +
                                '<button type="button" title="Order Now" class="action tocart primary">' +
                                    'Order Now <i class="fas fa-cart-plus" style="float: right;"></i>' +
                                '</button>' +
                            '</a>'
            } else {
                addToCart = '<form data-role="tocart-form"' +
                                    'data-product-sku="' + product.sku + '"' +
                                    'action="https://www.digidirect.com.au/checkout/cart/add/uenc/%25uenc%25/product/'+ product.refId +'" method="post"><?php echo $block->getBlockHtml("formkey"); ?>' +
                                    '<input type="text" name="ref_id" value="'+ product.refId +'" hidden/>' +
                                    '<input type="text" name="qty" value="1" hidden/>' +
                                    '<input type="text" name="widget_id" value="631dfdd4-dc01-ef11-abf3-02bf4bf6447c" hidden/>' +
                                    '<input type="text" name="route_id" value="'+ routeId +'" hidden/>' +
                                    '<button type="submit" title="Add to Cart" class="action tocart primary" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '">' +
                                    '<span>Add to Cart</span><i class="fas fa-cart-plus" style="float: right;color: #fff;"></i>' +
                                '</button>' +
                            '</form>'
            }
            //console.log(product.name, sellerName);
            if (!isDigiSeconds) {
                if (sellerName != "20329" && sellerName !== undefined) {
                    digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                } else {
                    digiDealsLogo = '';
                }
            }
            
            if (product.prices[0].discountPrice) {
                if (!isDigiSeconds) {
                    digiDealsLogo = '<div class="digideals-overlay"><img src="https://www.digidirect.com.au/media/wysiwyg/digidirect/digiDeals-Logo.png"/></div>';
                    if (sellerName != "20329" && sellerName !== undefined) {
                        digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                    }
                }
                
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                let discountPriceToDisplay = "$" + Number(product.prices[0].discountPrice).toFixed(2);
                let discount = "$" + Number(product.prices[0].price - product.prices[0].discountPrice).toFixed(2);
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label">Price Slashed </span>' + 
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="discount-price-wrapper"><span class="discount-price">'+ discount +'</span> Off</div>' +
                            '</div>';
            } else {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }
            
            let hideProductItem = "";
            if (isMobile && productCtr > 4) {
                hideProductItem = "hide-product-item";
            }
            var view = "";
            if (isMobile) {
                view = "-mobile";
            } else {
                view = "-desktop";
            }
            var tileId = 'product-' + product.refId + view;
            productItem = '<div id="'+ tileId +'" class="product-item-info product-item '+ hideProductItem +'" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '">' +
                            '<div class="wish-list-wrapper" data-role="add-to-links">' +
                                '<a href="#"' +
                                'data-post=""' +
                                'class="action towishlist" data-action="add-to-wishlist"' +
                                'title="Add to Wish List">' +
                                '<i class="fas fa-heart" style="font-size: 25px; color: #e6e6e6;"></i>' +
                                '</a>' +
                            '</div>' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                digiDealsLogo + digiSeconds +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                            '<div class="product actions product-item-actions">' +
                                '<div class="actions-primary"><div class="s19-rental-price-target"><p style="font-size: 13px; font-weight: 500;">Buy now pay later</p><p style="font-size: 13px; font-weight: 500; text-transform: uppercase;">Options Available</p></div>' +
                                    addToCart +
                                '</div>' +
                            '</div>' +
                        '</div>'
            $(appendTo).append(productItem);
            //slots(product.refId, recommenderId, campaignId, tacticId);
        });
        $('.pa-digidirect-product-widget-container.widget-placeholder').remove();
    }
    
    function bundleOverlay(widgetId, prependTo) {
        let productItem = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        var productCtr = 0;
        if (!widgetSlots.length) {
            $("#bundle-overlay-container").remove();
            return
        }
        Object.keys(widgetSlots).forEach(key => {
            productCtr++;
            let product = widgetSlots[key].products[0];
            let campaignId = widgetSlots[key].campaignId;
            let recommenderId = widgetSlots[key].recommenderId;
            let tacticId = widgetSlots[key].tacticId;
            let digiDealsLogo = "";
            let priceBlock = "";
            let addToCart = "";
            
            let digiSeconds = "";
            let digiSecondsOverlay = "";
            let digiSecondsRating = "";
            let sellerName = "";
            
            let finalPrice = "";
            
            let categories = product.attributes.find(obj => {
                return obj.name === 'Categories';
            })
            
            let seller = product.attributes.find(obj => {
                return obj.name === 'DDR_Seller_Id';
            })
            
            let digiPrint = product.attributes.find(obj => {
                return obj.name === 'is_digiprint';
            })
            
            let digiPrintLink = product.attributes.find(obj => {
                return obj.name === 'digiprint_customlink';
            })
            
            sellerName = seller.stringValue;
            
            let digiSecondsCategories = ["PRELOVED","OPENBOX","REFURB"];
            let isDigiSeconds = digiSecondsCategories.includes(categories.options[0].value);
            
            if (categories.options[0].value == "PRELOVED") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-pre-loved.png"/>';
            } else if (categories.options[0].value == "OPENBOX") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-demo.png"/>';
            } else if (categories.options[0].value == "REFURB") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-refurbished.png"/>';
            }
            
            digiSeconds = '<div class="digiseconds-overlay">' + digiSecondsOverlay + '<div class="digiseconds-rating">' + digiSecondsRating + '</div></div>';
            //console.log(attribute);
            let digiPrintValue = digiPrint.stringValue;
            let digiPrintLinkValue = digiPrintLink.stringValue;
            
            if (digiPrintValue == 1) {
                addToCart = '<a class="ordernow-link" href="' + digiPrintLinkValue + '" target="_blank">' +
                                '<button type="button" title="Order Now" class="action tocart primary">' +
                                    'Order Now <i class="fas fa-cart-plus" style="float: right;"></i>' +
                                '</button>' +
                            '</a>'
            } else {
                addToCart = '<form data-role="tocart-form"' +
                                    'data-product-sku="' + product.sku + '"' +
                                    'action="https://www.digidirect.com.au/checkout/cart/add/uenc/%25uenc%25/product/'+ product.refId +'" method="post"><?php echo $block->getBlockHtml("formkey"); ?>' +
                                    '<input type="text" name="ref_id" value="'+ product.refId +'" hidden/>' +
                                    '<input type="text" name="qty" value="1" hidden/>' +
                                    '<input type="text" name="widget_id" value="631dfdd4-dc01-ef11-abf3-02bf4bf6447c" hidden/>' +
                                    '<input type="text" name="route_id" value="'+ routeId +'" hidden/>' +
                                    '<button type="submit" title="Add to Cart" class="action tocart primary" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '">' +
                                    '<span>Add to Cart</span><i class="fas fa-cart-plus" style="float: right;color: #fff;"></i>' +
                                '</button>' +
                            '</form>'
            }
            //console.log(product.name, sellerName);
            if (!isDigiSeconds) {
                if (sellerName != "20329" && sellerName !== undefined) {
                    digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                } else {
                    digiDealsLogo = '';
                }
            }
            
            if (product.prices[0].discountPrice) {
                if (!isDigiSeconds) {
                    digiDealsLogo = '<div class="ribbon-digideals">digiDeals</div>';
                    if (sellerName != "20329" && sellerName !== undefined) {
                        digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                    }
                }
                
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                let discountPriceToDisplay = "$" + Number(product.prices[0].discountPrice).toFixed(2);
                let discount = "$" + Number(product.prices[0].price - product.prices[0].discountPrice).toFixed(2);
                
                finalPrice = Number(product.prices[0].discountPrice).toFixed(2);
                
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label">Price Slashed </span>' + 
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="discount-price-wrapper"><span class="discount-price">'+ discount +'</span> Off</div>' +
                            '</div>';
            } else {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                
                finalPrice = Number(product.prices[0].price).toFixed(2);
                
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }
            
            let hideProductItem = "";
            var view = "-bundle";
            var tileId = 'product-' + product.refId + view;
            productItem = '<div id="'+ tileId +'" class="product-item-info product-item" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '">' +
                            '<div class="pa-checkbox-container">' +
                                '<label class="pa-checkbox-label">' +
                                    '<input type="checkbox" data-product-id="'+ product.refId +'" data-product-price="'+ finalPrice +'" class="pa-checkbox-input pa-bundle-overlay-product"><span><i class="fas fa-clipboard fa-2x"></i></span>' +
                                '</label>' +
                            '</div>' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                digiDealsLogo + digiSeconds +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                            '<div class="product actions product-item-actions">' +
                                '<div class="actions-primary">' +
                                    addToCart +
                                '</div>' +
                            '</div>' +
                        '</div>'
            $(prependTo).prepend(productItem);
            //slots(product.refId, recommenderId, campaignId, tacticId);
        });
    }
    
    function productTileMinicart(widgetId, appendTo, isMobile) {
        let productItem = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        var productCtr = 0;
        Object.keys(widgetSlots).forEach(key => {
            productCtr++;
            let product = widgetSlots[key].products[0];
            let campaignId = widgetSlots[key].campaignId;
            let recommenderId = widgetSlots[key].recommenderId;
            let tacticId = widgetSlots[key].tacticId;
            let digiDealsLogo = "";
            let priceBlock = "";
            let addToCart = "";
            
            let digiSeconds = "";
            let digiSecondsOverlay = "";
            let sellerName = "";
            
            let categories = product.attributes.find(obj => {
                return obj.name === 'Categories';
            })
            
            let seller = product.attributes.find(obj => {
                return obj.name === 'DDR_Seller_Id';
            })
            
            let digiPrint = product.attributes.find(obj => {
                return obj.name === 'is_digiprint';
            })
            
            let digiPrintLink = product.attributes.find(obj => {
                return obj.name === 'digiprint_customlink';
            })
            
            let digiSecondsRatingValue = product.attributes.find(obj => {
                return obj.name === 'item_rating';
            })
            
            let digiSecondsRating = "";            
            
            if (digiSecondsRatingValue.stringValue == "5") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "4") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "3") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "2") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            } else if (digiSecondsRatingValue.stringValue == "1") {
                digiSecondsRating = '<i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>';
            }
            
            sellerName = seller.stringValue;
            
            let digiSecondsCategories = ["PRELOVED","OPENBOX","REFURB"];
            let isDigiSeconds = digiSecondsCategories.includes(categories.options[0].value);
            
            if (categories.options[0].value == "PRELOVED") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-pre-loved.png"/>';
            } else if (categories.options[0].value == "OPENBOX") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-demo.png"/>';
            } else if (categories.options[0].value == "REFURB") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-refurbished.png"/>';
}
            
            digiSeconds = '<div class="digiseconds-overlay">' + digiSecondsOverlay + '<div class="digiseconds-rating">' + digiSecondsRating + '</div></div>';
            //console.log(attribute);

            let digiPrintValue = digiPrint.stringValue;
            let digiPrintLinkValue = digiPrintLink.stringValue;

            if (digiPrintValue == 1) {
                addToCart = '<a class="ordernow-link" href="' + digiPrintLinkValue + '" target="_blank">' +
                                '<button type="button" title="Order Now" class="action tocart primary">' +
                                    'Order Now <i class="fas fa-cart-plus" style="float: right;"></i>' +
                                '</button>' +
                            '</a>'
            } else {
                addToCart = '<form data-role="tocart-form"' +
                                    'data-product-sku="' + product.sku + '"' +
                                    'action="https://www.digidirect.com.au/checkout/cart/add/uenc/%25uenc%25/product/'+ product.refId +'" method="post"><?php echo $block->getBlockHtml("formkey"); ?>' +
                                    '<input type="text" name="ref_id" value="'+ product.refId +'" hidden/>' +
                                    '<input type="text" name="qty" value="1" hidden/>' +
                                    '<input type="text" name="widget_id" value="631dfdd4-dc01-ef11-abf3-02bf4bf6447c" hidden/>' +
                                    '<input type="text" name="route_id" value="'+ routeId +'" hidden/>' +
                                    '<button type="submit" title="Add to Cart" class="action tocart primary" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '">' +
                                    '<span>Add to Cart</span><i class="fas fa-cart-plus" style="float: right;color: #fff;"></i>' +
                                '</button>' +
                            '</form>'
            }
            //console.log(product.name, sellerName);
            if (!isDigiSeconds) {
                if (sellerName != "20329" && sellerName !== undefined) {
                    digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                } else {
                    digiDealsLogo = '';
                }
            }
            
            if (product.prices[0].discountPrice) {
                if (!isDigiSeconds) {
                    digiDealsLogo = '<div class="digideals-overlay"><img src="https://www.digidirect.com.au/media/wysiwyg/digidirect/digiDeals-Logo.png"/></div>';
                    if (sellerName != "20329" && sellerName !== undefined) {
                        digiDealsLogo = '<div class="ribbon-online">Online only</div>';
                    }
                }
                
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                let discountPriceToDisplay = "$" + Number(product.prices[0].discountPrice).toFixed(2);
                let discount = "$" + Number(product.prices[0].price - product.prices[0].discountPrice).toFixed(2);
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label">Price Slashed </span>' + 
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="discount-price-wrapper"><span class="discount-price">'+ discount +'</span> Off</div>' +
                            '</div>';
            } else {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }
            
            var view = "-minicart";
            var tileId = 'product-' + product.refId + view;
            productItem = '<div id="'+ tileId +'" class="product-item-info product-item minicart-item" product-id="'+ product.refId +'" widget-id="' + widgetId + '" campaign-id="' + campaignId + '" recommender-id="' + recommenderId + '" tactic-id="' + tacticId + '">' +
                            '<div class="wish-list-wrapper" data-role="add-to-links">' +
                                '<a href="#"' +
                                'data-post=""' +
                                'class="action towishlist" data-action="add-to-wishlist"' +
                                'title="Add to Wish List">' +
                                '<i class="fas fa-heart" style="font-size: 25px; color: #e6e6e6;"></i>' +
                                '</a>' +
                            '</div>' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                digiDealsLogo + digiSeconds +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                            '<div class="product actions product-item-actions">' +
                                '<div class="actions-primary"><div class="s19-rental-price-target"><p style="font-size: 13px; font-weight: 500;">Buy now pay later</p><p style="font-size: 13px; font-weight: 500; text-transform: uppercase;">Options Available</p></div>' +
                                    addToCart +
                                '</div>' +
                            '</div>' +
                        '</div>'
            $(appendTo).append(productItem);
            //slots(product.refId, recommenderId, campaignId, tacticId);
        });
        $('.pa-digidirect-product-widget-container.widget-placeholder').remove();
    }
    
    digiMarketSidePanel('011987ea-124e-ef11-abf3-02bf4bf6447c', '#explore-digimarket-side-panel');
    frequentlyBoughtWith('ca223b70-fc3d-ec11-aae9-02dca44cceec', '#pdp-frquently-bought-with-desktop');
    productTile('011987ea-124e-ef11-abf3-02bf4bf6447c', '#explore-digimarket-desktop', false);
    productTile('011987ea-124e-ef11-abf3-02bf4bf6447c', '#explore-digimarket-mobile', true);
    productTile('cecb45e7-043e-ec11-aae9-02dca44cceec', '#people-who-viewed-this-item-also-viewed-desktop', false);
    productTile('cecb45e7-043e-ec11-aae9-02dca44cceec', '#people-who-viewed-this-item-also-viewed-mobile', true);
    productTile('252b5970-293e-ec11-aae9-02dca44cceec', '#you-may-also-like-desktop', false);
    productTile('252b5970-293e-ec11-aae9-02dca44cceec', '#you-may-also-like-mobile', true);
    bundleOverlay('02ed2d33-ee8e-ec11-aae9-02dca44cceec', '#pdp-bundle-overlay-desktop');
    
    $("#pa-digimarket-side-panel .product-item-info.product-item:not(.slot)").each(function() {
        var element = $(this).attr("id");
        var productId = $(this).attr("product-id");
        var recommenderId = $(this).attr("recommender-id");
        var campaignId = $(this).attr("campaign-id");
        var tacticId = $(this).attr("tactic-id");
        isElementInViewPort(element, productId, recommenderId, campaignId, tacticId);
    });
    $(".pa-digidirect-product-widget .product-item-info.product-item:not(.pa-bundle-container, .slot)").each(function() {
        var element = $(this).attr("id");
        var productId = $(this).attr("product-id");
        var recommenderId = $(this).attr("recommender-id");
        var campaignId = $(this).attr("campaign-id");
        var tacticId = $(this).attr("tactic-id");
        isElementInViewPort(element, productId, recommenderId, campaignId, tacticId);
    });
    
    function slots(productId, recommenderId, campaignId, tacticId) {

        var widgetId = '631dfdd4-dc01-ef11-abf3-02bf4bf6447c';

        var date = new Date();

        const slotData = {
            customerId: configCustomerId,
            sessionId: configSessionId,
            events: [
                {
                    currentUrl: currentUrl,
                    eventTime: date.toISOString(),
                    refId: productId,
                    widgetId: widgetId,
                    routeId: routeId,              
                    recommenderId: recommenderId,
                    campaignId: campaignId,
                    tacticId: tacticId
                }
            ]
        };

        console.log(JSON.stringify(slotData));

        $.ajax({
            //async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/events/slots",
            type: "POST",
            data: {
                eventData: slotData
            },
            success: function(data){
                //console.log(data);
            },
            error: function(){
                console.log('AJAX Fail!');
            }
        });
    }
    
    function uuidv4() {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'
        .replace(/[xy]/g, function (c) {
            const r = Math.random() * 16 | 0, 
                v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }

    $(".pa-digidirect-product-widget .product-item-info.product-item").click(function(){
        
        var tileId = $(this).attr("id");
        var productId = $(this).attr("product-id");
        var recommenderId = $(this).attr("recommender-id");
        var campaignId = $(this).attr("campaign-id");
        var tacticId = $(this).attr("tactic-id");
        
        var widgetId = '631dfdd4-dc01-ef11-abf3-02bf4bf6447c';

        var date = new Date();

        const clickData = {
            customerId: configCustomerId,
            sessionId: configSessionId,
            events: [
                {
                    currentUrl: currentUrl,
                    eventTime: date.toISOString(),
                    clickId: uuidv4(),
                    refId: productId,
                    actionType: 1,
                    contextType: 1,
                    routeId: routeId,
                    widgetId: widgetId,              
                    recommenderId: recommenderId,
                    campaignId: campaignId,
                    tacticId: tacticId
                }
            ]
        };
        
        /*var thisElement = document.getElementById(tileId);
        let rect = thisElement.getBoundingClientRect();

        console.log("Product ID id ", element, "The bounding Rect of element is ", rect);*/

        //console.log(JSON.stringify(clickData));

        $.ajax({
            //async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/events/clicks",
            type: "POST",
            data: {
                eventData: clickData
            },
            success: function(data){
                console.log(data);
            },
            error: function(){
                console.log('AJAX Fail!');
            }
        });

    });
    
    $(".pa-digidirect-product-widget .action.tocart").click(function(){

        var productId = $(this).attr("product-id");
        var recommenderId = $(this).attr("recommender-id");
        var campaignId = $(this).attr("campaign-id");
        var tacticId = $(this).attr("tactic-id");
        var widgetId = '631dfdd4-dc01-ef11-abf3-02bf4bf6447c';

        var date = new Date();
        var product = {"refId": productId, "quantity": 1};
        const productData = {
            customerId: configCustomerId,
            sessionId: configSessionId,
            events: [
                {
                    currentUrl: currentUrl,
                    eventTime: date.toISOString(),
                    product: product,
                    widgetId: widgetId,
                    routeId: routeId,   
                    recommenderId: recommenderId,
                    campaignId: campaignId,
                    tacticId: tacticId
                }
            ]
        };

        //console.log("productData", JSON.stringify(productData));

        $.ajax({
            async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/events/addtocart",
            type: "POST",
            data: {
                eventData: productData
            },
            success: function(data){
                console.log(data);
            },
            error: function(){
                console.log('AJAX Fail!');
            }
        });

    });
    
    $("#product-addtocart-button").click(function(){

        var productId = <?= $productId; ?>;
        var quantity = $("#qty").attr("value");

        var date = new Date();

        const productData = {
            customerId: configCustomerId,
            sessionId: configSessionId,
            events: [
                {
                    currentUrl: currentUrl,
                    eventTime: date.toISOString(),
                    product: {"refId": productId, "quantity": quantity}
                }
            ]
        };

        //console.log("productData", JSON.stringify(productData));

        $.ajax({
            async: false,
            url: "https://www.digidirect.com.au/particularaudienceapi/events/addtocart",
            type: "POST",
            data: {
                eventData: productData
            },
            success: function(data){
                console.log(data);
            },
            error: function(){
                console.log('AJAX Fail!');
            }
        });

    });
    
    function isElementInViewPort(element, productId, recommenderId, campaignId, tacticId){
        //console.log("element", element);
        var thisElement = document.getElementById(element);
        let rect = thisElement.getBoundingClientRect();

        // check if element is completely visible inside the viewport
        if ((rect.top <= 600 && rect.top >= 0) && rect.height != 0) {
            console.log("Product ID id ", element, "The bounding Rect of element is ", rect);
            //return (isTopInViewPort && isLeftInViewPort && isBottomInViewPort && isRightInViewPort);
            slots(productId, recommenderId, campaignId, tacticId);
            $(thisElement).addClass("slot");
        }
    }

    window.addEventListener('scroll', function() {
        $("#pa-digimarket-side-panel .product-item-info.product-item:not(.slot)").each(function() {
            var element = $(this).attr("id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            isElementInViewPort(element, productId, recommenderId, campaignId, tacticId);
        });
        $(".pa-digidirect-product-widget .product-item-info.product-item:not(.pa-bundle-container, .minicart-item, .slot)").each(function() {
            var element = $(this).attr("id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            isElementInViewPort(element, productId, recommenderId, campaignId, tacticId);
        });
    }, false);
    
    //Frequently Bought With
    $(".select-all-products-on-bundle").change(function() {
        if(this.checked) {
            $('.pa-bundle-product').each(function(){
                if (!$(this).is(":checked")) {
                    $(this).trigger('click');
                }
            });
        } else {
            $('.pa-bundle-product').each(function(){
                if ($(this).is(":checked")) {
                    $(this).trigger('click');
                }
            });
        }
    });

    $(".pa-bundle-product").change(function() {
        var bundleTotal = Number($("#pa-bundle-total").text().substring(1));
        var bundleProductPrice = Number($(this).attr("data-product-price"));
        console.log(bundleTotal, bundleProductPrice);
        if(this.checked) {
            var newBundleTotal = bundleTotal + bundleProductPrice;
        } else {
            var newBundleTotal = bundleTotal - bundleProductPrice;
        }
        $("#pa-bundle-total").text('$' + Number(newBundleTotal).toFixed(2));
    });
    
    $("#pdp-frquently-bought-with-desktop input").each(function() {
        $(this).prop("checked", true);
    });
    
    var fbwBundleTotal = 0;
    $("#pdp-frquently-bought-with-desktop .pa-bundle-product").each(function() {
        let bundleProductPrice = Number($(this).attr("data-product-price"));
        fbwBundleTotal += bundleProductPrice;
    });
    $("#pa-bundle-total").text('$' + Number(fbwBundleTotal).toFixed(2));
    
    $("#pdp-bundle-overlay-desktop input").each(function() {
        $(this).prop("checked", true);
    });

    var overlayBundleTotal = 0;
    $("#pdp-bundle-overlay-desktop .pa-bundle-overlay-product").each(function() {
        let bundleProductPrice = Number($(this).attr("data-product-price"));
        overlayBundleTotal += bundleProductPrice;
    });
    $("#pa-bundle-overlay-total").text('$' + Number(overlayBundleTotal).toFixed(2));
    
    const observerMinicart = new MutationObserver((mutations) => {
        console.log("MutationObserver!");
        $('.action.showcart').addClass("-active");
        $('#minicartSidebar').addClass("-active");
        $('.minicart-items.item-qty').attr("style", "visibility: hidden !important;");
    }); 

    var miniCart = document.querySelector('.minicart-wrapper');
    const configMinicart = { attributes: false, childList: true, subtree: true }; 

    $("#add-bundle-tocart").click(function(){

        var productIds = [];

        $('.pa-bundle-product').each(function(){
            if(this.checked) {
                console.log("data-product-id: " + $(this).attr("data-product-id"));
                productIds.push($(this).attr("data-product-id"));
            }
        });

        var url = "https://www.digidirect.com.au/particularaudienceapi/index/frequentlyboughtwith";

        $.ajax({
            url: url,
            type: "POST",
            data: {
                productIds: productIds
            },
            success: function(data){
                console.log("Success!");
                observerMinicart.observe(miniCart, configMinicart);
            },
            error: function(){
                console.log("Fail!");
            }
        });
        observerMinicart.disconnect();
    });

    //Bundle Overlay
    $(".select-all-products-on-bundle-overlay").change(function() {
        if(this.checked) {
            $('.pa-bundle-overlay-product').each(function(){
                if (!$(this).is(":checked")) {
                    $(this).trigger('click');
                }
            });
        } else {
            $('.pa-bundle-overlay-product').each(function(){
                if ($(this).is(":checked")) {
                    $(this).trigger('click');
                }
            });
        }
    });

    $(".pa-bundle-overlay-product").change(function() {
        var bundleTotal = Number($("#pa-bundle-overlay-total").text().substring(1));
        var bundleProductPrice = Number($(this).attr("data-product-price"));
        console.log(bundleTotal, bundleProductPrice);
        if(this.checked) {
            var newBundleTotal = bundleTotal + bundleProductPrice;
        } else {
            var newBundleTotal = bundleTotal - bundleProductPrice;
        }
        $("#pa-bundle-overlay-total").text('$' + Number(newBundleTotal).toFixed(2));
    });

    $("#add-bundle-overlay-tocart").click(function(){

        var productIds = [];
        $('.pa-bundle-overlay-product').each(function(){
            if(this.checked) {
                console.log("data-product-id: " + $(this).attr("data-product-id"));
                productIds.push($(this).attr("data-product-id"));
            }
        });

        var url = "https://www.digidirect.com.au/particularaudienceapi/index/frequentlyboughtwith";

        $.ajax({
            url: url,
            type: "POST",
            data: {
                productIds: productIds
            },
            success: function(data){
                console.log("Success!");
                observerMinicart.observe(miniCart, configMinicart);
            },
            error: function(){
                console.log("Fail!");
            }
        });
        observerMinicart.disconnect();
        $("#bundle-overlay-container").hide();
    });

    $("#bundle-overlay-exit").click(function(){
        $("#bundle-overlay-container").hide();
    });

    $("#product-addtocart-button").click(function(){
        $("#bundle-overlay-container").show();
        $("#pdp-bundle-overlay-desktop .product-item-info.product-item").each(function() {
            var element = $(this).attr("id");
            var productId = $(this).attr("product-id");
            var recommenderId = $(this).attr("recommender-id");
            var campaignId = $(this).attr("campaign-id");
            var tacticId = $(this).attr("tactic-id");
            isElementInViewPort(element, productId, recommenderId, campaignId, tacticId);
        });
    });
    
    const observer = new MutationObserver((mutations) => { 
        if ($("#pa-minicart-desktop").length) {
            //console.log("MutationObserver!");
            productTileMinicart('5576c304-fd3d-ec11-aae9-02dca44cceec', '#pa-minicart-desktop', false);
            stopMutationObserver();
        }
    }); 
    
    const config = { attributes: true, childList: true, subtree: true }; 
    observer.observe(document.body, config); 
    
    function stopMutationObserver() {
        observer.disconnect(); 
    }
    
    /*var minicart = $("#minicartSidebar");
    
    const minicartObserver = new MutationObserver((mutations) => { 
        if (minicart.hasClass("-active")) {
            $(".pa-digidirect-product-widget .product-item-info.product-item.minicart-item:not(.slot)").each(function() {
                var element = $(this).attr("id");
                var productId = $(this).attr("product-id");
                var recommenderId = $(this).attr("recommender-id");
                var campaignId = $(this).attr("campaign-id");
                var tacticId = $(this).attr("tactic-id");
                isElementInViewPort(element, productId, recommenderId, campaignId, tacticId);
            });
        }
    }); 
    
    const minicartConfig = { attributes: true, childList: false, subtree: false }; 
    minicartObserver.observe(minicart, minicartConfig); */
    
});
</script>

<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
           "bindSubmit": true
        }
    }
}
</script>

<script>
    
    function loadMoreProducts(widgetClass) {
        var hiddenTiles = document.querySelectorAll('.'+ widgetClass + ' ' + ' .hide-product-item'); 
        var ctr = 0;
        for (let x = 0; x < hiddenTiles.length; x++) {
          ctr++;
          hiddenTiles[x].classList.remove('hide-product-item');
          if (ctr == 4) break;
        }
        var hiddenTilesCount = document.querySelectorAll('.'+ widgetClass + ' ' + ' .hide-product-item'); 
        if (hiddenTilesCount.length == 0) {
            document.querySelectorAll('.'+ widgetClass + ' ' + '.load-more')[0].style.display = "none";    
            document.querySelectorAll('.'+ widgetClass + ' ' + '.view-less')[0].style.display = "block";    
             
            try {
                document.querySelectorAll('.'+ widgetClass + ' ' + '.view-all')[0].style.display = "block"; 
            }
            catch(err) {
            }
        }
    }

    function viewLessProducts(widgetClass) {
        var productTiles = document.querySelectorAll('.'+ widgetClass + ' ' + '.mobile-widget .product-item'); 

        var ctr = 0;
        for (let x = 0; x < productTiles.length; x++) {
          ctr++;
          if (ctr > 4) {
             productTiles[x].classList.add('hide-product-item');
          }
        }
        
        document.querySelectorAll('.'+ widgetClass + ' ' + '.load-more')[0].style.display = "block";    
        document.querySelectorAll('.'+ widgetClass + ' ' + '.view-less')[0].style.display = "none";    
        try {
            document.querySelectorAll('.'+ widgetClass + ' ' + '.view-all')[0].style.display = "none"; 
        }
        catch(err) {
        }
        document.getElementById(widgetClass).scrollIntoView();
    }
    
</script>