<?php
    use Magento\Framework\App\Action\Action;
?>
<script>
    
require(['jquery'], function ($) {
    
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }
    
    var customerId = getCookie('PAC');
    var customerParam = "";
    
    if (customerId) {
        customerParam = "&customerId=" + customerId;
    }
    
    console.log('customerId', customerId);
    
    const getRecommendationsUrl = "https://api-recs.particularaudience.com/3.0/recommendations?currentUrl=https://www.digidirect.com.au/pa-digi-products-pdp&expandProductDetails=true"+customerParam;
    const accessToken = "<?= $block->getBearerToken() ?>"; // Replace with your actual access token

    var result;

    $.ajax({
        async: false,
        url: getRecommendationsUrl,
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-Type': "application/json"
        },
        type: "GET",
        success: function(data){
            result = data;
        },
        error: function(){
            console.log('AJAX Fail!');
        }
    });
    
    var recommendationsResult = result;
    var widgets  = recommendationsResult.recommendations.route.widgets;

    function digiMarketSidePanel(widgetId, appendTo) {
        let productItem = "";
        let priceBlock = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        Object.keys(widgetSlots).forEach(key => {
            let product = widgetSlots[key].products[0];
            //widgetSlots[key].products[0].refId;
            
            if (product.prices[0].discountPrice) {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                let discountPriceToDisplay = "$" + Number(product.prices[0].discountPrice).toFixed(2);
                let discount = "$" + Number(product.prices[0].price - product.prices[0].discountPrice).toFixed(2);
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label">Price Slashed </span>' + 
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="discount-price-wrapper"><span class="discount-price">'+ discount +'</span> Off</div>' +
                            '</div>';
            } else {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }
            
            productItem = '<div class="product-item-info product-item">' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                        '</div>'
            $(appendTo).append(productItem);
        });
        $('.pa-product-widget-container.widget-placeholder').remove();
    }
    
    function productTile(widgetId, appendTo, isMobile) {
        let productItem = "";
        let widget = widgets.find(obj => {
            return obj.id === widgetId;
        })
        let widgetSlots = widget.slots;
        var productCtr = 0;
        Object.keys(widgetSlots).forEach(key => {
            productCtr++;
            let product = widgetSlots[key].products[0];
            let digiDealsLogo = "";
            let priceBlock = "";
            let addToCart = "";
            
            let digiSeconds = "";
            let digiSecondsOverlay = "";
            let digiSecondsRating = "";
            
            let attribute = product.attributes.find(obj => {
                return obj.name === 'Categories';
            })
            
            if (attribute.options[0].value == "PRELOVED") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-pre-loved.png"/>';
            } else if (attribute.options[0].value == "OPENBOX") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-demo.png"/>';
            } else if (attribute.options[0].value == "REFURB") {
                digiSecondsOverlay = '<img src="https://www.digidirect.com.au/media/wysiwyg/digiseconds/overlays/badge-refurbished.png"/>';
            }
            
            digiSeconds = '<div class="digiseconds-overlay">' + digiSecondsOverlay + '<div class="digiseconds-rating">' + digiSecondsRating + '</div></div>';
            //console.log(attribute);

            if (product.is_digiprint) {
                addToCart = '<a class="ordernow-link" href="' + product.digiprint_customlink + '" target="_blank">' +
                                '<button type="button" title="Order Now" class="action btn-ordernow primary">' +
                                    'Order Now <i class="fas fa-cart-plus" style="float: right;"></i>' +
                                '</button>' +
                            '</a>'
            } else {
                addToCart = '<form data-role="tocart-form"' +
                                    'data-product-sku="' + product.sku + '"' +
                                    'action="https://www.digidirect.com.au/checkout/cart/add/uenc/%25uenc%25/product/'+ product.refId +'" method="post"><?php echo $block->getBlockHtml("formkey"); ?>' +
                                '<button type="submit" title="Add to Cart" class="action tocart primary">' +
                                    '<span>Add to Cart</span><i class="fas fa-cart-plus" style="float: right;color: #fff;"></i>' +
                                '</button>' +
                            '</form>'
            }
            
            if (product.prices[0].discountPrice) {
                digiDealsLogo = '<div class="digideals-overlay"><img src="https://www.digidirect.com.au/media/wysiwyg/digidirect/digiDeals-Logo.png"/></div>';
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                let discountPriceToDisplay = "$" + Number(product.prices[0].discountPrice).toFixed(2);
                let discount = "$" + Number(product.prices[0].price - product.prices[0].discountPrice).toFixed(2);
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="old-price-wrapper"><span class="old-price">' +
                                    '<span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label">Price Slashed </span>' + 
                                            '<span id="old-price-'+ product.refId +'" data-price-amount="'+ priceToDisplay +'" data-price-type="oldPrice" class="price-wrapper ">' +
                                                '<span class="price">'+ priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="current-price-wrapper has-special-price">' +
                                    '<div class="digidirectprice">' +
                                        '<span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span>' +
                                    '</div>' +
                                    '<span class="special-price"><span class="price-container price-final_price tax weee">' +
                                        '<span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ discountPriceToDisplay +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">'+ discountPriceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                                '<div class="discount-price-wrapper"><span class="discount-price">'+ discount +'</span> Off</div>' +
                            '</div>';
            } else {
                let priceToDisplay = "$" + Number(product.prices[0].price).toFixed(2);
                priceBlock = '<div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ product.refId +'" data-price-box="product-id-'+ product.refId +'">' +
                                '<div class="current-price-wrapper no-special-price">' +
                                    '<div class="digidirectprice"><span>digi</span><span style="color: #000;">Direct <span style="font-weight: 400;">Price</span></span></div>' +
                                        '<span class="special-price"><span class="price-container price-final_price tax weee"><span class="price-label"></span>' + 
                                            '<span id="product-price-'+ product.refId +'" data-price-amount="'+ product.prices[0].price +'" data-price-type="basePrice" class="price-wrapper ">' +
                                                '<span class="price">' + priceToDisplay +'</span>' +
                                            '</span>' + 
                                        '</span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>';
            }
            
            let hideProductItem = "";
            if (isMobile && productCtr > 4) {
                hideProductItem = "hide-product-item";
            }
            productItem = '<div class="product-item-info product-item ' + hideProductItem + '">' +
                            '<div class="wish-list-wrapper" data-role="add-to-links">' +
                                '<a href="#"' +
                                'data-post=""' +
                                'class="action towishlist" data-action="add-to-wishlist"' +
                                'title="Add to Wish List">' +
                                '<i class="fas fa-heart" style="font-size: 25px; color: #e6e6e6;"></i>' +
                                '</a>' +
                            '</div>' +
                            '<a href="' + product.url + '" class="product photo product-item-photo" tabindex="-1">' +
                                digiDealsLogo + digiSeconds +
                                '<span class="product-image-container" style="width: 240px;">' +
                                    '<span class="product-image-wrapper" style="padding-bottom: 125%;">' +
                                        '<img class="product-image-photo" src="' + product.images[0] + '" loading="lazy" width="240" height="300" alt="Product Image">' +
                                    '</span>' +
                                '</span>' +
                            '</a>' + 
                            '<div class="product details product-item-details">' +
                                '<strong class="product-item-name">' +
                                    '<a title="' + product.name + '" href="' + product.url + '" class="product-item-link">' +
                                        product.name +
                                    '</a>' +
                                '</strong>' +
                                priceBlock +
                            '</div>' +
                            '<div class="product actions product-item-actions">' +
                                '<div class="actions-primary">' +
                                    addToCart +
                                '</div>' +
                            '</div>' +
                        '</div>'
            $(appendTo).append(productItem);
        });
        $('.pa-digidirect-product-widget-container.widget-placeholder').remove();
    }
    
    digiMarketSidePanel('458d80ed-033e-ec11-aae9-02dca44cceec', '#test-pa-digimarket-side-panel .product-item-container');
    //productTile('94e9300c-023e-ec11-aae9-02dca44cceec', '#recommended-for-you-widget-desktop', false);
    //productTile('94e9300c-023e-ec11-aae9-02dca44cceec', '#recommended-for-you-widget-mobile', true);
});

</script>

<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
           "bindSubmit": true
        }
    }
}
</script>