<?php
/**
 * @var $block \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable
 * @var $infoBlock \Ewave\OutOfStockNotif\Block\Product\View\AvailableDate
 */
?>
<?php
    $isSalable = $block->getProduct()->isSalable() ? 1 : 0;
    $availabilityDateInfo = '{}';
    $soldOutMessageInfo = '[]';
    if ($infoBlock = $block->getLayout()->getBlock('outstock.info')) {
        $availabilityDateInfo = $infoBlock->getAvailabilityDateInfo($block->getAllowProducts());
        $soldOutMessageInfo = $infoBlock->getSoldOutMessageInfo($block->getAllowProducts());
    }
?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "outstockConfigurable": {
                "spConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>,
                "availableProducts": <?php /* @escapeNotVerified */ echo $block->getSwatchesSalableProductIds(); ?>,
                "isSalable": <?php echo (int)$isSalable; ?>,
                "superSelector": ".super-attribute-select",
                "outofstockInput": "outofstock-input",
                "swatchElements": "swatch-options",
                "swatchEventElements": ".swatch-option",
                "hiddenClass": "no-display",
                "visibleClass": "-visible-block",
                "availabilityDateInfo": <?php /* @escapeNotVerified */ echo $availabilityDateInfo ?>,
                "soldOutMessageInfo": <?php /* @escapeNotVerified */ echo $soldOutMessageInfo ?>
            }
        }
    }
</script>
