# The services of the project.
#
# Each service listed will be deployed to power your project.

mysql:
    type: mysql:10.4
    disk: 8192
redis:
    type: redis:6.x
elasticsearch:
    type: elasticsearch:7.9
    disk: 1024
