<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Braintree\Block\Paypal\Button $block
 */

$id = $block->getContainerId() . mt_rand();

$config = [
    'Magento_Braintree/js/paypal/button' => [
        'id' => $id,
        'clientToken' => $block->getClientToken(),
        'displayName' => $block->getMerchantName(),
        'actionSuccess' => $block->getActionSuccess()
    ]
];

?>
<div data-mage-init='<?= /* @noEscape */ json_encode($config) ?>'
    class="paypal checkout paypal-logo braintree-paypal-logo<?= /* @noEscape */ $block->getContainerId() ?>-container">
    <button data-currency="<?= /* @noEscape */ $block->getCurrency() ?>"
       data-locale="<?= /* @noEscape */ $block->getLocale() ?>"
       data-amount="<?= /* @noEscape */ $block->getAmount() ?>"
       id="<?= /* @noEscape */ $id ?>"
       class="action-braintree-paypal-logo action primary" disabled>
        <?= /* @noEscape */ __('Checkout with') ?>
        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -paypal-logo">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-paypal-logo"></use>
        </svg>
    </button>
</div>
