<?php
/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer -vast">
    <div class="block-title -great">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('New Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <div class="tick-block">
            <?= $block->getChildHtml() ?>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create button -responsive" title="<?= $block->escapeHtml(__('Create an Account')) ?>"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
