<?php
// @codingStandardsIgnoreFile
?>
<?php
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
/** @var \Magento\Bundle\Pricing\Render\FinalPriceBox $block */

/** @var \Magento\Bundle\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPrice();
$minimalPrice = $finalPriceModel->getMinimalPrice();
$maximalPrice = $finalPriceModel->getMaximalPrice();
/** ex: \Magento\Bundle\Pricing\Price\BundleRegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $regularPriceModel */
$regularPriceModel = $block->getPriceType('regular_price');
$maximalRegularPrice = $regularPriceModel->getMaximalPrice();
$minimalRegularPrice = $regularPriceModel->getMinimalPrice();
?>
<?php if ($block->getSaleableItem()->getPriceView()): ?>
    <p class="minimal-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
            'display_label'     => __('As low as'),
            'price_id'          => $block->getPriceId('from-'),
            'include_container' => true
        ]); ?>
        <?php if ($minimalPrice < $minimalRegularPrice): ?>
            <span class="old-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalRegularPrice, [
                    'display_label'     => __('Regular Price'),
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
        <?php endif ?>
    </p>
<?php else: ?>
    <?php if ($block->showRangePrice()): ?>
        <p class="price-from">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
                'display_label'     => __('Starts from'),
                'price_id'          => $block->getPriceId('from-'),
                'price_type'        => 'minPrice',
                'include_container' => true
            ]); ?>
        </p>
        <?php if ($catalogRulePDP = trim($this->getLayout()
            ->createBlock('Ewave\ExtendedCatalogPriceRule\Block\Pdp\DisplayMessage')
            ->setBlockName('digi_catalog_rule_pdp')
            ->setTemplate('Ewave_ExtendedCatalogPriceRule::product/view/price_rule.phtml')
            ->setActualAmount($minimalPrice)
            ->toHtml())) : ?>
            <div class="price-to">
                <span class="price-label"><?= /* @escapeNotVerified */ __('Cashback Available') ?></span>
            </div>
        <?php endif; ?>
    <?php endif ?>
<?php endif ?>
