<style>
 ul#digiEventlist {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-column-gap: 2rem;
    grid-row-gap: 2rem;
    list-style: none;
  }

  #digiEventlist h3 {
    font-size: 22px;
    color: #323232;
    font-weight: 400;
    margin-bottom: 5px !important;
  }

  #digiEventlist a {
    text-decoration: none;
    padding: 8px 15px;
    background: #004182;
    color: #ffff;
    border-radius: 3px;
    /* box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px, rgba(10, 37, 64, 0.35) 0px -2px 6px 0px inset; */
    margin-top: 15px !important;
  }

  .wrap_ticket_url {
    margin-top: 25px;
    position: absolute;
    bottom: 18px;
  }

  #digiEventlist li {
    width: 100%;
    height: 410px;
    background: #ffffff;
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    margin-bottom: 25px;
    /*padding-bottom: 25px;*/
    position: relative;
  }

  #digiEventlist li img {
    width: 100%;
  }

  #eventsbrite_name, #eventsbrite_date, #eventsbrite_description, #eventsbrite_link {
    margin: 0 15px;
    width: 95%;
    color: #636363;
    font-size: 15px;
  }

  #eventsbrite_date {
    color: #004182;
    font-weight: 400;
  }

  /* small phone */
  @media screen and (max-width: 768px) { 
    ul#digiEventlist {
      display: block;
      padding-left: 0px !important;
      margin: 0 5px;
    }

    #digiEventlist li {
      width: 100%;
      height: auto;
      background: #ffffff;
      box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
      margin-bottom: 25px;
      padding-bottom: 15px;
      position: relative;
    }

    .wrap_ticket_url {
      margin-top: 25px;
      position: relative;
      bottom: 2px;
    }
  }

  /* small ipad */

  @media screen and (min-width: 812px) and (max-width: 1024px) {
    ul#digiEventlist {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      grid-column-gap: 2rem;
      grid-row-gap: 2rem;
      list-style: none;
    }
  }

</style>

<h1> Test Page </h1>

<div class="eventbrite-datafeed">
    
    <ul id="digiEventlist"></ul>

</div>

