<?php

use Magento\Framework\App\Action\Action;

/**
 * @var $block \Magento\Catalog\Block\Product\AbstractProduct
 */
$_quickViewHelper = $this->helper('Ewave\QuickView\Helper\Data');

$showQuickView = $_quickViewHelper->isModuleEnabled();
$quickViewUseForMobile = true;
$quickViewLabel = __('Quick View');
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You May Also Like');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You May Also Like');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('You May Also Like');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('You May Also Like');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    default:
        $exist = null;
}
?>

<?php if ($exist):?>

    <?php if ($type === 'related' || $type === 'upsell'): ?>
        <?php if ($type === 'related'): ?>
            <div class="block <?= $block->escapeHtml($class); ?>"
                 data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
                 data-limit="<?= $block->escapeHtml($limit) ?>"
                 data-shuffle="<?= $block->escapeHtml($shuffle) ?>">
        <?php else: ?>
            <div class="products-widget _full-width-background upsell-block <?= $block->escapeHtml($class) ?>"
                 data-mage-init='{"upsellProducts":{}}'
                 data-limit="<?= $block->escapeHtml($limit); ?>"
                 data-shuffle="<?= $block->escapeHtml($shuffle); ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block products-widget _full-width-background <?= $block->escapeHtml($class); ?>">
    <?php endif; ?>
    <div class="title">
        <strong id="block-<?= $block->escapeHtml($class); ?>-heading"
                role="heading"
                aria-level="2">
            <?= $block->escapeHtml($title); ?>
        </strong>
    </div>
    <div class="block-content content"
         aria-labelledby="block-<?= $block->escapeHtml($class); ?>-heading">
        <?php if ($type === 'related' && $canItemsAddToCart): ?>
        <div class="block-actions">
            <?= /* @escapeNotVerified */ __('Check items to add to the cart or'); ?>
            <button type="button"
                    class="action select"
                    role="select-all">
                <span><?= /* @escapeNotVerified */ __('select all'); ?></span>
            </button>
        </div>
        <?php endif; ?>
        <div class="wrapper grid products-grid products-<?= $block->escapeHtml($type); ?>">
            <ol class="list items product-items"
                data-mage-init='{
                    "productTile": {
                        <?php if ($block->isRedirectToCartEnabled()): ?>
                        "isRedirectToCartEnabled": true,
                        <?php endif; ?>
                        "type": "<?= /* @escapeNotVerified */ (count($items) > 2) ? 'slider' : 'default'; ?>"
                    }
                    }'>
                <?php foreach ($items as $_item): ?>
                    <?php
                    $productId = $_item->getId();
                    $productName = $_item->getName();
                    $productUrl = $_item->getProductUrl();
                    $ruleMessage = $block->getChildBlock('product.tile.extended.catalog.rule');
                    $available = '';
                    ?>
                    <?php if ($type === 'related' && !$_item->isComposite() && $_item->isSaleable()): ?>
                        <?php if (!$_item->getRequiredOptions()): ?>
                            <?php $available = 'related-available'; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($type === 'related' || $type === 'upsell'): ?>
                        <li class="item product product-item" style="display: none;">
                    <?php else: ?>
                        <li class="item product product-item">
                    <?php endif; ?>
                    <div class="product-item-info <?= $block->escapeHtml($available); ?>"
                         data-parent-product-id="<?= $block->escapeHtml($productId); ?>">
                        <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)); ?>"
                           title="<?= $block->escapeHtml($productName); ?>"
                           class="product photo product-item-photo">
                            <?= $block->getImage($_item, $image)->toHtml(); ?>
                        </a>
                        <strong class="product name product-item-name">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)); ?>"
                               title="<?= $block->escapeHtml($productName); ?>"
                               class="product-item-link">
                                <?= $block->escapeHtml($productName); ?>
                            </a>
                        </strong>
                        <div class="product details product-item-details">
                            <?php if ($ruleMessage): ?>
                                <?= $ruleMessage->setProduct($_item)->toHtml(); ?>
                            <?php endif; ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>

                                <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                    <?php if (!$_item->getRequiredOptions()): ?>
                                        <div class="field choice related">
                                            <input type="checkbox"
                                                   class="checkbox related"
                                                   id="related-checkbox<?= $block->escapeHtml($productId); ?>"
                                                   name="related_products[]" value="<?= $block->escapeHtml($productId); ?>" />
                                            <label class="label"
                                                   for="related-checkbox<?= $block->escapeHtml($productId); ?>">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart'); ?></span>
                                            </label>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <?php if ($showAddTo || $showCart): ?>
                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php $addToCartUrl = $block->getAddToCartUrl($_item); ?>
                                                        <form data-role="tocart-form"
                                                              data-product-sku="<?= $block->escapeHtml($_item->getSku()); ?>"
                                                              data-mage-init='{"validation": {}}'
                                                              action="<?= $block->escapeUrl($addToCartUrl); ?>"
                                                              method="post">
                                                            <input type="hidden"
                                                                   name="product"
                                                                   value="<?= /* @escapeNotVerified */ (int)$_item->getEntityId(); ?>"/>
                                                            <input type="hidden"
                                                                   name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                   value="<?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Url\Helper\Data')->getEncodedUrl($addToCartUrl); ?>"/>
                                                            <?= $block->getBlockHtml('formkey'); ?>
                                                            <?php if ($toCartFormBlock = $block->getChildBlock('tocart_form')): ?>
                                                                <?= /* @escapeNotVerified */ $toCartFormBlock->setProduct($_item)->getChildHtml(); ?>
                                                            <?php endif; ?>
                                                            <button class="action tocart"
                                                                    type="submit" title="<?= /* @escapeNotVerified */ __('Add to Cart'); ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Cart'); ?></span>
                                                            </button>
                                                        </form>
                                                        <?php
                                                            $outOfStockNotifHelper = $this->helper(\Ewave\OutOfStockNotif\Helper\Data::class);
                                                            $isNotificationForBackorder = $outOfStockNotifHelper->isEnabledForBackorder();
                                                            $isBackOrderAllow = $outOfStockNotifHelper->isBackOrderAllow($_item);
                                                        ?>
                                                        <?php if ($isNotificationForBackorder && $isBackOrderAllow) : ?>
                                                            <script type="text/x-magento-init">
                                                                {
                                                                    "form[data-product-sku='<?= /* @escapeNotVerified */ $_item->getSku(); ?>']": {
                                                                        "outstockNotification": {
                                                                            "modal": false,
                                                                            "notificationForBackorder": 1,
                                                                            "isBackorderProduct": true,
                                                                            "backorderButtonLabel": "<?= /* @escapeNotVerified */ __('Back-order'); ?>",
                                                                            "addToCartFormSelector": "form[data-product-sku='<?= $block->escapeHtml($_item->getSku()); ?>']"
                                                                        }
                                                                    }
                                                                }
                                                            </script>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available">
                                                                <span><?= /* @escapeNotVerified */ __('In stock'); ?></span>
                                                            </div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <span><?= /* @escapeNotVerified */ __('Out of stock'); ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($showAddTo): ?>
                                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                        <?= $addToBlock->setProduct($_item)->getChildHtml(); ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showQuickView): ?>
                                                <span role="button"
                                                      data-role="quickview-button"
                                                      data-url="<?= $block->escapeUrl($block->getProductUrl($_item)) . '?quickview=1'; ?>"
                                                      class="quickview-button"
                                                      title="<?= $block->escapeHtml($quickViewLabel); ?>">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon">
                                                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-quick"></use>
                                                    </svg>
                                                    <span class="title"><?= $block->escapeHtml($quickViewLabel); ?></span>
                                                </span>
                                            <?php endif; ?>
                                        </div>
                                        <?php if ($rentBlock = $block->getChildBlock('product.tile.rent')): ?>
                                            <?= $rentBlock->toHtml(); ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>
