<div class="header-links header-link-left">
    <a class="store-locator-link" href="/store-locator-list" title="Store Locator" style="margin-right: 33px;">
        <img src="<?= $block->getViewFileUrl('images/icons/iconsax-location.svg') ?>" alt="Store Locator" /> <span style="margin-left: 2px;">Store Locator</span>
    </a>
    <a class="digiservices-link" href="/services" title="digiServices" style="margin-right: 32px;">
        <img src="<?= $block->getViewFileUrl('images/icons/box.svg') ?>" alt="Services" style="margin-right: 7px;"/> <span>Services</span>
    </a>
    <a class="faq-link" href="/faqs" title="FAQ">
        <img src="<?= $block->getViewFileUrl('images/icons/message-text.svg') ?>" alt="Questions" style="margin-right: 8px;"/> <span>Questions?</span>
    </a>
</div>
<div class="header-links header-link-right" style="margin-left: auto;">
    <a class="digiclub-link" href="/digiclub" title="digiClub">
        <img src="<?= $block->getViewFileUrl('images/icons/airdrop.svg') ?>" alt="digiClub" /> <span style=""><span style="color: #FE4C25;"> digi</span><span>Club</span><sup>®</sup></span>
    </a>
    <a class="gift-cards-link" href="https://digidirectgiftcards.viisolutions.com.au/" title="GIFT CARDS" target="_blank">
        <img src="<?= $block->getViewFileUrl('images/icons/iconsax-gift.svg') ?>" alt="Gift Card" style="margin-right: 7px;"/> <span>Gift Card</span>
    </a>
    <a class="click-and-collect-link" href="/click-and-collect" title="Click & Collect">
        <img src="<?= $block->getViewFileUrl('images/icons/cc.png') ?>" alt="Click & Collect" style="margin-right: 7px;"/> <span>Click & Collect</span>
    </a>
    <a class="digibusiness-link" href="/b2b" title="b2b">
        <img src="<?= $block->getViewFileUrl('images/icons/iconsax-briefcase-cross.svg') ?>" alt="digiDirect Business" style="margin-right: 7px;"/> <span>digiDirect Business</span>
    </a>
</div>
