<?php
/**
 * @var \Ewave\Blog\Block\Blog $block
 * @var \Ewave\Blog\Model\Post $post
 */

/**
 * @var \Ewave\Digi\Helper\Blog $blogHelper
 */
$blogHelper = $this->helper('Ewave\Digi\Helper\Blog');
$categoriesArrayNames = [];
?>
<?php if ($block->isListPageMode()): ?>
    <div class="blog-list blog-pg">
        <?php foreach ($block->getCollection() as $post): ?>
            <article class="post-card item">
                <?php if (!empty($post->getImageUrl())): ?>
                <a class="img-link" href="<?php echo $block->escapeUrl($post->getViewUrl()); ?>" title="<?php echo $block->escapeHtml($post->getTitle()) ?>">
                    <picture>
                        <source media="(min-width: 1280px)" srcset="<?php echo $block->escapeHtml($post->getImageUrl(null, 850)); ?>">
                        <img src="<?php echo $block->escapeHtml($post->getImageUrl(null, 750)); ?>" alt="<?php echo $block->escapeHtml($post->getTitle()) ?>">
                    </picture>
                </a>
                <?php endif; ?>
                <div class="container">
                    <?php if ($block->isShowCategoryNames()) : ?>
                        <?php $categoriesArray = $block->getCategoriesTitlesAsArray($post); ?>
                        <?php $categoriesTitlesCount = count($categoriesArray); ?>
                        <?php if ($categoriesTitlesCount) : ?>
                            <div class="categories">
                                <?php /** @var $category \Ewave\Blog\Model\Category*/ ?>
                                <?php $i=1; foreach ($categoriesArray as $key => $category): ?>
                                    <a href="<?php echo $block->escapeUrl($category->getViewUrl())?>" class="link item" title="<?php /* @escapeNotVerified */  echo $category->getName(); ?>"><?php /* @escapeNotVerified */  echo $category->getName(); ?></a><?php if ($categoriesTitlesCount != $i) : ?> <?php endif; ?>
                                    <?php $i++; ?>
                                    <?php array_push($categoriesArrayNames, $category->getName())?>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                    <h2 class="title">
                        <a class="link" href="<?php echo $block->escapeUrl($post->getViewUrl()) ?>" title="<?php echo $block->escapeHtml($post->getTitle()); ?>">
                            <?php echo $block->escapeHtml($post->getTitle()); ?>
                        </a>
                    </h2>
                    
                    <?php if (!$blogHelper->isPostRelatedToContributors($post)):?>
                        <div class="posted">
                            <span class="label"><?php /* @escapeNotVerified */ echo __('Posted on') ?></span>
                            <?php echo $block->escapeHtml($post->getCreatedDate()); ?>
                        </div>
                    <?php endif; ?>

                    <div class="description content"><?php /* @escapeNotVerified */ echo $block->getShortDescription($post); ?></div>

                    <a class="more" href="<?php echo $block->escapeUrl($post->getViewUrl()); ?>" title="<?php /* @escapeNotVerified */ echo __('Read More') ?>">
                        <span class="more-title"><?php /* @escapeNotVerified */ echo __('Read More') ?></span>
                        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon svgi-arrow">
                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-arrow"></use>
                        </svg>
                    </a>
                    <?php if($post->getTags()): ?>
                        <div class="tags">
                            <span class="label"><?php /* @escapeNotVerified */ echo __('Tags: ') ?></span>
                            <?php foreach ($post->getTags() as $tag): ?>
                                <a class="link  tag" href="<?php echo $block->escapeUrl($block->getTagUrl($tag)) ?>" title="<?php echo $block->escapeHtml($tag) ?>"><?php echo $block->escapeHtml($tag) ?></a>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>

                <a class="thumb" href="<?php echo $block->escapeUrl($post->getViewUrl()); ?>" title="<?php echo $block->escapeHtml($post->getTitle()) ?>"></a>

                <div class="init _hidden">
                    <script>
                        if (typeof fbq !== undefined) {
                            fbq('trackCustom', 'ViewArticle', {
                                blog_category: '<?php echo $this->helper("Magento\Framework\Json\Helper\Data")->jsonEncode($categoriesArrayNames)?>',
                                content_name: '<?php echo $block->escapeHtml($post->getTitle()) ?>'
                            });
                        }
                    </script>
                </div>
            </article>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="blog-list -grid small-block-grid-1 medium-block-grid-2 large-block-grid-3 blog-pg">
        <?php foreach ($block->getCollection() as $post): ?>
            <?php $thumb = ""; ?>
            <article class="post-card item">

                <?php if (!empty($post->getImageUrl())): ?>
                <a class="img-link" href="<?php echo $block->escapeUrl($post->getViewUrl()); ?>" title="<?php echo $block->escapeHtml($post->getTitle()) ?>">
                    <picture>
                        <source media="(min-width: 1280px)" srcset="<?php echo $block->escapeHtml($post->getImageUrl(null, 850)); ?>">
                        <img src="<?php echo $block->escapeHtml($post->getImageUrl(null, 750)); ?>" alt="<?php echo $block->escapeHtml($post->getTitle()) ?>">
                    </picture>
                </a>
                <?php endif; ?>

                <div class="container">
                    <?php if ($block->isShowCategoryNames()) : ?>
                        <?php $categoriesArray = $block->getCategoriesTitlesAsArray($post); ?>
                        <?php $categoriesTitlesCount = count($categoriesArray); ?>
                        <?php if ($categoriesTitlesCount) : ?>
                            <div class="categories">
                                <?php /** @var $category \Ewave\Blog\Model\Category*/ ?>
                                <?php $i=1; foreach ($categoriesArray as $key => $category): ?>
                                    <a href="<?php echo $block->escapeUrl($category->getViewUrl())?>" class="link item" title="<?php /* @escapeNotVerified */  echo $category->getName(); ?>"><?php /* @escapeNotVerified */  echo $category->getName(); ?></a><?php if ($categoriesTitlesCount != $i) : ?> <?php endif; ?>
                                    <?php $i++; ?>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>

                    <h2 class="title">
                    <a class="link" href="<?php echo $block->escapeUrl($post->getViewUrl()) ?>" title="<?php echo $block->escapeHtml($post->getTitle()); ?>">
                        <?php echo $block->escapeHtml($post->getTitle()); ?>
                    </a>
                </h2>
                    <?php if (!$blogHelper->isPostRelatedToContributors($post)):?>
                        <div class="posted">
                            <span class="label"><?php /* @escapeNotVerified */ echo __('Posted on') ?></span>
                            <?php echo $block->escapeHtml($post->getCreatedDate()); ?>
                        </div>
                    <?php endif; ?>
                <div class="description content"><?php /* @escapeNotVerified */ echo $block->getShortDescription($post); ?></div>

                    <a class="more" href="<?php echo $block->escapeUrl($post->getViewUrl()); ?>" title="<?php /* @escapeNotVerified */ echo __('Read More') ?>">
                        <span class="more-title"><?php /* @escapeNotVerified */ echo __('Read More') ?></span>
                        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon svgi-arrow">
                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-arrow"></use>
                        </svg>
                    </a>
                <?php if($post->getTags()): ?>
                    <div class="tags">
                        <span class="label"><?php /* @escapeNotVerified */ echo __('Tags: ') ?></span>
                        <?php foreach ($post->getTags() as $tag): ?>
                            <a class="link  tag" href="<?php echo $block->escapeUrl($block->getTagUrl($tag)) ?>" title="<?php echo $block->escapeHtml($tag) ?>"><?php echo $block->escapeHtml($tag) ?></a>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                </div>

                <a class="thumb" href="<?php echo $block->escapeUrl($post->getViewUrl()); ?>" title="<?php echo $block->escapeHtml($post->getTitle()) ?>"></a>
            </article>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if (!$block->getCollection()->getSize()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('There are no blog posts.') ?></div></div>
<?php endif; ?>
<?php if ($toolbar = $block->getChildHtml('toolbar')) : ?>
    <div class="toolbar blog-toolbar">
        <?php /* @escapeNotVerified */ echo $toolbar ?>
    </div>
<?php endif; ?>
