<header class="page-header">
    <div class="header content">
        <span data-action="toggle-nav" class="action nav-toggle"><svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-menu"></use></svg></span>
        <div class="logo-wrapper">
            <a class="c-logo" href="/">
                <img src="<?php echo $block->getUrl("media/wysiwyg/") ?>logo-white.svg"/>
            </a>
        </div>
    </div>
</header>

<script>
    require([
        'jquery'
    ],
    function ($) {
        $(".tablinks").click(function(){
          console.log("Tablinks OnClick Working!");
          $(".shop-by-category-menu .item-submenu.expand").attr("style", "width: 850px !important;");
          $(".menu-second-level .tab").attr("style", "width: 50% !important;");
        });
    });
</script>