<?php
/**
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
 ?>

<div class="field">
    <label for="<?php echo $block->getFieldId() ?>" class="required"><em>*</em><?php echo $block->getLabel() ?></label>
    <div class="input-box">
        <input type="email" name="confirm_email" id="<?php echo $block->getFieldId() ?>" value="" placeholder="<?php echo $block->getLabel() ?>" title="<?php echo $block->getLabel() ?>" class="input-text validate-email required-entry" />
    </div>
</div>
