<?php
/**
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
 ?>

<div class="field">
    <label for="<?php echo $block->getFieldId() ?>"><?php echo $block->getLabel() ?></label>
    <div class="input-box">
        <input type="text" name="fax" id="<?php echo $block->getFieldId() ?>" placeholder="<?php echo $block->getLabel() ?>" title="<?php echo $block->getLabel() ?>" value="" class="fax-field input-text <?php echo $block->getAttributeValidationClass('fax') ?>" />
    </div>
</div>
