<?php
/**
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
 ?>

<div class="field">
    <label for="<?php echo $block->getFieldId() ?>"<?php if ($block->isRequired()) echo ' class="required"' ?>><?php if ($block->isRequired()) echo '<em>*</em>' ?><?php echo $block->getLabel() ?></label>
    <div class="input-box">
        <input type="text" id="<?php echo $block->getFieldId() ?>" name="<?php echo $block->getFieldName() ?>" value="" placeholder="<?php echo $block->getLabel() ?>" title="<?php echo $block->getLabel() ?>" class="input-text <?php echo $block->getAttributeValidationClass('middlename') ?>" />
    </div>
</div>
