<?php
/**
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
 ?>

<div class="field">
    <label for="<?php echo $block->getFieldId() ?>" class="required"><em>*</em><?php echo $block->getLabel() ?></label>
    <div class="input-box">
        <input type="text" name="street" value="" placeholder="<?php echo $block->getLabel() ?>" title="<?php echo $block->getLabel() ?>" id="<?php echo $block->getFieldId() ?>" class="street-field input-text required-entry <?php echo $block->getAttributeValidationClass('street') ?>" />
    </div>
</div>
