<?php
/** @var \Digidirect\AbstractAttributes\Block\Attribute\Option\View $block */
/** @var $imageHelper \Digidirect\AbstractAttributes\Helper\Image */
$option = $block->getOption();
$imageHelper = $this->helper('Digidirect\AbstractAttributes\Helper\Image');
?>
<?php if ($option->getImage()) : ?>
    <div class="category-image">
        <img class="image" src="<?php echo $block->escapeUrl($imageHelper->init($option, 'image')->resize(400, 300)->getUrl()); ?>"
             alt="<?php echo $block->escapeHtml($option->getLabel()); ?>"/>
    </div>
<?php endif; ?>
<?php if ($_description = $option->getDescription()): ?>
    <div class="category-description">
        <?php /* @escapeNotVerified */ echo $_description; ?>
    </div>
<?php endif; ?>
<?php if ($_cmsBlock = $block->getCmsBlockContent()): ?>
    <div class="category-cms">
        <?php /* @escapeNotVerified */ echo $_cmsBlock; ?>
    </div>
<?php endif; ?>
