<?php

use Magento\Framework\App\Action\Action;

$blockData = $block->getData();
$searchTerm = $blockData['data']['searchTerm'];

$_productCollection = $block->getProductCollectionSearchResult($searchTerm);

?>
<?php if (!$_productCollection->count()): ?>
    <div>We can't find products matching your search</div>
<?php else: ?>
    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
    <ul style="list-style-type: none;margin: 0;">
        <?php foreach ($_productCollection as $_product): ?>
            <li>
                <a class="autocomplete-product-link" href="<?= $_product->getProductUrl() ?>"><?= $_product->getName() ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
