<div class="footer-partners">
    <div class="item -zip">
        <a href="/zip-money" title="ZIP Money">
            <img src="/pub/media/wysiwyg/partners/Zip_blk_300.png" alt="ZIP Money">
        </a>
    </div>
    <div class="item -studio19">
        <a href="/digirent" title="digiRent&quot;">
            <img src="/pub/media/wysiwyg/partners/digiRent_black.png" alt="digiRent">
        </a>
    </div>
    <div class="item -qantas">
        <a href="/qantas" title="Qantas Frequent Flyer">
            <img src="/pub/media/wysiwyg/partners/qantas-frequent-flyer.png" alt="Qantas Frequent Flyer">
        </a>
    </div>
</div>
