<nav data-action="navigation" class="footer-nav">
    <ul class="footer-menu">
        <li class="category-item item">
            <span class="link">Support</span>    
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="FAQ" href="/faq/" id="mi-2-1-1">FAQ</a>  </li>
                    <li><a class="link" title="digiProtect" href="/digiprotect/" id="mi-2-1-2">digiProtect</a>  </li>
                    <li><a class="link" title="In-Store Pickup" href="/pickup-instore" id="mi-2-1-3">In-Store Pickup</a>  </li>
                    <li><a class="link" title="Returns &amp; Refunds" href="/returns/" id="mi-2-1-4">Returns &amp; Refunds</a>  </li>
                    <li><a class="link" title="Terms and Conditions" href="/terms/" id="mi-2-1-5">Terms and Conditions</a>  </li>
                    <li><a class="link" title="Contact Us" href="/contact/" id="mi-2-1-6">Contact Us</a>  </li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class=" footer-menu">
        <li class="category-item  item">
            <span class="link">About</span>    
            <div class=" sub-items">
                <ul class="menu">
                    <li><a class="link" title="About digiDirect" href="/about/" id="mi-2-2-1">About digiDirect</a>  </li>
                    <li><a class="link" title="Store Locations" href="/store-locator/" id="mi-2-2-2">Store Locations</a>  </li>
                    <li><a class="link" title="Events" href="/events/" id="mi-2-2-3">Events</a>  </li>
                    <li><a class="link" title="Blog" href="/blog" id="mi-2-2-4">Blog</a>  </li>
                    <li><a class="link" title="Gift Cards" href="https://digidirectgiftcards.viisolutions.com.au/" id="mi-2-2-5">Gift Cards</a>  </li>
                    <li><a class="link" title="Earn Qantas Points" href="/qantas/" id="mi-2-2-6">Earn Qantas Points</a>  </li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class=" footer-menu">
        <li class="category-item  item">
            <span class="link">More Services</span>    
            <div class=" sub-items">
                <ul class="menu">
                    <li><a class="link" title="digiPrint - Photo Lab" href="/digiprint" id="mi-2-3-1">digiPrint - Photo Lab</a>  </li>
                    <li><a class="link" title="Passport Photos" href="/passport-photos" id="mi-2-3-2">Passport Photos</a>  </li>
                    <li><a class="link" title="digiRent" href="/digirent/" id="mi-2-3-3">digiRent</a>  </li>
                    <li><a class="link" title="Product Finder" href="/product-finder/" id="mi-2-3-4">Product Finder</a>  </li>
                </ul>
            </div>
        </li>
    </ul>
    <ul class=" footer-menu">
        <li class="category-item  item">
            <span class="link">Popular Links</span>    
            <div class="sub-items">
                <ul class="menu">
                    <li><a class="link" title="Manfrotto Tripods" href="/photo-accessories/tripods-and-stabilizers/manfrotto" id="mi-2-4-1">Manfrotto Tripods</a>  </li>
                    <li><a class="link" title="Peak Design Bags and Cases" href="/photo-accessories/bags-and-cases/peak-design" id="mi-2-4-2">Peak Design Bags and Cases</a>  </li>
                    <li><a class="link" title="Hoya Filters" href="/lenses/lens-filters/hoya" id="mi-2-4-3">Hoya Filters</a>  </li>
                    <li><a class="link" title="3 Legged Thing Tripods" href="/photo-accessories/tripods-and-stabilizers/3-legged-thing" id="mi-2-4-4">3 Legged Thing Tripods</a>  </li>
                    <li><a class="link" title="Pelican Bags and Cases" href="/photo-accessories/bags-and-cases/pelican" id="mi-2-4-5">Pelican Bags and Cases</a>  </li>
                    <li><a class="link" title="B+W Filters" href="/lenses/lens-filters/b-w" id="mi-2-4-6">B+W Filters</a>  </li>
                    <li><a class="link" title="Sandisk Memory Cards" href="/photo-accessories/memory-cards-and-drives/sandisk" id="mi-2-4-7">Sandisk Memory Cards</a>  </li>
                </ul>
            </div>
        </li>
    </ul>
</nav>