<div class="footer-line">
    <div class="footer-bottom">
        <nav class="nav-extra">
            <ul class=" menu">     
                <li class=" item -level1"> 
                    © DigiDIRECT 2021. All rights reserved.
                </li>    
                <li class=" item -level1"> 
                    <a class=" link" title="Privacy Policy" href="/privacy/" id="fi-1-1">Privacy Policy</a> 
                </li>    
                <li class=" item -level1"> 
                    <a class=" link" title="Terms of Use" href="/terms-of-use" id="fi-1-2">Terms of Use</a> 
                </li> 
            </ul>
        </nav> 
    </div>
</div>