<?php
/** @var $block \Digidirect\Navigation\Block\Menu */
$menuJson = $block->getMenuJson();
?>
<?php $menuArray = json_decode($menuJson); ?>
<?php
if (empty($menuArray)) {
    return;
}
?>

<nav class="<?php echo $block->escapeHtml($block->getAreaSelector());?><?php echo $block->getResponsive()? ' -responsive -'.$block->getOffCanvasSide()  : ''?>">
    <ul class="<?php echo $block->getWrapperClass() ? ' ' . $block->escapeHtml($block->getWrapperClass()) : '';?><?php echo $block->getHorizontal() == 'true' ? ' -horizontal' : '';?><?php echo $block->getExpanded() == 'true' ? ' -expanded' : '';?>">
        <?php $i = 1; $j = 1; foreach ($menuArray as $item) : ?>
        <?php if (isset($item->cms_block_content)){
            $length = strlen($item->cms_block_content) ;
        } else {
            $length = false;
        }?>
            <?php if(isset($item->style)) : ?>
                <?php $style = $item->style; ?>
            <?php else: ?>
                <?php $style = null; ?>
            <?php endif;?>
        <li class="<?php echo $block->escapeHtml($item->frontend_class); ?><?php echo $block->getItemClass() ? ' ' . $block->escapeHtml($block->getItemClass()) : '';?><?php echo $item->is_active ? ' -active': '' ?> -level<?php echo $block->escapeHtml((int)$i) ?>">
            <?php if ($item->url && ($item->is_link == '1' || $item->is_link === true)): ?>
                <a <?php if($style) : ?>style="<?php echo $block->escapeHtml($style) ?>" <?php endif; ?> class="<?php echo $block->getItemLabelClass() ? ' ' . $block->escapeHtml($block->getItemLabelClass()) : '';?>" title="<?php echo $block->escapeHtml($item->title) ?>" href="<?php echo $block->escapeUrl($item->url) ?>" id="fi-<?php echo (int)$i ?>-<?php echo $block->escapeHtml((int)$j) ?>"><?php echo $block->escapeHtml($item->title) ?></a>
            <?php else: ?>
                <span <?php if($style) : ?>style="<?php echo $block->escapeHtml($style)?>" <?php endif; ?> class="<?php echo $block->getItemLabelClass() ? ' ' . $block->escapeHtml($block->getItemLabelClass()) : '';?>" id="fi-<?php echo $block->escapeHtml((int)$i) ?>-<?php echo $block->escapeHtml((int)$j) ?>"><?php echo $block->escapeHtml($item->title) ?></span>
            <?php endif; ?>
        </li>
        <?php $j++; endforeach; ?>
    </ul>
</nav>
