<?php
/**
 * @var \Ewave\Blog\Block\Post\RelatedProducts $block
 */
if ($exist = $block->getItems()->getSize() && $block->displayProducts()) {
    $type = 'related';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Related Products');
    $items = $block->getItems();
    $limit = 0;
    $shuffle = 0;
    $canItemsAddToCart = true;

    $showWishlist = $block->displayWishList();
    $showCompare = $block->displayCompare();
    $showCart = $block->displayCart();
    $templateType = null;
    $description = false;
}
?>

<?php if ($exist): ?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php echo $block->escapeHtml($class); ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $block->escapeHtml($limit); ?>" data-shuffle="<?php echo $block->escapeHtml($shuffle); ?>">
        <?php else: ?>
            <div class="block <?php echo $block->escapeHtml($class); ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $block->escapeHtml($limit); ?>" data-shuffle="<?php echo $block->escapeHtml($shuffle); ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php echo $block->escapeHtml($class); ?>">
    <?php endif; ?>
    <div class="block-title title 12354678964561253">
        <strong id="block-<?php echo $block->escapeHtml($class) ?>-heading" role="heading" aria-level="2"><?php echo $block->escapeHtml($title); ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php echo $block->escapeHtml($class) ?>-heading">

        <div class="products wrapper grid products-grid products-<?php echo $block->escapeHtml($type); ?>">
            <ol class="products list items product-items" data-mage-init='{
                                "slickInit":{
                                    "arrows": false,
                                    "slidesToShow": 2,
                                    "slidesToScroll": 1,
                                    "mobileFirst": true,
                                    "waitForAnimate": false,
                                    "autoplay": false,
                                    "infinite": false,
                                    "swipeToSlide": true,
                                    "dots": false,
                                    "responsive": [
                                        {
                                            "breakpoint": 768,
                                            "settings": {"slidesToShow": 3
                                            }
                                        }, {
                                            "breakpoint": 1439,
                                            "settings": {"slidesToShow": 4,
                                            "arrows": true
                                            }
                                        }, {
                                            "breakpoint": 1800,
                                            "settings": {"slidesToShow": 5,
                                            "arrows": true
                                            }
                                        }
                                    ]
                                }
                            }'>
                <?php $iterator = 1; ?>
                <?php $i = 0; ?>
                <?php foreach ($items as $_item): ?>
                    <?php $available = ''; ?>
                    <?php if ($i > 9) {
                        break;
                    } ?>
                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                        <?php if (!$_item->getRequiredOptions()): ?>
                            <?php $available = 'related-available'; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($type == 'related' || $type == 'upsell'): ?>
                        <?php /* @escapeNotVerified */ echo ($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                    <?php else: ?>
                        <?php /* @escapeNotVerified */ echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <?php endif; ?>
                    <div class="product-item-info <?php echo $block->escapeHtml($available); ?>">
                        <?php echo '<!-- ' . $block->escapeHtml($image) . '-->' ?>
                        <a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                            <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name"><a class="product-item-link"
                                                                              title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                                                              href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                    <?php echo $block->escapeHtml($_item->getName()) ?></a>
                            </strong>

                            <?php /* @escapeNotVerified */  echo $block->getProductPrice($_item); ?>

                            <?php if ($templateType): ?>
                                <?php /* @escapeNotVerified */  echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart"
                                                            data-mage-init='{"redirectUrl": {"url": "<?php echo $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item),
                                                        ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available">
                                                        <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable">
                                                        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                   class="action towishlist" data-action="add-to-wishlist"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-heart"></use></svg>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php
                                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                ?>
                                                <a href="#" class="action tocompare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
                                                   data-role="add-to-links"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php /* @escapeNotVerified */ echo ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php $i++; ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
    </div>
<?php endif; ?>