<?php
$pageType = $block->getRequest()->getFullActionName(); // e.g., catalog_category_view, catalogsearch_result_index
if (in_array($pageType, ['catalog_category_view', 'catalogsearch_result_index'])): ?>
    <div id="plp-custom-loader" class="loading-mask">
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
<?php endif; ?>
