<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php
$_product = $block->getProduct();
$prontoStockStatus = $_product->getAttributeText('stock_status');
$prontoStockStatusSpecialValue = 'I';
?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($prontoStockStatus && $prontoStockStatus == $prontoStockStatusSpecialValue): ?>
        <div class="stock special" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span><?= /* @escapeNotVerified */ __('Special Delivery') ?></span>
        </div>
    <?php else: ?>
        <?php if ($_product->isAvailable()): ?>
            <div class="stock available" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                <span><?= /* @escapeNotVerified */ __('In stock') ?></span>
            </div>
        <?php else: ?>
            <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
            </div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
