<?php

use Magento\Framework\App\Action\Action;

/**
 * Author: Johnry Valeriano
 */
/** @var \Digidirect\SBCModule\Block\Widget\BestsellersProducts $block */
?>
<?php
    $type = 'widget-product-grid';
    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    
    $title = __('SBCModule');
?>

    <div class="block widget block-new-products product-home-listing products-widget <?= /* @noEscape */ $mode ?>">
        <div class="block-content">

            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <div id="sbc-carousel" 
                    class="product-items product-carousel owl-carousel owl-theme shop-by-category-container
                    <?= /* @noEscape */ $type ?>"
                    
                    data-mage-init='{
                      "productTile": {
                          <?php if($block->isRedirectToCartEnabled()): ?>
                          "isRedirectToCartEnabled": true,
                          <?php endif; ?>
                          "type":"<?= /* @escapeNotVerified */ (count($items) > 2) ? 'slider' : 'default'; ?>"
                      },
                      "truncateCollection": {
                            "addOn": "js/dist/widgets/truncate-collection/addons/catalog/index"
                        }
                     }'>

                     <div class="shop-by-category-category">
                         <a href="<?php echo $block->getUrl("cameras")?>">
                             <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-cameras.jpg"/>
                             <div class="product-count" id="cameras-count">Cameras(<?php echo $block->getProductCollectionCount(17); ?>)</div>
                         </a>
                     </div>
                     <div class="shop-by-category-category">
                        <a href="<?php echo $block->getUrl("lenses")?>">
                            <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-lens.jpg"/>
                            <div class="product-count"  id="lenses-count">Lenses(<?php echo $block->getProductCollectionCount(18); ?>)</div>
                        </a>
                    </div>
                     <div class="shop-by-category-category">
                        <a href="<?php echo $block->getUrl("drones")?>">
                            <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-drones.jpg"/>
                            <div class="product-count"  id="drones-count">Drones(<?php echo $block->getProductCollectionCount(21); ?>)</div>
                        </a>
                    </div>
                     <div class="shop-by-category-category">
                        <a href="<?php echo $block->getUrl("lighting-and-studio")?>">
                            <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-lights-and-studio.jpg"/>
                            <div class="product-count"  id="lighting-and-studio-count">Lighting & Studio(<?php echo $block->getProductCollectionCount(19); ?>)</div>
                        </a>
                    </div>
                     <div class="shop-by-category-category">
                        <a href="<?php echo $block->getUrl("photo-accessories")?>">
                            <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-photomemories.jpg"/>
                            <div class="product-count"  id="photo-accessories-count">Photo Accessories(<?php echo $block->getProductCollectionCount(71); ?>)</div>
                        </a>
                    </div>
                     <div class="shop-by-category-category">
                        <a href="<?php echo $block->getUrl("optics")?>">
                            <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-optics.jpg"/>
                            <div class="product-count"  id="optics-count">Optics(<?php echo $block->getProductCollectionCount(22); ?>)</div>
                        </a>
                    </div>
                     <div class="shop-by-category-category">
                        <a href="<?php echo $block->getUrl("audio-and-visual")?>">
                            <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-audio-and-visual.jpg"/>
                            <div class="product-count"  id="audio-and-visual-count">Audio & Visual(<?php echo $block->getProductCollectionCount(73); ?>)</div>
                        </a>
                    </div>
                    <div class="shop-by-category-category">
                        <a href="<?php echo $block->getUrl("pro-video")?>">
                            <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-provideo.jpg"/>
                            <div class="product-count"  id="pro-video-count">Pro Video(<?php echo $block->getProductCollectionCount(77); ?>)</div>
                        </a>
                    </div>
                    <div class="shop-by-category-category">
                        <a href="<?php echo $block->getUrl("home/smart-home")?>">
                            <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-smarthome.jpg"/>
                            <div class="product-count"  id="smart-home-count">Smart Home(<?php echo $block->getProductCollectionCount(704); ?>)</div>
                        </a>
                    </div>
                    <div class="shop-by-category-category">
                        <a href="<?php echo $block->getUrl("computers-mobile")?>">
                            <img src="<?php echo $block->getUrl("media/wysiwyg/category-grid")?>category-pcandlaptop.jpg"/>
                            <div class="product-count"  id="computers-mobile-count">Computers & Mobile(<?php echo $block->getProductCollectionCount(662); ?>)</div>
                        </a>
                    </div>
                </div>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>


<script>
    require(['jquery', 'owl_carousel'],
        function ($) {
            $(document).ready(function() {
                $('#sbc-carousel').owlCarousel({
                    loop:false,
                    nav:true,
                    navText:["<div class='nav-btn prev-slide'></div>","<div class='nav-btn next-slide'></div>"],
                    responsive:{
                        0:{
                            items:2,
                            margin: 15,
                            nav:false,
                            loop:true,
                            autoplay: true,
                            autoplayTimeout:3000
                        },
                        600:{
                            items:3,
                            nav:false
                        },
                        1000:{
                            items:4,
                            loop:false
                        },
                        1680:{
                            items:5,
                            loop:false
                        }
                    },
                    dots:false,
                    autoplay:false,
                    autoplayTimeout:3000
                })
            });
        }
    );
</script>