<?php
/**
 * @var $block Ewave\MyStoreWidget\Block\MyStore
 * @var $helper Ewave\MyStoreWidget\Helper\Config
 * @var $urlHelper Ewave\AbstractEntity\Helper\Url
 */
$helper = $this->helper('Ewave\MyStoreWidget\Helper\Config');
$urlHelper = $this->helper('Ewave\AbstractEntity\Helper\Url');
$selectedStore = $block->getStoreName();
?>
<?php if ($helper->isGoogleAutoSuggestEnabled()): ?>
    <?php
    $availableCountries = $helper->getAvailableCountries();
    $countCountries = count($availableCountries);
    ?>
<?php endif; ?>
<div data-bind="scope: 'my-store-widget'" class="mystorebar-wrapper" style="display: none">
    <div id="block-mystorebar"
         class="block-mystorebar"
         data-bind='attr: {"class": store.isStoreSelected() ? "block-mystorebar -selected" : "block-mystorebar"}, mageInit:
        {
            "myStoreSwitcher": {
                "saveUrl":"<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>",
                "searchUrl": "<?php /* @escapeNotVerified */ echo $block->getSearchUrl(); ?>",
                <?php if ($helper->isGeoLocationEnabled()): ?>
                   "isNeedKeepGeoLocation": <?php /* @escapeNotVerified */ echo (int)$helper->isNeedKeepGeolocation(); ?>,
                   "isGeoLocationEnabled": <?php /* @escapeNotVerified */ echo (int)$helper->isGeoLocationEnabled(); ?>,
                   "storesList": <?php /* @escapeNotVerified */ echo $block->getStores(); ?>,
                <?php endif; ?>
                <?php if ($helper->isGoogleAutoSuggestEnabled()): ?>
                    "isGoogleAutoSuggestEnabled": <?php /* @escapeNotVerified */ echo (int)$helper->isGoogleAutoSuggestEnabled(); ?>,
                    <?php if ($countCountries == 1): ?>
                        "singleCountryData":{"country": ["<?php /* @escapeNotVerified */ echo current($availableCountries); ?>"]},
                    <?php endif; ?>
                    <?php if ($countCountries > 1): ?>
                        "singleCountryData":{"country": <?php /* @escapeNotVerified */ echo json_encode($availableCountries); ?>},
                    <?php endif; ?>
                <?php endif; ?>
                "autocompleteSettings": {
                    "minLength": <?php echo (int)$helper->getSearchMinLength(); ?>
                },
                "isSelectedStore": <?php if ($selectedStore) :?>true<?php else: ?>false<?php endif; ?>
            },
            "modalMystorewidget":{}
        }
    '>
        <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
             alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
             class="sdd-loader"
        >
        <div class="mystore-modal-title"><?php /* @escapeNotVerified */ echo __('Choose Your Preferred Store') ?></div>
        <form class="form"
              action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>"
              method="post"
              id="mystore-form"
              data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
              data-bind="mageInit: {'validation': {}}"
        >
            <input type="hidden" name="abstract_entity_id" id="abstract_entity_id" value="<?php if ($block->isStoreSelected()): ?><?php /* @escapeNotVerified */ echo $block->getStore()->getId() ?><?php endif; ?>" />
            <?php echo $block->getBlockHtml('formkey')?>
            <input type="hidden" name="<?php /* @escapeNotVerified */ echo \Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED ?>" value="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Url\Helper\Data')->getEncodedUrl() ?>"/>
            <div class="change-mode">
                <label class="message" for="<?= /* @escapeNotVerified */ $block->getMyStoreInputId() ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon my-store-icon">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-pin"></use>
                    </svg>
                    <!-- ko if: (store.isStoreSelected()) -->
                        <!-- ko i18n: 'Pick up in-store - '--><!-- /ko -->
                    <!--/ko-->
                    <!-- ko ifnot: (store.isStoreSelected()) -->
                        <!-- ko i18n: 'Select your store'--><!-- /ko -->
                    <!--/ko-->
                </label>
                <div class="input-group store-select-section">
                    <div class="control">
                        <div class="selection">
                            <!-- ko if: (store.isStoreSelected() && store.storeUrl()) -->
                                <a data-bind="{attr: {href: store.storeUrl(), title: store.selectedStore()}}">
                                    <!-- ko text: store.selectedStore() --><!-- /ko -->
                                </a>
                            <!--/ko-->
                            <!-- ko ifnot: (store.isStoreSelected() && store.storeUrl()) -->
                            <!-- ko text: store.selectedStore() --><!-- /ko -->
                            <!--/ko-->
                        </div>
                    </div>
                    <a class="change-store-link" data-action="change-store" title="<?php /* @escapeNotVerified */ echo __('Change Store') ?>"> <?php /* @escapeNotVerified */ echo __('Change Store') ?></a>
                </div>
            </div>
            <div class="search-mode">

                <label class="message" for="<?= /* @escapeNotVerified */ $block->getMyStoreInputId() ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-gpss"></use>
                    </svg>
                </label>
                <div class="input-group">
                    <div id="mystore-control" class="control">
                        <input type="text" placeholder="<?php /* @escapeNotVerified */ echo __('Please enter your postcode or suburb.') ?>" name="store_name" id="<?= /* @escapeNotVerified */ $block->getMyStoreInputId() ?>" class="input-text" data-validate="{'required': true}" data-bind="attr: {value: store.selectedStore()}"/>
                    </div>
                    <button type="submit" class="search-mode-btn" data-action="save-mystore" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon -search"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-search"></use></svg>
                    </button>
                </div>
            </div>
            <!-- ko if: (store.isStoreSelected() && store.storeUrl()) -->
                <div class="store-info-section">
                    <div class="left-info">
                        <div id="storeHours">
                            <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon store-hours-icon">
                                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-clock"></use>
                            </svg>
                            <span class="opening-hours-title"><?php /* @escapeNotVerified */ echo __('Opening Hours') ?></span>
                            <span data-bind="html: store.openingHours"></span>
                        </div>
                    </div>
                    <div class="right-info">
                        <div id="storeStreet">
                            <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon store-street-icon">
                                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-building"></use>
                            </svg>
                            <span data-bind="text: store.storeStreet"></span>
                        </div>
                        <div id="storeUrl">
                            <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon store-url-icon">
                                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-pin"></use>
                            </svg>
                            <a data-bind="{attr: {href: store.storeUrl(), title: store.selectedStore()}}"><?php /* @escapeNotVerified */ echo __('Get Directions') ?></a>
                        </div>
                        <div id="storePhoneNumber">
                            <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon store-phone-icon">
                                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-phone"></use>
                            </svg>
                            <span data-bind="html: store.storePhoneNumber"></span>
                        </div>
                        <div id="storeFaxNumber">
                            <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon store-fax-icon">
                                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-fax"></use>
                            </svg>
                            <span data-bind="html: store.storeFaxNumber"></span>
                        </div>
                        <div id="storeEmail">
                            <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon store-email-icon">
                                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-mail"></use>
                            </svg>
                            <span data-bind="html: store.storeEmail"></span>
                        </div>
                        <a class="button action view-store-btn" data-bind="{attr: {href: store.storeUrl(), title: store.selectedStore()}}"><span><?php /* @escapeNotVerified */ echo __('View Store Details') ?></span></a>
                    </div>
                </div>
            <!--/ko-->
            <?php if ($helper->isGoogleAutoSuggestEnabled()): ?>
                <input type="hidden" name="find_store" id="mystore_find_store" value="0" />
                <input type="hidden" name="postcode" id="mystore_postal_code" value="" />
                <input type="hidden" name="city" id="mystore_locality" value="" />
                <input type="hidden" name="country" id="mystore_country" value="" />
            <?php endif; ?>
        </form>
    </div>
</div>
<div class="mystore-button">
    <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon mystore-icon">
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-stroke"></use>
    </svg>
    <span class="mystore-text" data-bind="scope: 'my-store-widget'">
        <span class="store-title"> <?php /* @escapeNotVerified */ echo __('Your Store') ?></span>
        <!-- ko if: (store.isStoreSelected() && store.storeUrl()) -->
            <a class="current-store-link" data-bind="{attr: {href: store.storeUrl(), title: store.selectedStore()}}"><!-- ko text: store.selectedStore() --><!-- /ko --></a>
        <!--/ko-->
        <!-- ko ifnot: (store.isStoreSelected() && store.storeUrl()) -->
            <span class="current-store" data-bind='attr: {"class": store.isStoreSelected() ? '><?php /* @escapeNotVerified */ echo __('Not Selected') ?></span>
        <!--/ko-->
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "my-store-widget": {
                    "component": "Ewave_MyStoreWidget/js/view/mystore-widget"
                }
            }
        },
        "Ewave_MyStoreWidget/js/model/store": {},
        "Ewave_MyStoreWidget/js/action/set-store": {},
        "Ewave_MyStoreWidget/js/activate": {}
    }
}
</script>
