<?php if ($product = $block->getProduct()->getData('whats_in_the_box')): ?>
<div class="new-block">
    <div class="title"><?php echo $block->escapeHtml(__('What’s In The Box')); ?></div>
    <div class="list">
        <?php echo $product; ?>
    </div>
</div>
<?php endif; ?>
<?php echo $this->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('pdp-details-card')
    ->toHtml();
?>
<?php echo $this->getLayout()
    ->createBlock('Ewave\ProductAttachment\Block\Product\View\Attachment')
    ->setTemplate('Ewave_ProductAttachment::product/view/attachments.phtml')
    ->toHtml()
?>
