<?php
$productSpec = $block->getProduct()->getShortDescription();
$_product = $block->getProduct();
$aeHelper = $this->helper('Ewave\Digi\Helper\AbstractEntities');
$features = $aeHelper->getProductKeyFeatures($_product);
$rulesBlock = $this->getChildHtml('block_rules');
?>
        
<!--<div class="bonus-qantas-wrapper">
    
    
   <div class="qantas-points qantas-points-bottom">
       <a href="#" id="click-me">
           <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-qantas"></use></svg>
            <span>Earn <?= $block->escapeHtml($finalQffBonusPoints); ?> <span class="highlight">bonus Qantas Points</span> to this product</span>    
       
       </a>
    
     
    </div>



    <div id="popup-mpdal" style="display:none;" >
    
    <img  class="qantas-modal-banner" src="<?php echo $this->getViewFileUrl('images/qantas-banner-modal.jpeg'); ?>" />
  
    <div class="qantas-modal-container">
        
    <div class="sticky-banner widget -home _full-width-background">
        
    
        <h1 class="qantas-modal-center">Earn  Qantas Points on Eligible Digidirect orders*</h1>
        <h3 class="qantas-modal-center">Shop now and earn  2 points per $1</h3>
        <p class="qantas-modal-center">Simply link your Qantas Frequent Flyer member ship number to your Digidirect account and earn points on eligible orders</p>
        
        <div class="row-modal-bottom">
            <div class="col-md-one md-qantas">    
                <div align="center">
                    <img  class="qantas-modal-logo "  src="<?php echo $this->getViewFileUrl('images/a.png'); ?>" /> 
                </div>
                <h3 class="column-h3">Link</h3>

                <p class="modal-p">Either by signing  into your account or linking your membership details before your order is placed.</p>
            </div>

            <div  class="col-md-one md-qantas"> 
                 <div align="center">
                    <img class="qantas-modal-logo "  src="<?php echo $this->getViewFileUrl('images/b.png'); ?>" />
                </div>
                
                <h3 class="column-h3">Shop</h3>

                <p class="modal-p">Shop thousands of Lenses,Camera and Camera Accessories.</p>
            </div>

            <div class="col-md-one md-qantas"> 
                <div align="center">
                     <img class="qantas-modal-logo "  src="<?php echo $this->getViewFileUrl('images/c.png'); ?>" />
                </div>
               
                 <h3 class="column-h3">Earn</h3>

                 <p class="modal-p">Earn 2 Qantas Points per $1 spent. Your points will be added to your account once you order is shipped.</p>
            </div>
        </div>
        <div class="you-container">
            <p class="you-must qantas-modal-center">*You must be a Qantas Frequent Flyer member to earn points. 
                A joining fee may apply. Membership and points are subject to the Qantas Frequent Flyer program terms and conditions. 
                To earn 2 Qantas Points per $1 spent, a member must purchase an eligible product via the Booktopia online retail 
                store and input their Qantas Frequent Flyer number at the time of purchase. Eligible products include; books, audio 
                books, stationery, DVDs, calendars and diaries. If you are unable to provide your Qantas Frequent Flyer membership 
                number at the time of the transaction, you will be unable to earn Qantas Points. A member will not be able to earn 
                Qantas Points on the following products; magazines, eBooks, gift cards and postage. Points will be allocated within
                7 days of the shipment date.
        </div>
        </div>
        </div>
    </div>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'jquery/ui'
        ],
        function(
            $,
            modal
        ) {
        console.log('test');
        
            var options = {
                   type: 'popup',
                   responsive: false,
                   innerScroll: false,
                   buttons: [{
                       text: $.mage.__('Continue'),
                       class: '',
                       click: function () {
                           this.closeModal();
                       }
                   }]
               };

               var popup = modal(options, $('#popup-mpdal'));
               $("#click-me").on('click',function(){
                   $("#popup-mpdal").modal("openModal");

               });

          
        }
    );
</script>    -->

<?php if ( $productSpec || $features || $rulesBlock): ?>
    <div data-role="trigger" class="overview-tab">
        <span class="title"><?php echo $block->escapeHtml(__('product overview')); ?></span>
        <div class="arrow">
            <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon svgi-action">
                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-left"></use>
            </svg>
        </div>
    </div>
    <div data-role="content" class="tabpanel">
    <?php echo $rulesBlock;?>
    <?php if ( $productSpec || $features ): ?>
        <span class="head"><?php echo $block->escapeHtml(__('product overview')); ?></span>
    <?php endif; ?>
    <div class="short-desc">
        <?php echo $productSpec ?>
    </div>
    <?php if ( $features ): ?>
        <div class="entity" data-mage-init='{
                                "slickInit":{
                                    "arrows": true,
                                    "slidesToShow": 6,
                                    "slidesToScroll": 1,
                                    "infinite": true,
                                    "swipeToSlide": true,
                                    "dots": false,
                                    "responsive": [
                                        {
                                            "breakpoint": 1439,
                                            "settings": {
                                                "slidesToShow": 6
                                            }
                                        },
                                        {
                                            "breakpoint": 1023,
                                            "settings": {
                                                "slidesToShow": 4
                                            }
                                        },
                                        {
                                            "breakpoint": 767,
                                            "settings": {
                                                "slidesToShow": 6
                                            }
                                        },
                                        {
                                            "breakpoint": 319,
                                            "settings": {
                                                "slidesToShow": 3
                                            }
                                        }
                                    ]
                                }
                            }'>
            <?php foreach ($features as $item): ?>
                <div class="item">
                    <img src="<?= $item->getImageUrl() ?>" alt="<?= $item->getName() ?>" class="img">
                    <span class="title"><?= $item->getName() ?></span>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
<?php endif; ?>
