<?php
/**
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */

/** @var \Plumrocket\Newsletterpopup\Block\Js $block */
?>

<script>
    requirejs(['prnewsletterpopup'], function() {
        window.prnewsletterPopup = new window.prnewsletterPopupClass(<?= /* @noEscape */ $block->getJsonConfig() ?>);
    });
</script>
