<?php
/**
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
 ?>

<div class="newspopup_up_bg" id="newspopup_up_bg_<?= (int) $block->getPopup()->getId() ?>" style="background: none; position: static;">
    <?= $block->getChildHtml('popup.body') ?>
</div>
<style type="text/css">
    body {
        width:800px!important;
    }

    ol, ul {
        list-style: outside none none;
        padding: 0;
        margin: 0;
    }
    .newspopup_up_bg {
        padding: 0!important;
        margin: auto!important;
    }
    .newspopup-theme {
        max-width: 860px;
    }

    .newspopup-animated-form {
        margin-top:0px!important;
    }
</style>
