<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \WebPanda\SalesProductImage\Helper\Data $helper */
$helper = $this->helper(\WebPanda\SalesProductImage\Helper\Data::class);
?>
    <style>
        .order-totals.shipment-email {
            th,
            td {
                border-top: 0 !important;
                background-color: #F2F2F7 !important;
            }
        }
    </style>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order) : ?>
    <table class="email-items digi-theme-glowup-shipment" style="border: none;">
        <thead>
        <tr>
            <th class="item-image" style="background-color: unset;"> </th>
            <th class="item-info" style="background-color: unset;"> </th>
            <th class="item-qty" style="background-color: unset; border-top: none;"><?= $this->escapeHtml(__('Qty')) ?></th>
            <th class="item-price" style="background-color: unset; border-top: none;"><?= $this->escapeHtml(__('Price')) ?></th>
        </tr>
        </thead>
        <?php foreach ($_shipment->getAllItems() as $_item) : ?>
            <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                <tbody>
                <tr>
                    <td class="item-image">
                        <?= $helper ? $helper->renderImage($_item, 'front', 'left') : '' ?>
                    </td>
                    <td class="item-info">
                        <strong><?= $this->escapeHtml($_item->getName()) ?></strong>
                        <?php if ($_item->getSku()): ?>
                            <div style="color:#777;font-size:12px;">SKU: <?= $this->escapeHtml($_item->getSku()) ?></div>
                        <?php endif; ?>

                        <?php if ($_options = $this->getItemOptions($_item)) : ?>
                            <dl class="item-options" style="margin-top:6px; font-size:12px; color:#666;">
                                <?php foreach ($_options as $option): ?>
                                    <dt><strong><em><?= $this->escapeHtml($option['label']) ?></em></strong></dt>
                                    <dd><?= /* @noEscape */ nl2br($this->escapeHtml($option['value'])) ?></dd>
                                <?php endforeach; ?>
                            </dl>
                        <?php endif; ?>

                    </td>
                    <td class="item-qty"><?= (int)$_item->getQty() ?></td>
                    <td class="item-price">
                        <?php
                        $price = null;
                        if (method_exists($_item, 'getPriceInclTax') && $_item->getPriceInclTax()) {
                            $price = $_item->getPriceInclTax();
                            $rowTotal = $_item->getRowTotalInclTax() ?: ($_item->getQty() * $price);
                        } else {
                            $price = $_item->getOrderItem() ? $_item->getOrderItem()->getPrice() : $_item->getPrice();
                            $rowTotal = $_item->getRowTotal() ?: ($_item->getQty() * $price);
                        }
                        ?>
                        <div><?= $_order->formatPrice($price) ?></div>
<!--                        <div style="font-size:12px;color:#777;">--><?php //= $this->escapeHtml(__('Row total:')) ?><!-- --><?php //= $_order->formatPrice($rowTotal) ?><!--</div>-->
                    </td>
                </tr>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
