<?php
/**
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */

$lists = $block->getLists();
?>
<?php if (count($lists) > 0): ?>
    <h3><?= $block->escapeHtml(__('Mailing List(s)')) ?></h3>
<?php endif; ?>

<?php
$first = true;
$popupId = $block->getPopup()->getId();
foreach ($lists as $key => $item) {
    $id = 'mailchimp_' . $key . $popupId;
    ?>
    <div class="mailchimp_item">
        <input type="radio" name="mailchimp_list" value="<?php echo $key ?>" id="<?php echo $id ?>"<?php if ($first) echo ' checked="checked"' ?>>
        <label for="<?php echo $id ?>"><?php echo $item->getLabel() ?></label>
    </div>
<?php
$first = false;
}
