<?php /* @var $block \Digidirect\PreOrder\Block\Product\View\Preorder\ProductConfigurable */ ?>
<script type="text/x-magento-init">
{
    "*": {
        "preOrderConfigurable": {
            "preOrderNote": "<?php echo $block->escapeHtml($block->getPreorderNote())?>",
            "addToCartLabel": "<?php echo $block->escapeHtml($block->getCartLabel()) ?>",
            "isAllProductsPreorder": <?php echo (int)$block->isAllProductsPreorder() ?>,
            "map": <?php /* @escapeNotVerified */ echo json_encode($block->getProductPreorderMap()) ?>,
            "currentAttributes": <?php /* @escapeNotVerified */ echo json_encode($block->getConfigurableAttributes()) ?>,
            "addToCartForm": "#product_addtocart_form"
        }
    }
}
</script>
