<?php
/** @var \Magento\Captcha\Block\Captcha\DefaultCaptcha $block */

/** @var \Magento\Captcha\Model\DefaultModel $captcha */
$captcha = $block->getCaptchaModel();
?>
<div class="field captcha required" role="<?= $block->escapeHtmlAttr($block->getFormId()) ?>">
    <label for="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>" class="label"><span><?= $block->escapeHtml(__('Please type the captcha code')) ?></span></label>
    <div class="control captcha">
        <div class="code">
            <input name="<?= $block->escapeHtmlAttr(\Magento\Captcha\Helper\Data::INPUT_NAME_FIELD_VALUE) ?>[<?= $block->escapeHtmlAttr($block->getFormId()) ?>]" type="text" class="input-text required-entry" data-validate="{required:true}" id="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>" autocomplete="off"/>
        </div>
        <div class="nested">
            <div class="field captcha no-label"
                 data-captcha="<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
                 id="captcha-container-<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
                 data-mage-init='{"captcha":{"url": "<?= $block->escapeUrl($block->getRefreshUrl()) ?>",
                                            "imageLoader": "<?= $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif')) ?>",
                                             "type": "<?= $block->escapeHtmlAttr($block->getFormId()) ?>"}}'>
                <div class="control captcha-image">
                    <div class="wrap-captcha">
                        <img alt="<?= $block->escapeHtmlAttr(__('Please type the letters and numbers below')) ?>" class="captcha-img" src="<?= $block->escapeUrl($captcha->getImgSrc()) ?>"/>
                    </div>
                    <button type="button" class="action reload captcha-reload -icon" title="<?= $block->escapeHtmlAttr(__('Reload captcha')) ?>">
                        <svg>
                            <use xlink:href="#svgi-reload"></use>
                        </svg>
                    </button>
                </div>
            </div>
            <?php if ($captcha->isCaseSensitive()) :?>
                <div class="captcha-note note">
                    <?= $block->escapeHtml(__('<strong>Attention</strong>: Captcha is case sensitive.'), ['strong']) ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
