<nav data-testid="navigation-footer-container" class="footer-wrapper">
</nav>

<script type="text/x-magento-init">
    {
        "*": {
            "navigation": {
                "menu": <?php /* @escapeNotVerified */ echo $block->getMenuJson(); ?>,
                "horizontal": false,
                "area":".footer-wrapper",
                "wrapperClass": "footer-links",
                "action": "click"
            }
        }
    }
</script>
