<?php
/**
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
?>

<?php /** @var \Plumrocket\Newsletterpopup\Block\Popup\Fields $block */  ?>

<?php if ($fields = $block->getFields()): ?>
    <ul class="pr-np-fields-wrapper">
        <?php foreach ($fields as $field): ?>
            <li <?php echo ($field->getName() === 'recaptcha') ? 'class="prrecaptcha-wrapper"' : ''?>>
                <?= $block->getFieldHtml($field) ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
