<?php
/** @var \Ewave\CollectAbstractEntityMSI\Block\Product\View\Availability $block */
$availability = $block->getAvailability();
$product = $block->getProduct();
$cmsSddBlock = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cms_pdp_sdd_info')->toHtml();
$cmsPickUpInStoreTitle = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cms_pdp_pick_up_in_store_title')->toHtml();
$cmsSddBoxTitle = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cms_pdp_sdd_title')->toHtml();
$availabilityCheckArray = json_encode($availability);
?>
<div class="msiavailability-root-wrapper">
    <div class="pick-up-in-store-link">
        <span class="title"><?php echo $cmsPickUpInStoreTitle; ?></span>
        <span class="mystore-text" data-bind="scope: 'my-store-widget'">
            <!-- ko if: (store.isStoreSelected() && store.storeUrl()) -->
                <a class="current-store-link"><!-- ko text: store.selectedStore() --><!-- /ko --></a>
            <!--/ko-->
            <!-- ko ifnot: (store.isStoreSelected() && store.storeUrl()) -->
                <a class="current-store-link" data-bind='attr: {"class": store.isStoreSelected() ?'>
                    <?php /* @escapeNotVerified */ echo __('No Store Selected') ?>
                </a>
            <!--/ko-->
        </span>
        <span id="availabilityAddition"></span>
    </div>
    <div id="msi-availability" class="msiavailability-wrapper"
         data-mage-init='{
                    "collapsible":{
                        "collapsible": true,
                        "openedState": "active",
                        "active": false
         }}'
    >
        <div data-role="title" class="availability-wrapper">
            <div>
                <div class="arrow">
                    <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon svgi-action">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svgi-left"></use>
                    </svg>
                </div>
            </div>
        </div>
        <div data-role="content" class="tabpanel">
            <?php if (!empty($availability)): ?>
                <?php foreach ($availability as $name => $isAvailable): ?>
                    <div class="msi-availability">
                        <span class="name"><?= $block->escapeHtml($name) ?></span>
                        <?php if ($isAvailable): ?>
                            <span class="status -available"><?= /* @noEscape */
                                __('Available') ?></span>
                        <?php else: ?>
                            <span class="status -unavailable"><?= /* @noEscape */
                                __('Unavailable') ?></span>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="message info"><span><?= /* @noEscape */
                        __('Please select the option to see Product availability') ?></span></div>
            <?php endif; ?>
        </div>
    </div>
</div>
<div id="sdd_block" data-bind="scope: 'sdd-ship-checker'" class="msiavailability-wrapper sdd">
  <!-- ko template: getTemplate() --><!-- /ko -->
    <div class="cms-sdd-info-block-modal-data" style="display: none"><?= /* @escapeNotVerified */ $cmsSddBlock ?></div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Ewave_CollectAbstractEntityMSI/js/availability-tab": {},
            "Magento_Ui/js/core/app": {
            "components": {
                "sdd-ship-checker": {
                    "component": "Ewave_ShippingAvailabilityCheck/js/sdd-shipping-checker",
                    "productPrefix": "<?= /* @escapeNotVerified */ $product->getId() ?>",
                    "restUrl": "<?= $block->escapeJs($block->getBaseUrl() . 'rest/V1/check_ssd_availability/') ?>",
                    "cmsSddBoxTitle": <?= json_encode(str_replace(array("\r", "\n"), "", $cmsSddBoxTitle))?>
                }
            }
         }
       }
    }
</script>
<script>
    window.availabilityCheckArray = {"content": <?php echo json_encode(str_replace(array("\r", "\n"), "", $availability))?>};
</script>
