<div class="back-button">
    <a class="action back">
    <span><?= $block->escapeHtml(__('Back')) ?></span>
    </a>
</div>

<script>
    require(['jquery'], function ($) {
        $(function () {
            $('.action.back').on('click', function () {
                if (window.history.length > 1) {
                    window.history.back();
                } else {
                    window.location.href = '/'; // fallback (e.g. homepage)
                }
            });
        });
    });
</script>