<?php
namespace Digidirect\ShopByCategory\Block\Index;
 
use Magento\Framework\View\Element\Template;
 
class View extends Template
{
    public function __construct(
        Template\Context $context, 
        \Magento\Catalog\Model\ResourceModel\Product\CollectionFactory $productCollectionFactory,
        \Magento\Catalog\Model\ProductFactory $productFactory,
        array $data = [])
    {
        $this->_productCollectionFactory = $productCollectionFactory;
        $this->productFactory = $productFactory;
        parent::__construct($context, $data);
    }

    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
 
    public function getProducts($productId)
    {
       return $productId;
    }
    
    /* Get product count on a category */
    public function getProductCollectionCountWithBrand($categoryId, $brandId) 
    {
        $productCollection = $this->_productCollectionFactory->create();
        $productCollection->addAttributeToSelect('*');
        $productCollection->addCategoriesFilter(['in' => $categoryId]);
        $productCollection->addAttributeToFilter('status', \Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
        $productCollection->addAttributeToFilter('brand', $brandId);
        return $productCollection->count();
    }
    
    public function getBrandname($brandId) 
    {
        $product = $this->productFactory->create();
        $isAttributeExist = $product->getResource()->getAttribute('brand'); 
        $optionText = $isAttributeExist->getSource()->getOptionText($brandId);
        $optionText = strtolower($optionText);
        $optionText = str_replace(' ', '-', $optionText);
        return $optionText;
    }
}